### ISSUE TITLE
Converting Jira.Task.Status to DevOps.(Task.Status + Task.Tag)

### ISSUE THREAD

**Issue by Tridy** [solidify/jira-azuredevops-migrator#100]
Hi.
Is it possible while mapping a custom Jira task with the status "Unclear request" to the DevOps task with a status "In Progress", and at the same time create a Tag for the task "Unclear request"?
Thanks!

**Comment by MOlausson** [comment]
@Tridy, no this is not possible today. I'll add it for review to see if we could implement this.

**Comment by cforce** [comment]
Related #101
