### ISSUE TITLE
Custom Field in Jira not exporting the data correctly, fields missing in export

### ISSUE THREAD

**Issue by advitakhadke24** [solidify/jira-azuredevops-migrator#1004]
Currently using the Solidify tool(jira-azuredevops-migrator-3.0.186) to migrate our on-premises Jira board to Azure Board. Initially, I successfully migrated work items for one of our teams as they didn't have many rigid requirements. However, for the next team, they require all fields present in Jira to be migrated to Azure DevOps (ADO).

Currently, I'm facing challenges with two specific custom fields: "Client Code" and "Fix Version/s". The "Client Code" appears as blank upon exporting, and the "Fix Version" is not exported at all

A clear and concise description of what the problem/bug is.

**Tool version**
 - Version of the jira-azuredevops-migrator-3.0.186

**Attachments**

- config.json

**Comment by advitakhadke24** [comment]
To reproduce the issue,

1. Create a ticket in jira with following fields Client: Custom field  Fix Version/s: System defined
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/23686549-1a5d-4e1e-b3bc-ab9da6284515)

2. Try exporting with above 2 fields populated

**Comment by Alexander-Hjelm** [comment]
See the FAQ for guidelines on how to map custom fields: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

The Fixes Version field has the field ID "fixVersions" under the hood

**Comment by advitakhadke24** [comment]
Field Id "fixVersions" did work for me. Thankyou!

For the other custom field its a drop down field so I have I tried using Map Array for this i.e
      {
        "source": "customfield_10205",
        "target": "Custom.ClientCode",
        "mapper": "MapArray"
      },
      
    In the exported logs it says "the specific field contains unparsable type Null, using text"
Please find the attached log below
[jira-export-log-240325-124312.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14760400/jira-export-log-240325-124312.txt)

**Comment by Alexander-Hjelm** [comment]
The ClientCode field in your Jira view looks suspiciously like the tag field. Could it maybe do the trick to use the mapper "MapTags"?

The debug message means that the field does not have a value on the first revision. This could be expected or not, depending on when in the changlog you modified the ClientCode field.

**Comment by advitakhadke24** [comment]
Tried with the "MapTags" still no luck in getting this populated
      {
        "source": "customfield_10205",
        "target": "Custom.ClientCode",
        "mapper": "MapTags"
      },
      
      
[FONE-2920.json](https://github.com/solidify/jira-azuredevops-migrator/files/14762244/FONE-2920.json)

[jira-export-log-240326-121404.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14762246/jira-export-log-240326-121404.txt)

**Comment by Alexander-Hjelm** [comment]
Try to specify the full FieldReferenceName for all of your fields in the config?

e.g. ServiceNow_Incident becomes `Custom.ServiceNow_Incident`

Also here I can see that you have many cases of using the Display name of the target fields (ADO) instead of the FieldReferenceName. This might affect your experience with the tool negatively, although I cannot say exactly what the consequences will be:

```json
      {
        "source": "customfield_16300",
        "target": "Impact Score",
        "mapper": "MapInteger"
      },
      {
        "source": "customfield_16301",
        "target": "Effort Score",
        "mapper": "MapInteger"
      },
      {
        "source": "fixVersions",
        "target": "Fix Version",
        "mapper": "MapString"
      },
      {
        "source": "customfield_16302",
        "target": "Priority Rank",
        "mapper": "MapInteger"
      },
      {
        "source": "Developer",
        "target": "Dev Assignee",
        "mapper": "MapUser"
      },
      {
        "source": "Assignee",
        "target": "Dev Assignee",
        "mapper": "MapUser"
      },
```

You can find some troubleshooting steps related to migrating custom fields here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#troubleshooting-my-custom-field-is-not-migrated-correctlynot-migrated-at-all

**Comment by advitakhadke24** [comment]
Thank you so much! I was able to get the ServiceNow_Incident fields populated. It was my mistake—I was looking at the wrong ADO process template. Our user story has this field defined with a different name compared to bugs. However, for the Client Code, I am still unable to figure out what’s going wrong. I would really appreciate it if you could help me with this.

I have tried specifying with the suggested Custom fields it's showing blank ' ' on exporting:
**Attachments:**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/783c5589-6945-4aba-b4fb-330b57268295)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/da450a45-083e-49f8-93ea-f785ee820b23)


![ADOClientField](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/82a59e33-eb4e-4b64-b4bd-bbe2bff652fe)
![JiraClientField](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/e0c49f64-8085-428c-b56f-72d04f7d9faf)

**Comment by advitakhadke24** [comment]
To add to the above

When there is multiple clients it understands that and mapps  " ; "   where as when there is single client it shows  ' '
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/59e6e138-73ea-4add-ab23-a395ea6db0a6)

**Comment by Alexander-Hjelm** [comment]
@advitakhadke24 Have you tried to map both by "name" and "id"? As mentioned here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by Alexander-Hjelm** [comment]
`source-type` cannot have the value "Client", it must either be "name" or "id".

**Comment by advitakhadke24** [comment]
Got it, I have tried with the source-type = Name since the values are like KI, AJ, AH

      {
        "source": "Client",
        "source-type": "Name",
        "target": "Custom.ClientCode"
      },
      
    And just to check I have also tried with ID as well, still no luck!  
      
      {
        "source": "Client",
        "source-type": "id",
        "target": "Custom.ClientCode"
      },

**Comment by Alexander-Hjelm** [comment]
If using:

```
"source-type": "id",
```

Then the `source` should be the custom field key. Something like `customfield_12345`. You may need to use the REST API to retrieve this data.

**Comment by advitakhadke24** [comment]
Can you please explain on how to achieve this? If you have any document which I can follow to identity this?
Thanks!

**Comment by Alexander-Hjelm** [comment]
The only document we have with known solutions is here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by advitakhadke24** [comment]
I did some research and it looks like there are 2 ways to find they custom field in ADO through ADO web portal or via API. I have already looked through web portal  by going to Process -> work item type(User Story , Bugs)->Select the Custom Field
looks like custom field key in Jira is displayed as "Field reference name" in ADO

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/9e05ee21-19d3-4a64-9f1d-67bb2cbe9235)

**Comment by Alexander-Hjelm** [comment]
Hum... What type is the field Custom.ClientCode in Azure DevOps? Is it a picklist? If so, maybe the value you are trying to import is not among the selectable values?

**Comment by advitakhadke24** [comment]
Yes the "Custom.ClientCode" in Azure DevOps is a picklist and it is present in the picklist group.
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/67f51c87-c032-4d53-a6ab-4d1c467aed90)
Also, field has option to typein if not available in picklist
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/60a6dd5c-6109-435c-b676-c245b09f4000)

Another thing to note, there is another field which is also a picklist "labels" this works fine with the Maptags 
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/6ed5b0d0-b9d1-432c-9431-895b63aa6f3a)

**Comment by Alexander-Hjelm** [comment]
@advitakhadke24 For experimentation purposes, what you happen if you were to create a new Test field in your target Work Item Type process model and map the ClientCode field to that? Does the full value come over then? Or does it not change the value at all?

**Comment by advitakhadke24** [comment]
I tried adding a new test client code field - with a single line text field 
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/c604d778-2643-45f1-b44b-d46d138683f1)

Tried with Mapstring & tag
      {
        "source": "customfield_10205",
        "target": "Custom.TestClientCode",
        "mapper": "MapString"
      },
      
     {
        "source": "customfield_10205",
        "target": "Custom.TestClientCode",
        "mapper": "MapTags"
      },

It just gives blank on exporting itself 
[D][13:42:10]    Mapped value ' ' to field 'Custom.TestClientCode'.

**Comment by Alexander-Hjelm** [comment]
Try MapArray?

https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#mappers

**Comment by advitakhadke24** [comment]
I have already tried that, if you see the comment here https://github.com/solidify/jira-azuredevops-migrator/issues/1004#issuecomment-2020669052

I gave another shot this morning with test as well as the orignal Client field but still it's the same ' '

      {
        "source": "customfield_10205",
        "target": "Custom.TestClientCode",
        "mapper": "MapArray"
      },

**Comment by advitakhadke24** [comment]
@Alexander-Hjelm anything else I could try? We want this field migrated and thinking off getting Pro migrator tool...In case we do  purchase ..will that be helpful to get this field populated?
