### ISSUE TITLE
JIra Key not found exception

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#1007]
when a JIRA  key which is part of comment does not exist in JIRA the method downloadIssue of JIRAprovider throws exception.. how to validate the response instead of throwing the exception 
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/154508737/5151c68f-30f3-48ab-b586-1095d2dc2de1)

**Comment by Alexander-Hjelm** [comment]
Setting a breakpoint at line 349 and inpecting the value of the `response` variable should be sufficient, no? Or set up the same query in postman, curl, or similar web testing software.
