### ISSUE TITLE
Map more than  one Jira field to System.Tags values

### ISSUE THREAD

**Issue by cforce** [solidify/jira-azuredevops-migrator#101]
I want to add fields values from Jira custom fields as a "tag"

**Comment by MOlausson** [comment]
Have you tried using the "MapTags" mapper? It should work with any space separated list of values:

      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },

**Comment by cforce** [comment]
it throws an Terror when i define Systems.tags twice.  or more Times as target

**Comment by MOlausson** [comment]
Got it. We'll investigate.

**Comment by Freakling** [comment]
Any progress on this?
