### ISSUE TITLE
Custom fields assigned a value on creation and not changed are not exported

### ISSUE THREAD

**Issue by YoavLax** [solidify/jira-azuredevops-migrator#1014]
Hi, 

I have a few custom fields, from type: Label in my Jira that i'm trying to migrate. 
This mostly works perfectly, but I've noticed a case which isn't migrating the data. 
If these fields were assigned a value on the creation of the item and haven't been updated since, the exporter doesn't export their values.
Though if a make a change on the field and return to original value, then the exporter does export the value of these fields.  

Are you familiar with such a case? Is there something i'm missing?

**Comment by Alexander-Hjelm** [comment]
Sometimes switching to using either field id or name as the `source` can be a workaround. See different options here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by YoavLax** [comment]
It didn't help, as i mentioned it's not persistent, it happens only in the case i mentioned where the value was assigned on creation and not changed since. 
If it has been updated \ modified since creation it works perfectly.

**Comment by Alexander-Hjelm** [comment]
@YoavLax Ok!

Can you confirm that this is the type of your custom field?

I will set up some integration tests to confirm export of Label-type custom field as soon as I find the time.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/d0d30915-e49d-484b-8191-e5f90cde95e8)

**Comment by Alexander-Hjelm** [comment]
The following field mapping worked for me: 

```json
      {
        "source": "alexander-testar-custom-labels",
        "target": "Custom.CustomLabels",
        "source-type": "name",
        "mapper": "MapTags"
      }
```

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/39d550d2-5eda-478c-bcfc-d914b1f34c5b)


![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/32806b4d-2f3e-46c3-8c0c-97b8548b5821)

**Comment by Alexander-Hjelm** [comment]
Ah, my bad,

It seems that under these conditions, the data is not properly exported. Here is what I am getting:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/eded8ebe-8d58-474c-aed6-2b2cf29d0a2a)

I will mark this issue as a bug. Will work on a fix as soon as I can find the time.

**Comment by Alexander-Hjelm** [comment]
The bug has potentially been fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/1015

At least it now works on my end.

Can you try to build the PR from source, or should I provide you with a binary to test? @YoavLax

**Comment by YoavLax** [comment]
I'll build and test. 
I'll update soon! Thanks!

**Comment by YoavLax** [comment]
Issue solved! Thank you very much!

**Comment by Alexander-Hjelm** [comment]
Great! Closing this issue. Reopen if the problem resurfaces.
