### ISSUE TITLE
Import all the fields of Test case instead of few fields.

### ISSUE THREAD

**Issue by KRVijayalakshmi** [solidify/jira-azuredevops-migrator#1018]
# Read this before submitting your support ticket/bug report
---

**Describe the problem**
Currently at my project level, i am able to import only few fields at test case level.

**To Reproduce**

Add the details of all the columns and details and try to import under specific test suite in ADO.

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/163000488/fef82abd-00fc-4598-b555-1aef3b76fecd)

But i am able to import all the field details in the sample project. Kindly let me know the settings/permissions that is required to do so and the detailed steps to perform the same.

**Comment by Alexander-Hjelm** [comment]
Hi @KRVijayalakshmi, refer to our discussion here: https://github.com/solidify/jira-azuredevops-migrator/issues/996

Import of test case data via CSV file is not support by this tool.

Closing, continued in https://github.com/solidify/jira-azuredevops-migrator/issues/996
