### ISSUE TITLE
Is there a version of application which is supporting Jira with extension structure 

### ISSUE THREAD

**Issue by muthu3758** [solidify/jira-azuredevops-migrator#1019]
We have in our Jira hierarchy additional of 2 levels.

Portfolio Epic
Capability

Epic
Stories
Task

If there is such version or how to mention it in the config file, please do share that information.

**Comment by muthu3758** [comment]
We have done that type mapping for the custom work item type, but we are missing the child links.

1. I don't see the child link when I check in the API
2. I don't see the history related with this Child link in the parent work item of Jira

Are these reasons that tool is not able to get the child links

**Comment by Alexander-Hjelm** [comment]
Not to my knowledge. Are the children in the same project as the parents?

Maybe the links are in fact not standard Jira IssuesLinks but something custom managed by an extension of yours? In that case we cannot guarantee that your data will be supported.

**Comment by muthu3758** [comment]
How do we check whether links are  managed by Extension or standard links.

**Comment by Alexander-Hjelm** [comment]
You should be able to see them in the list of links on the Jira Issue:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/9853a62a-8e49-4971-9dc0-c27189202f1f)

Also, they must be present on the issue Rest API reponse. Here is an example query: `https://xxxxxxxxxx.atlassian.net/rest/api/3/issue/PROJECTKEy-123?expand=issuelinks`

See the below screenshots.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/134b959e-10ee-453d-9135-c51b682dbcfe)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/076e43ce-b0bf-472c-a82b-88dea0799115)

**Comment by muthu3758** [comment]
Below are the screenshots from RestAPI call and Jira

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/24650846/b56a5503-5d59-4b62-b625-d644af33cfa8)

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/24650846/e5834e9c-9359-466d-aed7-2436f97d7e43)

In this case there is a chance that this might have attached via some extension?

**Comment by muthu3758** [comment]
What recommendations do you have for resolving the current issue?

**Comment by muthu3758** [comment]
For me it looks like this is **not the standard one**, reasons are.

1. I'm not getting this Child links in Rest API call
2.  If you see the above screenshot of **API** IssueLinks[] and SubTasks[] tags are empty.

So in that case Is that true tool is not capable of getting Custom links by default?

This is the below Linking setup I have it in my Instance, not on the Specific project settings.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/24650846/2de76cb5-41ad-4571-8288-3d6da4ba67b8)

**Comment by Alexander-Hjelm** [comment]
Custom link types should be supported!

But judging from your screenshot in your last comment, there does not seem to be any custom link type named "Child" or  "Parent" or similar, so I actually doubt that the default parent-child relationship is being overshadowed by some custom link type.

**Comment by muthu3758** [comment]
@Alexander-Hjelm Can you please tell us how to map if the links are available in rest api with some customfields, As you have seen the below image out of 4 links I could get 3 of them as a child, but i'm missing one link.(DITVM-764). Below is my config of link mapping.

**"epic-link-field": "Parent Link",**
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users_ALL 3.txt",
  "base-area-path": "LinkMigrated",
  "base-iteration-path": "LinkMigrated",
  "ignore-failed-links": true,
  "process-template": "Agile",
  "link-map": {
    "link": [{
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Blocks",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Cause",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Cloners",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Defect",
        "target": "System.LinkTypes.Dependency-Reverse"
      },
      {
        "source": "Dependent",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      {
        "source": "Dependency",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Fix",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Hierarchy",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Implement",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Issue split",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Jira External",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Lead/Included",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Related",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Sync",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Verify",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Tests",
        "target": "System.LinkTypes.Related"
      }
    ]
  },

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/24650846/b8bc6eb8-75c2-4554-9688-750f68305f65)

Can you please tell us my config file is correct or need to do some modifications to get all the 4 links

**Comment by muthu3758** [comment]
Hi @Alexander-Hjelm,

Thanks for your response.

We have 2 projects which we need to migrate together, as you have seen in the screenshot.

Project 1 has top hierarchy configured as **Parent Link** and Project 1 has top hierarchy configured as **Feature Link**, because of which when we are migrating together we are not able to get all the links.

Questions:
1. Is there any way to have to more than one value for "epic-link-field"
2. Is there any way to have more than one epic-link field configuration.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/24650846/b100d7ed-2bed-470b-a73f-1aa8b111e294)

**Comment by Alexander-Hjelm** [comment]
Ok! what is strange from your latest messages is that the linked issues seem to be stored as a custom field (customfield_13150) rather than an issuelink. Maybe that could have something to do with why you are not seeing them come across?

You can maybe try the Issue Field Data discovery endpoint and see if you can get any more information on customfield_13150. It would be interesting to see if you can find any clues to whether this field has been brought in by an extension or not. The endpoint looks something like this:

```
http://kelpie9:8081/rest/api/2/issue/createmeta?projectKeys=QA&issuetypeNames=Bug&expand=projects.issuetypes.fields
```

If this is the case, then I doubt that this tool will be able to support your requirement of migrating those links. This tool does not have the capability of migrating IssueField as Links. The best thing you could do is probably to map the field "customfield_13150" to a new Custom Field in ADO to ensure full traceability, then after the migration you can run some powershell automation or similar to set up the work item links based on the contents of that field.

> Is there any way to have to more than one value for "epic-link-field", Is there any way to have more than one epic-link field configuration.

I don't believe so. The standard Epic Link field (which has now been superseded by the new Parent field in later versions of Jira Cloud) is the only field which tracks epic links.
