### ISSUE TITLE
option to overwrite/skip already imported jira issues

### ISSUE THREAD

**Issue by cforce** [solidify/jira-azuredevops-migrator#102]
It would be a great enhancement to add an optional importer param that allows to locate and overwrite an before already imported issue what is currently just created again (duplicated)
E.g detect by title search should be possible already - maybe there is another way to identify the  source and target via same JIRA issue id.
Additionally than allow to skip the import for this issue if it has been imported before.

**Comment by MOlausson** [comment]
Thanks for the suggestion @cforce, agree that it could be useful. What's the use-case you have in mind? I see use for it when testing a migration or potentially in a sync scenario but not really in a real migration (other than if an item was incorrectly imported but then I'd probably delete it, fix the problem and try again to get a clean history).

Today we support importing remaining items or restarting by using the --force parameter, would that be enough in your case?

**Comment by cforce** [comment]
in fact i meint a synchron scenario, with starting of following logisch: 
1.don't overwrite if hast eben imported before
2. overwrite in and case
3. only overwrite if last modified of origin is newer than target in case it exists already. This will allow to create read only copy on target side. This will also alle to define jql filtern like implemented already, so based on issue Status You can Setup a two way synced worflow.

**Comment by AmitNaveh23** [comment]
@MOlausson Also maybe, if you have access to existing work items, you could update them during the import and add links to them if needed.
Now you have to import all together if you want to keep all the links between them

**Comment by JeffBor** [comment]
Additional use case:
Phased migration vs. all-at-once cutover.  "Phased" = gradual migration, keeping source periodically sync'ed to target (one-way only, not bidirectional).

**Comment by sheyincp** [comment]
@MOlausson @JeffBor @cforce  or is it possible to customize the code to support filter (Param will be a date) in import commands ?

**Comment by sheyincp** [comment]
@MOlausson @JeffBor @cforce or is it possible to customize the code to support filter (Param will be a date) in import commands ?
