### ISSUE TITLE
Development / Releases are supported? 

### ISSUE THREAD

**Issue by YoavLax** [solidify/jira-azuredevops-migrator#1022]
Hi, 

Are migration of Development links supported in any way? 
Is there the ability to migrate also links to PR's/Commits from Jira?

**Comment by Alexander-Hjelm** [comment]
Releases and the fixesVersion/affectsVersion fields have extended support in our PRO offering.

Commit links are supported in the Community edition, read more here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#13-how-to-migrate-development-links-commit-pr-branch

PR and Branch links are not supported as of today. We are looking into how we can add support for this. Both of these link types will probably be supported in the PRO edition only. :)

**Comment by YoavLax** [comment]
Hey! Thanks, 
Just checking cause it's not really clear to me, 
If i haven't moved my repository, what would be the way to export the link to the commit? 
For example, i have my repo in GitHub and it's staying there, and all i want is to export the link to this commit from the Jira item to the Azure DevOps item.

**Comment by Alexander-Hjelm** [comment]
That is correct, the recommended approach will only work if you have also migrated your Bitbucket repositories to Azure DevOps.

I am not sure how that would work with the GitHub code integration to be honest. The existing solution is designed to work with Bitbucket and has been tested with Bitbucket, so whether it works out of the box or not would depend on whether the API schemas for the commit/branch links are the same for GitHub and Bitbucket links.

Also I do not think that links to existing GitHub repositories which are not scheduled for migration is supported as of today, even if I think that this is technically doable. Both ADO and Jira would need to be integrated with the same GitHub organization at the time of migration of course.

I will create a feature request on this!

**Comment by Alexander-Hjelm** [comment]
Feature request created. I cannot give an ETA for how soon we can start working on the new feature, unfortunately!
