### ISSUE TITLE
multi project import: mappings of jira projects to ado projects

### ISSUE THREAD

**Issue by cforce** [solidify/jira-azuredevops-migrator#103]
Currently you can only only map an jira export to one dedicated ado target when importing and sofore will loos references between exported tickets, when you d imports on them in several dedicated import steps, don't you?

Allow to import several projects source->target mappings in same import, so you can keep the cross references between issues in ADO at the end.
E.g provide and additional mapping file for projects, that allows to import->export from several jira 
projects and map each of it to another or same ado project:

jira source project; ado target project

**Comment by MOlausson** [comment]
@cforce interesting idea. Today you can split the migrations into multiple runs where each would select a set of items, export and import, this way you will be able to bucket what gets imported where. In what scenarios do you see the use for a merge or split in one migration? 

One I could imagine would be to split top-level items (epics, features) to a portfolio backlog and sub-items (stories, bugs) to team level backlogs in different project and then also keeping a parent-child relation between the items.

**Comment by cforce** [comment]
parent-child relations and all other references between issues will in any case be lost if you do more than one import process to migrate several projects, aren't they?

**Comment by weirbt2k** [comment]
You can only put in one source-project but you can query more than one project in the same Jira instance from what I've seen. 

Here's an example where I exported all issues in the 'To Do' or 'In Progress' statusCategory from three projects used by the same team (so I could consolidate them into Azure DevOps). I hope this helps.

"query": "project in (Project1,Project2,Project3) AND statusCategory IN ('To Do', 'In Progress') ORDER BY Rank ASC",

alternatively I could've used

"query": "project in (Project1,Project2,Project3) AND statusCategory NOT IN ('Done') ORDER BY Rank ASC",

**Comment by cforce** [comment]
@weirbt2k  You misunderstood my request. I was requesting to be able to have several destination projects for the same source, but keeping links between issues in destinations projects because they have the same source project where they was linked too before. If you don't have that import in one go, you will loose the context and for that the reference.
