### ISSUE TITLE
Description Field Blank in ADO User Story

### ISSUE THREAD

**Issue by jford427** [solidify/jira-azuredevops-migrator#1034]
**Describe the problem**

The description section is blank in the user stories created in ADO.

**To Reproduce**

1. Validate that the data is correct in the ADO user story after running the steps
2. Check on Description
3. See issue => The Description field is blank

**Tool version**
v3.0.407

**Attachments**

- config.json
[config-agile-fee-center.json](https://github.com/solidify/jira-azuredevops-migrator/files/15134664/config-agile-fee-center.json)

- jira-export-log.txt
[jira-export-log-240424-095242.txt](https://github.com/solidify/jira-azuredevops-migrator/files/15134661/jira-export-log-240424-095242.txt)

- wi-import-log.txt
[wi-import-log-240426-130254.txt](https://github.com/solidify/jira-azuredevops-migrator/files/15135202/wi-import-log-240426-130254.txt)

**Screenshots**
Jira View
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/70026613/d8ae03d4-e471-4c8b-b8ed-38c2b6d6563f)

ADO View
![adoView](https://github.com/solidify/jira-azuredevops-migrator/assets/70026613/99c298c4-42f8-4777-993f-d6623c10db23)

Ticket JSON
[CPCAG-724.json](https://github.com/solidify/jira-azuredevops-migrator/files/15134713/CPCAG-724.json)

**Comment by Alexander-Hjelm** [comment]
Weird. The error is happening on the import side, but no errors or warnings in the import log related to revision 0 of item CPCAG-724. So it seems like the value of System.Description is being set and not rejected.

Is it possible to run the import again for CPCAG-724 only with log-level = debug in the configuration?

Also, could it be possible to query Work Item 2601 with the ADO Rest API to see if maybe the value of System.Description is set under the hood or not?
