### ISSUE TITLE
Support for Continuing an Import at a Specific Revision

### ISSUE THREAD

**Issue by Dejulia489** [solidify/jira-azuredevops-migrator#1039]
**Is your feature request related to a problem? Please describe.**
I have to restart an import from revision 0
**Describe the solution you'd like**
I would like to be able to restart an import after a failure. 
**Describe alternatives you've considered**

**Additional context**

**Comment by Alexander-Hjelm** [comment]
Solution is already in place. See https://github.com/solidify/jira-azuredevops-migrator/issues/1011

**Comment by Dejulia489** [comment]
Awesome. Thanks! Did I miss that in the documentation somewhere?

**Comment by Alexander-Hjelm** [comment]
I suppose that would be here! https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/wi-import.md

But maybe we should add an FAQ entry about it too.

**Comment by Alexander-Hjelm** [comment]
I have documented the topic here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#5-what-is-the-purpose-of-the---force-flag
