### ISSUE TITLE
Best way to migrate large amount of issues

### ISSUE THREAD

**Issue by YoavLax** [solidify/jira-azuredevops-migrator#1043]
Hi, 

Would like to hear what would be the most recommended way yo migrate a large amount of issues.
I see there is the ability to split the export like explained here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#15-how-to-limit-the-number-of-issues-to-be-exported-during-jira-export-pagination

Which indeed could be useful and save time on the export side, but how would this affect in the import? 
If for example i split in to 5 paginations, how would i proceed with the import? In parallel? Wouldn't this cause some data to get missed? 
Or on the import phase we should go one after the other? 

Just looking for the best way to save some time during the migration and in addition to ensure all the data stays safe.

**Comment by YoavLax** [comment]
So just to verify i understand the process, the recommendation will be:

**Export**: 

1. Set "download-options": 0
2. Force = true
3. Export each config into a separate workspaces in parallel

**Import:**

1. Import one workspace at a time
2. DON'T use force
3. After every import completes, copy the itemsJournal.txt from one workspace to the next, this will ensure mappings of the items and will continuously get updated on every import.

Did i get it right? Anything missed?

**Comment by Alexander-Hjelm** [comment]
That sounds about right!

**Comment by Alexander-Hjelm** [comment]
Looks like maybe the itemsJournal file was corrupted? Check it and verify that there are no empty lines and that there are no other weird things going on.

**Comment by YoavLax** [comment]
I see this warning in the import log:
[W][20:54:23] Detected unicode characters, removed.
[W][20:54:23] Detected unicode characters, removed.
[W][20:54:27] Detected unicode characters, removed.

Could be related? 
Though i don't see any corruption in the itemsjournal . 

In addition, i checked if the item that it's trying to add in that revision appears inside the itemsjournal and it's indeed there.

**Comment by Alexander-Hjelm** [comment]
Should be fine. The unicode character warning comes from this PR: https://github.com/solidify/jira-azuredevops-migrator/pull/706, which solved another error related to characters that could not be properly parsed.

**Comment by YoavLax** [comment]
So any thoughts why this is happening? 
What could be the issue leading to this error? 
We see that most links are migrated properly, but we see many errors like described above which are failing to link.

**Comment by Alexander-Hjelm** [comment]
Not sure straight away. Here is the line which is logging the above error:

```csharp
Logger.Log(LogLevel.Info, $"Processing {importedItems + 1}/{revisionCount} - wi '{(wi.Id > 0 ? wi.Id.ToString() : "Initial revision")}', jira '{executionItem.OriginId}, rev {executionItem.Revision.Index}'.");
```

See: https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/WorkItemImport/ImportCommandLine.cs#L131

I am not sure, but it seems like the expression `(wi.Id > 0 ? wi.Id.ToString() : "Initial revision")` results in an empty string? Any idea why that could be?

**Comment by YoavLax** [comment]
I'm sorry, the ID was mistakenly deleted. 
It does exist, like here: 
**Processing 5614/147165 - wi '1853211', jira 'TST-10220, rev 5'**


I think it's failing here: 
https://github.com/solidify/jira-azuredevops-migrator/blob/304e6e2f5692e6211ab6b40e154f0702fdc670c3/src/WorkItemMigrator/WorkItemImport/Agent.cs#L91
Which means for some reason the incomplete = true
Which is probably happening here: 
https://github.com/solidify/jira-azuredevops-migrator/blob/304e6e2f5692e6211ab6b40e154f0702fdc670c3/src/WorkItemMigrator/WorkItemImport/Agent.cs#L643

**Comment by YoavLax** [comment]
Seems like it's failing here: 
int sourceWiId = _context.Journal.GetMigratedId(link.SourceOriginId);

Cause if it was failing here:
 int targetWiId = _context.Journal.GetMigratedId(link.TargetOriginId);

It would have gotten into :
 if (link.TargetWiId == -1)
                    {
                        var errorLevel = Settings.IgnoreFailedLinks ? LogLevel.Warning : LogLevel.Error;
                        Logger.Log(errorLevel, $"'{link}' - target work item for Jira '{link.TargetOriginId}'" +
                            $" is not yet created in Azure DevOps/TFS. You can safely ignore this warning if" +
                            $" this work item is scheduled for import later in your migration.");
                        success = false;
                        continue;
                    }

**Comment by Alexander-Hjelm** [comment]
Ok! I see now that the Author and Datetime stamp of the issue has not been set, which indicates an internal failure in the Exporter. Did the JiraExport result in any obvious errors? Check the log maybe.

**Comment by YoavLax** [comment]
They have also been set, but removed so no internal data is published. 
Sorry for misleading.

**Comment by YoavLax** [comment]
Hi @Alexander-Hjelm , 

Updating we have managed to solve the issue by one small change. 

In the export section, instead of setting "download-options": 0, we have set it to 7. 
Then, copied itemsjournal and  Imported without force. 
This way it ensures that the migration passes including all its relations. 

Thank you so much for your assistance!
