### ISSUE TITLE
how can I use the tool if I have issue types Test and Test Plan and I don't have Task or sub task or any issue types else on jira  ?

### ISSUE THREAD

**Issue by HodaAyman2024** [solidify/jira-azuredevops-migrator#1045]
how can I use the tool if I have issue types Test and Test Plan and I don't have Task or sub task or any issue types else on jira  ?

**Comment by Alexander-Hjelm** [comment]
Hello @HodaAyman2024 

Test artifacts are supported by our premium offering, in the form of a separate program called the Jira Test Management Migrator which runs on top of the Jira Azure DevOps Migrator.

You can read more here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-test-management-migrator, or visit the product page at our website: https://solidify.dev/products/atlassian-migration-suite

Feel free to reach out to us at [support.jira-migrator@solidify.dev](mailto:support.jira-migrator@solidify.dev)

More information in this issue: https://github.com/solidify/jira-azuredevops-migrator/issues/996
