### ISSUE TITLE
Workitem Linking not working as expected

### ISSUE THREAD

**Issue by advitakhadke24** [solidify/jira-azuredevops-migrator#1047]
Thankyou so much for this amazing tool!

**Describe the problem**

When I am exporting a specific issue, is there a way to also download all the linked work items? I followed the documentation, and it looks like if I have download=7 in the configuration, it should be able to solve this, but it’s not happening for me. This might be causing the links to be only seen in the comments but not actually in the linked Azure DevOps (ADO).

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 3.0.418, 3.0.420]

**Attachments**

[FONE-2857.json](https://github.com/user-attachments/files/15542275/FONE-2857.json)
(If see here this is export of one of the ticket which has bunch of linked worked Item they are showing up in comments but not getting linked in ado)

[rcsnetconfigbf1.json](https://github.com/user-attachments/files/15542279/rcsnetconfigbf1.json)
- config.json

- jira-export-log.txt
[jira-export-log-240603-225222.txt](https://github.com/user-attachments/files/15542434/jira-export-log-240603-225222.txt)

- wi-import-log.txt
[wi-import-log-240603-225305.txt](https://github.com/user-attachments/files/15542438/wi-import-log-240603-225305.txt)

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/595bdc72-acf6-48e7-a6ee-2b6bbfca5a06)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/78161169/2d1d22c4-66ec-4a8b-a728-fb1bddae059d)

**Comment by Alexander-Hjelm** [comment]
I think there is an old feature request related to this: https://github.com/solidify/jira-azuredevops-migrator/issues/125

Currently the `download-options` flag does not support related issues, only hierarchical links like parent, child, subtask, etc.

So the workaround would be to try and capture the linked items in your query.

**Comment by advitakhadke24** [comment]
How do I capture the linked item in query? right now I am running query "team = 44 and issue type = "Business Feature"

**Comment by Alexander-Hjelm** [comment]
That depends on how your organization is set up!
