### ISSUE TITLE
Sprint information is not exporting

### ISSUE THREAD

**Issue by TKallem** [solidify/jira-azuredevops-migrator#1048]
**Describe the problem**

I am trying to export Jira work items into Azure DevOps, I have managed to export all fields data except for Sprint information into Area Path or Iteration Path. 

It looks like its not exporting for work items where there are no revisions for Sprint field. 

**To Reproduce**

1. Go to Jira
2. Create a new user story with sprint information
3. Try export the user story

**Tool version**
jira-azuredevops-migrator-3.0.407

**Attachments**

Please attach the following files:

[config-agile.json](https://github.com/user-attachments/files/15639618/config-agile.json)
[jira-export-log-240606-153325.txt](https://github.com/user-attachments/files/15639669/jira-export-log-240606-153325.txt)

**Comment by Alexander-Hjelm** [comment]
I see the following messages in your log file. It seems that the iteration and area path are correctly mapped for at least 2 of the items, correct? Does that mean that the error could be on the import side?

```
[D][15:33:28]    Mapped value 'Sprint 11 - 2024 (2705 - 0706)' to field 'System.IterationPath'.
[D][15:33:28]    Mapped value 'Sprint 11 - 2024 (2705 - 0706)' to field 'System.AreaPath'.
```

**Comment by TKallem** [comment]
Hi @Alexander-Hjelm , 

Thank you for looking into this. Yes it worked for one Jira user story but for the other one ([DSPUBI-2390] Thiru Test User Story - Summary 3), it didn't export any sprint details. 

I have attached Jira screenshot for your reference. 
![Screenshot 2024-06-07 085049](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/6fc51bfc-090a-4bbb-861a-f1393416473c)

**Comment by Alexander-Hjelm** [comment]
Maybe there is an issue with special characters in the sprint name? Or does the problem happen exclusively for items where the sprint has been set only on the initial revision? Or have you noticed any other pattern?

**Comment by TKallem** [comment]
I don't think its the special characters, I believe its to do with initial revision. 

If I update the sprint information and run the export it will export the sprint details correctly.

**Comment by Alexander-Hjelm** [comment]
Ok! We have already identified this issue separately and are working on a patch.

**Comment by TKallem** [comment]
Excellent. Thank you

**Comment by Alexander-Hjelm** [comment]
@TKallem, I have made a PR here with a patch that fixes the issue for me locally: https://github.com/solidify/jira-azuredevops-migrator/pull/1050

Are you able to build the tool from source and try the PR out for yourself?

**Comment by TKallem** [comment]
Hi @Alexander-Hjelm , 

I have tested the change from your PR and it looks like it is exporting and importing the Sprint information from initial revisions fine now. 

Thank you for your prompt response on this issue. 

Regards,
Thiru

**Comment by Alexander-Hjelm** [comment]
Perfect! Thank you for reporting this issue :)

**Comment by Brentenbrood** [comment]
#1050 also fixed it for me, thanks a lot!
