### ISSUE TITLE
Attachments are not exporting

### ISSUE THREAD

**Issue by TKallem** [solidify/jira-azuredevops-migrator#1049]
**Describe the problem**

I have a user story with multiple attachments, however when I run the export, there are no files exported, no attachments folder created and in the export log the following messages are logged. 

Note: I have Jira Admin access. 

[D][09:24:15]    Downloaded issue: DSPUBI-2383 changelog.
[D][09:24:15]    No attachment to undo for 'Added 13972/Regression.sql'.
[D][09:24:15]    Attachment Regression.sql cannot be migrated because it was deleted.
[D][09:24:15]    No attachment to undo for 'Added 13971/image.png'.
[D][09:24:15]    Attachment image.png cannot be migrated because it was deleted.
[D][09:24:15]    Created 29 history revisions.

**Tool version**
jira-azuredevops-migrator-3.0.407

**Attachments**

Please attach the following files:
[config-agile.json](https://github.com/user-attachments/files/15726032/config-agile.json)
[jira-export-log-240607-092412.txt](https://github.com/user-attachments/files/15726076/jira-export-log-240607-092412.txt)

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/8ff7063a-1b22-4f86-b93d-726f5747d186)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/3faf7c84-e5fc-456d-b42a-1042d3d31a02)

**Comment by Alexander-Hjelm** [comment]
What does the history of the affected Jira Issue look like? Have the attachments been added in the normal fashion? Or deleted from the issue at some point? Any other possible patterns identified?

**Comment by TKallem** [comment]
Hi @Alexander-Hjelm , 

There is no issue on this, everything is attached fine, nothing has been deleted from the issue. There is no pattern identified.

**Comment by Alexander-Hjelm** [comment]
Is the issue related to https://github.com/solidify/jira-azuredevops-migrator/issues/851?

**Comment by TKallem** [comment]
I have been through the #851 but I don't think its related because we are using the Jira Cloud not Jira Server. I don't see any setting to change the default location for attachments. 

I have been through many issues which were reported with similar issue for attachments but couldn't find the solution. Now I am using the latest version and still the same issue.

**Comment by Alexander-Hjelm** [comment]
Ok! Relabeled as a bug, but we are lacking sufficient repro steps to commence work.

Any identified patterns or possible causes are helpful here.

Any chance you could send us a scrubbed screenshot of the history of the issue for which the attachment is failing to migrate, to see what happened with the attachment during each revision?

**Comment by TKallem** [comment]
Hi @Alexander-Hjelm , 

I understand but I haven't done anything different. I have tried for few different user stories and none of their attachments are exporting. Like I said its not even creating the attachments folder. 

However as you asked, please see below screenshots for the history of the user story from Jira. 

![Screenshot 2024-06-10 093319](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/3012436d-74f8-44ed-b808-0f1ce1348a24)
![Screenshot 2024-06-10 093156](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/e267da85-a8ca-4aee-ad2e-cef39332551e)
![Screenshot 2024-06-10 092913](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/2bbd71d8-893c-46db-8af7-203f0b9e6b23)

**Comment by Alexander-Hjelm** [comment]
Does not seem like anything out of the ordinary. Can you confirm that neither of the 3 attachments are exported?

It seems to me that there are two attachments named `Regression.sql` which have been added at different points in time. Can you confirm this? Why is this happening?

**Comment by TKallem** [comment]
None of them are exported. 

There are no two attachments for Regression.sql. I have just taken the screenshots overlapping the last activity.

**Comment by Alexander-Hjelm** [comment]
Ah, ok! My bad.

How many attachments are there in total? Can you send a screenshot illustrating the attachments currently present on the issue?

**Comment by TKallem** [comment]
there are 4 in the attachments section.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/233374e5-8020-44c7-9162-1f375f385c2e)

**Comment by TKallem** [comment]
The top attachment has been added in comments section. 

![Screenshot 2024-06-10 102127](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/c97f732d-34cb-43af-a1bb-3163976b468a)

**Comment by TKallem** [comment]
Hi @Alexander-Hjelm , 

I have done some digging and I think I have resolved the attachments issue. In the field configurations the attachment field was set to hide. 

I have changed to show and now it is exporting attachments. 

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/171953075/b7e24331-e26a-4486-a9e7-be5d136666e7)

**Comment by Alexander-Hjelm** [comment]
Ok! Strange that showing or hiding a field in the GUI should have an effect the API response. Because this is essentially what the hide button does, right?

Are you now able to export all attachments as expected?

**Comment by TKallem** [comment]
@Alexander-Hjelm , Yes its a bit strange one, I was exploring the API response and I couldn't see attachment attribute in JSON, then found out that it needs to be set to show.

I haven't tested for all issues in Jira but I have exported a handful and all of their attachments exported as expected. 

Thank you for your continuous support.

**Comment by TKallem** [comment]
I am closing this issue now.
