### ISSUE TITLE
Option to combine multiple Jira fields to 1 ADO string field

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#105]
Can you add an option to map several fields (and combine them) to one ADO field ? 
It can be very helpful for my migration 

maybe for start you can only support combination of string type fields.

**Comment by MOlausson** [comment]
Good suggestion @AmitNaveh23, I'll add it for triage.

**Comment by mihirsaxena-ril** [comment]
Hi @MOlausson ,

Has this Functionality been added to the latest version of Solidify ? 
If yes, Can you suggest the syntax for the same.

Regards,
Mihir Saxena

**Comment by MOlausson** [comment]
@mihirsaxena-ril not got to this yet but it's bubbling up in priority. I'll bring it up in our next planning meeting.

**Comment by V-MTHOMAS6** [comment]
@MOlausson ,

Is this functionality available now ?

**Comment by MOlausson** [comment]
@V-MTHOMAS6 let me sync up on this, I know we have code for it but not sure if it ever got to the public codebase.

**Comment by V-MTHOMAS6** [comment]
Thanks for the reply, could you please let me know further details?

**Comment by PrashantRanjanTR** [comment]
> @V-MTHOMAS6 let me sync up on this, I know we have code for it but not sure if it ever got to the public codebase.

@MOlausson please share the code to combine multiple Jira fields to 1 ADO string field.

**Comment by V-MTHOMAS6** [comment]
@PrashantRanjanTR  - Thanks, the code base we took got it from this repository doesn't have the code base for this functionality.

If you can refer any branches with latest code, that would be helpful.

**Comment by raja9787** [comment]
Hello,
Has there been any progress on this request? I'm looking for this exact feature on our migration too. would be great if this is possible.

**Comment by Alexander-Hjelm** [comment]
@raja-17 @PrashantRanjanTR @thomasmebin @mihirsaxena-ril @AmitNaveh23 

This feature has been implemented in PR https://github.com/solidify/jira-azuredevops-migrator/pull/693.

If anyone of you are still using our tool, could you give this PR a try and let us know if the new mapper solves your needs?

**Comment by raja-17** [comment]
Great! I'm done with our migration. But one of our other teams is working
on theirs. I'll have them try it out if they need it. thanks

**Comment by Alexander-Hjelm** [comment]
Reverted PR. This feature will be available through paid engagements with Solidify,

Closing issue for now. Feel free to reach out to us at info@solidify.dev for inquiries
