### ISSUE TITLE
Jira exporting stop while downloading .docx type attachment

### ISSUE THREAD

**Issue by sgullluu** [solidify/jira-azuredevops-migrator#106]
tool is not able to download docx type attachment. It is not giving any error but it stopped the exporting. after we removed the docx file from the issue then only it is exported.

**Comment by rpdomingo** [comment]
For me its working, docx file is downloaded and successfully imported to azuredevops

**Comment by MOlausson** [comment]
@sgullluu it works for me as well. Can you try again and share the logfile? Even if the process hangs and is terminated we should see at what step it stopped.

**Comment by rpdomingo** [comment]
@MOlausson it's also possible to migrate Sprint Boards in Jira to azuredevops Boards?

**Comment by rpdomingo** [comment]
@MOlausson I've also notice one of my exported file didn't imported to AzureDevOps. Please see below details:

Successfully exported 8 json file
![image](https://user-images.githubusercontent.com/26340099/67168208-86b2ec80-f3d4-11e9-9f78-027bbb727995.png)

When imported to AzureDevOps **xr-3** not included
![image](https://user-images.githubusercontent.com/26340099/67168242-d7c2e080-f3d4-11e9-989c-bf39226c75cc.png)

Thanks in advance :)

**Comment by sgullluu** [comment]
it is working for me now.
thanks
