### ISSUE TITLE
How to map the Jira issue type to a custom field in a DevOps issue?

### ISSUE THREAD

**Issue by cacti77** [solidify/jira-azuredevops-migrator#1062]
**Describe the problem**
How can you set a field in a DevOps Issue based on the _type_ of a Jira issue?

**To Reproduce**
In the source Jira project to migrate I have only Bugs and Improvements. In the target DevOps project I only have Issues. (My DevOps process is inherited from Basic and has both Epic and Task disabled). To distinguish between bugs and improvements in the DevOps project I therefore added a new field to Issue called 'Issue Type' (ref name _Custom.IssueType_). It is a required field of type _picklist (string)_ with 2 possible values: _Bug_ or _Improvement_.

In my config json for jira-export I have this to map all the Jira types to Issue:
```
 "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Issue"
      },
      {
        "source": "Improvement",
        "target": "Issue"
      },
      {
        "source": "Bug",
        "target": "Issue"
      }
    ]
  },
```
I also have this to try to map the issue type in Jira to my custom field:
```
  "field-map": {
    "field": [
     {
        "source": "type",
	"target": "Custom.IssueType"
      },
```
The jira-export tool runs without error, but no field called Custom.IssueType appears in the json files representing the Jira issues. Hence when the issues are imported into DevOps their required field 'Issue Type' is left unset.

It looks like the type of the Jira issue is only interpreted by the _type-map_ field of the config json, and can't also be referred to as a field under _field-map_. Hopefully I'm wrong about this!

Great tool, BTW, thanks a lot!

**Tool version**
3.0.442

**Comment by Alexander-Hjelm** [comment]
I believe like this, in the simplest possible form!

The below mapping would work for a Text (Single line) field in Azure DevOps:

```json
"field-map": {
  "field": [
    {
      "source": "issuetype",
      "target": "Custom.IssueType",
    }
  ]
}
```

You can use the `issue/createmeta` API endpoint to retrieve a list of all available fields, for example:

```
GET https://myorg.atlassian.net/rest/api/2/issue/createmeta?projectKeys=MYPROJ&issuetypeNames=Task&expand=projects.issuetypes.fields
```

**Comment by cacti77** [comment]
Perfect - that worked! The json files now have that field and the 'Issue Type' field is now populated when they're imported into DevOps. Thank you so much.
(Weirdly, on my Jira server that GET call only returned an empty list for _issuetypes_, but you've fixed this anyway.)
