### ISSUE TITLE
Field 'Activated Date' cannot be empty

### ISSUE THREAD

**Issue by nickn00** [solidify/jira-azuredevops-migrator#1077]
When migrating to a CMMI template, the standard ADO workflow is "Proposed" as the initial state and not "New".

In the function CorrectActivatedByAndActivatedDate, it only picks up the state change from "New" to another state and sets the activated date accordingly.

It doesn't pick up the change in state from "Proposed" to another, so never sets the "Activated Date" and throws the following error in Devops:

Field 'Activated Date' cannot be empty

![image](https://github.com/user-attachments/assets/061cab14-06a8-4bd1-a12b-eba22052db99)

Version 3.0.486

**Comment by nickn00** [comment]
Scrum will probably have the same issue with Tasks
![image](https://github.com/user-attachments/assets/a2eaf261-a07d-4447-b50b-2c983c5bee6e)

**Comment by Alexander-Hjelm** [comment]
This feature is included in the Jira Azure DevOps Migrator PRO offering.

You can read more about the various features available here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-azure-devops-migrator-pro

See this one in particular:

> Support for state transition dates (e.g. ActivatedDate, ClosedDate) for workflows with custom states. By default, only New, Closed and Done are supported.

**Comment by nickn00** [comment]
@Alexander-Hjelm, ah, thank you.  Managed to include the proposed state in the source code, but I won't do a pull request if you're keeping it a PRO feature.
