### ISSUE TITLE
Columns mapping issue while migrating boards from JIRA to ADO

### ISSUE THREAD

**Issue by vani760** [solidify/jira-azuredevops-migrator#1082]
Hi Team,

we are migrating boards from JIRA to ADO through Solidify Migrator tool.
for custom columns mapping is not working properly , in ADO for those columns we are getting blank. can you please help us to resolve this issue

<img width="329" alt="Screenshot 2024-12-17 203441" src="https://github.com/user-attachments/assets/4a79b865-653e-422b-b48a-514546d639aa" />

Thanks,
Vani

**Comment by Alexander-Hjelm** [comment]
@vani760 
I see so many problems with your configuration. Please open a new issue for every specific question you have.

Please consult the documentation here for an overview of what you can do with the config file: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md

Config samples can be found here: https://github.com/solidify/jira-azuredevops-migrator/tree/master/docs/Samples

Frequently asked questions, including advice on how to map custom fields: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

**Comment by vani760** [comment]
Hi @Alexander-Hjelm 
could you please let me know how to map Jira custom fields for example fix version, component, these fields i need to map these are custom field.
