### ISSUE TITLE
List of Mapper Function Values

### ISSUE THREAD

**Issue by kmuthukumar-rp** [solidify/jira-azuredevops-migrator#109]
Hello, 
        You have specified 'Mapper' property used for field mapping as 'mapper function used for value translation'. Where can we find the different values available for this property. If in our Azure Server instance, can you please provide some guidance on where to find this info. Thank you.

**Comment by AmitNaveh23** [comment]
hey @kmuthukumar-rp , Mappers are small conversion functions that translate more complex fields, for instance an array. It's not fully documented yet but you can find the implementation at the end of -  https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraMapper.cs

**Comment by kmuthukumar-rp** [comment]
Hi @AmitNaveh23, thank you appreciate it.

**Comment by MOlausson** [comment]
The mapping logic is naive and something we would like to improve. I've added a section that lists the different mapper and their purpose for now, see https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#mappers. But the best way to really understand (and if needed, extend) is to check out the code as @AmitNaveh23 suggested.
