### ISSUE TITLE
Jira to Azure DevOps (VSTS or TFS) migration article is not available

### ISSUE THREAD

**Issue by brysk** [solidify/jira-azuredevops-migrator#112]
Dears,

I have been trying to access Jira to Azure DevOps (VSTS or TFS) migration article by following the link in README: https://solidify.se/jira-azure-devops-migration/ but unfortunately it's not available anymore, I'm getting 404 error message.

Any chance you can fix it or provide new link?

**Comment by MOlausson** [comment]
Thanks for reporting @brysk, updated the links now.
