### ISSUE TITLE
Bulk emails received by the Assigned Person of a workitem during Migration

### ISSUE THREAD

**Issue by piyaln** [solidify/jira-azuredevops-migrator#113]
Hi
We noticed that the Work item assigned person will get emails (1 email per assigned issue) during the migration which is annoying. I think better option is that either it has to be completely disabled or there should be a setting in the config file to disable or enable it.

Regards
Piyal

**Comment by MOlausson** [comment]
Hi @piyaln, not sure we can control that but will take a look.

**Comment by AmitNaveh23** [comment]
@piyaln you can control it yourself in the project\organization settings. Just turn off the notifications during the migration and return them after.
https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops-2019

**Comment by piyaln** [comment]
Thanks Amit. Will try this suggestion and let you know the result.

**Comment by MOlausson** [comment]
@piyaln I don't see any way we can disable the notifications since it's a configured behaviour in Azure DevOps. Closing this one for now.
