### ISSUE TITLE
Inline images not showing up in migrated items

### ISSUE THREAD

**Issue by mgurevich69** [solidify/jira-azuredevops-migrator#114]
Hello team.

I apologize if this a known issue. Just noticed that inline images in imported items don't show up. Instead they show as `Test comment with a picture inline !image-20191106-180232.png|width=638,height=467!`
However, the images available in attachments tab.

Would be great to hear a solution.

**Comment by MOlausson** [comment]
Hi @mgurevich69, thanks for reporting this. Where are you having problem with the images? Is it in the description texts, comments or other?

**Comment by mgurevich69** [comment]
The issue is occurring with User Story body images. When migrated images don't get rendered in the content.

**Comment by MOlausson** [comment]
Fixed from r2.2.57.
