### ISSUE TITLE
Error in Building jira-azuredevops-migrator using Azure DevOps Pipeline

### ISSUE THREAD

**Issue by piyaln** [solidify/jira-azuredevops-migrator#115]
Hi
I downloaded the jira-azuredevops-migrator-2.2.46 code and created a repo in Bitbucket and defined an Azure DevOps Pipeline for the Project. But it failed with 3 errors and see the attached debug log file. - Oh I cant see a way of attaching too.
Here is the error log text:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Build solution **\*.sln
3 errors
1 warning
14s
D:\a\1\s\src\WorkItemMigrator\WorkItemMigrator.sln.metaproj(0,0): Error MSB3202: The project file "D:\a\1\s\src\WorkItemMigrator\Migration.Common.Log\Migration.Common.Log.csproj" was not found.
src\WorkItemMigrator\Migration.WIContract\WiItemProvider.cs(1,17): Error CS0234: The type or namespace name 'Common' does not exist in the namespace 'Migration' (are you missing an assembly reference?)
Process 'msbuild.exe' exited with code '1'.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I think it refers Migration.Common.Log.csproj project which is missing.  How to resolve this? Can I have code for that ?

Also I attached the .Net Build configs 

Note:
My intention is to customize/fix issues in jira-azuredevops-migrator  (i.e. optimize) the tool.

Regards
Piyal

**Comment by piyaln** [comment]
[7.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3818013/7.txt)
[migrator ADO pipeline config.docx](https://github.com/solidify/jira-azuredevops-migrator/files/3818021/migrator.ADO.pipeline.config.docx)

Above are the attachments

**Comment by piyaln** [comment]
Hi MOLaussson

Any update on this?

Regards
Piyal

**Comment by MOlausson** [comment]
Hi @piyaln, I've updated the documentation on how to build the project locally, it does however require Windows and Visual Studio 2019 to do so. See https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/CONTRIBUTING.md.

**Comment by piyaln** [comment]
Thanks, Will check and get back to you.
