### ISSUE TITLE
Write log with all failures details

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#120]
It would be great if there will be a separate import & export log with all of the summary and details about all the issues that failed. 
It would really help for big migrations like mine. It's really uncomfortable to look for failed issues in a big export\import log which most of the work items successfully migrated.

My suggestion for log format - 
1- start with a list of all work items (their keys) that didn't migrate properly 
2- (for the import log) then will be the links that didn't complete 
3- full data regarding the failure for each work item

Thanks

**Comment by MOlausson** [comment]
Good suggestion @AmitNaveh23, we'll address when we're making some other improvemnts to the logging that we have planned.

**Comment by Alexander-Hjelm** [comment]
Continued in #223
