### ISSUE TITLE
Detected a unicode character, failed to import

### ISSUE THREAD

**Issue by sgullluu** [solidify/jira-azuredevops-migrator#123]
while importing the data to azure devops few workitems is not getting imported with below error.

[I][12:59:25] Building execution plan...
[W][12:59:31] Detected unicode characters, removed.
[W][12:59:31] Failed to load 'TEJ-11340.json' (perhaps not a migration file?).
[W][12:59:33] Detected unicode characters, removed.
[W][12:59:33] Failed to load 'TEJ-47340.json' (perhaps not a migration file?).
[W][12:59:42] Detected unicode characters, removed.
[W][12:59:54] Detected unicode characters, removed.
[W][12:59:54] Detected unicode characters, removed.
[W][12:59:54] Failed to load 'TEJ-5679.json' (perhaps not a migration file?).
[W][13:00:02] Detected unicode characters, removed.
[W][13:00:03] Failed to load 'TEJ-1079.json' (perhaps not a migration file?).

**Comment by MOlausson** [comment]
@sgullluu can you share one of the exported json files? It sounds like we may have an issue with the unicode replacement.

**Comment by sgullluu** [comment]
Hi @MOlausson : please check the attachment.

[TEJ-11340.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3854086/TEJ-11340.zip)

**Comment by MOlausson** [comment]
Thanks @sgullluu, I found we had a bad regexp for replacing unicode characters, pushing a fix for this now.

**Comment by MOlausson** [comment]
Fixed in r2.2.59.

**Comment by sgullluu** [comment]
@MOlausson : now it is not exporting workitem from jira having unicode character.

i have exported unicode data from version 2.46 and imported from 2.2.59

**Comment by sgullluu** [comment]
@MOlausson :still i am getting same error. i have attached
[sdk.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3880101/sdk.zip)
[wi-import-log-191122-202714.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3880102/wi-import-log-191122-202714.txt)

 the json file and log file.

**Comment by AmitNaveh23** [comment]
+1, happens in a few work items
for example, I've had that Unicode character which failed the import - '\u001B'
