### ISSUE TITLE
Epic link field missing for config field 'Epic Link'.

### ISSUE THREAD

**Issue by svenSternberg** [solidify/jira-azuredevops-migrator#144]
Hi community,
when trying to export the JIRA issues I am getting the following warnings and no issue has been exported.
[I][20:46:38] Export started. Exporting 0 items.
[W][20:46:38] Epic link field missing for config field 'Epic Link'.
[W][20:46:39] Sprint link field missing for config field 'Sprint'.

Your help is needed quite urgently as we are running out of time :-(

**Comment by MOlausson** [comment]
@svenSternberg can you share the log and your config file?

**Comment by svenSternberg** [comment]
Hi @MOlausson this is my log file:
====================================================================
Jira Export Log
====================================================================
Tool version : 2.2.59
Start time   : 05.12.2019 21:44:23
Telemetry    : Enabled
Session id   : b5060a82-9502-4ec4-b7bd-d3f64d5eebd9
Tool user    : ###MYuser
Config       : config-scrum.json
Force        : yes
Log level    : Info
Machine      : ###MyPC
System       : Microsoft Windows 10.0.16299
Jira url     : MyJiraURL
Jira user    : MyJiraUser
Jira version : 1001.0.0-SNAPSHOT
Jira type    : Cloud
====================================================================
[I][21:44:21] Connecting to Jira...
[I][21:44:21] Retrieving Jira fields...
[I][21:44:22] Retrieving Jira link types...
[I][21:44:23] Export started. Exporting 0 items.
[W][21:44:23] Epic link field missing for config field 'Epic Link'.
[W][21:44:23] Sprint link field missing for config field 'Sprint'.
[I][21:44:23] Initializing Jira field mapping...
[I][21:44:24] Export complete. Exported 0 items (0 errors, 2 warnings) in 00:00:02.

and this my config:

**Comment by svenSternberg** [comment]
myconfig file

**Comment by MOlausson** [comment]
@svenSternberg it looks like your query returns nothing ("query": "issuekey = xxx-xxx"), check step 1 in https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md#migrate-work-items on how to define the query that matches the set if issues to export.

**Comment by svenSternberg** [comment]
@MOlausson I don´t think so. This query actually returns the issue with the project XXX and Key xxx in my current JIRA environment.

**Comment by svenSternberg** [comment]
@MOlausson any news?

**Comment by svenSternberg** [comment]
issue was related to user in config.json file. The complete username (email) solved the problem.

**Comment by MOlausson** [comment]
@svenSternberg thanks for for closing the loop. Did you mean using the full email to login?

**Comment by svenSternberg** [comment]
@MOlausson yes I meant the full email to logon.

**Comment by MOlausson** [comment]
Thanks for confirming @svenSternberg.
