### ISSUE TITLE
Error in uploading test case steps and expected result through excel in Azure devops.

### ISSUE THREAD

**Issue by Akhithareddy** [solidify/jira-azuredevops-migrator#145]
I am currently unable to upload Test Case Steps (Step Action and Step Expected Result) from MS Excel into Azure DevOps.
Is this possible? We need this functionality urgently in order to upload data in bulk from MS Excel into the tool. Is this possible at all?
I can import the Test Cases but the test steps are not imported.

**Comment by Akhithareddy** [comment]
I am currently unable to upload Test Case Steps (Step Action and Step Expected Result) from MS Excel into Azure DevOps.
Is this possible? We  need this functionality urgently in order to upload data in bulk from MS Excel into the tool. Is this possible at all?
I can import the Test Cases but the test steps are not imported.

**Comment by MOlausson** [comment]
Hi @Akhithareddy, the tool is only intended to migrate from Jira to Azure DevOps. We may be able help you with test cases as well, contact us at info@solidify.se to discuss this further.
