### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added - still exists

### ISSUE THREAD

**Issue by runerasmussen** [solidify/jira-azuredevops-migrator#147]
Hi,

Release v2.3.10 was supposed to resolve #139 
Unfortunately I am still experiencing the issue.
Details on my issue is posted in Pull Request #140 

Direct link:
https://github.com/solidify/jira-azuredevops-migrator/pull/140#issuecomment-562089409

Please can you take a look if this is the same issue or a new one?

**Comment by madkoo** [comment]
@runerasmussen, looking at the log you provided it looks like to me that in your user mapping file you have a duplicate user mapping.

**Comment by runerasmussen** [comment]
@madkoo, thanks for interpretating the log. I did have duplicate in the user mapping file.
Thank you for a quick response. I am closing the issue.
