### ISSUE TITLE
Exception : "VS402625: Dates must be increasing with each revision"

### ISSUE THREAD

**Issue by yfrindel** [solidify/jira-azuredevops-migrator#152]
Hi,
The tool is excellent, but I have some revisions not imported during the migration with the following error message :

**[Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException] Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: TF237121: Cannot complete the operation. An unexpected error occurred.
Technical information (for administrator):
VS402625: Dates must be increasing with each revision.**

Could you help me to find a solution, or could you manage this case of error please ? (log in attachments)
[wi-import-log-191209-184543.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3941062/wi-import-log-191209-184543.txt)

**Comment by MOlausson** [comment]
@yfrindel sorry about this. Can you share a scrubbed version of the HEM-907 json file? Also are you using the latest code?

**Comment by yfrindel** [comment]
Hi @MOlausson. I've updated the program today, so yes the code is up-to-date. You'll find all the files in attachments.
[JiraImport.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3941462/JiraImport.zip)
Thx

**Comment by yfrindel** [comment]
For an unknown reason, the "changedDate" value is automatically modified by Azure DevOps after the revision 4. It's maybe due to the workflow. I can fix the problem with these modifcations of code, but with this solution the changedDate are modified and so not correct. 
![image](https://user-images.githubusercontent.com/22955005/70469932-4d405880-1aca-11ea-8206-5b493f44bb32.png)

**Comment by yfrindel** [comment]
Maybe we could check here if the changedDate of the work item is corresponding to the previous revision : 
![image](https://user-images.githubusercontent.com/22955005/70470119-a27c6a00-1aca-11ea-9940-9bc172c99dc1.png) and if it's not the case an update could be done to rectify the changedDate value ?

**Comment by madkoo** [comment]
@yfrindel, I investigated and what I noticed right now is that there might be a state conflict that is causing Azure DevOps to modify the "change date" . Looking at the HEM-907.json then the last state change is to "Active" and the root item has the same state which shouldn't be correct. To my knowledge, the first revision should have the previous state which in this case is "Resolved" because I see only two state changes. 

What happens if you export this issue once more, do you get the same JSON result that you provided us?

**Comment by yfrindel** [comment]
Hi @madkoo ,
thx for your help.
I have not the problem only with 1 work item, but with a lot of work items.
Take a look on this complete report (JSON files also added)
[JiraImport2.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3956237/JiraImport2.zip)
[wi-import-log-191205-153246.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3956244/wi-import-log-191205-153246.txt)

**Comment by yfrindel** [comment]
And that's the history of the ticket on JIRA :
![image](https://user-images.githubusercontent.com/22955005/70721989-ca501580-1cf6-11ea-9aeb-52d5e03566eb.png)

**Comment by madkoo** [comment]
@yfrindel  is it possible for you to provide your config file?

**Comment by yfrindel** [comment]
yes, of course 
[config-scrum.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3956414/config-scrum.zip)

**Comment by yfrindel** [comment]
N.B : the issue happens in the revision 5, not in the last revision 
![image](https://user-images.githubusercontent.com/22955005/70793425-8ebb5700-1d9b-11ea-80f9-e0c62614cd17.png)

**Comment by MOlausson** [comment]
Fixed in v2.3.36.

**Comment by StephenWTurner** [comment]
I've also found this issue occurs if you poke around in the work items as they are being created by the importer. It seems they are updated just by looking at them.

The simple solution is to leave the project alone until the import is completed.
