### ISSUE TITLE
Add option to define default target user mapping

### ISSUE THREAD

**Issue by Jura** [solidify/jira-azuredevops-migrator#16]
Add [optional] possibility to indicate default target user account which should be used to map all unmappable usernames from source repository. Usually there are many historical entities which do not have counterparts in the new setup so export tool should map those to default user.

**Comment by Jura** [comment]
Can it be implemented as a fallback option? I mean if specific user is not provided explicitly but wildcard option is present.

**Comment by MOlausson** [comment]
Yes. Checkout the latest release, we've added the * match so now explicit first then if * is present we map to a default user, if not then we copy over the source value.

**Comment by Jura** [comment]
@MOlausson , I've tested release [2.1.1](https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v2.1.1) and also I have `*=[username]` line in my users.txt mapping file exporter doesn't use it - that's what I got in revisions (partial excerpt):

```
		}, {
			"Author": null,
			"Time": "2018-12-14T02:01:52-05:00",
			"Index": 1,
			"Fields": [],
			"Links": [],
			"Attachments": [],
			"AttachmentReferences": false
		}, {
			"Author": null,
			"Time": "2018-12-14T08:05:51-05:00",
			"Index": 2,
			"Fields": [],
			"Links": [],
			"Attachments": [],
			"AttachmentReferences": false
		}, {
			"Author": null,
			"Time": "2018-12-14T08:10:08-05:00",
			"Index": 3,
			"Fields": [],
			"Links": [],
			"Attachments": [],
			"AttachmentReferences": false
		}, {
```

**Comment by pliljecrantz** [comment]
We will not implement the default user functionality on unassigned tasks or revisions without an author (this last one was your use case) at this moment. Especially for revisions it will throw the history off when setting the author to a user that did not make the change in the beginning, so we have decided not to implement that. For unassigned work items we recommend you to do a bulk update on the imported work items to set them to a default user if you want that.

**Comment by quadmig** [comment]
@pliljecrantz , what is your recommendation for work items that are unassigned during the history of the work item?  We have a lot of items that originally assigned to staff and then changed to unassigned while they waited in the backlog to be selected for a sprint, but this causes the history item to fail to import.

[I][15:19:58] Processing 9/20 - wi '4282', jira 'ERTA-1, rev 8'.
[E][15:19:58] Failed to import revisions for '4282'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkItemImport.Agent.EnsureAssigneeField(WiRevision rev, WorkItem wi)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi): 
   at WorkItemImport.Agent.EnsureAssigneeField(WiRevision rev, WorkItem wi)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi)

This is rev 8
"Index":8,"Fields":[{"ReferenceName":"System.AssignedTo","Value":null}],"Links":[],"Attachments":[],"AttachmentReferences":false},{"Author":"flast@oururl.com","Time":"2018-06-11T11:48:17.42-05:00"

I would be fine if it imported as blank/unassigned or as some default migration user; as long as the change imports.

**Comment by pliljecrantz** [comment]
@quadmig Which version of the tool are you using?

**Comment by quadmig** [comment]
2.2.31

**Comment by pliljecrantz** [comment]
@quadmig How does the user file look? If that is used it should not throw an exception but if it does we have to take a look at it.

**Comment by quadmig** [comment]
@pliljecrantz , The user file has about 30 names on it that are matching correctly.  

I tried putting *=itsd.quadmig@oururl.com at the end of the user file but with it or without it I get the same error.
