### ISSUE TITLE
Removed labels in Jira also migrates

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#164]
Hey, 

I've noticed that if I have a ticket in Jira that had a label and later on that same label was deleted, the tool does not delete that label and it exists as a tag in the ADO work item

**Comment by MOlausson** [comment]
Hi @AmitNaveh23, this sounds like a case we're not covering. We'll investigate!

**Comment by madkoo** [comment]
@AmitNaveh23 this will be fixed in the up coming release. Closing this issue at the moment. If you still experience problems in the upcoming new release feel free to reopen this issue.
