### ISSUE TITLE
Unable to Link Sub Tasks in JIRA as Tasks to User Story

### ISSUE THREAD

**Issue by mihirsaxena-ril** [solidify/jira-azuredevops-migrator#166]
Hello,

While using the jira-export.exe, I am facing two issues:
1. I am unable to extract Sub-tasks from JIRA
The following error is displayed
![image](https://user-images.githubusercontent.com/56682753/71727292-c92a8800-2e5f-11ea-88fd-4e7183f09012.png)
Whereas, In the code I have made a type-map:
{
				"source": "Sub Task",
				"target": "Task"
			},
			
			{
				"source": "Story",
				"target": "User Story"
			},

Does the sequence of appearance matter here: Sub-task appearing before Story.

2. Is there some format specification for attachments: I am able to download .jpg but when a story contains a .msg extension the program stops running.
![image](https://user-images.githubusercontent.com/56682753/71727245-a009f780-2e5f-11ea-9b72-c632acd52484.png)
 As you can see, I am unable to go past item 53/82 while exporting.

Would really appreciate if someone can help out !

Regards,
Mihir

**Comment by MOlausson** [comment]
Hi @mihirsaxena-ril, 

Regarding 1. you need to add a dash in the issue type name, "Sub-task" instead of "Sub Task".

      {
        "source": "Sub-task",
        "target": "Task"
      }

Consering 2. - can you provide us with the log file or the session id (in the log file) then we can invesigate.

**Comment by mihirsaxena-ril** [comment]
Hi @MOlausson , 

Thank you for your reply.
Will implement the change and run the file once again. Will share the log file ASAP.

**Comment by mihirsaxena-ril** [comment]
Hi @MOlausson ,

Since our JIRA instance is On Prem, Sharing the Log file snippet where we are facing an issue w.r.t Attachments. 
**Attachment of .XLSX is closing the command**
`[I][14:15:51] Processing 128/252 - 'CEDS19001-125'.
[D][14:15:51]    Downloaded item.
[D][14:15:51]    Rendered field customfield_10106 contains unparsable type Null, using text
[D][14:15:51]    Rendered field workratio contains unparsable type Null, using text
[D][14:15:51]    Rendered field priority contains unparsable type Null, using text
[D][14:15:51]    Rendered field customfield_10100 contains unparsable type Null, using text
[D][14:15:51]    Rendered field customfield_10101 contains unparsable type Null, using text
[D][14:15:51]    Rendered field customfield_10102 contains unparsable type Null, using text
[D][14:15:51]    Rendered field assignee contains unparsable type Null, using text
[D][14:15:51]    Rendered field status contains unparsable type Null, using text
[D][14:15:51]    Rendered field attachment contains unparsable type Array, using text
[D][14:15:51]    Rendered field summary contains unparsable type Null, using text
[D][14:15:51]    Rendered field creator contains unparsable type Null, using text
[D][14:15:51]    Rendered field reporter contains unparsable type Null, using text
[D][14:15:51]    Rendered field customfield_10000 contains unparsable type Null, using text
[D][14:15:51]    Downloaded issue: CEDS19001-125 changelog.
[D][14:15:51]    Undone attachment 'Added 10375/Migration Status_13_09_19.xlsx'.
[D][14:15:51]    Created 10 history revisions.
[D][14:15:51]    Mapping revision 0.
[D][14:15:51]    Mapped value 'R&M - IT - Provide weekly update and check status' to field 'System.Title'.
[D][14:15:51]    Mapped value 'Data Visualizations - Sprint 4' to field 'System.IterationPath'.
[D][14:15:51]    Mapped value '3' to field 'Microsoft.VSTS.Common.Priority'.
[D][14:15:51]    Mapped value '10' to field 'Microsoft.VSTS.Scheduling.StoryPoints'.
[D][14:15:51]    Mapped value 'Abhik.Bhattacharya' to field 'System.CreatedBy'.
[D][14:15:51]    Mapped value 'To Do' to field 'System.State'.
[D][14:15:51]    Mapping revision 1.
[D][14:15:51]    Mapping revision 2.
[D][14:15:51]    Mapping revision 3.
[D][14:15:51]    Mapped value 'Tejashri.Jambure@ril.com' to field 'System.AssignedTo'.
[D][14:15:51]    Mapping revision 4.
[D][14:15:51]    Mapping revision 5.
[D][14:15:51]    Mapping revision 6.
[D][14:15:51]    Mapped value 'In Progress' to field 'System.State'.
[D][14:15:51]    Mapping revision 7.
[D][14:15:51]    Downloading attachment info for attachment '10375'.`

Alternatively, Session ID is 983c91e1-ffba-4f4a-a777-e3e646cbdb6a

**Comment by mihirsaxena-ril** [comment]
Hi @MOlausson ,

As per my discussion with peers ,There is some policy issue on my System which prevented me from Downloading attachments.
It worked on another colleagues system.

I am unable to get mapping of some custom Issue Types in my JIRA instance,
In type Map
`{
				"source": "Impediment",
				"target": "Impediment"
			},
			{
				"source": "Spike",
				"target": "Spike"
			}`
In Error File
`[I][10:52:24] Processing 18/55 - 'CEEC19017-38'.
[D][10:52:25]    Downloaded item.
[D][10:52:25]    Created 4 history revisions.
[D][10:52:25]    Mapping revision 0.
[D][10:52:25]    Mapping revision 1.
[D][10:52:25]    Mapping revision 2.
[D][10:52:25]    Mapping revision 3.
[D][10:52:25]    Exported as type 'Impediment'.
`

**Comment by mihirsaxena-ril** [comment]
All attachment issues have been resolved.
