### ISSUE TITLE
Discussion contains elements that should be in "History" tab in devops after migration

### ISSUE THREAD

**Issue by phoez** [solidify/jira-azuredevops-migrator#168]
After migration I've noticed that my issues have comments in discussion like

"Removed attachments(s): [Removed] 25397/"
and 
"Added link(s): [Added] "JIRA-XXX-1"->"DEVOPS-XXX-1" [System.LinkTypes.Hierarchy-Reverse]"

Additonally when importing attachements it imports two files per 1 image, thumb and full one.

**Comment by madkoo** [comment]
@phoez  thank you for your input :). 
The comments that you mentioned in the discussion are there by implementation to have trace ability.
The second issue that you reported will be fixed in the latest release v2.3.41.

**Comment by madkoo** [comment]
Closing this issue in lack of further response. @phoez feel free to reopen if you still experience problems
