### ISSUE TITLE
Issue with Linking User Stories with Sub Tasks

### ISSUE THREAD

**Issue by mihirsaxena-ril** [solidify/jira-azuredevops-migrator#170]
In our JIRA system ver 7.12, User Story are linked with Sub-Task not Tasks.
My JSON config file has Used following Link types:
`
"link-map": {
		"link": [

			{
				"source": "Relates",
				"target": "System.LinkTypes.Related"
			},
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
				"source": "Child",
				"target": "System.LinkTypes.Hierarchy-Reverse"
			},

			{
				"source": "Duplicate",
				"target": "System.LinkTypes.Duplicate-Forward"
			},

			{
				"source": "Cloners",
				"target": "System.LinkTypes.Related"
			},

			{
				"source": "Epic",
				"target": "System.LinkTypes.Hierarchy-Reverse"
			},
			{
				"source": "Blocks",
				"target": "System.LinkTypes.Related"
			}
		]
	},`
However on Export Log,
I get the following warning:
 Link with description 'This issue is blocked by CECE19017-205' is either not found or this issue (CECE19017-156) is not inward issue.

This happens for many user Stories

Require Urgent Help.

**Comment by mihirsaxena-ril** [comment]
@MOlausson Hi,

Can you assist me on this ?

Regards,
Mihir

**Comment by madkoo** [comment]
@mihirsaxena-ril sorry for the late response. Are you still stuck with this issue ?

One thing that I noticed in your linking config is the "Child"  link has "System.LinkTypes.Hierarchy-Reverse" but according to [MS Documenation](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20item%20relation%20types/list?view=azure-devops-rest-5.1) the Child link should have "System.LinkTypes.Hierarchy-Forward". "

**Comment by mihirsaxena-ril** [comment]
Hi @madkoo ,

Thank you for the response. I was able to take care of the issue on a case-by-case basis.
Thanks to your tool I was able to get JIRA data imported to Azure

**Comment by madkoo** [comment]
Sorry again for the late response but Happy to hear you were able to take care of your issue. Thank you for your positive feedback we appreciate it :)

**Comment by punyautkalika** [comment]
@mihirsaxena-ril  I am having the same issue . can you please let me know how you have solved
