### ISSUE TITLE
Work item is not ready to save.

### ISSUE THREAD

**Issue by sgullluu** [solidify/jira-azuredevops-migrator#173]
while trying to migrate from Jira 5.2 to azure devops , most of the issues are getting below error.

Error message
[Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException] Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException: TF237124: Work Item is not ready to save
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)

[JCANDROID-2346.zip](https://github.com/solidify/jira-azuredevops-migrator/files/4084731/JCANDROID-2346.zip)

**Comment by sgullluu** [comment]
is there any way to ignore the resolved date or Change date field through Json ? iam geeting this error because they have invalid format like " 01/Jan/12" or "14/April/17".
why this fields are migrated automatically?

**Comment by madkoo** [comment]
@sgullluu Those fields are migrated to get correct state and history of workitem changes. Otherwise the history the dates will have time datetime when the import is ran. 
Why do you believe the format is incorrect ? can you provide more information ?

**Comment by madkoo** [comment]
Closing this issue in lack of further response. @sgullluu  feel free to reopen if you still experience problems
