### ISSUE TITLE
Is it possible to map watchers?

### ISSUE THREAD

**Issue by anamarioc** [solidify/jira-azuredevops-migrator#174]
Hello team,

Is it possible to map the watchers in Jira with the followers in Azure?
I'm not sure about the "target" value.

{
        "source": "watcher",
        "target": "what's the value here??",
        "mapper": "MapUser"
}

Thank you and Best Regards,
Ana

**Comment by madkoo** [comment]
@anamarioc Sorry for the late response, but at the current time Azure Devops does not support this action.
If you have other problems feel free to contact us.

**Comment by anamarioc** [comment]
@madkoo that's ok, thanks for the reply.
