### ISSUE TITLE
Symantec Endpoint Protection blocks .exe's

### ISSUE THREAD

**Issue by phoez** [solidify/jira-azuredevops-migrator#176]
![image](https://user-images.githubusercontent.com/9357970/73159799-ababaf80-40e7-11ea-891f-ce22d80e2bd6.png)

I can freely use version 2.2.31 but from this version upwards files get quarantined with infected status.

**Comment by MOlausson** [comment]
Hi @phoez, we haven't seen this. Can you share a bit more about what you see? Any logs explaining what Symantic is triggering on?

**Comment by phoez** [comment]
![image](https://user-images.githubusercontent.com/9357970/73246508-12e06700-41af-11ea-8b51-72714ceecb00.png)
https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973

Basically I think it just quarantines it because of no new info about it but just wanted to let you guys know that this does and can happen.

**Comment by MOlausson** [comment]
Thanks @phoez for brining this to our attention. We'll investiage if we should send info to Symantec since it incorrectly blocks our .exes.
