### ISSUE TITLE
Unable to get jira export working 

### ISSUE THREAD

**Issue by Shyamal0212** [solidify/jira-azuredevops-migrator#178]
Command: jira-export -u user.name -p XXXXX --url jiraURL --config config-scrum.json --force
Error:
Copyright (c) Solidify
[I][15:55:15] Connecting to Jira...
[I][15:55:15] Retrieving Jira fields...
[I][15:55:18] Retrieving Jira link types...
[E][15:55:20] Failed to get item count using query: 'project = CTUCC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'CTUCC' does not exist for the field 'project'."],"errors":{}}

I tried with username, email address, password, API Token but it didnt work for me. Same JQL is working in jira. Can you please help asap?

**Comment by madkoo** [comment]
Hi @Shyamal0212 , looking at the error then the first question I would ask is that is the project name correct that you are using? 
Secondly how does you full query look like in the configuration file ?

**Comment by Shyamal0212** [comment]
Hi @madkoo,
My full query is taken from JQL and it looks like below:
 "query": "project = <projectKeyInJira>",
I also tried with different queries such as - 
project = <JiraProjectFullName> AND issuetype = Bug
But all these ended up with same error. 

Interesting thing to note is - 
even if I provide wrong password in the Jira export command, I get the same error as {"errorMessages":["The value '_NAME_' does not exist for the field 'project'."],"errors":{}}

This is command I am using:
jira-export -u USERNAME -p PASSWORD --url https://jira.DOMAIN.io/  --config config-scrum.json --force

I also tried with all combinations of email ID instead of user name and API Token instead of Password but ended up with same error as above.

**Comment by madkoo** [comment]
@Shyamal0212  , in the query you have not provided any project name.

**Comment by Shyamal0212** [comment]
I had provided the project name in quotes which removed everything let me paste it again - 
"query": "project = ProjectKeyInJira",
I also tried with different queries such as -
project = 'ProjectKeyInJira AND issuetype = Bug

Also tried with project full name inside '' instead of project key.

**Comment by madkoo** [comment]
@Shyamal0212 is the path to your config correct " --config config-scrum.json " ?

**Comment by Shyamal0212** [comment]
Yes, path to config is correct. Cause if I change project name in config-scrum.json then I get error message for entered project. So it is reading config-scrum.json.

**Comment by madkoo** [comment]
@Shyamal0212  just to be sure, then your config is on the same path as the export executable that you are running?
If yes, then it must be some other configuration, in that case, can you provide the full error message or the export json file?

**Comment by Shyamal0212** [comment]
Pasting jira log below:
====================================================================
Jira Export Log
====================================================================
Tool version : 2.3.41
Start time   : 2/3/2020 7:43:33 PM
Telemetry    : Enabled
Session id   : 422b8c5a-aca7-4641-90d2-0de8354476b6
Tool user    : MINDTREE\M1021479
Config       : config-scrum.json
Force        : yes
Log level    : Info
Machine      : D1ML15234
System       : Microsoft Windows 10.0.18362
Jira url     : https://jira.wolterskluwer.io/
Jira user    : shyamal.sambhare
Jira version : 8.3.4
Jira type    : Server
====================================================================
[I][19:43:30] Connecting to Jira...
[I][19:43:30] Retrieving Jira fields...
[I][19:43:31] Retrieving Jira link types...
[E][19:43:32] Failed to get item count using query: 'project = CTUCC AND issuetype = Bug'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'CTUCC' does not exist for the field 'project'.","Field 'issuetype' does not exist or this field cannot be viewed by anonymous users."],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'CTUCC' does not exist for the field 'project'.","Field 'issuetype' does not exist or this field cannot be viewed by anonymous users."],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
[I][19:43:33] Export started. Exporting 0 items.
[W][19:43:33] Epic link field missing for config field 'epic'.
[W][19:43:33] Sprint link field missing for config field 'sprint'.
[I][19:43:33] Initializing Jira field mapping...
[W][19:43:34] No target type 'Story' is set, field status cannot be mapped.
[E][19:43:34] Failed to retrive issues
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'CTUCC' does not exist for the field 'project'.","Field 'issuetype' does not exist or this field cannot be viewed by anonymous users."],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'CTUCC' does not exist for the field 'project'.","Field 'issuetype' does not exist or this field cannot be viewed by anonymous users."],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
[I][19:43:35] Export complete. Exported 0 items (2 errors, 3 warnings) in 00:00:04.

**Comment by Shyamal0212** [comment]
[jira-export-log-200203-194330.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4148304/jira-export-log-200203-194330.txt)
Thats correct, config file is at the same path as export executable. Attaching jira error log.

Some more info if that can help you drill down
Jira version - v8.3.4
Solidify version - v2.3.41

Thank you very much for helping out on this.

**Comment by madkoo** [comment]
@Shyamal0212 reading comments above and looking at the log of the export I am thinking the problem might be with authentication because in the export log it says "{"errorMessages":["The value 'CTUCC' does not exist for the field 'project'.","Field 'issuetype' does not exist or this field cannot be viewed by anonymous users."]"
1) Make sure the username and password are valid to login. It might be that ut is required to use the API token instead of password.
2) Make sure the account you are using has access to the project you are trying to export

**Comment by Shyamal0212** [comment]
I am trying this from my ID and I do have access to this project and admin access of Jira. I did try using API token, in my case it was xsrf token. Is that correct way of passing it in place of password parameter?

**Comment by ShadowXVII** [comment]
Might be related to #126 -- I also cannot get it to export at all -- see my findings below.

> 
> Seems the request, specifically the Issue search is failing -- note the BadRequest response from Atlassian.SDK.
> 
> Tried removing maxResults but no change.
> Tried changing search parameters, no change.
> Tried urlencoding the search parameters, no change.
> Tried changing the project, no change.
> It seems almost like an authentication issue? As if the API can't seem to find the projects? The credentials look like they're being passed via cookie though.
> 
> "{\"errorMessages\":[\"The value 'FG' does not exist for the field 'project'.\",\"Field 'type' does not exist or this field cannot be viewed by anonymous users.\",\"Field 'resolution' does not exist or this field cannot be viewed by anonymous users.\"],\"warningMessages\":[]}"
> 
> image
> 
> Jira version is latest cloud, not on-prem.

**Comment by ShadowXVII** [comment]
I've just queried the API manually using the same Username and API Key and it worked fine -- perhaps it's an issue with how the Atlassian.net-SDK is interpreting the username and password?

**Comment by madkoo** [comment]
@ShadowXVII , @Shyamal0212 , we have released a new version. Can you try with that to see if your authentication issue is corrected?

**Comment by ShadowXVII** [comment]
Oh, it seems OK now -- I created a new token. 

We moved domain recently as well, seems the API doesn't redirect the subdomain (unlike the frontend). So I think it's working now. Will continue testing.

**Comment by madkoo** [comment]
@ShadowXVII that is good to hear. I will close this issue. If you still have issues feel free to contact us.
