### ISSUE TITLE
User picker custom field not being exported

### ISSUE THREAD

**Issue by calvinmichel** [solidify/jira-azuredevops-migrator#179]
I have tried every option in the config file to get this working but this field is being ignored on the export.  I have tried using the name and "source-type": "name".  I've tried with and without the mapper.  This is the only custom field in the config that is not being exported at all.

      {
        "source": "customfield_10100",
        "target": "Custom.Tester",
        "mapper": "MapUser",
        "for": "User Story,Defect"
      }

**Comment by madkoo** [comment]
@calvinmichel  just to clarify is your custom field a single user or multiuser picker?
I would suggest using the source-type: "name". Tested this and had no problem exporting custom user picker, using this mapping:  `{
        "source": "SingleUserPicker",
        "source-type": "name",
        "target": "Custom.TestField",
        "for": "Product Backlog Item",
        "mapper": "MapUser"
      }`

**Comment by madkoo** [comment]
Closing this issue in lack of further response. @calvinmichel  feel free to reopen if you still experience problems

**Comment by calvinmichel** [comment]
@madkoo Sorry again that I did not respond.  I am not receiving notifications from GitHub when comments are added.  I have updated the config file as suggested
      {
        "source": "Tester",
        "source-type": "name",
        "target": "Custom.Tester",
        "for": "User Story,Defect",
        "mapper": "MapUser"        
      }

I ran the export and for a JIRA issue that has a value in the Tester field, the json does not have that field.  Other custom fields are mapped and Assigned To is mapped as well.  Please let me know if you need any additional information to help in resolving this.
