### ISSUE TITLE
Failed to load 'config-agile.json' while trying to import workitems in Azure DevOps

### ISSUE THREAD

**Issue by sanjeev40084** [solidify/jira-azuredevops-migrator#180]
@MOlausson  I am running latest release v2.3.41 and everytime i try to load work items in Azure DevOps i get the warning message saying _'Failed to load 'config-agile.json' (perhaps not a migration file?)_.  Although the tool imports work items in Azure DevOps successfully, i believe there is some bug in the code. I downloaded the code and ran locally, and found that the reason i was getting that error was because of null Revisions during deserialization of json file. The code is in WiItemProvider.cs > LoadFile method.

![image](https://user-images.githubusercontent.com/3292092/74109764-3662c480-4b54-11ea-8674-60688a6b51d4.png)

![image](https://user-images.githubusercontent.com/3292092/74109795-85a8f500-4b54-11ea-99ec-bf2cf1985fd0.png)

**Comment by MOlausson** [comment]
Hi @sanjeev40084 , I think this is the expected behavior. If you have other .json files in the directory used for the migration items those will not have the expected format. Our design is to skip the those files and report the warning to see. Best practice is to keep config separate from the migration directory.

**Comment by MOlausson** [comment]
@sanjeev40084 did you get this sorted out? Closing the issue for now but feel free to re-open if you think we have a bug somewhere.

**Comment by sanjeev40084** [comment]
@MOlausson yes that worked, i moved config-agile.json file inside separate folder and i didn't get that error anymore.
