### ISSUE TITLE
Attachments error - attachments are not being exported correctly

### ISSUE THREAD

**Issue by anamarioc** [solidify/jira-azuredevops-migrator#181]
Hi team,
In addition to issue #177 

I have a Jira issue that contains two attachments (one .jpg and one .txt). The .jpg one is also included in the description of the Jira issue:
![Jira issue](https://user-images.githubusercontent.com/26895529/74334124-3bf91e00-4d91-11ea-8bf9-4ed4eb18c026.PNG)

When exporting the issue I can see in the workspace I defined the two attachments but I can't preview them. When opening the .jpg attachment, it says "It seems we don't support the file's format":
![test-img-exported](https://user-images.githubusercontent.com/26895529/74334167-5206de80-4d91-11ea-81bc-2b2bd864c71c.PNG)

When opening the .txt file I can see some html code, although my .txt file contains just "qweqewqweqw":
![test-txt-exported](https://user-images.githubusercontent.com/26895529/74334200-5c28dd00-4d91-11ea-9d2f-1b8a5dd81b52.PNG)

When importing the issue to azure, I can see the image in the description:
![azure1](https://user-images.githubusercontent.com/26895529/74334604-23d5ce80-4d92-11ea-94dc-cb4909f34345.PNG)

 ..but in the attachments section, if I click on the image the "loading attachment" never ends:
![azure2](https://user-images.githubusercontent.com/26895529/74334296-85e20400-4d91-11ea-834b-00bea101a77e.PNG)

.. and If I tried to download it, for the txt file, I got again the html code and for the image, I see also "It seems we don't support the file's format"

 
[JiraExportTest - Copy.zip](https://github.com/solidify/jira-azuredevops-migrator/files/4192089/JiraExportTest.-.Copy.zip) - In the zip file you have all the log files for the export/import and also the json file. Please note that my json file is still a work in progress. Please let me know if you need more details.

Best Regards,
Ana

**Comment by anamarioc** [comment]
Also I tested other issues with attachments, and sometimes, if it has attachments in the description, the description is not migrated at all or it is migrated but we see the following (the config file is the same as the one I attached above, just the query is different)
![Capture](https://user-images.githubusercontent.com/26895529/74335930-2e459780-4d95-11ea-91b5-d78c3fd70ee5.PNG)

**Comment by anamarioc** [comment]
Also please note that **for most of the cases**, when we have images in the description, the images are being shown like this [the json file used for the described case and below case was the same] 
![Capture](https://user-images.githubusercontent.com/26895529/74353286-9904cc00-4db1-11ea-925a-a921c88cd2a2.PNG)

**Comment by anamarioc** [comment]
@MOlausson and @madkoo can you please help? We want to use your tool but the attachments error is a real big issue for us

**Comment by madkoo** [comment]
@anamarioc  thank you for reporting this. We are currently investigating this issue.

**Comment by anamarioc** [comment]
Hopefully you will be able to reproduce it @madko. Please note that this is happening for all of attachment's types , not just for  .jpg and .txt extensions.
Don't forget to try to reproduce also the case where the images in the description appear broken. 
Please let me know in case you need more details :)

**Comment by madkoo** [comment]
@anamarioc  closing this issue. If you still have problems feel free to reopen the issue.
