### ISSUE TITLE
Export/Import errors

### ISSUE THREAD

**Issue by richa89s** [solidify/jira-azuredevops-migrator#187]
Hi team,

I have a few questions. 

1. While exporting, I get Cannot find info for attachment '397947', skipping. Reason 'Response Content: {"errorMessages":["The attachment with id '397947' does not exist"],"errors":{}}'. However, attachments are available in Jira and also How Solidify is reading attachment values? ex: 397947.

2. While importing I get Azure DevOps services are not available from server https://dev.azure.com/SITA-PSE.
Technical information (for administrator):
  The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

while there is no connection error.

Can you please help on above.

Lastly, my description of imported data does not come in new lines rather appears as a paragraph, can we fix it?

**Comment by MOlausson** [comment]
Hi @richa89s, 

1. Can you see the attachment in question in Jira?
2. Can you share the log file for this run? Or at least the session id from the log file so we can analyze?
3. Can you share (a scrubbed) version of the exported file that has problem with formatting?

**Comment by richa89s** [comment]
Hi Molausson,

1. I will check the Jira side and will get back to you.
2. Session id is c43ce42a-3a18-4bf4-914a-6bd589f97632. One of the sample examples of the error appeared at "[E][13:31:22] Failed to import ". 
3. Description section which has definition as below:
 {
        "source": "description",
        "target": "System.Description",
		
      },

In source some of issue type has description like below:
Source (Description) This is a test record.
Will be used for the ADO export using solidifiy.
Another example of the description.

However, after import it's coming in the below format.
ADO (Description)
This is a test record.Will be used for the ADO export using solidifiy.Another example of the description.
Please let me know if anything else is required and thank you for your prompt response.

**Comment by sanjeev40084** [comment]
@richa89s i have noticed this during my migration too. I think this happens anytime when user in JIRA removes any attachment in the original issue. Go to History tab under Activity section in JIRA (for the issue where you see these type of error message) and check to see if there is any history for removal of attachment.

**Comment by richa89s** [comment]
thanks @sanjeev40084

**Comment by madkoo** [comment]
@richa89s , closing issue, because it seems that you found your answer. If you still have problems, feel free to reopen this issue.
