### ISSUE TITLE
User picker custom field not being exported (reference #179)

### ISSUE THREAD

**Issue by calvinmichel** [solidify/jira-azuredevops-migrator#191]
Wasn't sure how to re-open #179 .  Here is the last comment I added from that issue.
@madkoo Sorry again that I did not respond. I am not receiving notifications from GitHub when comments are added. I have updated the config file as suggested
{
"source": "Tester",
"source-type": "name",
"target": "Custom.Tester",
"for": "User Story,Defect",
"mapper": "MapUser"
}

I ran the export and for a JIRA issue that has a value in the Tester field, the json does not have that field. Other custom fields are mapped and Assigned To is mapped as well. Please let me know if you need any additional information to help in resolving this.

**Comment by madkoo** [comment]
@calvinmichel  what filed type you are using in Jira for this specific custom one? 
How does the data look in it? 
When Exporting do you get any errors/warnings for this field ?

**Comment by apiotuchAoD** [comment]
![image](https://user-images.githubusercontent.com/61207513/75195370-a6ee1180-570e-11ea-9320-55ee40771337.png)

No errors or warnings are thrown when I include "mapper": "MapRendered" regardless if I specify target to a custom field in Azure or to "target": "Microsoft.VSTS.TCM.ReproSteps".

**Comment by calvinmichel** [comment]
@madkoo The tester field is a User picker (single user).  I've attached a snapshot from JIRA.
![Test Field Type](https://user-images.githubusercontent.com/20405266/75198763-01936780-5727-11ea-95a6-8b929eaa6273.PNG)

I set the log level to "Debug".  I've attached a portion of the export log for a defect that has a value in the Tester field.  I did a search on the word Tester in the export log and other than text in a field, it did not show up.  The field does not show up in the CBE-438 json.

I also searched on the custom field id "10100" and that did not appear in the logs.
[export log.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4247363/export.log.txt)

**Comment by madkoo** [comment]
@calvinmichel  we have found a bug when getting "user picker (single user) "custom field from Jira Server. 
The only workaround I found was to create/rename the custom filed name to all lowercase. Then modify the issue/s that use that field so the change history would be saved. In the config.json "Source" field should have name of the filed and without "source-type": "name" and you can keep the MapUser mapper. Try if that works for you as a workaround
We will fix this as soon as possible.

**Comment by calvinmichel** [comment]
Thanks for the workaround!  This worked.

**Comment by rambaliga** [comment]
Hi @madkoo , I am running into this issue for a custom field ( single user picker ). Can I know if this was fixed in the latest version of the tool? Below are my configurations. We will not be able to modify the field name to all lower case in JIRA. 

{
		"source": "Deployement Approved By",
		"target": "Custom.DeploymentApprovedBy",
		"mapper": "MapUser"
	}

The export JSON doesn't have the value for this field. Please let me know if I am missing something.

Tried with custom field ID as well, but no luck
{
		"source": "customfield_10753",
		"target": "Custom.DeploymentApprovedBy",
		"mapper": "MapUser"
	}
