### ISSUE TITLE
Links not created on import for parent that does not exist yet (reference #163)

### ISSUE THREAD

**Issue by calvinmichel** [solidify/jira-azuredevops-migrator#192]
This is in reference to #163 .  Wasn't sure how to re-open the ticket, here is the last comment.

@madkoo Sorry about not responding, I did not get notifications of your comments. I have updated the link map to include all link types.
"link-map": {
"link": [
{
"source": "Epic",
"target": "System.LinkTypes.Hierarchy-Reverse"
},
{
"source": "Relates",
"target": "System.LinkTypes.Related"
},
{
"source": "Duplicate",
"target": "System.LinkTypes.Duplicate-Reverse"
},
{
"source": "Blocks",
"target": "System.LinkTypes.Dependency"
},
{
"source": "Predecessor",
"target": "System.LinkTypes.Dependency"
}
]
}

I tried the export again and here is what I see. CBE-1 is a subtask and is linked to an Epic, CBE-27. In the export, CBE-1 shows the Epic link below
"Links": [
{
"Change": 0,
"TargetOriginId": "CBE-27",
"TargetWiId": 0,
"WiType": "System.LinkTypes.Hierarchy-Reverse"
}
]

CBE-27 does NOT show CBE-1 (or any of the other subtasks) as linked to it in any of the Indexes
"Links": [],

I have looked through the documentation again. I've also searched to see if the sub-task has a unique link type like the Epic, but it is not a "link" necessarily. So I'm not sure how it identifies that the sub-task is linked the Epic. Is there something I am missing?

**Comment by madkoo** [comment]
@calvinmichel  How is your link defined in Jira for this kind of link (Epic to sub-task)?

**Comment by calvinmichel** [comment]
It looks like JIRA does not understand or track a relationship between Epic and sub-task.  Atlassian theory is that sub-tasks will always have a Parent that is associated with the Epic.  When I look at a Story(CBE-43) linked to a defect (CBE-438) that is more recent, the link does not show in the parent (CBE-43) but it does show up in the child (CBE-438) with the correct link type.  I'm going to close this and talk with the team about their Epic to sub-task associations.
