### ISSUE TITLE
JQL Query not pulling only the desired work items

### ISSUE THREAD

**Issue by E-McKee** [solidify/jira-azuredevops-migrator#193]
Hello,

I have a project in jira named Clarion, of which i need to port over only the work items that have a status of "ready for deployment"

I assumed you could do this, and tried to use the JQL Query to only pull the work items that had the project = CLAR and status = "ready for deployment.

"query": "project = CLAR AND status = \\"Ready for Deployment\\" ORDER BY Rank ASC",

The above statement does indeed pull only the Clarion project, but pulls ever work item of that project, regardless of status. 

Is there any way to do this, i dont want all of the work items. just the specific ones that match those criteria.

Thank you

**Comment by MOlausson** [comment]
@E-McKee This should work... Can you share your log file with us or the session id from it?

Not that it should matter but test using single quotes for the status expression, 

"query": "project = CLAR AND status = 'Ready for Deployment' ORDER BY Rank ASC"

**Comment by E-McKee** [comment]
@MOlausson Im so sorry. ill marked this as closed, this was user error. I was modifiying it, thinking i was modifying the file i had placed in my applications folder, when really i was modifying where i had copied it from. So in short i was changing it but i never saw any differences because i was changing the wrong file. So sorry about that.

**Comment by E-McKee** [comment]
I should also specify that this did work as intended and i was able to pull just the specific work items

**Comment by MOlausson** [comment]
Glad to hear you found the problem.
