### ISSUE TITLE
Exported comments have no author

### ISSUE THREAD

**Issue by LiljebergXYZ** [solidify/jira-azuredevops-migrator#194]
I'm trying to export from Jira and for some reason the comments all have author: `null`. 

Did I miss something in the configuration?

**Comment by madkoo** [comment]
@LiljebergXYZ  are you using Jira Cloud? If yes then Jira has made changes in their REST API which is causing this behavior you are seeing. We are working on finding a proper solution for that.

**Comment by LiljebergXYZ** [comment]
Yes I am. I just figured it could map on the account ID, just like the assignees

**Comment by sanjeev40084** [comment]
@LiljebergXYZ @madkoo in my case, all the imported comments in DevOps shows me as author or whoever runs the import tool. :(

**Comment by LiljebergXYZ** [comment]
> @LiljebergXYZ @madkoo in my case, all the imported comments in DevOps shows me as author or whoever runs the import tool. :(

Yep that's exactly what happens for me as well, it's the same issue. The fact that the author is not set in the exported file

**Comment by MaggyLarsen** [comment]
Hi All, I have the same Issue. I am hoping for a fix here as well :) Thanks a lot !

**Comment by MaggyLarsen** [comment]
Modification in method BuildRevisions in class JiraItem, line 58 :

//string author = change.ExValue<string>("$.author.name");
string author = change.ExValue<string>("$.author.accountId");

**Comment by MaggyLarsen** [comment]
+ fix also needed in the BuildComment revision method  :

private static List<JiraRevision> BuildCommentRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
        {
            var renderedFields = jiraItem.RemoteIssue.SelectToken("$.renderedFields.comment.comments");
            var comments = jiraProvider.Jira.Issues.GetCommentsAsync(jiraItem.Key).Result;
            return comments.Select((c, i) =>
            {
                var rc = renderedFields.SelectToken($"$.[{i}].body");

                //+++
                var rcAuthor = renderedFields.SelectToken($"$.[{i}].author");
                var determinedAuthor = rcAuthor.SelectToken("accountId");

                return new JiraRevision(jiraItem)
                {
                    //Author = c.Author,
                    Author = determinedAuthor.Value<string>(),
                    Time = c.CreatedDate.Value,
                    Fields = new Dictionary<string, object>() { { "comment", c.Body }, { "comment$Rendered", rc.Value<string>() } },
                    AttachmentActions = new List<RevisionAction<JiraAttachment>>(),
                    LinkActions = new List<RevisionAction<JiraLink>>()
                };
            }).ToList();
        }

**Comment by sanjeev40084** [comment]
@madkoo @LiljebergXYZ  get the new release V2.3.79 and as long as users.txt has mapping for guid value, when the work items gets imported to Azure DevOps (both on comments and assigned to) seems to work fine :)

**Comment by madkoo** [comment]
@sanjeev40084 . @LiljebergXYZ  that is good to hear it worked. We will take a look at how we can improve user mapping. Will close this issue, for now, feel free to contact us if you have problems.

**Comment by emanuellimabr** [comment]
> @LiljebergXYZ @madkoo in my case, all the imported comments in DevOps shows me as author or whoever runs the import tool. :(

It is happening with me, I am using Jira Cloud and when I try to map users using ID I get the error " Could not find user identity in user map". Can you share how did you fixed it?
