### ISSUE TITLE
Users '{guid value}' not found in Jira, using username '{guid value}' for mapping.

### ISSUE THREAD

**Issue by sanjeev40084** [solidify/jira-azuredevops-migrator#196]
We are in JIRA cloud and recently we have started getting Users '{guid value}' not found in Jira, using username '{guid value}' for mapping. error message while exporting jira items. Tried current release and one before that. 

![image](https://user-images.githubusercontent.com/3292092/75300267-51e0f700-5805-11ea-8c52-0fa3a839a04e.png)

**Comment by chelms0101** [comment]
I've been getting the same issue starting a few days ago.

![Capture](https://user-images.githubusercontent.com/61553404/75460429-721ccd00-594f-11ea-9f49-e86c87345322.PNG)

**Comment by madkoo** [comment]
@sanjeev40084 , @chelms0101  sorry for the late reply. Jira Cloud has changed its API for getting user data. We are looking into this.

**Comment by ibrahimonder** [comment]
I have the same issue unfortunately. This is holding us down to migrate. Is there anything I can do or help with, to speed this up?

**Comment by sanjeev40084** [comment]
@madkoo @chelms0101 @ibrahimonder this still seems to be issue with new release  V2.3.79(which is Jira Api issue) but as long as users.txt has mapping for guid value, when the work items gets imported to Azure DevOps (both on comments and assigned to) seems to work fine :)

Nice work @madkoo

**Comment by madkoo** [comment]
@sanjeev40084 that is good to hear it worked. We will take a look at how we can improve user mapping. Will close this issue, for now, feel free to contact us if you have problems.

**Comment by ibrahimonder** [comment]
> @madkoo @chelms0101 @ibrahimonder this still seems to be issue with new release V2.3.79(which is Jira Api issue) but as long as users.txt has mapping for guid value, when the work items gets imported to Azure DevOps (both on comments and assigned to) seems to work fine :)
> 
> Nice work @madkoo

What do you mean with guid mapping. So instead of using emails to map, you’re using guids of the user accounts in the users.txt file?

**Comment by sanjeev40084** [comment]
@ibrahimonder yes we keep updating same users.txt file anytime when we find new guid or username during migration
