### ISSUE TITLE
Import Error & Users Missing on Export

### ISSUE THREAD

**Issue by chelms0101** [solidify/jira-azuredevops-migrator#198]
I performed a migration to DevOps about 2 weeks ago & everything worked fine. Now, however, I have been getting this error using the same config file on a significant amount of my work items. 

[E][10:00:31] Failed to import revisions for '3762'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException] Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: There is a problem on the server. Contact your Azure DevOps Server administrator. ---> System.Web.Services.Protocols.SoapException: VS403417: ChangedBy value cannot be empty when BypassRules is specified
...

Also, as someone else had noted, user names are no longer being pulled from Jira.

[W][09:43:33] User '5cd5ed9eb588780fd3da48db' not found in Jira, using username '5cd5ed9eb588780fd3da48db' for mapping.
[W][09:43:33] Could not find user '5cd5ed9eb588780fd3da48db' identity in user map. Using default identity 'AzureDevops.default'.
[I][09:43:33] Processing parent issue 'TFM-3359'.
[I][09:43:35] Processing 2/157 - 'TFM-3486'.
[W][09:43:37] User '5cd5ed9eb588780fd3da48db' not found in Jira, using username '5cd5ed9eb588780fd3da48db' for mapping.
[W][09:43:37] Could not find user '5cd5ed9eb588780fd3da48db' identity in user map. Using default identity 'AzureDevops.default'.
[I][09:43:37] Processing 3/157 - 'TFM-3485'.
[W][09:43:39] User '5c9a519d657940451306f967' not found in Jira, using username '5c9a519d657940451306f967' for mapping.
[W][09:43:39] Could not find user '5c9a519d657940451306f967' identity in user map. Using default identity 'AzureDevops.default'.
...

**Comment by MOlausson** [comment]
@chelms0101 thanks for reporting. It's unfortunately an issue cause by a change in Jira Cloud. We're looking at ways to fix this in #196. Closing this as a duplicate.
