### ISSUE TITLE
Add NuGet, Chocolatey or npm support

### ISSUE THREAD

**Issue by pvandorp** [solidify/jira-azuredevops-migrator#2]
To improve the getting started experience it would be better to have Azure DevOps publish to a package management system like NuGet or npm. 

When using npm the solution should also support running on Linux and Mac. It's a big change, but it will definitely increase the relevant user base.

**Comment by MOlausson** [comment]
We've talked about pushing to nuget and publishing a chocolatey package, but I couldn't see the immediate benefit of this. What would you say make that easier since you need to have nuget/chocolatey/npm installed first?
