### ISSUE TITLE
Pictures in the description dont migrate as expected

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#200]
When there are pictures in the description, the first picture appear in all places instead of the other pictures.
it happens even though in the export json there are the correct picture links.

ex.
part of description field in json: 
<img src=\"http://10.75.130.10:8080/secure/attachment/70190/70190_screenshot-3.png\" align=\"absmiddle\" border=\"0\" /></li>\n\t</ul>\n\t</li>\n</ul>\n\n\n<p><p> <img src=\"http://10.75.130.10:8080/secure/attachment/70191/70191_screenshot-4.png\" align=\"absmiddle\" border=\"0\"

in the imported work item you see **screenshot-1** instead of them.
In the attachments, everything exists as it should be

**Comment by madkoo** [comment]
Sorry for the late response. 
Thank you for reporting this issue. We are looking into this.

**Comment by madkoo** [comment]
@AmitNaveh23  I have introduced a fix for this issue. This should be released in the next version.

**Comment by madkoo** [comment]
@AmitNaveh23 closing issue. you can try with the new version when it is released. If you still have issues then feel free to contact us.
