### ISSUE TITLE
Unable to connect to Jira Server

### ISSUE THREAD

**Issue by zahhar** [solidify/jira-azuredevops-migrator#205]
I am unable to use this tool because of two isses. 
One I could resolve myself, for another one community help is much appreciated.

My setup: 

- migrator v2.3.44
- Jira Server v7.13.11 on custom domain, publicly accessible using username & password 

My issues:

1. Seems migrator does not work at all if user's passord starts with double quote (e.g. **"password** ) - in this case migrator behaves like it's parameters are incomplete. No errors, just nothing. Took me a while to figure out that issue is with my password. OK, password changed to less fancy one and now migrator attempts to connect to Jira Server on the URL provided. However, then I am facing another issue.

2. My server expectes authorization with username and password. Jira Server does not allow API tokens yet, so this is not an option. Username is plain old username - part of email before @-sign, but not the whole email. 

Given that, migrator responds with (see full log attached):

`[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON.`

Log contains HTML content for login page on the URL provided as parameter.   

Page itself says:

`function LoginErrors() { 
this.userNameFormatError = 'Enter your user ID in the format \u0026quot;domain\\user\u0026quot; or \u0026quot;user@domain\u0026quot;.'; 
this.passwordEmpty = 'Enter your password.'; 
this.passwordTooLong = 'Password is too long (\u0026gt; 128 characters).';}; 
var maxPasswordLength = 128;
`
Obviously, my password is not empty and it is not more then 128 characters. I can log into Jira Server using my username and password exactly as I am providing them for Migrator. 

Any ideas how to troubleshoot it further and make it work? 

[jira-export-log-200324-130214.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4375129/jira-export-log-200324-130214.txt)

**Comment by madkoo** [comment]
@zahhar  how does your whole command look like. Can you provide an example?

**Comment by zahhar** [comment]
@madkoo it looks exactly as you described. 
I verified that I can log in with exactly same username and password given in the command when I open exactly same URL. So credentials work from browser, but not from command line.

Also first 2 lines of command output before error happens hint that connection to Jira was succesfull. Might issue be with my config file?

>jira-export.exe -u username -p password --url https://jira.hostname.com --config my.json
Jira Exporter v2.3.44
Copyright (c) Solidify
[I][13:38:07] Connecting to Jira...
[I][13:38:07] Retrieving Jira fields...
(here erre output in red - as in log)
[I][13:37:53] Export complete. Exported 0 items (1 errors, 0 warnings) in 00:00:02.

**Comment by madkoo** [comment]
@zahhar it might be. Can you share your config file?
Another question is that is your config file in the same folder as the jira-export.exe?

**Comment by zahhar** [comment]
@madkoo my config indeed in the same folder. 
Actually, exported has pretty good error handling, so I could analyze all possible issues myself. When it can't find config file, it says:

[E][13:52:45] Required JSON configuration file 'asdfasdf.json' was not found. Please ensure that this file is in the correct location.

Also, when config file is corrupted, it tell clearly:
[E][13:53:35] Cannot deserialize the JSON text from configuration file. Please ensure it is formatted properly.

But these are not my cases. Please see my config attached. Ofc, I am running it as json (had to add .txt extention to be able to upload here).

Also, after I log into my Jira server, I can run same query that is mentioned in the my.json config literallu copy-pasting it from there into Jira. So this part is also tested and works well. 

But how jir-export attempts to read the data? Does it run export to xml, to json, or to csv on the Jira Server it had connected to? It might be that some export options are not configured or disabled for my user on that Jira server (just a guess). 


[my.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4387214/my.json.txt)

**Comment by madkoo** [comment]
@zahhar  it will export to JSON. I tried out with your config and worked for me on a Jira Server. 
As I understand the error that you get is the one you posted on your first comment?
Based on that it looks like an authentication issue.

**Comment by zahhar** [comment]
@madkoo if this would be authentication issue, I assume error would be thrown after saying "Connecting to Jira...", but it comes after saying "Retrieving Jira fields...". 

Good point with JSON, thank you. I logged into the server as a user and attempted to export filter query results to JSON. Gotcha: I was not able to! My server said that I have no sufficient priviledges. Funny enough that I can export same filter query to CSV and XML. 

Meanwhile I try to extend my priviledges to be able to export to JSON. But does jira-export has any flag to use XML instead of JSON for example?

**Comment by madkoo** [comment]
@zahhar do jira-export does not have any flag to get XML output instead. It could be a possible enhancement we will take it into consideration.

**Comment by zahhar** [comment]
@madkoo Understood, thank you.

As I said, my user does not have access to JSON export, but Jira server admin in our organization can export it for me. Given that, will I be able to skip jira-export and just use that JSON file on the next step to feed it for import to Azure DevOps?

**Comment by madkoo** [comment]
@zahhar if I understood you correct is that your server admin will run the export tool? then Yes you can use that result as input for the import tool.

**Comment by zahhar** [comment]
@madkoo Not exactly. My server admin will NOT run export tool. He agreed to do manual export of my JQL to JSON from Jira server using Jira built-in exporter. Then he will send that JSON to me by email, and I am supposed to deal with it further. I want to feed it "as-is" into import tool. Will it work?

**Comment by madkoo** [comment]
@zahhar No, unfortunately, it will not work. You can add an enhancement request/suggestion and we will consider it. As this is an open-source project and we do development here on the best effort basis. But for urgent matters, help in migration or customization can we offer paid services, you can contact us directly for that.

**Comment by zahhar** [comment]
@madkoo Thank you, understood. This time I do not have budget for extrenal services, also with current situation it would be super slow (and expensive) to get into all agreements just because of this small task. So I have to find another way how to do export/import in my case. 

Last question: in the very biginning I could not run the jira-export tool with my password starting with double quote character (this one: **"**). Is it a bug, or I did smth wrong, or such passwords are not supported because Windows command line gets confused when sees quote?

**Comment by madkoo** [comment]
@zahhar indeed such passwords are not supported. We will keep this in mind for future development. Thank you for your input :)

**Comment by madkoo** [comment]
Will close this issue for now. If you have any other problems feel free to contact us.
