### ISSUE TITLE
Support import from local files (json|xml) containing JQL export result set

### ISSUE THREAD

**Issue by zahhar** [solidify/jira-azuredevops-migrator#209]
#FeatureRequest #Enhancement 

Seems that there are cases when jira-export tool cannot connect to Jira instance at all. For this situation it would be beneficial if user could manually download JQL result as JSON or XML file, put it into local folder and then run transformation and import to Azure DevOps pointing tool to the local file instead of Jira instance URL. 

#205

**Comment by Alexander-Hjelm** [comment]
We will likely not be fixing this. If you don't have connectivity to your JIRA server then there are no issues with the Jira migrator itself.

Closed due to inactivity. Feel free to open again if this is still an issue
