### ISSUE TITLE
Jira Export Breaks on missing Epic

### ISSUE THREAD

**Issue by boldtlm** [solidify/jira-azuredevops-migrator#211]
We have a large Jira project to migrate to Azure DevOps. When it gets to a specific issue it breaks. It shows the error message and shows 181 issues migrated but only 34 really downloaded. Turns out about 2 years ago someone linked an issue from another project to issues in this migration project and now that project is no longer in Jira. Is it possible to make it skip these issues like it does when it can't find an attachment?
I've attached the export log. A piece of it is:

[I][13:34:31] Processing epic parent 'ONB-3'.
[E][13:34:32] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Atlassian.Jira.Remote.ResourceNotFoundException: Response Content: {"errorMessages":["Issue does not exist or you do not have permission to see it."],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---

We have migrated a lot of projects so far and this is the first time seeing this error.

**Comment by madkoo** [comment]
@boldtlm  thanks for reporting the issue. We will look into this

**Comment by madkoo** [comment]
@boldtlm  good to hear you were able to find a workaround.

**Comment by madkoo** [comment]
@boldtlm  actually there was a way to skip items: by not using --force in the export command and creating files with specific key names you wanted to skip. Closing this issue.
