### ISSUE TITLE
Import Priority Issue

### ISSUE THREAD

**Issue by gekap** [solidify/jira-azuredevops-migrator#213]
Hello,

When I try to import in azure devops I get the following error...

[E][12:13:27] Failed to update fields.
[Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException: TF26027: A field definition Microsoft.VSTS.Common.Priority in the work item type definition file does not exist. Add a definition for this field or remove the reference to the field and try again.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionCollection.get_Item(String name)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldCollection.get_Item(String name)
   at WorkItemImport.Agent.SetFieldValue(WorkItem wi, String fieldRef, Object fieldValue)
   at WorkItemImport.Agent.UpdateWIFields(IEnumerable`1 fields, WorkItem wi):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionCollection.get_Item(String name)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldCollection.get_Item(String name)
   at WorkItemImport.Agent.SetFieldValue(WorkItem wi, String fieldRef, Object fieldValue)
   at WorkItemImport.Agent.UpdateWIFields(IEnumerable`1 fields, WorkItem wi)

In confifguration I have the below

       "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
			{
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "2"
            },
            {
              "source": "Major",
              "target": "3"
            },
            {
              "source": "Minor",
              "target": "3"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }

Any idea how to fix it?

**Comment by madkoo** [comment]
@gekap based on the error I am assuming that for one of the work item types you do not have a field with the mapping, priority.  I would suggest double check your fields in your work item type configuration

**Comment by gekap** [comment]
Hello,

I have double check the fields and in this error the Priority is Minor

**Comment by gekap** [comment]
Hello again,

Something is wrong with your export.

On the same jira project I used the jira-export.exe from 2.2.59 version and completed without any errors.

I import the jira project to Azure DevOPS using the 2.3.79 version and completed without any issues.

Nothing has change on azure devops

**Comment by madkoo** [comment]
@gekap sorry but I don't follow the last comment, do you still have a problem? 
I would suggest using the same version for exporting and importing

**Comment by gekap** [comment]
Hello madkoo,

In the previous versions I did not have this issue.  I am using the latest version but on many Jira items I have this issue.

Is any configuration issue? How can I solve it as it seems that items does not import successfully

**Comment by madkoo** [comment]
@gekap Did you try to export and import with the latest version?
I do not have problems exporting and importing the priority field. Also looking at the error message you posted earlier it states in it as well that "TF26027: A field definition Microsoft.VSTS.Common.Priority in the work item type definition file does not exist. Add a definition for this field or remove the reference to the field and try again." Meaning that working you are importing does not have that filed defined in Azure DevOps. 

Can you provided one of the failing exported JSON files and your configuration?

**Comment by madkoo** [comment]
@gekap  just to confirm then you are 100% sure that the WorkItem type "New Feature" has a filed called Priority (with reference name: Microsoft.VSTS.Common.Priority)?

**Comment by gekap** [comment]
![image](https://user-images.githubusercontent.com/43109822/80119459-6a198c00-8592-11ea-8874-c38b2feffecc.png)
Hello,

As you can see it has Priority field with value

**Comment by madkoo** [comment]
@gekap sorry I did not specify my question enough. What I meant was that you are importing eg this "New Feature" item to Azure DevOps and as the initial error said, that you posted,  that the field "Microsoft.VSTS.Common.Priority" (which is a field reference name and not the actual field name that is displayed) does not exist in your "New Feature" Work Item type in  Azure DevOps project. My question was that are you certian that the Work item type "New Feature" in Azure Devops has the field called Priority (reference name: Microsoft.VSTS.Common.Priority).

**Comment by gekap** [comment]
@madkoo I created all the WorkItems the same way.

Now there are some WorkItems "New feature" that did not have this issue or WorkItem "Improvement" same as "New Feature" and there is no error on import.

**Comment by gekap** [comment]
@madkoo  I saw what you mean... Indeed that field does not appear in the workItem I added as custom field and I will give a try.

Thank you

**Comment by madkoo** [comment]
@gekap  welcome. Closing this issue for now, if you experience problems feel free to contact us.
