### ISSUE TITLE
"Your usage on this account has exceeded our rate limiting thresholds" - in Azure DevOps

### ISSUE THREAD

**Issue by jochenvw** [solidify/jira-azuredevops-migrator#214]
I'm migrating a JIRA project to Azure DevOps and I'm seeing the error message described here: [https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#user-experience](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#user-experience)

The JIRA project has approx 120 user-stories and one has 4700 revisions who is the primary suspect to trigger this threshold. Any guidance how I can avoid hitting this limit ?

**Comment by madkoo** [comment]
@jochenvw  Do I understand correctly that one story has around 4700 revisions or that is the total count of revisions?

**Comment by MOlausson** [comment]
@jochenvw you can contact Azure support and ask them to temporarily remove this constraint during a migration. The import will complete regardless but if will go slower if you hit the rate limit threashold.

**Comment by jochenvw** [comment]
Sorry for not responding earlier. We did as you suggested and this worked! Thanks.
