### ISSUE TITLE
More items migrated than expected

### ISSUE THREAD

**Issue by ElementalDev** [solidify/jira-azuredevops-migrator#215]
Hi there,

I used a JQL Query that should have migrated 32 User Stories with relationships to Epics, tasks, attachments etc. 

We expected the relationships not to be maintained between the Epics and tasks as they wouldn't be in DevOps.

When it got to DevOps, it imported 36 items when it should have imported 32 and when I checked out what was different, it seemed to import 3 tasks and an Epic that only had titles.

I double checked the JQL query and it definitely only returns 32 items, and it seems to sever the links on most work items migrated across so i'm confused where the Epics and Tasks came from?

**Comment by madkoo** [comment]
@ElementalDev sorry for the late response, how many JSON files were exported? Can you provide the configuration you are using?

**Comment by MOlausson** [comment]
@ElementalDev see my comment in issue #219.
