### ISSUE TITLE
Fix & Affected versions migration

### ISSUE THREAD

**Issue by gekap** [solidify/jira-azuredevops-migrator#217]
Hello,

How can I migrate the Affected Version and Fix Versions from Jira to AzureDEVOps ?

**Comment by gekap** [comment]
@madkoo I have to add them in the field-map?

**Comment by madkoo** [comment]
@gekap yes, you have to add to the field-map.

**Comment by gekap** [comment]
@madkoo Can you please provide an example how the configuration file will be for those fields?

**Comment by madkoo** [comment]
@gekap  it will depend on your setup but one simple example: 
      {
        "source": "Fix versions",
        "source-type": "name",
        "target": "Custom.FixVersions",
      }

**Comment by gekap** [comment]
@madkoo Thank you I will try it

**Comment by madkoo** [comment]
@gekap  Closing this. Feel free to contact us if you have any problems.
