### ISSUE TITLE
Bidirectional link ("Discovered while testing" / "Testing discovered") in JIRA turns into unidirectional link in AZD

### ISSUE THREAD

**Issue by clausb** [solidify/jira-azuredevops-migrator#218]
For bidirectional link relationships in the Bonfire testing scenario ("discovered while testing" / "testing discovered"), we found that the is added to only one of the two work items on the Azure DevOps side. It seems that the information required to set up the bidirectional link s in fact already lost while exporting from JIRA, i.e. in jira-export. Only one of the JIRA json files produced by the exported has link information in the `Links` array.

Our test scenario in JIRA:

- FOOBAR-4812 has a link to FOOBAR-4607 of type "discovered while testing"
- FOOBAR-4607 has a link to FOOBAR-4812 of type "testing discovered"

After exporting from JIRA, only FOOBAR-4607.json receives link information, but not FOOBAR-4812.json. (Actually, to be more precise, it depends on the export sequence which of the two .json files has the link information and which one doesn't.)

FOOBAR-4607.json:

```
     "Links": [
        {
          "Change": 0,
          "TargetOriginId": "FOOBAR-4812",
          "TargetWiId": 0,
          "WiType": "Microsoft.VSTS.Common.TestedBy-Reverse"
        }
```

FOOBAR-4812.json:
```
    "Links": [],
```

Is this a known problem? Is my analysis correct that the information is already lost in the `jira-export` step, or should the workitem import step be able to reconstruct the bidirectional link despite the partially missing information in the .json files produced by the exporter?

I debugged further into the problem and found a hack which improved the situation for us (https://github.com/clausb/jira-azuredevops-migrator/tree/experimental_handle_incoming_links). The hack is in `JiraItem.TransformLinkChange` which already considered outward links, but not inward links. However, as I cannot claim to understand the design of the exporter, I'd be VERY surprised if my solution was the correct one, and it may have all kinds of side-effects - so I am referring to the hack only as a further illustration of the problem.

**Comment by madkoo** [comment]
@clausb thank you for the input.  One thing you did not provide was how does your link mapping configuration look like?

**Comment by clausb** [comment]
Thanks for your reply and for looking into this! During my experiments, the link map looked like this:

```
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      {
        "source": "Blocks",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Bonfire Testing",
        "target": "Microsoft.VSTS.Common.TestedBy-Reverse"
      },
      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Cloners",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Finish-to-Finish Dependency",
        "target": "System.LinkTypes.Dependency-Reverse"
      },
      {
        "source": "Finish-to-Start Dependency",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Start-to-Finish Dependency",
        "target": "System.LinkTypes.Dependency-Reverse"
      },
      {
        "source": "Start-to-Start Dependency",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Sibling",
        "target": "System.LinkTypes.Dependency-Reverse"
      }
    ]
  },
```

**Comment by madkoo** [comment]
@clausb This should be fixed with the latest version of the tool. 
Closing this issue for now feel free to reopen or contact us if the problem  still persists.
