### ISSUE TITLE
More items are getting exported than expected

### ISSUE THREAD

**Issue by prasathe-git** [solidify/jira-azuredevops-migrator#219]
Hello,

I have a JQL query which is selecting specific items from Jira using issueKey attribute. I am expecting 193 items to be exported but getting 198 items as output.
What could be the reason?
Following is the JQL query

project = MVP AND issueKey IN ('MVP-266','MVP-315','MVP-347','MVP-381','MVP-438','MVP-441','MVP-448','MVP-450','MVP-454','MVP-456','MVP-463','MVP-471','MVP-498','MVP-528','MVP-539','MVP-542','MVP-555','MVP-557','MVP-576','MVP-579','MVP-592','MVP-597','MVP-600','MVP-612','MVP-617','MVP-621','MVP-629','MVP-631','MVP-643','MVP-676','MVP-685','MVP-706','MVP-737','MVP-739','MVP-756','MVP-815','MVP-852','MVP-877','MVP-880','MVP-883','MVP-900','MVP-921','MVP-922','MVP-948','MVP-964','MVP-972','MVP-975','MVP-978','MVP-986','MVP-1000','MVP-1005','MVP-1007','MVP-1037','MVP-1039','MVP-1050','MVP-1053','MVP-1055','MVP-1056','MVP-1059','MVP-1061','MVP-1066','MVP-1068','MVP-1072','MVP-1082','MVP-1108','MVP-1111','MVP-1135','MVP-1146','MVP-1148','MVP-1164','MVP-1176','MVP-1177','MVP-1181','MVP-1189','MVP-1198','MVP-1199','MVP-1200','MVP-1202','MVP-1204','MVP-1222','MVP-1225','MVP-1234','MVP-1235','MVP-1237','MVP-1238','MVP-1244','MVP-1246','MVP-1247','MVP-1248','MVP-1253','MVP-1257','MVP-1258','MVP-1262','MVP-1265','MVP-1266','MVP-1267','MVP-1269','MVP-1274','MVP-1275','MVP-1277','MVP-1278','MVP-1279','MVP-1282','MVP-1283','MVP-1285','MVP-1287','MVP-1289','MVP-1291','MVP-1292','MVP-1294','MVP-1298','MVP-1301','MVP-1302','MVP-1307','MVP-1311','MVP-1321','MVP-1326','MVP-1332','MVP-1333','MVP-1339','MVP-1340','MVP-1341','MVP-1342','MVP-1344','MVP-1345','MVP-1347','MVP-1348','MVP-1349','MVP-1350','MVP-1351','MVP-1352','MVP-1353','MVP-1354','MVP-1355','MVP-1357','MVP-1358','MVP-1359','MVP-1362','MVP-1363','MVP-1364','MVP-1365','MVP-1366','MVP-1367','MVP-1368','MVP-1369','MVP-1371','MVP-1372','MVP-1373','MVP-1374','MVP-1375','MVP-1376','MVP-1377','MVP-1379','MVP-1380','MVP-1381','MVP-1389','MVP-1392','MVP-1393','MVP-1402','MVP-1408','MVP-1410','MVP-1412','MVP-1413','MVP-1417','MVP-1420','MVP-1425','MVP-1427','MVP-1428','MVP-1429','MVP-1433','MVP-1436','MVP-1439','MVP-1442','MVP-1453','MVP-1454','MVP-1456','MVP-1462','MVP-1463','MVP-1469','MVP-1473','MVP-1475','MVP-1481','MVP-1484','MVP-1487','MVP-1496','MVP-1497','MVP-1505','MVP-1506','MVP-1507','MVP-1508','MVP-1509','MVP-1510','MVP-1511')

If I run the same query in Jira then I get exact number of items.

Thanks 

Pradyumna sathe

**Comment by MOlausson** [comment]
Hi @prasathe-git,

I would guess it's because the tool downloads some additional items which the listed items have relationships to, you can check the log for traces of this. If so it can be controlled in the configuration file using the download-options setting (https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#download-options).

Mathias

**Comment by prasathe-git** [comment]
It works for one issue type, now I will try out for others, Thank you for your suggestion.

Pradyumna Sathe

**Comment by MOlausson** [comment]
@prasathe-git jhappy to hear you're making progress!
