### ISSUE TITLE
401 System.Security.Authentication.AuthenticationException:

### ISSUE THREAD

**Issue by lcempulik** [solidify/jira-azuredevops-migrator#22]
I'm having some problems with connecting to cloud version of JIRA ( V2a39c429 ), I have .bat file with following statement : 

jira-export.exe -u some@login.com -p somepassword --url https://someorg.atlassian.net/ --config .\Samples\config-scrum.json

but it looks like I'm unable to authenticate, why I get 401 here ?

**Comment by lcempulik** [comment]
Ok, I have solution for this problem : 
Instead of using full  :    username@some-host.com  I switched to username . It would be good to point it in doc.

**Comment by MOlausson** [comment]
@lcempulik thanks for pointing this out. I will try to repro and update the docs accordingly.
