### ISSUE TITLE
Azure import is getting interrupted due to network glitch 

### ISSUE THREAD

**Issue by prasathe-git** [solidify/jira-azuredevops-migrator#222]
Hello,

Azure import is getting interrupted due to network glitch, can I start the import from where it got interrupted?

Thanks in advance

Pradyumna Sathe

**Comment by madkoo** [comment]
@prasathe-git  Sorry for the late reply. Do not use "-force" option in the command line then the tool will continue from the previous run. 
Closing this issue, for now, feel free to contact us if still face problems.
