### ISSUE TITLE
Inline images in description with spaces between words of filename are not mapping.

### ISSUE THREAD

**Issue by mahidharguggilam** [solidify/jira-azuredevops-migrator#225]
If there is any inline image of description with file name like "screen shot.jpg" are not mapping. So I fixed it like this in Agent.cs class. As the images is getting saved as "screen+shot.jpg" when Jira son is exported

 private void CorrectImagePath(WorkItem wi, WiItem wiItem, WiRevision rev, ref string textField, ref bool isUpdated)
        {
            foreach (var att in wiItem.Revisions.SelectMany(r => r.Attachments.Where(a => a.Change == ReferenceChangeType.Added)))
            {
                var fileName = att.FilePath.Split('\\')?.Last() ?? string.Empty;
                **var splitfileName = fileName.Split(' ');**

                if (textField.Contains(fileName) **|| textField.Contains(string.Join("+", splitfileName))**)
                {

                    var tfsAtt = IdentifyAttachment(att, wi);

                    if (tfsAtt != null)
                    {
                        string imageSrcPattern = $"src.*?=.*?\"([^\"])(?=.*{att.AttOriginId}).*?\"";
                        textField = Regex.Replace(textField, imageSrcPattern, $"src=\"{tfsAtt.Uri.AbsoluteUri}\"");
                        isUpdated = true;
                    }
                    else
                        Logger.Log(LogLevel.Warning, $"Attachment '{att.ToString()}' referenced in text but is missing from work item {wiItem.OriginId}/{wi.Id}.");
                }
            }
            if (isUpdated)
            {
                DateTime changedDate;
                if (wiItem.Revisions.Count > rev.Index + 1)
                    changedDate = RevisionUtility.NextValidDeltaRev(rev.Time, wiItem.Revisions[rev.Index + 1].Time);
                else
                    changedDate = RevisionUtility.NextValidDeltaRev(rev.Time);

                wi.Fields[WiFieldReference.ChangedDate].Value = changedDate;
                wi.Fields[WiFieldReference.ChangedBy].Value = rev.Author;
            }
        }

AB#5957

**Comment by madkoo** [comment]
@mahidharguggilam Thanks for the input, you could have submitted this as a PR :)

**Comment by Yeronimo** [comment]
Will you be merging this as a PR? Else I will create one for this.

**Comment by MOlausson** [comment]
@Yeronimo we're catching up with migration work so will look into this starting next week. If you could create a PR for this we'll test and merge. Thanks!

**Comment by Alexander-Hjelm** [comment]
Fixed by: https://github.com/solidify/jira-azuredevops-migrator/pull/489
