### ISSUE TITLE
How to migrate themes from JIRA to Azure DevOps

### ISSUE THREAD

**Issue by rsikr** [solidify/jira-azuredevops-migrator#228]
In JIRA we have themes and we have Issues in epic linked with themes. How can we migrate these?
Also please share sample config for CMMI process where artefacts link change request, process, milestones, question etc are mapped to Azure DevOps.

**Comment by MOlausson** [comment]
Hi @rsikr, you should be able to migrate themes like other issue types by providing the correct mapping. Did you manage to get it configured? Also the CMMI mapping is a nice idea, we'll add it to the backlog but also something someone can help contribute to this project.

**Comment by MOlausson** [comment]
@rsikr closing this one now. Feel free to reach out if you have other questions.
