### ISSUE TITLE
Could you add a '--continue True' option to the Extract? Alike wi-import already got?

### ISSUE THREAD

**Issue by arjanh888** [solidify/jira-azuredevops-migrator#231]
Hi,
Could you please add a '--continue True' option to the Extract? Alike the wi-import already got?
Or is this somehow already possible?

I got 5000+ cards to migrate, and it stops now regulary (unexpected migration error. Issue does not exist or no privilege), and then I got to manually restart it. I would like it to finish without manual intervention, even if some cards are lost.
By the way: great tool!

Regards,
Arjan.

**Comment by arjanh888** [comment]
Kind of workaround, using the CLI only:
1) remove the PAUSE from Extract.cmd
2) know how many stories you got to migrate
3) use powershell to restart the Extract, until that file count is reached:
File go.ps1:
echo starting

cd C:\progs\JIRAuitMigratie\TeamBlue\WorkItems
while ((Get-ChildItem -File | Measure-Object).Count -lt 5000)
{
	cd C:\progs\JIRAuitMigratie\TeamBlue
	sleep 10
	echo "restarting"
	cd C:\progs\JIRAuitMigratie\TeamBlue\WorkItems
}
echo "stopped restarting, reached 5000 files"

**Comment by madkoo** [comment]
@arjanh888  thanks for the input, we have added this feature to our tool now. It will be available in the next release. 
Closing this issue, for now, feel free to contact us if you have problems.
