### ISSUE TITLE
Link map for Successor and Predecessor

### ISSUE THREAD

**Issue by rsikr** [solidify/jira-azuredevops-migrator#235]
How can we specify link for below link types:

JIRA - 'has to be done after' 
AND
DevOps - 'Successor'

JIRA - 'has to be done before'
AND
DevOps - 'Predecessor'

**Comment by deeepakmhaskar** [comment]
You can map it using Link type Microsoft.VSTS.Common.Affects-Reverse

**Comment by rsikr** [comment]
Hi Deepak,

Please share the exact mapping with source and target both.

**Comment by deeepakmhaskar** [comment]
In my case it was named as 'Blocks" in JIRA. Here is the mapping
`{
        "source": "Blocks",
        "target": "Microsoft.VSTS.Common.Affects-Reverse"
      },`

**Comment by madkoo** [comment]
@rsikr indeed @deeepakmhaskar  comment is valid, good yo hear you were able to solve this :)
I will close this issue at this moment. Feel free to contact us if you further problems.
