### ISSUE TITLE
Link back to Jira issue in comments

### ISSUE THREAD

**Issue by jerone** [solidify/jira-azuredevops-migrator#236]
I would like to add an extra comment in DevOps with an custom text, including a link to the original Jira issue. Is this possible?

**Comment by jerone** [comment]
Or via the Hyperlink Type: https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops#hyperlink-type

**Comment by madkoo** [comment]
@jerone  Thanks for the suggestion! We will look into this. At this time we don't support that unfortunately but you can either add a link in the comment which will be migrated or a custom field containing the jira link with custom text.

**Comment by jerone** [comment]
We are going to migrate Jira this sprint, so I started to look into creating an extra comment with a ping back to the Jira isue, but I couldn't find the code to create the Jira url. I don't want to manually add a comment to 700 issues :smile:
