### ISSUE TITLE
How to export the test cases from JIRA

### ISSUE THREAD

**Issue by rsikr** [solidify/jira-azuredevops-migrator#237]
We are using Zephyr for JIRA plugin in JIRA for managing Test cases. How can we export the data and import it into Azure DevOps?

[sample.txt](https://github.com/solidify/jira-azuredevops-migrator/files/4624730/sample.txt)

**Comment by MOlausson** [comment]
Hi @rsikr, I guess you have resolved this already but we're tracking it in #172 and are looking at implementing support in v3 which we will start working on soon.

**Comment by mbenachour-premierinc** [comment]
@MOlausson  facing same issue, any plans to ship in future releases ?
