### ISSUE TITLE
Emails for accounts with non-public emails are being fetch every time

### ISSUE THREAD

**Issue by benventive** [solidify/jira-azuredevops-migrator#239]
Hello! First, I want to thank you for this tool. It's really well done and easy to use!
We've noticed that, when running an export against one of our Jira projects, the warning `Email is not public for user '[userId]' in Jira, using usernameOrAccountId '[userId]' for mapping.` keeps showing up. 
Looking at the code of the [JiraProvider](https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraProvider.cs#L336), it seems like if the email isn't found for a given ID, there's not addition to the user email cache, causing the same thing to happen the next time said ID is encountered. 
I believe adding such ID to the cache could improve the performance of the export. Also, since the tool already supports mapping a Jira user ID to an ADO account, the fetch of the email for the account could be skipped entirely if the ID is already present in the mapping.

**Comment by madkoo** [comment]
@benventive thank you for the suggestion, we will look into this.

**Comment by madkoo** [comment]
@benventive  closing this issue as this is a suggestion, not an actual issue. Also, we have addressed this in one of our PR-s

**Comment by benventive** [comment]
I understand. I've seen the PR in question. Thanks a lot!
