### ISSUE TITLE
Duplicate import

### ISSUE THREAD

**Issue by gekap** [solidify/jira-azuredevops-migrator#242]
Hello,

A customer informed me that a Jira ticket imported twice in azure devops

1st is
![image](https://user-images.githubusercontent.com/43109822/82428525-4d8a4a00-9a93-11ea-98d7-41ec1061159b.png)

2nd is
![image](https://user-images.githubusercontent.com/43109822/82428594-61ce4700-9a93-11ea-9a20-7f7be89fb7a7.png)

Can you please advice how can I fix it?

I did the import twice and both times I use --force option

**Comment by madkoo** [comment]
@gekap  the --force option will create duplicates as it will create all the items in the directory regardless if they exist in ADO.

**Comment by MOlausson** [comment]
Adding to this, the fix is unfortunately to manually remove the duplicates. I've updated the [documentation](https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/wi-import.md) to make this more evident.

**Comment by gekap** [comment]
Is any way to search azure devops for duplicate items?
