### ISSUE TITLE
Custom fields not exporting

### ISSUE THREAD

**Issue by dlauryssen** [solidify/jira-azuredevops-migrator#251]
Hi, 

I'm trying to export some custom fields but not succeeding, I have read all manuals and other issues and can't find the solution and spent quite some time on it already. So I'm reaching out. 

One example below

![image](https://user-images.githubusercontent.com/11612664/83894677-e71f5000-a751-11ea-8c9f-4f87fa7f9844.png)

have tried every possible variation of the config

	  {
        "source": "customfield_19029",
         "source-type": "name",
        "target": "Custom.UseCase",		
	"mapper": "MapArray"
      },

tried with MapArray and MapTags or without mapper
tried with source-type name and without source type
tried with both "Use case" and "customfield_19029" as source

resulting in

        {
          "ReferenceName": "Custom.UseCase",
          "Value": null
        },

Not quite sure which type the source field is but it behaves as labels. 

The Jira REST result mentions

"customfield_19029":["Manage_Product_Information"],

Any help much appreciated.

Thanks,
David

**Comment by madkoo** [comment]
@dlauryssen not sure how the combinations looked like what you tried but the example here : 
``` 
  {
    "source": "customfield_19029",
     "source-type": "name",
    "target": "Custom.UseCase",		
"mapper": "MapArray"
  },
````
won't work. if you are using source-type: name that means the source must be the field display name, not the "reference" name you have in Jira.

**Comment by dlauryssen** [comment]
Hi thanks for the follow up. 

Let's take the following example. 
 {
        "source": "Account",	
	"source-type": "name",	
        "target": "Custom.Account"	
  },
is not giving any export of this field in de JSON. The field is not even listed.


REST API says
"customfield_18916":{"self":"https://jira.sqli.com/jira/rest/tempo-accounts/1/account/1","id":"1","key":"B4UPHASE1","name":"B4U Phase 1"}

The field is disaplyed as Account 
![image](https://user-images.githubusercontent.com/11612664/84190291-fcb8b080-aa96-11ea-879d-05e4deedff33.png)

What am i missing? 

Thanks

**Comment by dlauryssen** [comment]
Also tried
 {
       "source": "Account",	
	"source-type": "name",	
        "target": "Custom.Account",
	"mapper": "MapArray"		
      },

but no luck

**Comment by madkoo** [comment]
@dlauryssen what your missing is the Displayed name and the actual field name do not match. 
REST API result that you showed:
``` 
"customfield_18916":{"self":"https://jira.sqli.com/jira/rest/tempo-accounts/1/account/1","id":"1","key":"B4UPHASE1","name":"B4U" Phase 1"}
```

Based on the rest API the "source" value in the mapping should be either "name" value **"B4U"** or the "Key" value **"B4UPHASE1"** but then in the mapping don't use "source-type"

**Comment by dlauryssen** [comment]
Hi thanks for your reply. 

I'm afraid you lost me there as you are mentioning that I should use either "B4U" or ""B4UPHASE1" as source. But that puzzles me as this is the selected actual value of the field, not the column name, be it the technical name or the display name.
In any case, I tried it but no result.

Notice that there was an " too much in my abstract from the REST result.
Another example of a value from the REST result for another record
 
```

.....
"customfield_18915":null,
"customfield_18916":{"self":"https://jira.sqli.com/jira/rest/tempo-accounts/1/account/8","id":"8","key":"B4URelease","name":"B4URelease"},
"duedate":null,
"customfield_18917":null
....

```

it's confusing as to why i should not be able to use customfield_18916 as the source 

where the following DOES work for acceptance criteria
```
 {
        "source": "customfield_19028",
        "target": "Microsoft.VSTS.Common.AcceptanceCriteria",
        "for": "User Story" 
      },
```


So not really knowing what to do I tried all of the following combo's. 

```
 {
        "source": "customfield_18916",	
	"source-type": "name",			
        "target": "Custom.Account"		
 },
{
        "source": "customfield_18916",		
        "target": "Custom.Account1"		
},	
{
        "source": "customfield_18916",		
        "target": "Custom.Account2",
	"source-type": "key"		
},
{
        "source": "customfield_18916",		
        "target": "Custom.Account3",
	"source-type": "id"		
},
 {
        "source": "customfield_18916",	
	"source-type": "name",			
        "target": "Custom.Accounta"
	,"mapper": "MapArray" 		
 },
 {
        "source": "customfield_18916",		
        "target": "Custom.Account1a"	
        ,"mapper": "MapArray" 				
 },	
 {
        "source": "customfield_18916",		
        "target": "Custom.Account2a",
	"source-type": "key"		
	,"mapper": "MapArray" 		
},
 {
        "source": "customfield_18916",		
        "target": "Custom.Account3a",
	"source-type": "id"		
	,"mapper": "MapArray" 		
 },
 {
        "source": "customfield_18916",	
	"source-type": "name",			
        "target": "Custom.Accountb"	
       ,"mapper": "MapRendered" 				
 },
 {
        "source": "customfield_18916",		
        "target": "Custom.Account1b"	
       ,"mapper": "MapRendered" 		
 },	
 {
        "source": "customfield_18916",		
        "target": "Custom.Account2b",
	"source-type": "key"	
        ,"mapper": "MapRendered" 		
 },
 {
        "source": "customfield_18916",		
        "target": "Custom.Account3b",
	"source-type": "id"	
        ,"mapper": "MapRendered" 		
 },
```

None of these is working. Tried customfield_18916, cf[18916], Account, account, tempo-accounts, B4U as source values.

I'm probably going to work around this by bulk labelling those fields with their values in jira, migrate them to tags in devops and then bulk update the values there again. 

Thanks

**Comment by dlauryssen** [comment]
@madkoo i did the migration with my workaround using labels, so not urgent anymore, but indeed would very much like to know what the issue was. I check out the REST call you mentioned and the fields I was referring to e.g. "Account" are not even mentioned there. Strange. What does that mean?

**Comment by smanthena2** [comment]
@dlauryssen  Can you please share the workaround you mentioned if you have no problem to share. I would like to try it for my project and check if that works for me

**Comment by dlauryssen** [comment]
@smanthena2 it is what I mentioned above. In my situation I had trouble with the migration of 2 fields, both of them picklists with limited number of options/values. So basically I queried Jira for each value, added Labels in Jira reflecting the value, migrated it as such to devops to Tags, and then updating the field manually in devops based on querying those tags.  All manual edits using queries and bulk changes. In total for me for about 10 ish values.  It's a bit stupid, but do-able when facing deadlines because it was "only" 10 ish. If you have more it's not really do-able.
If you have no deadline, best to check with madkoo first. 
Did you find your custom field using the  "https://yourjira.atlassian.net/rest/api/2/field"  REST call? I didn't.

**Comment by madkoo** [comment]
@dlauryssen  that is weird indeed you did not get that field from the Rest call. It could've been due to permissions because that call returns only fields you have access to.

@smanthena2 can you be specific what type of field it is, what kind of values there are etc. So I could reproduce the same case.

**Comment by dlauryssen** [comment]
@madkoo I'm not sure but I think these fields are part of an app/plugin from jira marketplace. Does that make a difference?

**Comment by smanthena2** [comment]
@madkoo  We have a custom field called "Company/Client Name" of type "Labels" in Jira and we are trying to map it to a text field in AZD. For few of the work items all the values are populated with a space as seperator. For few work items it exports ";" or ";;;" instead of the values and for few other values are empty.

**Comment by madkoo** [comment]
@smanthena2 so  the field and its data  look kind of like this : 
![image](https://user-images.githubusercontent.com/1208114/85697528-89dc4600-b6e2-11ea-8b3a-f5c7f334f2be.png)

**Comment by smanthena2** [comment]
@madkoo  Yes.  And the work items after import in the two scenarios i mentioned looks like [this:](url
![AZD imports](https://user-images.githubusercontent.com/48346389/85702744-560e1a00-b6fc-11ea-8df4-48445ea37e97.jpg)
)

**Comment by madkoo** [comment]
@smanthena2 can you provide your mapping configuration for this field?

**Comment by smanthena2** [comment]
{
"source": "customfield_10300",
"target": "Custom.ExternalTicketReporter"
},

And rest api for this filed.
{"id":"customfield_10300","key":"customfield_10300","name":"Company/Client Name","untranslatedName":"Company/Client Name","custom":true,"orderable":true,"navigable":true,"searchable":true,"clauseNames":["cf[10300]","Company/Client Name"],"schema":{"type":"array","items":"string","custom":"com.atlassian.jira.plugin.system.customfieldtypes:labels","customId":10300}}

**Comment by smanthena2** [comment]
@madkoo  we have the same fields as shown in above screenshot for both the work items. Strangely, it maps the values for one item, but gives ";;;;" for other

**Comment by madkoo** [comment]
@smanthena2  I understand that the same field is shown for different work items. What I meant was that for that Work Item that has ";;;;" in the field, if you open the same issue in Jira how does the data look there compared to the other that migrated proper data?

All the issue data that is exported in the .json files will be saved to azure. You can check or share how that data looks in the exported file. I am guessing it is already wrong there. 

The reason I'm asking these questions is to make sure how the data looks like because otherwise, it is hard to reproduce the same scenario. From my screenshot before I was able to migrate the test data.

**Comment by smanthena2** [comment]
@madkoo  This is how it looks in exported json file.
{
          "ReferenceName": "Custom.ExternalTicketReporter",
          "Value": ";;;;;;;"
        },

And this is how it looks in jira
![jira](https://user-images.githubusercontent.com/48346389/85708153-83a99200-b701-11ea-93f4-00533830bd4c.JPG)

**Comment by madkoo** [comment]
@smanthena2 sorry for my late reply. UnfortunatelyI was not able to reproduce your problem
