### ISSUE TITLE
"target work item for Jira is not yet created in Azure DevOps/TFS"

### ISSUE THREAD

**Issue by VictorioBerra** [solidify/jira-azuredevops-migrator#253]
Why doesn't it just create that issue first then? Does'nt it have all the info it needs to know that theres some parent issues that should be created first?

**Comment by madkoo** [comment]
@VictorioBerra  Please try with the latest version of the tool, that should have fixed this issue. 
Closing this issue for now. Feel free to contact us if still facing problems.

**Comment by junejaalok** [comment]
@madkoo We have pulled the latest version and that is still the issue. We encounter that very frequently. Any solution to it.
