### ISSUE TITLE
links not exported to JSON

### ISSUE THREAD

**Issue by dlauryssen** [solidify/jira-azuredevops-migrator#254]
Hi guys,

Having issues with links totally not exporting to JSON.

Not even the related links, and especially the created aka defect links

REST API provides me the following link type names 

![image](https://user-images.githubusercontent.com/11612664/84529222-5c0a0100-ace1-11ea-829a-17a21b6cb4d3.png)

It's a jira server 8.6

I'm using the following config

`{
  "source-project": "XXXXXX",
  "target-project": "XXXXXX",
  "query": "project = XXXXXXAND id in (XXXXXX)",
  "using-jira-cloud": false,
  "workspace": "C:\\_LOCAL\\XXXXXX\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "C:\\_LOCAL\\XXXXXX\\users-test.txt",
  "base-area-path": "",
  "base-iteration-path": "",
  "ignore-failed-links": true,
  "process-template": "Agile",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      {
        "source": "Blocks",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Bonfire testing",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Cloners",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Defect",
        "target": "System.LinkTypes.Related"
      },
	  {
        "source": "created",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Ordonnancement",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Problem/Incident",
        "target": "System.LinkTypes.Related"
      },
	  {
		"source": "Dependency",
		"target": "System.LinkTypes.Dependency-Forward"
	  }	  
    ]
  },`

![image](https://user-images.githubusercontent.com/11612664/84529138-35e46100-ace1-11ea-85fa-78f2a82fdcb0.png)

**Comment by dlauryssen** [comment]
The only result I'm getting is  "Links": [],  in both of the files (the one being pointed to and the one pointing)

**Comment by dlauryssen** [comment]
Solved. The links were migrating after using the correct names i got from the REST API.  They  were exported in the JSON, but in the history. I was under the wrong assumption that the links should have appeared on the top section where it says       

`      ],
      **"Links": [],**
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "XXXX@XXXX.com",
      "Time": "2019-03-27T17:15:37+01:00",
      "Index": 1,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },`

**Comment by madkoo** [comment]
@dlauryssen  good to hear you were able to solve this issue :) 
I will close this issue.
