### ISSUE TITLE
Story Points with decimal seperator not migrating to devops correctly

### ISSUE THREAD

**Issue by dlauryssen** [solidify/jira-azuredevops-migrator#255]
Hi guys,

Just wanted to let you know that Story Points field with values such as 4.25 are downloading correctly into JSON as 4.25 but uploading to devops as 425

And yes, I know, why oh why use decimal seperators in a story point field. I get that question. This wasn't my choice as I'm only migrating it :) 

I will probably be manually correcting them in devops using Exel plugin. 

KR,
David

**Comment by madkoo** [comment]
@dlauryssen thanks for the issue report, but not sure how you mean? Because I was not able to reproduce your scenario. When I added 4.25 story point in Jira and Imported that to Azure then it was the same "4.25".

**Comment by madkoo** [comment]
@dlauryssen closing issue due do inactivity and unable to reproduce. Feel free to contact us if the problem persists.
