### ISSUE TITLE
Export Command Returning HTML Rather than JSON

### ISSUE THREAD

**Issue by theonetruejediknight** [solidify/jira-azuredevops-migrator#256]
Executing the following export command, I get the JIRA project home page in html as the return response rather than JSON. Can anyone explain why?

Executed:
jira-export -u user -p pwd --url https://XXXX/projects/<Project> --config config-agile.json --force

I have removed the actual URL but this is the general command.

Response
[I][15:16:41] Connecting to Jira...
[I][15:16:42] Retrieving Jira fields...
[E][15:16:43] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: DOCTYPE html

**Comment by madkoo** [comment]
@theonetruejediknight it is kind of hard to explain why you might get this exception just seeing a small part of the log. 
It could access related nad then the login page HTML is retired or it could be something else.
That being said it would be useful to see the entire export log.

**Comment by kkagwade** [comment]
Hi,
I am also facing the same issue for command
jira-export -u user -p pwd --url https://XXXX/projects/ --config config-scrum.json --force

Kindly help me with this issue.

check the attachment for logs
[jira-export-log-220908-203453.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9528095/jira-export-log-220908-203453.txt)

**Comment by Alexander-Hjelm** [comment]
@kkagwade, please create a new issue for your support errand :)
________________________________
