### ISSUE TITLE
Jira issue projects

### ISSUE THREAD

**Issue by gekap** [solidify/jira-azuredevops-migrator#257]
Hello,

I have a question.

If I have a Jira Project proj1 and on the same project there issues from proj2. When I do the export Project1 I have proj1-1111.json and proj2-2222.json.

When I import Project1 on azure devops is it possible the proj2-2222.json to import on the project2 instead of project1 and create a link which connect the two projects??

Thank you,
George

**Comment by madkoo** [comment]
@gekap the tool currently does not support this kind of migration. Thank you for the input.

**Comment by gekap** [comment]
Hello,

Is it possible to add it as feature ?

**Comment by sgullluu** [comment]
after migration to azure devops , you can move that issue to project 2  a manually using " move to Team project" option in GUI

**Comment by Alexander-Hjelm** [comment]
Closing this, as we have no future plans of supporting cross-project scenarios.
