### ISSUE TITLE
Values not available for System Generated Fields

### ISSUE THREAD

**Issue by masghah** [solidify/jira-azuredevops-migrator#262]
I'm experiencing an issue pulling values for fields that are generated systematically in Jira. We have an Analyst (user) custom field that is set to the authoring user on create of a Jira ticket. This value doesn't show up in the issue history, but does contain a value in the field on the issue form. If a user changes the value to another user, the field value will change and will then show up in the history log and therefore is available in the Jira JSON export. 

I have confirmed that this field does not display in the JSON results when running the following Jira API calls: 
a.	https://[company].atlassian.net/rest/api/latest/issue/[issuekey]/
b.	https://[company].atlassian.net/rest/api/latest/issue/[issuekey]/changelog

Is there any way to update the config file to either always include this value or statically set that field to the author on the first revision? I'm also open to other suggestions. 

Thanks!

**Comment by MOlausson** [comment]
Hi @masghah, I'll take a look at this. Can you share the definition of the Analyst field in Jira for us to setup a scenario to test?

**Comment by masghah** [comment]
Sure! 

**Field Name:** Analyst
**DataType:** User Picker (com.atlassian.jira.plugin.system.customfieldtypes:userpicker)
**Orderable:** True
**Navigable:** True
**Searchable:** True

Hopefully that's what you're looking for. Let me know if need other information.

**Comment by MOlausson** [comment]
@masghah sorry for the slow response. Did you manage to resolve it?

**Comment by MOlausson** [comment]
@masghah closing this one for now, feel free to open it up again.
