### ISSUE TITLE
Missing Attachments and linked issues

### ISSUE THREAD

**Issue by ShindhujaaR** [solidify/jira-azuredevops-migrator#263]
Hi ,

While exporting the issue types from jira there arises and error in the export log stating : the info for the attachment with id "<somevalue>" is not found and once after the import is completed the attachments are being found with some data loss so the attachment fails to download and the size of the attachments also seems to be a variation in the file size.
There were also some work items in which the linked issue types were missing in both the child and parent link as well after the import has been done.
Kindly help us in getting an update on the above mentioned issues.

Regards,
Shindhujaa R

**Comment by ShindhujaaR** [comment]
@MOlausson can you please help us in sorting this issue

**Comment by MOlausson** [comment]
@ShindhujaaR can you try again using the latest release?

**Comment by MOlausson** [comment]
@ShindhujaaR assuming you've made progress on this one? Closing for now but feel free to re-open if you need more help.
