### ISSUE TITLE
Images are not displayed after importing to Azure

### ISSUE THREAD

**Issue by hema368** [solidify/jira-azuredevops-migrator#266]
![imagenotimport](https://user-images.githubusercontent.com/68506870/89391822-56033000-d726-11ea-9454-9a9faf901ebc.png)

**Comment by MOlausson** [comment]
@hema368 can you provide an example from Jira + the config file you used for the mapping?

**Comment by anveshgonu** [comment]
@MOlausson The images are not displayed within the respective details sections, instead respective mapping value is appearing. but they are available as attachment as shown in screenshot available in attachments section.
![image](https://user-images.githubusercontent.com/61251856/89454693-b625c080-d77e-11ea-832b-4dacb15328cb.png)
![image](https://user-images.githubusercontent.com/61251856/89455389-e1f57600-d77f-11ea-8e01-6f668d4b08fb.png)

**Comment by MOlausson** [comment]
@hema368 which version of the migrator are you using? Also can you share the exported json and the config file? This works fine in my test case on v2.3.117, that's why I'm asking.

**Comment by hema368** [comment]
Hi I used the same v2.3.117

**Comment by MOlausson** [comment]
Ok. Can you share the json file from the export?

**Comment by MOlausson** [comment]
@hema368 did you get this to work?

**Comment by MOlausson** [comment]
@hema368 closing this one, feel free to reopen if you still face this issue.
