### ISSUE TITLE
Image with space in name failed to display after imported to Azure.

### ISSUE THREAD

**Issue by rrongcheng** [solidify/jira-azuredevops-migrator#267]
I just found if an image has space in its name, Jira will use '+' to replace space. Then wi-import can't pick this path up.

Here is an example:
We have a Jira ticket that has an image named '**SAND G06 duplicate.jpg**' in the description.
In the Jira web page, the image address is like ''...&name=**SAND%20G06%20duplicate**.jpg&...'
By calling Jira API, it return '<img src=\"/secure/attachment/32887/32887_**SAND+G06+duplicate.**jpg\" '
After I export the issue from Jira, the attachments save the image with its original name, which is with space,
![image](https://user-images.githubusercontent.com/15684748/89501670-51a64800-d7f6-11ea-8be4-50352bd5a338.png)
And description field has it with '+' which is direct from Jira.

Then in wi-import, Agent.CorrectImagePath(), it won't find 'SAND G06 duplicate.jpg' in the description field, then the temp path '/secure/attachment/...' will be pass to Azure DevOps. 

As a result, the image won't be able to be displayed in DevOps.

I'll hardcode the fix in my local. But think it worth reporting here.

AB#5956

**Comment by MOlausson** [comment]
@rrongcheng good catch, I haven't seen this before but with the details you provide we should have no problem to repro. Which version of the migrator are you using (the latest I suppose since you seems to have fixed it locally)?

**Comment by rrongcheng** [comment]
Hi @MOlausson ,
Sorry for missing this part, I found and repro this bug on version 2.3.85 and 2.3.117.

**Comment by madkoo** [comment]
This is related to #225 and #226. We will look into this.

**Comment by Alexander-Hjelm** [comment]
Fixed by: https://github.com/solidify/jira-azuredevops-migrator/pull/489
