### ISSUE TITLE
Links from Epics are not correct, if Epic is created after the childs

### ISSUE THREAD

**Issue by rpes2** [solidify/jira-azuredevops-migrator#268]
Hello,
I try to migrate a project from Jira Server to Azure Devops. I have some Epics in the project, that were created after the features and tasks.
If I import this data in Azure Devops the first feature of the Epic becomes the parent of the Epic in Azure Devops. All other features get an error in the import, "You can not add a Parent link to this work item because a work item can have only one link of this type.. Link Source: 5533, Target: 5531 in 'IKS-844', rev 2 will be skipped."

If I change in the Epic Json-file the time of the first revision to a time before the first feature, the import is correct.
In the zip-File you will find the configuration and the relevant Json-Files. IKS-844 ist the Epic.

[jira-exporter3.zip](https://github.com/solidify/jira-azuredevops-migrator/files/5050392/jira-exporter3.zip)

**Comment by madkoo** [comment]
@rpes2 it seemes that your "child" link configuration in your config.json is incorrect. 
It should look like this:`      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },`

**Comment by rpes2** [comment]
Thank you for your help. This solved the problem.
