### ISSUE TITLE
Unable to map story point estimate to Effort

### ISSUE THREAD

**Issue by vittau** [solidify/jira-azuredevops-migrator#269]
Hi,

I have set up the following mapping
`{
  "source": "Story point estimate",
  "type": "double",
  "target": "Microsoft.VSTS.Scheduling.Effort",
  "for": "Product Backlog Item,Task,Bug,Design"
}`
but it doesn't export the estimates. Also, why is the default source in the sample config files "Story Points", when apparently the JIRA default is "Story point estimate"; and why doesn't it work?

Thanks!

**Comment by vittau** [comment]
Apparently for some reason it was a custom field in our board, and I had to use _/rest/api/2/field_ to discover the custom field name.

**Comment by MOlausson** [comment]
@vittau happy to hear you figured it out!
