### ISSUE TITLE
Hi, I have a query regarding link types pointing to other project in Jira. 

### ISSUE THREAD

**Issue by PraveenaSeela** [solidify/jira-azuredevops-migrator#277]
Currently I am running migration from Jira to Azure Devops using Solidify. And in our project we have dependency links pointing/mapping to other project, which is already been migrated to Azure. 

So in this case how to establish the links in Azure during migration?

And below is the code i used in config file.

{
        "source": "Dependency",
        "target": "System.LinkTypes.Dependency-Reverse"
      },

Forward/Reverse depends upon the link mapping.

Please let me know the solution as asap, as the migration is on hold due to this issue.

**Comment by madkoo** [comment]
@PraveenaSeela the tool can only link items that are being migrated.  Unfortunately, it is not possible to link to an existing item in azure

**Comment by PraveenaSeela** [comment]
@madkoo Oh..k. anyway thanks for your reply.

And one more question related to Link Types mapping: 

In the latest migration i also noticed that, only 'Open' link workitems are mapping to Azure but not the 'closed and Resolved' links. Is it something wrong in the code or to include anything..?
I used the below code in the config file.
 "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Dependency",
        "target": "System.LinkTypes.Dependency-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Related Issue",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      {
        "source": "Fixes",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Issue split",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Change Requests",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Cloners",
        "target": "System.LinkTypes.Related"
      }
