### ISSUE TITLE
How to migrate a Project which has bulk data?

### ISSUE THREAD

**Issue by PraveenaSeela** [solidify/jira-azuredevops-migrator#278]
Hi,

I wanted to migrate a Project which has around 22,000 issues from Jira to Azure Devops. Also the project has dependency & inter dependency link types.

So can anyone suggest me the better way migration so that all the links should happen properly.?

Thanks

**Comment by MOlausson** [comment]
@PraveenaSeela is this related to #277? The tool handles large migrations so that should not be a problem. Link types outside of core Jira as well as 3rd-party extension may need customizations to the tool. We support that as a paid service so feel free to contact us directly at info@solidify.se.

**Comment by PraveenaSeela** [comment]
@MOlausson Thank you so much for your reply.                                                                                                                                                But my concern here is how many days it will take to migrate? I have seen for couple of projects which have around 7000 workitems took one complete day for export and import. Also noticed if we lost the Jira connection in between, the export will be stopped and need to start the export again from first.

If we divide the data as below n export all the data first separately to 'temp' folder and then import at once to Azure, will the migration and mappings of the link dependencies work as expected?
Export 1- 2015: project = XXXX AND created >= 2015-01-01 AND created <= 2015-12-31 ORDER BY created ASC  -- 4114 Workitems
Export 2-2016: project = XXXX AND created >= 2016-01-01 AND created <= 2016-12-31 ORDER BY created ASC  -- 889 Workitems
Export 3-2017:: project = XXXX AND created >= 2017-01-01 AND created <= 2017-12-31 ORDER BY created ASC  -  7442 Workitems
Export 4-2018:: project = XXXX AND created >= 2018-01-01 AND created <= 2018-12-31 ORDER BY created ASC  -- 4689 Workitems
Export 5-2019:: project = XXXX AND created >= 2019-01-01 AND created <= 2019-12-31 ORDER BY created ASC  -- 3403 Workitems
Export 6-2020: project = XXXX AND created >= 2020-01-01 AND created <= 2020-08-31 ORDER BY created ASC  -- 1903 Workitems

**Comment by madkoo** [comment]
@PraveenaSeela if you happen to get connection issues with Jira and the export stops then you can continue where you left of the export. In the command don't use the "--force" parameter then. All previously exported items will be skipped.

**Comment by PraveenaSeela** [comment]
@madkoo thanks for your information.

**Comment by PraveenaSeela** [comment]
@madkoo Then in the above case, as per your suggestion, can i do migration export steps wise? Will the migration and mappings of the link dependencies work as expected?

Please suggest me on this.

Thanks.

**Comment by madkoo** [comment]
@PraveenaSeela Theoretically it should work, have not done a migration with steps. 
Just a suggestion to avoid getting inconsistencies is to initially export steps to different folders and then copy them into a single folder before running import

**Comment by PraveenaSeela** [comment]
@madkoo Thanks. I will try migration as you suggested.
