### ISSUE TITLE
wi-import: System.NullReferenceException

### ISSUE THREAD

**Issue by Tallies** [solidify/jira-azuredevops-migrator#28]
Hi,

I exported from my Jira project without error. I can see a whole lot of `JiraProject-<NUM>.json` files as well as attachments in the Attachments folder. Step 6 in the migration guides mentions a journal file, which I don't see, but I might not be far enough in to process to see one.

When running import, I get the following exception:

`Unexpected error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Migration.WIContract.WiItemProvider.LoadFile(String path)
   at Migration.WIContract.WiItemProvider.<EnumerateAllItems>d__5.MoveNext()
   at Migration.Common.MigrationContext.<EnumerateAllItems>d__36.MoveNext()
   at WorkItemImport.ExecutionPlanBuilder.BuildExecutionPlanFromDir()
   at WorkItemImport.ExecutionPlanBuilder.BuildExecutionPlan()
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh)`

The command I use:

`.\wi-import.exe --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --url https://dev.azure.com/MYDEVOPS --config C:\temp\JiraExports\JiryToDevOps\config-JiraProject-DevopsProject.json`

The config file:
[config-JiraProject-DevopsProject.zip](https://github.com/solidify/jira-azuredevops-migrator/files/2851569/config-JiraProject-DevopsProject.zip)

The import log file.
[log.ee3fcdc1-f388-4522-9cc7-c323fa1b45f1.zip](https://github.com/solidify/jira-azuredevops-migrator/files/2851583/log.ee3fcdc1-f388-4522-9cc7-c323fa1b45f1.zip)

Any help on whether I'm doing something wrong would be appreciated.

Kind regards,
Charl Marais

**Comment by MOlausson** [comment]
Hi Charl,

It looks like the import tool fails to iterate over the set of exported .json files. Can you verify that the path used in the export is the same as for the import? Also check if the folder contains any .json files that aren't exporter Jira issues (I assume that can be a problem). To simplify I would suggest having the tools and configuration in one folder (i.e. c:\temp\jira-azuredevop) and export to a different folder (i.e. c:\temp\jira-export).

Mathias

**Comment by MOlausson** [comment]
@Tallies Did you get to work around this? I tested and get the same error if for instance the config.json is in the same folder as the export files. I'll start work on a fix to resolve this issue but in the meantime you should be unblocked by keeping the export files in a separate directory for the import.

**Comment by Tallies** [comment]
@MOlausson 

Apologies for the tardy response. I haven't had a chance to retry. I'm running right now with the proposed solution, and will let you know. 

Thanks for your prompt response!

Tals

**Comment by MOlausson** [comment]
@Tallies take your time. Let us know when you have tested, we've got an update in the works what will handle the error but you should be fine by separating the file types for now.

**Comment by Tallies** [comment]
Hi Mathias,

Work if your config is separate from your export/import folder.

Thanks!

**Comment by JulienDecottignies** [comment]
Hi, I have exactly the same exception but my Export folder is not in my config folder.

Here is my export.config.json file:

[export.config.zip](https://github.com/solidify/jira-azuredevops-migrator/files/2930683/export.config.zip)

Here the log with the exception
[log.5c4ba1ae-5440-42e7-98cb-6089316fccda.zip](https://github.com/solidify/jira-azuredevops-migrator/files/2930686/log.5c4ba1ae-5440-42e7-98cb-6089316fccda.zip)

Thanks for your help !

**Comment by Jeroenskie** [comment]
I had the same problem. When I delete the hidden file .json  in the export directory the problem is fixed.

**Comment by MOlausson** [comment]
Thanks all for your feedback. We have an update in progress, hope to release it tomorrow. The new version will also include more verbose logging to help troubleshoot.
