### ISSUE TITLE
Summary/Description field changes not being reflected in revisions

### ISSUE THREAD

**Issue by halljames** [solidify/jira-azuredevops-migrator#280]
I want to use this tool in a one way sync process, by NOT using the --force parameter, it seems to work well by simply adding in the revisions, however, it does not seem to handle the summary field in JIRA.  If I amend a Jira issue and update its title, this is treated as a new revision, so multiple exports and imports seems to correctly update the item in AzureDevOps.  However, updating the summary/description does not seem to create a new revision, and that change is lost.

**Comment by madkoo** [comment]
@halljames  sorry for the late response. As I understand the revision is not created on Jira side when you update summary/description ?

**Comment by halljames** [comment]
Thanks for the response.  I think I have actually sorted it however.  The solution for some reason was to update the config file so that the summary field uses the default mapper.  For some reason, this started bringing through the summary/description updates.

**Comment by madkoo** [comment]
@halljames that's good to hear that you were able to sort it out :)
