### ISSUE TITLE
Commits, pull request and branch are not showing in Azure DevOps WI

### ISSUE THREAD

**Issue by rakeshkulkarni6** [solidify/jira-azuredevops-migrator#281]
I have started Migration from Jira to Azure Devops, I am able to map most of the fields, states in Azure.
I have Azure Git Integration with JIRA, which adds commits, pull Requests  and Branches in field Azure Git in JIRA.
I am not sure how to map these fields in Azure DevOps.[](url)x-special/nautilus-clipboard
copy
![Screenshot from 2020-09-17 00-40-00](https://user-images.githubusercontent.com/26158574/93381581-82aa7b80-f87e-11ea-989b-83f14ddcbed2.png)
![Screenshot from 2020-09-17 00-39-41](https://user-images.githubusercontent.com/26158574/93381587-84743f00-f87e-11ea-957e-c83e30d96f38.png)

**Comment by MOlausson** [comment]
@rakeshkulkarni6 we don't yet support this scenario, it's tracked in enhancement #233 which we plan to address in the coming v3.

**Comment by cbladd** [comment]
Does this issue refer only to Azure DevOps.x-special/nautilus-clipboard or is there, more generally, no current support for importing commit/ticket links from jira to ADO?
