### ISSUE TITLE
How can Jira key can be placed in separate field in Azure Devops via Solidify.

### ISSUE THREAD

**Issue by Dushki** [solidify/jira-azuredevops-migrator#285]
Hi,
While migration through Solidify, Jira key is appended in the starting of summary title of Azure work items. I need to publish the same as a hyperlink(so that i can click on the jira key and navigate directly to jira) in a seprate field in Azure Devops. Is it possible? Where to change the code ?

**Comment by MOlausson** [comment]
@Dushki you can specify in the config file how to map (transform) the different fields, there are multipe options as described here:

https://github.com/solidify/jira-azuredevops-migrator/blob/b273087406e88bc452ec1df9aeea856e7ee2d622/docs/config.md#mappers

You can then also create a custom mapper but in your scenario you can use the MapTitleWithoutKey mapper for the title and then a default mapping for the key to the separate field in Azure DevOps.

**Comment by Dushki** [comment]
Thanks @MOlausson , It seems i need to create custom mapper. Any reference on how i can create hyperlink in Jiramapper.cs file.

**Comment by MOlausson** [comment]
Take a look at https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraMapper.cs. Then you can add a mapper to concatenate a proper URL. If you then map it to an HTML field it will render as a link.

**Comment by Dushki** [comment]
Thanks :)

**Comment by Dushki** [comment]
Thanks
