### ISSUE TITLE
The work items of type bug are not aligned properly.

### ISSUE THREAD

**Issue by ShindhujaaR** [solidify/jira-azuredevops-migrator#295]
When migrating the work items from jira to AzureDevOps the work items of the type Bug are not aligned properly. The description of the issue in jira with the bullet formats are not displayed in AzureDevOps with the proper alignment and the content is displayed as entire paragraph. Attached the screenshot for reference

![image](https://user-images.githubusercontent.com/68641470/98236811-f5d09400-1f89-11eb-83df-950421585a42.png)

Could you please suggest a way to resolve this alignment issue in priority.

Thanks,
Shindhujaa R

**Comment by ShindhujaaR** [comment]
Team can you please help on this

**Comment by ShindhujaaR** [comment]
@MOlausson can you please help with this issue

**Comment by Paradox92** [comment]
you need to define the correct mapper in the map section

```
{
    "source": "description",
    "target": "Microsoft.VSTS.TCM.ReproSteps",
    "mapper": "MapRendered",
    "for": "Bug"
}
```

**Comment by ShindhujaaR** [comment]
I have also given the same mappers but still then am facing the same issues with alignments in the description of the work items of type Bug

**Comment by Pairoba** [comment]
Double check if you have provided the correct config-file and that you don't have configured this map entry twice. For me it's working as expected since just changing the mapper from default configuration.

**Comment by Alexander-Hjelm** [comment]
See solution by @Pairoba

Closed due to inactivity. Feel free to open again if this is still an issue
