### ISSUE TITLE
Migration in not working for on-premises Jira.

### ISSUE THREAD

**Issue by Nikhilnick1203** [solidify/jira-azuredevops-migrator#296]
**Describe the bug**
When I ever I run the Jira-export command, I'm getting an **Unexpected migration error**. I tried with only username and with the domain name as well. Attached a log file

**To Reproduce**
1. The command I'm using Jira-export -u username -p xxxxxxx --url https://jira-url/ --config config-scrum.json --force
2. [E][10.35.03] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Response Content: <html>

<head>
    <title>Unauthorized (401)</title>
[jira-export-log-201106-103729.txt](https://github.com/solidify/jira-azuredevops-migrator/files/5499206/jira-export-log-201106-103729.txt)

**Comment by gekap** [comment]
Hello,

What is your version of Jira?

**Comment by Nikhilnick1203** [comment]
Hi,

My Jira version is 8.8.1

**Comment by gekap** [comment]
Hello,

Please confirm that the  using-jira-cloud":  has value **false** in your configuration.

I have Jira 8.4.1 on premises and I do not have your issue.

Thank you,

**Comment by Alexander-Hjelm** [comment]
Verfiy that you are using a JIRA access token and not your account password.

Closed due to inactivity. Feel free to open again if this is still an issue
