### ISSUE TITLE
Error "target work item for Jira 'Project' is not yet created in Azure DevOps/TFS" when importing

### ISSUE THREAD

**Issue by bientt210** [solidify/jira-azuredevops-migrator#304]
Hi Everyone,

I has issue when importing data to Azure:
**[W][10:34:33] '[Added] Project20-331/-1->Project20-347/-1 [System.LinkTypes.Hierarchy-Reverse]' - target work item for Jira 'Project20-347' is not yet created in Azure DevOps/TFS.**

It's happen so many time when I importing.
My config-agile.json with `child` and `parent` as below :

`  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },`

Does anyone has the same error? How to fix that?

Thanks you

**Comment by Alexander-Hjelm** [comment]
Closed due to inactivity. Feel free to open again if this is still an issue
