### ISSUE TITLE
Wrong states mapping

### ISSUE THREAD

**Issue by gekap** [solidify/jira-azuredevops-migrator#305]
Hello,

I use the latest version of your tool to migrate Jira to Azure DevOps,

A user complained that the tool migrated the wrong states in Azure DevOps.

For example, In jira a issue was in Closed and instead of Complete and new state was Review which wrong.

Any ideas?

On Jira,

![image](https://user-images.githubusercontent.com/43109822/101697260-2bccd080-3a80-11eb-90a9-dad219f343d1.png)

Same on json file.

![image](https://user-images.githubusercontent.com/43109822/101698280-e7423480-3a81-11eb-9700-577d3a69996d.png)

My states on my config file

![image](https://user-images.githubusercontent.com/43109822/101698382-093bb700-3a82-11eb-850e-3f0c2b74f501.png)

![image](https://user-images.githubusercontent.com/43109822/101698481-34260b00-3a82-11eb-99c3-fb21d42cd8f1.png)

![image](https://user-images.githubusercontent.com/43109822/101698528-4b64f880-3a82-11eb-85e8-c4a8d2617ef6.png)

![image](https://user-images.githubusercontent.com/43109822/101698580-68013080-3a82-11eb-9482-a0755ce97fc8.png)

As you can see I have not map Closed to Review.

Can you please advice what can I do?

**Comment by gekap** [comment]
Hello

I run the export from jira to AzDO and I have wrong mapping

![image](https://user-images.githubusercontent.com/43109822/101740908-18e2ec00-3ad2-11eb-9387-7ad08990da5e.png)

My confing
![image](https://user-images.githubusercontent.com/43109822/101740989-30ba7000-3ad2-11eb-8062-d7c65b075eec.png)

As you can see it should be Development and not New.

What can be wrong?
It's a blocker as migration is in progress.

**Comment by kedarbhise** [comment]
@gekap could you please take a look at #344?
In your output JSON, we can see that you have managed to export FixVersion correctly, which is the problem we are facing.
Thanks in advance for your help.
