### ISSUE TITLE
Mapping issue

### ISSUE THREAD

**Issue by Nagachandra3458** [solidify/jira-azuredevops-migrator#310]
Hello Support,
I tried to move one of the projects from Jira to Azure DevOps, work items have not changed the State it's still in "New",
![image](https://user-images.githubusercontent.com/71813581/102741503-8582a400-4378-11eb-93dc-96466d3b213f.png)

In Boards, no data is moved.
![image](https://user-images.githubusercontent.com/71813581/102741818-59b3ee00-4379-11eb-8194-8369dc2df269.png)

In Jira
![Boards in Jira](https://user-images.githubusercontent.com/71813581/102741835-6d5f5480-4379-11eb-873a-0990003d6e97.PNG)

Script I used 

{
  "source-project": "xxxxxx",
  "target-project": "xxxxxxx",
  "query": "project='xxxxxx'",
  "using-jira-cloud": true,
  "workspace": "A:\\Temp\\JiraExport\\xxxxxx",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "Agile",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Feature"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "User Story"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Feature,Epic,User Story,Bug",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            },
            {
              "source": "PEER REVIEW",
              "target": "PEER REVIEW" 
            },
            {
              "source": "RESOLVED",
              "target": "RESOLVED"
            },
            {
              "source": "TASK COMPLETED",
              "target": "TASK COMPLETED"
            },
            {
              "source": "UAT",
              "target": "UAT"
            },
            {
              "source": "LIVE",
              "target": "LIVE"
            },
            {
              "source": "READY FOR TEST",
              "target": "READY FOR TEST"

            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "PEER REVIEW",
              "target": "PEER REVIEW" 
            },
            {
              "source": "RESOLVED",
              "target": "RESOLVED"
            },
            {
              "source": "READY FOR TEST",
              "target": "READY FOR TEST"

            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.StoryPoints",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      },
      {
        "source": "environment",
        "source-type": "name",
        "target": "Microsoft.VSTS.TCM.SystemInfo",
        "for": "Bug,Epic"
      }
    ]
  }
}

Can you please help me out with this migration?

You can reach me at 
Email : nagachandra3458@outlook.com
Cell : +91 9000114478

**Comment by Nagachandra3458** [comment]
Can you advise

**Comment by gekap** [comment]
Hello,

I have the same issue and I noticed that the wrong mapping does not affect all the issues just some.

I have reported 14 days ago

**Comment by Nagachandra3458** [comment]
@Solidify : Can you please guide us on this issue.

**Comment by sgullluu** [comment]
u were mapping story of Jira to Feature of Azure devops.
1) have u created To Do , In progress , done ...   States in Azure devops , since your feature doesnot have To do , in progress state its workflow so it is taking New.
2) in kanban board u were looking into Story board , but data should be present in Feature Board , as u have done mapping from Story to feature.

**Comment by Nagachandra3458** [comment]
Thank you Georgios for your reply, we did migration and all set, again thank you for your support.
________________________________
