### ISSUE TITLE
 Missing mapping value 'Merge to Trunk (SVN)' for field 'status' for item type 'Story'.

### ISSUE THREAD

**Issue by AjayKumaraj** [solidify/jira-azuredevops-migrator#311]
While running am getting this missing mapping value  anything am doing wrong in the configuration
58:57] Missing mapping value 'Merge to Trunk (SVN)' for field 'status' for item type 'Story'.
[W][20:58:57] Missing mapping value 'Code Review' for field 'status' for item type 'Story'.
[W][20:58:58] Missing mapping value 'Code Review' for field 'status' for item type 'Story'.
[W][20:58:58] Missing mapping value 'Merge to Trunk (SVN)'
[config-basic.zip](https://github.com/solidify/jira-azuredevops-migrator/files/5735908/config-basic.zip)

 for field 'status' for item type 'Story'

**Comment by sgullluu** [comment]
u need add those missing status in Json file
 {
        "source": "status",
        "target": "System.State",
		"for": "Issue,Story,Bug,Task,Sub_task",
        "mapping": {
          "values": [
            {
              "source": "Pending Requirements",
              "target": "Pending Requirements"
            },
			{
              "source": "Merge to Trunk (SVN)",
              "target": "Merge to Trunk (SVN)"
            },
			 {
              "source": "Code Review",
              "target": "Code Review"
            },

**Comment by Alexander-Hjelm** [comment]
Resolved by @sgullluu , closing
