### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by DouglasG96** [solidify/jira-azuredevops-migrator#318]
i'll try to describe this, i can't speak english good but...

**To Reproduce**
i was trying to migrate all my issues (finished, to do, etc), that i have in my Jira Project and in this project we're 4 developers everyone has issues linked but in the DevOps Project they aren't members and when i try to import from jira all my issues the cli show me the next error:

**[E][14:02:45] Unexpected migration error.
[System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex no puede ser mayor que la longitud de la cadena.
Nombre del parámetro: startIndex**

**Expected behavior**
It's an unhandled exception

**Screenshots**
![image](https://user-images.githubusercontent.com/43095613/105228641-6f5b3580-5b28-11eb-8533-dbb057a55a18.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by MOlausson** [comment]
@DouglasG96 , thanks for the good issue report. Can you share your configuration file with us (here or send to support (at) solidify.se) to help us troubleshoot?

**Comment by DouglasG96** [comment]
> @DouglasG96 , thanks for the good issue report. Can you share your configuration file with us (here or send to support (at) solidify.se) to help us troubleshoot?

- This is my file configuration

confi-agile.json:

{
  "source-project": "SistemaMiSalud",
  "target-project": "Sistema Medico Mantenimientos",
  "query": "project = SistemaMiSalud AND status = 'To Do' ORDER BY createdDate ASC",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "Agile",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"  
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Historia",
        "target": "Feature"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "User Story"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Feature,Epic,User Story,Bug",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Done",
              "target": "Resolved"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Removed",
              "target": "Removed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "Tareas por hacer",
              "target": "New"
            },
            {
              "source": "En curso",
              "target": "Active"
            },
            {
              "source": "Finalizada",
              "target": "Closed"
            },
            {
              "source": "Removed",
              "target": "Removed"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.StoryPoints",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      },
      {
        "source": "environment",
        "source-type": "name",
        "target": "Microsoft.VSTS.TCM.SystemInfo",
        "for": "Bug,Epic"
      }
    ]
  }

**Comment by Alexander-Hjelm** [comment]
Fixed by: https://github.com/solidify/jira-azuredevops-migrator/pull/276 (not yet merged)
