### ISSUE TITLE
System.InvalidOperationException: Response was not recognized as JSON

### ISSUE THREAD

**Issue by MochaboM** [solidify/jira-azuredevops-migrator#319]
I am trying to migrate data from our project Jira server using the Agile config file. When I run the import command on the cli I got the error [E][12:49:29] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. 

**To Reproduce**
1. Configure the agile-config.json file with project details
2. Open command prompt, run the jira export command
3. See error

**Expected behavior**
Successful export from Jira

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version 88.0.4324.96 (Official Build) (64-bit)

We are using the Jira server V8.5.3

**Comment by jerrodgeorge** [comment]
I am having the same error. With the same recreate steps. 

[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

**Comment by jerrodgeorge** [comment]
I read through more documentation and I was able to get past this error by using my UN and not an email. I have now encountered another error that I am working my way through. 

NEW ERROR:
 Atlassian.Jira.Remote.ResourceNotFoundException: Response Content: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"

**Comment by attinder4u** [comment]
not able to export the data from jira getting below error 
 One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON
Using jira on premise server v8.5.4

Is there any work around to fix this?

**Comment by Alexander-Hjelm** [comment]
The "Response was not recognized as JSON" is likely a problem with authentication, since the unauthorized page renders as html.

I will close this issue due to inactivity. If you are still having problems, reopen the issue and mention me and I will try and help.

**Comment by kkagwade** [comment]
I am having the same error with the same recreate steps.
[E][20:20:20] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 500. Response Content: <html>
<head><title>JIRA &mdash; Internal Server Error</title>
<meta name="decorator" content="none"/>
</head><body>
<h1>JIRA &mdash; Internal Server Error</h1>
<p>Error reference: 9225cdbe-bbeb-4502-99c1-f4353a386549</p>
<p>Unable to render full error details at this time.
Please consult the error logs for more information.</p>

**Comment by Alexander-Hjelm** [comment]
@kkagwade create a new issue for your support errand :)
________________________________
