### ISSUE TITLE
Iteration Path of Sub-task in not moving to azure

### ISSUE THREAD

**Issue by ayushmaheswari** [solidify/jira-azuredevops-migrator#335]
Hi,

Whenever I try to export data from Jira-export I am always getting the iteration path as null only for the Sub-task workitem even though data is present in my Jira account I am searching whole code But not able to get it please help me as soon as possible.

Here I am putting Json file for one Sub-task workitem for your reference

{
  "Type": "Task",
  "OriginId": "PROJ-15",
  "WiId": -1,
  "Revisions": [
    {
      "Author": "ayush@gmail.com",
      "Time": "2021-03-03T12:24:27.944+05:30",
      "Index": 0,
      "Fields": [
        {
          "ReferenceName": "System.Title",
          "Value": "Task in task"
        },
        **{
          "ReferenceName": "System.IterationPath",
          "Value": null
        },**
        {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": "3"
        },
        {
          "ReferenceName": "System.State",
          "Value": "To Do"
        }
      ],
      "Links": [
        {
          "Change": 0,
          "TargetOriginId": "PROJ-14",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        }
      ],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "ayush@gmail.com",
      "Time": "2021-03-03T12:24:28.358+05:30",
      "Index": 1,
      "Fields": [],
      "Links": [
        {
          "Change": 1,
          "TargetOriginId": "PROJ-14",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        },
        {
          "Change": 0,
          "TargetOriginId": "PROJ-14",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        }
      ],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "ayush@gmail.com",
      "Time": "2021-03-03T12:26:41.346+05:30",
      "Index": 2,
      "Fields": [
        {
          "ReferenceName": "System.AssignedTo",
          "Value": "ayush@gmail.com"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    }
  ]
}

**Comment by Alexander-Hjelm** [comment]
Hi Ayush!

Paste your config file here and I will try and help you.

Since this is an old issue, I will close it due to inactivity. Feel free to open again if you require further help.

**Comment by ayushmaheswari** [comment]
Thankyou so much but i am able to complete that task.

**Comment by Alexander-Hjelm** [comment]
Ok, no worries!

And apologies for the long inactivity. We have had a change of staff, during which no one was monitoring issues.

**Comment by abbinenis** [comment]
> 

Hi Ayush. Could you please tell on how you were able to fix this issue. i am facing the same problem.
