### ISSUE TITLE
Date fields (both custom and Jira fields) are not migrating

### ISSUE THREAD

**Issue by mebithomas** [solidify/jira-azuredevops-migrator#346]
**Describe the bug**

Trying to migrate issues from Jira cloud to ADO.

Two date fields available in few Jira issues , start date & due date, both are added in the config file, but both are not migrating into ADO.

Please refer the config below.

    {
        "source": "customfield_12004",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.StartDate" ,
        "comment":"start date"
      },
      {
        "source": "duedate",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.DueDate",          
        "comment":"due date"
      }

1. Exported Issue json file reviewed, no reference about these two date fields.
2. Export & import log verified, no reference/errors about these two date fields.
3. Also not showing any errors related to these fields when we are running the export/import exes.

**To Reproduce**
No error or reference anywhere related to these fields

**Expected behavior**
Exact date from Jira issues should be migrated to ADO work items.

**Screenshots**
Image from Jira issue
![image](https://user-images.githubusercontent.com/74974644/111777999-549d0700-88b4-11eb-903c-ac1aaf7d5366.png)

Image from ADO work item.
![image](https://user-images.githubusercontent.com/74974644/111777941-3d5e1980-88b4-11eb-8f92-5f404927e23a.png)

AB#4705

**Comment by madkoo** [comment]
@mebithomas , remove from your mapping source-type: "name" that makes the tool to try mapping against the name of the field but as you are using IDs so there is no need to have that.

**Comment by mebithomas** [comment]
Hi @madkoo;

Thanks for the reply.

We tried without "source-type" and it was not working, so we tried with below and works as expected.
