### ISSUE TITLE
Field-Reason, Status-'InvalidEmpty ' Value : '' ValidationException - Workitem is not ready to save

### ISSUE THREAD

**Issue by tchoujar01** [solidify/jira-azuredevops-migrator#347]
Hi

I am unable to import more than half of my workitems as I get this error on import. I dont have  a feild -Reason, and I dont see it in the history as well, could be possible thta it was a part of the workitems before.
Logs:
[I][00:30:13] Field: 'Reason', Status: 'InvalidEmpty', Value: '' 
[E][00:30:13] Failed to import revisions for '0'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException] Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException: TF237124: Work Item is not ready to save

Thanks 

AB#4716

**Comment by Alexander-Hjelm** [comment]
Hi!

This is a common issue after switching process templates. You will either have to make sure that all items have the Reason field set, or try migrating to a project with a different temaplte

Closed due to inactivity. Feel free to open again if this is still an issue
