### ISSUE TITLE
Epic and Story links incorrect if items moved from one project to another

### ISSUE THREAD

**Issue by snims** [solidify/jira-azuredevops-migrator#348]
Here’s an interesting one.
The linking between a story and an epic will pull up the original jira id – meaning a jira moved from one project to another.
Here’s my query -   "query": "id=gcs-392 or id=gcs-318 " – just doing a test for the two items.

In the json for 392:
        {
          "Change": 0,
          "TargetOriginId": "CTCA-3897",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Forward"
        }

Conversely 318 was in the CTCA project and was moved as well and the json for 318 points to the wrong item.

Thus, the linking is broken.

Any ideas how to resolve?

AB#4774

**Comment by madkoo** [comment]
Not sure I 100% follow what you are trying to test here?
The linking is based on the metadata received from Jira APIs.

**Comment by snims** [comment]
why would the api return the original id versus the current id?

do you have any ideas on how that can be switched?  Things like:
do something in Jira to make it pass the current id
do something post writing of the json to have them switched

**Comment by Alexander-Hjelm** [comment]
Closed due to inactivity. Feel free to open again if this is still an issue
