### ISSUE TITLE
config-scrum.json does not like base-area-path and base-iteration path with "\" or "\\" 

### ISSUE THREAD

**Issue by Django0** [solidify/jira-azuredevops-migrator#352]
The config-scrum.json does not  path with "\" or "\\" 

This works: `"workspace": "C:\\Temp\\JiraExport\\",`

But, it failes for the below paths
```
  "base-area-path": "Workstreams\\Hardware\\Firmware",
  "base-iteration-path": "2021\\2021-4",
```

Kindly fix this. Thanks.

**Comment by lasseporsch** [comment]
Hi @Django0, 

we ran into the same problem. Counterintuitively, the correct notation for sprint/area hierarchies in the config file is to use single forward slashes:
`
  "base-area-path": "Workstreams/Hardware/Firmware",
  "base-iteration-path": "2021/2021-4",
`
Make sure to include the "root" sprint/area, which should be the same as your project name.

**Comment by priya785467** [comment]
hey @Django0 and @lasseporsch what are base area path and iteration paths? is it specific to Jira or azure boards?
