### ISSUE TITLE
How do I migrate the 'Rank' of issues in backlog in Jira to Order or 'StackRank' in Azure DevOps

### ISSUE THREAD

**Issue by Jonheidur** [solidify/jira-azuredevops-migrator#359]
Hi,

I have been testing export from Jira server to Azure Dev Ops and even if I rank the issues in the JQL query used in the config file when exported the issues seem to appear in random order in the backlog in Azure Boards.

Is there some known way of keeping the rank of issues between the two systems? I have tried googling but can not find any information on this so I feel that I am either missing something obvious or this is not possible.

I have tried mapping between 
      {
        "source": "Rank",
        "target": "Microsoft.VSTS.Common.StackRank",
        "for": "User Story, Issue, Epic, Feature"
      }
but StackRank field was empty in the tickets imported to Azure dev ops.

Any help on this would be greatly appriciated.

Best, Jónheiður

AB#5013

**Comment by lula-code** [comment]
Hi,
Jira and AzureDevops use different ranking systems.
You have to convert the Jira strings (like: "1|dfla1xx") into a double number.

Jira ranking system: https://tmcalm.nl/blog/lexorank-jira-ranking-system-explained/
DevOps: https://docs.microsoft.com/en-us/azure/devops/boards/queries/planning-ranking-priorities?view=azure-devops

Use a scripting language (e.g. Python) between export and import. 
- Export all IDs and Jira ranks from the ticket files.
(The ticket KA-666 is prioritised higher than KA-667 in Jira !!)

JiraID | Jira Rank
------------ | -------------
KA-667 | 1aaabbb3
KA-666 | 1aaabbb2

- Sort all IDs according to their Jira rank.

JiraID | Jira Rank
------------ | -------------
KA-666 | 1aaabbb2
KA-667 | 1aaabbb3

- Assign a number to the Ids (DevOps StackRank).
(Like: 1750000000 +(index*666) )

index | JiraID | Jira Rank | DevOps StackRank
------------ | ------------ | ------------- | -------------
1 | KA-666 | 1aaabbb2 | 1750000666
2 | KA-667 | 1aaabbb3 | 1750001332

- Replace the Jira strings with the new StackRank numbers in all ticket files.

Example for the KA-666.json file:
From:
`
{
          "ReferenceName": "Microsoft.VSTS.Common.StackRank",
          "Value": "1aaabbb2"
        }
`
To:
`
{
          "ReferenceName": "Microsoft.VSTS.Common.StackRank",
          "Value": 1750000666
        }
`

**Comment by anfisrz** [comment]
Is there a phyton scrip available for doing this? (I do not know phyton...)
