### ISSUE TITLE
Unable to map Fix Version from JIRA to Azure DevOps (on Prem)

### ISSUE THREAD

**Issue by abarua4** [solidify/jira-azuredevops-migrator#370]
While migrating fix version from JIRA to ADO, we need to map text from "Fix Version" of JIRA to Date field in ADO using mapping set in configuration.
But the output json files does not contain transformed Fix version.

Using below snippet for mapping -
![image](https://user-images.githubusercontent.com/31831440/121766375-3eb48080-cb49-11eb-88e3-be6bef714736.png)

For example -
Fix version in JIRA 
![image](https://user-images.githubusercontent.com/31831440/121766177-137d6180-cb48-11eb-8362-4634975b7295.png)

Release Date of Fix version - 10 April 2021

Expected value in ADO
![image](https://user-images.githubusercontent.com/31831440/121766238-8be42280-cb48-11eb-89ec-0e764e3733b5.png)

AB#5181

**Comment by Alexander-Hjelm** [comment]
Hi! See the FAQ for how to map custom fields: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

// Alexander
