### ISSUE TITLE
If the multi select custom field in Jira has more than 2 values selected, the jira export returns value as ;;;

### ISSUE THREAD

**Issue by sungalyr** [solidify/jira-azuredevops-migrator#374]
**Describe the bug**
In Jira, i've a multiselect custom field and if the field selected with more than 2 values, the jira export results the value as ; ; ; instead the value1;value2;value3

Sample config-agile.json:
{
"source": "customfield_15625",
"target": "Custom.AccountableTeam",
"mapper": "MapArray"
}
Jira JSON data of that custom field
"customfield_15625": [
      {
        "self": "urlxxxxxxxqqq",
        "value": "QA",
        "id": "62616",
        "disabled": false
      },
      {
        "self": "urlxxxxxxxwww",
        "value": "SE",
        "id": "62617",
        "disabled": false
      },
      {
        "self": "urlxxxxxxxee",
        "value": "Development",
        "id": "62620",
        "disabled": false
      },
      {
        "self": "urlxxxxxxxrr",
        "value": "Analyst",
        "id": "62622",
        "disabled": false
      }
    ],
Exported JIRA reference:
4 values selected in the multiselect field. 
Actual:
{
  "ReferenceName": "Custom.AccountableTeam",
  "Value": ";;;"
},
Expected:
{
  "ReferenceName": "Custom.AccountableTeam",
  "Value": "QA;SE;Development;Analyst"
},

2 Values selected in multiselect:
Actual:
{
  "ReferenceName": "Custom.AccountableTeam",
  "Value": "QA;Development"
},
Expected:
{
  "ReferenceName": "Custom.AccountableTeam",
  "Value": "QA;Development"
},

Could you please check and fix the issue?

AB#5295

**Comment by rambaliga** [comment]
Hi @Alexander-Hjelm - can you please let me know if there was a fix for this issue? we are facing the same issue and unable to figure out a way to make it work.

**Comment by FokkoVeegens** [comment]
@sungalyr @rambaliga Can you check the list of fields in Jira using the REST API;
```
[your jira url]/rest/api/latest/field
```
Then search for the field (in the case of the op it's: customfield_15625). Example:
``` json
{
  "id": "customfield_15625",
  "name": "Accountable Team",
  "custom": "true",
  "clauseNames": [
    "cf[15625]",
    "accountableTeam"
  ]
}
```
Now look carefully; in the case above, there is a property called "clauseNames", that contains multiple field names. One is cf[15625] and the other one is "accountableTeam". Now use "accountableTeam" (replace accountableTeam with the value you found in your output of the field list) instead of customfield_15625 in your config-agile.json file. In my case, this solved the issue.

**Comment by FokkoVeegens** [comment]
@Alexander-Hjelm can you consider to reopen this? I ran into the same issue again and my previous fix didn't work. I have a fix though; in https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraItem.cs you would need to add a `using System.Text.RegularExpressions` at the top. Furthermore, you'll need to change this line: https://github.com/solidify/jira-azuredevops-migrator/blob/44c9bb821d4ab7f6c556723c4bc8b91722346999/src/WorkItemMigrator/JiraExport/JiraItem.cs#L429 in: 
``` C#
if (Regex.Match((string)value, "^[;]+$").Success || (string)value == "")
```
Hope you can change this.

**Comment by Alexander-Hjelm** [comment]
@FokkoVeegens , thanks for spotting. I will apply this fix next week :)

**Comment by csaket** [comment]
@Alexander-Hjelm I was locally doing this:

`if (((string)value).All(c => c == ';') || (string)value == "")`

Is the fix the better way to handle this?
