### ISSUE TITLE
AzDO Rate Limiting Handling

### ISSUE THREAD

**Issue by rheidt** [solidify/jira-azuredevops-migrator#377]
Azure DevOps being a SAAS, rate limiting applies and for large amounts of work items (the reason a tool like this is handy :P) it will impact the ability of the tool to get all the way through the import step.

How to properly handle through AzDO response headers:
- https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops
- Responses give a nice way to adjust throttling in API workflow, the hard part is the M$ TFS libs encompass handling of responses.

Work Arounds and thoughts
- Will add artificial throttling to my code when processing new items. (sleep waits)

AB#5328

**Comment by Alexander-Hjelm** [comment]
This is above my knowledge, but perhaps @madkoo or @MOlausson can look into it?

**Comment by csaket** [comment]
I got around this by introducing a sleep between each item imported

https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/WorkItemImport/ImportCommandLine.cs#L150

**Comment by Alexander-Hjelm** [comment]
To do: add an option to induce a sleep() to artificially throttle the application. This should be controlled from the configuration.
