### ISSUE TITLE
Child items that were created before the parent, has "not yet created" error.

### ISSUE THREAD

**Issue by junejaalok** [solidify/jira-azuredevops-migrator#379]
We are encountering the same issue as in https://github.com/solidify/jira-azuredevops-migrator/issues/163#issuecomment-600650846

I am wondering if there is some solution to it that someone has found. 

BR

AB#5351

**Comment by madkoo** [comment]
@junejaalok you could import first the parent items, keep the journal file that is generated and then import the rest of the items as a workaround.

The issue will be received if you don't have a proper mapping set to get the child items with the parent link.  This can be logged either as a warning or an error depending on your configuration. If it's a warning then this can be fine as long as the parent/child has a link to the child/parent  then it will be connected on the AzureDevops side.

**Comment by junejaalok** [comment]
@madkoo Do you have some example showing mapping set to get the child items. I would like to compare to what I have it.
@yogi001, might be this be any help for you.

**Comment by madkoo** [comment]
It is easier if you share your mapping file. I can then provide tips what to change etc.

**Comment by yogi001** [comment]
@madkoo : Thanks for your quick reply! 
See below is the example of @junejaalok file:
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Gantt End to Start",
        "target": "System.LinkTypes.Dependency-Forward"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      {
        "source": "Blocks",
        "target": "System.LinkTypes.Dependency-Forward"
      }
    ]

**Comment by madkoo** [comment]
@junejaalok 
@yogi001 

I would add this one as well :
 `
  {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
`

Duplicate I would change to 
`
  {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Reverse"
      }, 
`
