### ISSUE TITLE
Sample of CMMI process template

### ISSUE THREAD

**Issue by carun** [solidify/jira-azuredevops-migrator#384]
At the moment, the samples are available for Agile, Scrum and Basic process templates.

I would like to have a sample to migrate Agile Jira project to CMMI ADO process.

AB#5570

**Comment by IbrahimUmar** [comment]
Any answer or feedback on this question? 

I am also looking for the way to migrate to other process templates like , 

CMMI , Agile ....
It always asking for mapping pf Story to Product Backlog items , which i dont want. 

Any idea?
