### ISSUE TITLE
Migration to Other Process Templats in Azure DevOps

### ISSUE THREAD

**Issue by IbrahimUmar** [solidify/jira-azuredevops-migrator#385]
I want to migrate to some other proces template in azure devops like ,

**Agile , CMMI or some custom ones. Any possibillity?**

**Comment by IbrahimUmar** [comment]
I have fixed the above error. 

There is another error when i try to import Jira Items to Azure DevOps Server 

**TF31002: Unable to connect to this Azure DevOps Server:** https://Mydomain/tfs/CollectionName/tfsmigration

I already created PAT with full rights at Collection Level.

**Comment by MOlausson** [comment]
Yes, it's "just" mapping. Take a look at https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md for reference and https://github.com/solidify/jira-azuredevops-migrator/tree/master/docs/Samples for examples.

**Comment by IbrahimUmar** [comment]
Thanks for your feedback. 
Why Jira considered STORY as FEATURE? because in agile template of Azure DevOps , we have "User stories" and we dont think this is right to map STORY to FEATURE. It should be STORY as USER STORY.

How can i change this mapping accoridng to right template?

Why do you considered this mapping in such way. Kindly share your feedback?
Thanks and Regards

**Comment by tung-nt-niteco** [comment]
@IbrahimUmar I think it is just a matter of config. In the sample config, it actually maps Story to Product Backlog Item in scrum methodology: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/Samples/config-scrum.json
In my practical case, I also map Story to User Story in Agile methodology, different with the given sample (https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/Samples/config-agile.json)

**Comment by IbrahimUmar** [comment]
I want to use AGILE TEMPLATE of Azure DevOps.

In this scenario , STORY in Jira should be translated in User Story in Azure DevOps. is this possible? Because i can't see any config file which doing that.

This is my question.

Target: target is to move Items types from Jira to Azure DevOps in same way. No alternative.

STORY = USER STORY
TASK = TASK
EPIC = EPIC
FEATURE = FEATURE
this is the ultimate goal.

**Comment by tung-nt-niteco** [comment]
@IbrahimUmar And I already answered you, it is possible, just change the "target" value in the config and start experiencing :)
