### ISSUE TITLE
System.InvalidOperationException: Response was not recognized as JSON.

### ISSUE THREAD

**Issue by gevorkca** [solidify/jira-azuredevops-migrator#394]
**Describe the bug**
When I run the command line to export Jira tickets I'm getting an error Response was not recognized as JSON. I trimmed down my request to only 1 bug thinking maybe it is the content of the issue that is causing the problem but that was not the case.

AB#5726

**Comment by Alexander-Hjelm** [comment]
Hi! Please share the log and config file you're using

// Alexander

**Comment by Alexander-Hjelm** [comment]
@gevorkca  Is this still an issue? :)

**Comment by frjon92** [comment]
Hi,

Sorry for my late reply! No there is no issue any more. you can mark this as resolved.

Kind regards,
Fredrik
