### ISSUE TITLE
Jira Test Case Migration using an API call instead of a JQL query

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#396]
Hi,

Is it possible to use an API call such as https://{host and port}/jira/rest/atm/1.0/testcase/search?query=projectKey = "TM"&maxResults=400 in place of the JQL query as per the config.json file?

![image](https://user-images.githubusercontent.com/92213401/136658316-8c7740b1-93f8-40eb-8644-846f5061af3d.png)

Thanks

Chris

AB#5742

**Comment by Alexander-Hjelm** [comment]
Hi Chris!

No, unfortunately not, and we will not be implementing this feature.

You can remediate this by going into the Issues tab of your JIRA project, creating the query there and pasting it into your config file.

// Alexander
