### ISSUE TITLE
Export of Jira Server attachments not working for attachments with spaces in their name. 

### ISSUE THREAD

**Issue by FacePath21** [solidify/jira-azuredevops-migrator#397]
When we're running this tool, a large portion of our attachments are being truncated into 2kb files that cannot be opened. 

I've checked all of our Jira logs and cannot find anything obvious. The logs on the exporter just say the following:

[D][17:16:33]    Mapping revision 1.
[D][17:16:33]    Downloading attachment info for attachment 'XXXX'.
[D][17:16:33]    Downloaded attachment '<Name of attachment>.docx'

Upon further inspection, i've noticed that the export is failing on attachments with spaces in their names. Sure enough, when I open one of the broken docx files with Notepad++, the contents are as follows:

  404 - File or directory not found.
  The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

Is there any way to change the exporter to support file names which include spaces? 

Many thanks in advance for your time.

**Comment by Alexander-Hjelm** [comment]
Hi!

Thank you noticing this bug. We will verify it on our end and implement a fix in an upcoming release.

Unfortunately there is no quick solution. Until further notice, you can rename all of your attachments in JIRA prior to exporting them, and rename them back in azure devops. If there are too many issues to go through manually, you can also implement an API solution to do a bulk rename. Tag the faulty issues and filter on the tag when renaming your issues back in AzDo.

// Alexander

**Comment by tung-nt-niteco** [comment]
Not sure if a fix I have done is related but I think it would be helpful:
https://github.com/tung-nt-niteco/jira-azuredevops-migrator/commit/95d9d5c8d3041239bf162e81bc74846884a0bf27

**Comment by Alexander-Hjelm** [comment]
URL encoding the file name should do the trick yes. Please open a pull request if it's possible for you, and I will notify the dev team to look at it :) @tung-nt-niteco

**Comment by tung-nt-niteco** [comment]
Thanks @Alexander-Hjelm it has been sometime so I can't remember all lines of code that I wrote, and also in fact someone already had a pull request here although Kookabura and I made a slightly improvement: https://github.com/solidify/jira-azuredevops-migrator/pull/327

Some other discussions:
https://github.com/solidify/jira-azuredevops-migrator/issues/267
https://github.com/solidify/jira-azuredevops-migrator/issues/225
https://github.com/solidify/jira-azuredevops-migrator/issues/226
https://github.com/solidify/jira-azuredevops-migrator/issues/200

**Comment by Alexander-Hjelm** [comment]
Perfect! :)

**Comment by Alexander-Hjelm** [comment]
Fixed by: https://github.com/solidify/jira-azuredevops-migrator/pull/489
