### ISSUE TITLE
Jira Portfolio issue links migrate to ADO

### ISSUE THREAD

**Issue by lgalardi1965** [solidify/jira-azuredevops-migrator#398]
**Is your feature request related to a problem? Please describe.**
I am trying to migrate **Jira Portfolio issue links** to ADO.  The issues migrate but the links do not.  Is Jira Portfolio with the "Parent Link" field supported?

**Describe the solution you'd like**
I would like the parent link field in jira portfolio to be supported in the migration from Jira to ADO

**Describe alternatives you've considered**
I have considered and tried various configurations in the config-bt file, to no avail

**Additional context**
Primarily I would like to see if it is possible to preserve the parent link between jira portfolio issues when migrated to ADO

AB#5791

**Comment by Alexander-Hjelm** [comment]
Hi! Have you tried using the IncludeParents flag as described here? https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#download-options

// Alexander

**Comment by GaryRogers** [comment]
I think so, but the dual exports worked for us. We can probably close this Issue.

**Comment by Alexander-Hjelm** [comment]
Ok! Closing this issue for now. Let us know if you require additional support :)
