### ISSUE TITLE
Migrating Users:

### ISSUE THREAD

**Issue by IbrahimUmar** [solidify/jira-azuredevops-migrator#404]
Hi ,

I am migrating the Jira work items to Azure DevOps Cloud Services. Jira Export has done for 15k Work items perfectly fine. When i do import , There are two Challenges.

1. I created a token with FULL ACCESS in azure devops and on import , it throws en error. tf401289: the current user does not have permissions to create tags.  User in migration has VS Subscription and Project Admin. Then why this error is happening?
2. I am trying to Migrate the Users from Jira to Azure DevOps Cloud. Jira is also on Cloud. Users are on Company domain and private user email addresses. 
3. Am i missing the format of the Users mapping file?
![image](https://user-images.githubusercontent.com/41017019/143478841-567a0f3d-782c-4caa-a0c1-4332b8572ecf.png)

Kindlly help me to sort out these two Questions.

AB#5868

**Comment by IbrahimUmar** [comment]
Is there any , or ; required between two email addresses?  Am i missing anything? Thanks

**Comment by Alexander-Hjelm** [comment]
Hi!

Make sure that the user to whom the PAT belongs has the "Create Tag Definition" permission at the Team Project level, either directly or via a security group.

Verify that the user mapping adheres to the following format:
 ```
a@test.com=a@test.com
b@test.com=b@test.com
c@test.com=c_tst@test.com
*=a@test.com
```

If all else fails, provide us the log for one of the failing work items!

// Alexander

**Comment by Alexander-Hjelm** [comment]
@IbrahimUmar  Is this still an issue? :)

**Comment by Alexander-Hjelm** [comment]
Closing due to inactviity. Feel free to reopen this issue if the problem persists.

**Comment by IbrahimUmar** [comment]
Could not find user 'username@domain.com' identity in user map. Using original identity 'username@domain.com'.
Format of file is like below.

a@test.com=a@test.com
b@test.com=b@test.com
c@test.com=c_tst@test.com
*=a@test.com
