### ISSUE TITLE
I am not able to get parent/child  link for epic and feature when using issue type link .But if i am using Epic link it worked fine .

### ISSUE THREAD

**Issue by punyautkalika** [solidify/jira-azuredevops-migrator#405]
I have issue linked in jira but that has not transferred to azure board .
My feature is part of epic and story is part of feature but i could not see the links between epic/feature /pbi .
Please find my config file  and snapshot from jira 

![image](https://user-images.githubusercontent.com/40838628/145011474-d4655352-7cfb-47af-afa7-c3b108412ca9.png)

{
  "source-project": "TEST",
  "target-project": "TEST",
  "query": "project = 'TEST' AND id = OMONE-TEST",
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "using-jira-cloud": false,
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Debug",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Jira Migration Test",
  "base-iteration-path": "migrated/Jira Migration Test",
  "ignore-failed-links": true,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map":{
    "type": [
    
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Theme",
        "target": "Epic"
      },
      {
        "source": "New Feature",
        "target": "Feature"
      },
      {
        "source": "Slice",
        "target": "Epic"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Product Backlog Item"
      },
      {
        "source": "Spike",
        "target": "Product Backlog Item"
      },
      {
        "source": "OPEN",
        "target": "Product Backlog Item"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Bug-task",
        "target": "Task"
      },
      {
        "source": "Task",
        "target": "Task"
      },
      {
        "source": "Kanban Item",
        "target": "Product Backlog Item"
      },
      {
        "source": "Impediment",
        "target": "Impediment"
      },
      {
        "source": "Improvement",
        "target": "Product Backlog Item"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },
      {
        "source": "General Task",
        "target": "Task"
      },
      {
        "source": "User story",
        "target": "Product Backlog Item"
      },  
      {
        "source": "Technical Task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "None",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {   
              "source": "Approved",
              "target": "To Do"
            },           
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "Open",
              "target": "To Do"
            },
            {
              "source": "Closed",
              "target": "Done"
            },
            {
              "source": "On Hold/Blocked",
              "target": "To Do"
            },
            {
              "source": "ready for verification",
              "target": "To Do"
            },
            {
              "source": "Ready for sprint",
              "target": "To Do"
            },
            {
              "source": "verification",
              "target": "To Do"
            },
            {
              "source": "verifying",
              "target": "To Do"
            },
            {
              "source": "Analyzing",
              "target": "To Do"
            },
            {
              "source": "analyzing for business case",
              "target": "To Do"
            },
            {
              "source": "Prioritized",
              "target": "To Do"
            },
            {
              "source": "Reopened",
              "target": "To Do"
            }, 
            {
              "source": "Resolved",
              "target": "Done"
            },    
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Bug,Product Backlog Item",
        "mapping": {
          "values": [
            {
              "source": "Accepting",
              "target": "Committed"
            },
            {
              "source": "Analyzing",
              "target": "New"
            },
            {
              "source": "analyzing for business case",
              "target": "New"
            },
            {
              "source": "Closed",
              "target": "Done"
            },
            {
              "source": "high level impacting",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "Committed"
            },
            {
              "source": "On Hold/Blocked",
              "target": "Approved"
            },
            {
              "source": "Open",
              "target": "New"
            },
            {
              "source": "prepared for analysis",
              "target": "New"
            },
            {
              "source": "Prioritized",
              "target": "New"
            },
            {
              "source": "Prepared for high level analysis",
              "target": "New"
            },
            {
              "source": "ready for acceptance",
              "target": "Committed"
            },
            {
              "source": "ready for implementation",
              "target": "Committed"
            },
            {
              "source": "ready for poker",
              "target": "Approved"
            },
            {
              "source": "Ready for sprint",
              "target": "Approved"
            },
            {
              "source": "Resolved",
              "target": "Done"
            },
            {
              "source": "Reopened",
              "target": "New"
            }, 
            {
              "source": "ready for verification",
              "target": "Committed"
            },
            {
              "source": "Reviewing",
              "target": "Approved"
            },
            {
              "source": "verifying",
              "target": "Committed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Epic,Feature",
        "mapping": {
          "values": [
            {
              "source": "Accepting",
              "target": "In Progress"
            },
            {
              "source": "Analyzing",
              "target": "New"
            },
            {
              "source": "analyzing for business case",
              "target": "New"
            },
            {
              "source": "Closed",
              "target": "Done"
            },
            {
              "source": "high level impacting",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            },
            {
              "source": "On Hold/Blocked",
              "target": "New"
            },
            {
              "source": "Open",
              "target": "New"
            },
            {
              "source": "prepared for analysis",
              "target": "New"
            },
            {
              "source": "Prioritized",
              "target": "New"
            },
            {
              "source": "Prepared for high level analysis",
              "target": "New"
            },
            {
              "source": "ready for acceptance",
              "target": "In Progress"
            },
            {
              "source": "ready for implementation",
              "target": "In Progress"
            },
            {
              "source": "Ready for sprint",
              "target": "New"
            },
            {
              "source": "ready for verification",
              "target": "In Progress"
            },
            {
              "source": "Reviewing",
              "target": "New"
            },
            {
              "source": "verifying",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}

AB#5961

**Comment by punyautkalika** [comment]
@Alexander-Hjelm  Thanks for your response. 


I have added parent child link in my jira where feature is part of Epic and story is part of Feature . But when i am migrating those work items i am having below in my logs :

 Link with description 'This issue is part of INNOAUTHEN-2' is either not found or this issue (INNOAUTHEN-7) is not inward issue. 

But INNOAUTHEN-2 is already downloaded as i am exporting  as per the Rank . 
[D][13:19:33]    Downloaded issue: INNOAUTHEN-2 changelog.
[D][13:19:33]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-5'.
[D][13:19:34]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-6'.
[D][13:19:34]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-7'.
[D][13:19:34]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-8'.

**Comment by punyautkalika** [comment]
As per you comment i have modified my config and used the below but still he link didn't created
{
"source": "Split From",
"target": "System.LinkTypes.Related"
},
{
"source": "Split To",
"target": "System.LinkTypes.Related"
},

**Comment by Alexander-Hjelm** [comment]
Is this issue still separate from #406 ?

**Comment by Alexander-Hjelm** [comment]
Try setting "ignore-failed-links": false and see if there are any additional errors

**Comment by Alexander-Hjelm** [comment]
Continued in #406
