### ISSUE TITLE
Links are not created between parent/child

### ISSUE THREAD

**Issue by punyautkalika** [solidify/jira-azuredevops-migrator#406]
Link has not created between the feature and story . I am posting my config file and the log :

"link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
        },
        {
        "source": "parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
        },
        {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
        },
        {
          "source": "Issue split",
          "target": "System.LinkTypes.Related"
          },
        {
            "source": "Blocks",
            "target": "System.LinkTypes.Dependency"
        },
        {
            "source": "child",
            "target": "System.LinkTypes.Hierarchy-Forward"
        },
        {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
        }

Log:
[D][19:15:55]    Downloaded issue: INNOAUTHEN-2 changelog.
[D][19:15:55]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-5'.
[D][19:15:55]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-6'.
[D][19:15:55]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-7'.
[D][19:15:55]    Undone link 'Added [parent/child] INNOAUTHEN-2->INNOAUTHEN-8'.

Jira Snapshot 
![image](https://user-images.githubusercontent.com/40838628/145085580-bfaac570-77f8-419e-9ef1-7c042fcabcbd.png)

Jira API response for issue link 

![image](https://user-images.githubusercontent.com/40838628/145085904-e00099a0-54cc-492e-974d-f860d90c4333.png)

As per the jira api response the type of link name is parent/child and it has outward issue linked with feature . 
But when i export from jira i didnt get any links 
  "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
Please help me to understand if i am doing anything wrong in my config or missing any kind of mapping .

AB#5965

**Comment by punyautkalika** [comment]
@madkoo @Alexander-Hjelm  can you please help

**Comment by Alexander-Hjelm** [comment]
I have no idea, but shouldn't it be Parent with a big P?
Otherwise set "ignore-failed-links": false, and see if there are any more detailed errors

**Comment by punyautkalika** [comment]
Hello @Alexander-Hjelm  I have tried with ""ignore-failed-links": false," what i have observed if there is no epic link then we are not getting any child parent relation .

**Comment by Alexander-Hjelm** [comment]
Ok! How did you find that out? Provide us with any errors/warnings from the log. If there are no errors, provide us the log for that issue.

my knowledge ends here, so @madkoo or @MOlausson will have to take over

**Comment by punyautkalika** [comment]
@Alexander-Hjelm  If i have one feature and which have 3 story  linked in Jira . After migrating from  jira the links are missing in azdo .
INNOAUTHEN-7- Story 
INNOAUTHEN-2- Feature 
The link in jira type is parent/child as i have fetched the link details from jira api as shown in above image.
**Feature and pbi in jira** 
![image](https://user-images.githubusercontent.com/40838628/146754779-80742e66-5be5-473e-ae4c-c5cfebd13147.png)
[D][11:36:02]    Exported as type 'Product Backlog Item'.
[I][11:36:02] Processing 2/8 - 'INNOAUTHEN-7'.
[D][11:36:03]    Downloaded item.
[D][11:36:03]    Rendered field customfield_15400 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_10500 contains unparsable type Null, using text
[D][11:36:03]    Rendered field priority contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_13603 contains unparsable type Null, using text
[D][11:36:03]    Rendered field issuelinks contains unparsable type Null, using text
[D][11:36:03]    Rendered field status contains unparsable type Null, using text
[D][11:36:03]    Rendered field creator contains unparsable type Null, using text
[D][11:36:03]    Rendered field reporter contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_11801 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_11800 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_11000 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_13301 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_14902 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_14900 contains unparsable type Null, using text
[D][11:36:03]    Rendered field workratio contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_13800 contains unparsable type Null, using text
[D][11:36:03]    Rendered field summary contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_10001 contains unparsable type Null, using text
[D][11:36:03]    Rendered field customfield_10400 contains unparsable type Null, using text
[D][11:36:03]    Downloaded issue: INNOAUTHEN-7 changelog.
**[D][11:36:03]    Link with description 'This issue is part of INNOAUTHEN-2' is either not found or this issue (INNOAUTHEN-7) is not inward issue.**
[D][11:36:04]    Created 2 history revisions.
[D][11:36:04]    Mapping revision 0.
[D][11:36:04]    Mapped value '[INNOAUTHEN-7] conversie' to field 'System.Title'.
[D][11:36:04]    Mapped value '4' to field 'Microsoft.VSTS.Common.Priority'.
[D][11:36:04]    Mapped value '' to field 'System.IterationPath'.
[D][11:36:04]    Mapped value 'New' to field 'System.State'.
[D][11:36:04]    Mapping revision 1.
[D][11:36:04]    Exported as type 'Product Backlog Item'.

**Comment by KumarNSR** [comment]
@punyautkalika ,

 Am facing same type of issue , if any parent item has child links i.e in subtask - approvals and taks then only tasks are exported in jira log 

Same issue with "relates to" links as well

Can you pls help on this issue
