### ISSUE TITLE
Unable to migrate resolved/closed date (to a custom field in ADO)

### ISSUE THREAD

**Issue by monishcm-msft** [solidify/jira-azuredevops-migrator#408]
**The bug**
Trying to run a  migration between Jira and ADO for 1000s of items.
From issue #346 and #117 it is understood that we cannot migrate resolved date field from Jira to closed date field in ADO. Hence, we are trying to migrate it to a custom field and that does not work either.

**Configuration file mapping**
Config file mapping
      `{`
        `"source": "resolutiondate",`
        `"source-type": "id",`
        `"target": "Custom.Closed_Date",`
      `}`,

**Expected behavior**
resolution date is migrated to the custom field.

**Error**
`[E][10:31:07] Error mapping field 'Custom.Closed_Date' on item 'abc-1234'.`
`[System.InvalidCastException] System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.String'.`
`   at JiraExport.JiraMapper.<>c__DisplayClass18_01.<IfChanged>b__0(JiraRevision r)`
`   at JiraExport.JiraMapper.MapFields(JiraRevision r): `
`   at JiraExport.JiraMapper.<>c__DisplayClass18_01.<IfChanged>b__0(JiraRevision r)`
`   at JiraExport.JiraMapper.MapFields(JiraRevision r)`

**Running on ADO build server**
 - OS: Windows 2019

**Trials**
1. Custom_Date is a DateTime field in ADO
2. The same error is displayed even if Custom_Date is modified to a text field.
3. Tried resolutiondate and resolved field names
4. tried source-type = name and id, both did not work.

AB#5989

**Comment by Alexander-Hjelm** [comment]
Hi Monish.

Have you tried migrating to a custom field of type Date/Time instead of string?

![image](https://user-images.githubusercontent.com/10683896/147084439-055bfb16-55c8-4a43-9af1-34d24329b7bc.png)

**Comment by monishcm-msft** [comment]
@Alexander-Hjelm - Yes, the custom field I am using - closed_date is a Date/Time field.

![image](https://user-images.githubusercontent.com/84397640/147107241-c4da7516-a015-43bc-927d-7b9a0260a43e.png)

_Note: The internal name of the field is closed_date._

Interestingly I have a custom date field in Jira that migrates properly to yet another custom field in ADO (both Date/Time). I am not sure why there is an error for resolved date.

**Comment by monishcm-msft** [comment]
As per https://github.com/solidify/jira-azuredevops-migrator/issues/346#issuecomment-804066181 i used `id` as the source-type also used using `resolved` instead of `resolutiondate`. 

`      {`
`"source": "resolved",`
`        "source-type": "id",`
`        "target": "Custom.Closed_Date"`
`      },`

Now I do not get any errors, but still the values are not migrated. 😞

**Comment by Alexander-Hjelm** [comment]
I would say start by trying to map another field to Custom.Closed_Date, to verify that your azure devops custom field is set up properly.

**Comment by tung-nt-niteco** [comment]
As I looked at the code, it seems that you would need to add this to the config in addition to source and target:
"type": "datetime"
For example:
{ "source": "resolutiondate", "target": "Microsoft.VSTS.CodeReview.AcceptedDate", "type": "datetime" }

More advance, in JiraMapper.cs InitializeFieldMappings() function, you can also do:
if (item.SourceType == "id" && item.Source == "resolutiondate") item.Type = "datetime";
but it is not recommended I guess ^^

**Comment by rambaliga** [comment]
Hi @Alexander-Hjelm , @tung-nt-niteco 

I am trying to migrate a custom date field from jira to custom date/time field in AzDO. In the export JSON, the value for this date field is as below

<img width="264" alt="image" src="https://user-images.githubusercontent.com/45536124/161800434-4040f76d-d949-43ac-820b-120943a85ace.png">

However, when this field is migrated , the date and time value gets imported as below.

<img width="153" alt="image" src="https://user-images.githubusercontent.com/45536124/161800676-146aaaf1-c3c0-4426-af6f-f8db9941f9dd.png">

what can be done in this case to fix this? Please suggest

**Comment by tung-nt-niteco** [comment]
@rambaliga It's the time zone difference between Azure DevOps and Jira. Make them the same before importing, then it will be correct.

**Comment by rambaliga** [comment]
Hi @tung-nt-niteco ,

Both AZDO and JIRA server have the same time zone. 
AzDO:
![image](https://user-images.githubusercontent.com/45536124/161885274-4861ceb0-d4a9-41d4-a29d-48f728daad90.png)
JIRA:
![image](https://user-images.githubusercontent.com/45536124/161885294-e5d5ad47-595e-4066-9370-7f372e81f667.png)

Values for the standard date fields are reflecting correctly, its only the custom fields (NW Due Date, InQADate) I am facing the issue with:

![image](https://user-images.githubusercontent.com/45536124/161885189-e4271f53-5f01-4265-905d-3a82f804daf3.png)

![image](https://user-images.githubusercontent.com/45536124/161885158-f6308ba2-2ea1-477d-83be-303110950a06.png)

**Comment by tung-nt-niteco** [comment]
@rambaliga I guess you should check the personal settings of Azure DevOps for the time zone as well.

**Comment by rambaliga** [comment]
@tung-nt-niteco - like I mentioned in my previous reply, time settings in my Azure Devops profile is also same as JIRA. Not sure why I am still seeing this difference.

**Comment by tung-nt-niteco** [comment]
@rambaliga There are 2 places to set the time zone in Azure DevOps: Organization Settings, Personal Settings.
If they all look good, then I don't know :)  Perhaps Alexander or the developers of this tool knows why.

**Comment by Alexander-Hjelm** [comment]
@rambaliga please create a new issue, this issue is monishcm-msft’s support errand
