### ISSUE TITLE
Can i Map a jira external link with hyperlink in azure devops using solidfy 

### ISSUE THREAD

**Issue by punyautkalika** [solidify/jira-azuredevops-migrator#409]
I have one external link field in jira and i want to migrate that links to Azure board . Can i migrate as Hyperlink .Is it supported by solidify .

{
        "source": "customfield_10003",
        "target": "Hyperlink"
        }, 

AB#5994

**Comment by Alexander-Hjelm** [comment]
If you map the link as a string value ("https://example.com/..."), the full text will be copied over and converted into a hyperlink on the azure devops side.

I don't think we support transformation of field values, so if you need to transform your hyperlinks you may need to script this solution yourself

**Comment by punyautkalika** [comment]
@Alexander-Hjelm  Thanks a lot for the response , I am trying to migrate the a custom link field  from jira to the Target link which is hyperlink 
![image](https://user-images.githubusercontent.com/40838628/148114871-4e3caea1-80fc-4251-ada1-99bc1f89555f.png)
![image](https://user-images.githubusercontent.com/40838628/148115278-6252465c-993b-4aab-a6fa-c5674bab37de.png)
![image](https://user-images.githubusercontent.com/40838628/148115424-c40a8716-3d0c-4e0f-abd1-bef032a05a2f.png)

But unfortunately this is not migrating .

**Comment by Alexander-Hjelm** [comment]
It might be that this is not supported. I would recommend migrating the hyperlink to a custom field, and then writing a script yourself that copies over the value of that custom field to a new hyperlink, via the workitem update API!

**Comment by Alexander-Hjelm** [comment]
Any update on this? @punyautkalika

**Comment by punyautkalika** [comment]
@Alexander-Hjelm  i have resolved .Thank you :)

**Comment by Alexander-Hjelm** [comment]
Great that it worked out! :) If you have the opportunity, we would greatly appreciate it if you could describe your solution in a few lines. Otherwise happy hacking!
