### ISSUE TITLE
The value 'SPV' does not exist for the field 'project'."],"warningMessages"

### ISSUE THREAD

**Issue by tg1991** [solidify/jira-azuredevops-migrator#411]
**Describe the bug**
I am admin of my project and trying to run the tool for getting everything from Jira, it is strange as I ran it once and it connected with no issues but without changing anything I can no longer get it to work without the following errors. 
As can see from the shot below the details of U P and rest of the settings appear to be what they should be.

![image](https://user-images.githubusercontent.com/36793219/148354823-bfb93fef-69a0-4f9a-8379-61f564190ac9.png)

Here is my config 
![image](https://user-images.githubusercontent.com/36793219/148355086-a1bbe7aa-ac3f-4f20-a180-480bc41e608e.png)

as can see the project is called SPV and I also have full admin rights for the project.

Any help would be much appreciated.

all the best
tom

**Expected behavior**
For it to run correct and not say project SPV can not be found

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser chrome
 - Version tool v 2.3.117

AB#5996

**Comment by tg1991** [comment]
Forgot to add my file is in the root as it asks
![image](https://user-images.githubusercontent.com/36793219/148355962-b95f3797-fc16-4ea2-8ba2-59849c7b7ee6.png)

**Comment by tg1991** [comment]
If wat a text version here is the cmd module after ran, including what is being passed in 

C:\Users\*******\Downloads\jira-azuredevops-migrator-2.3.117>jira-export -u ******@******.co.uk -p API KEY --url https://*****dev.atlassian.net --config config-scrum.json --force
Jira Exporter v2.3.117
Copyright (c) Solidify
[I][08:54:03] Connecting to Jira...
[I][08:54:03] Retrieving Jira fields...
[I][08:54:03] Retrieving Jira link types...
[E][08:54:04] Failed to get item count using query: 'project = SPV ORDER BY Rank ASC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SPV' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SPV' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
[I][08:54:04] Export started. Exporting 0 items.
[W][08:54:04] Epic link field missing for config field 'Epic Link'.
[W][08:54:04] Sprint link field missing for config field 'Sprint'.
[W][08:54:04] User mapping file 'C:\Temp\JiraExport\users.txt' not found, ignoring mapping user identities.
[I][08:54:04] Initializing Jira field mapping...
[E][08:54:05] Failed to retrieve issues
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SPV' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__23.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SPV' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__23.MoveNext()
[I][08:54:05] Export complete. Exported 0 items (2 errors, 3 warnings) in 00:00:02.

**Comment by tg1991** [comment]
Full config file 

{
  "source-project": "SPV",
  "target-project": "Synergist Test",
  "query": "project = SPV ORDER BY Rank ASC",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Product Backlog Item"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "Product Backlog Item"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Bug,Product Backlog Item",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "Committed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Epic,Feature",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}

**Comment by Alexander-Hjelm** [comment]
Going over some previous migrations, I saw that we used quotes around the project name. Try something like this:
```
"query": "project = \"ANT\" ORDER BY created DESC",
```

**Comment by tg1991** [comment]
> Going over some previous migrations, I saw that we used quotes around the project name. Try something like this:
> 
> ```
> "query": "project = \"ANT\" ORDER BY created DESC",
> ```

Hey Thank you for the fast response, just tried this and had the same issue :( 
![image](https://user-images.githubusercontent.com/36793219/148358331-2dd2b6fc-097c-4ba5-a41c-0df7e09fa8ce.png)

**Comment by Alexander-Hjelm** [comment]
Ok! Here are some more things you should try:
- Verify that the porject key is indeed "SPV" in jira
- Verify your jira access token

What happens if you run the exact same query inside JIRA issues? Do you find any items=

**Comment by tg1991** [comment]
> Ok! Here are some more things you should try:
> 
> * Verify that the porject key is indeed "SPV" in jira
> * Verify your jira access token
> 
> What happens if you run the exact same query inside JIRA issues? Do you find any items?

from trying the above I get this, confirms the project name is SPV and that the search works in jira 
![image](https://user-images.githubusercontent.com/36793219/148360279-df1659c6-1db2-4270-acd1-a387d384a63b.png)

And below shows my API token is working as it shows it was last accessed 15min ago which is when I last ran the script 
![image](https://user-images.githubusercontent.com/36793219/148360376-4f7a0456-e3c1-4e73-bb2c-89bee0052979.png)

**Comment by Alexander-Hjelm** [comment]
So have ruled out the project setup and authentication, I'm wondering if the user you are trying to authenticate as maybe doesn't have access to the SPV project. Try the Permission helper as an admin account to verify that you actually have permission over the project:
https://confluence.atlassian.com/adminjiraserver/jira-admin-helper-938847791.html#JiraAdminHelper-PermissionHelper

FYI: This is not an issue with the migrator, so if we cannot help you here, you might have better luck with the atlassian support :)

**Comment by tg1991** [comment]
> So having ruled out the project setup and authentication, I'm wondering if the user you are trying to authenticate as maybe doesn't have access to the SPV project. Try the Permission helper as an admin account to verify that you actually have permission over the project: https://confluence.atlassian.com/adminjiraserver/jira-admin-helper-938847791.html#JiraAdminHelper-PermissionHelper
> 
> FYI: This is not an issue with the migrator, so if we cannot help you here, you might have better luck with the atlassian support :)

I have tried a lot of scenarios through this and they all show I have permission, are you sure there is nothing wrong in my settings etc? 

here is an image showing my admin rights etc are set up so dont think its an atlassian issue 
![image](https://user-images.githubusercontent.com/36793219/148363825-2b5cf9e2-5d4f-4d9b-807c-d163df1db095.png)

**Comment by tg1991** [comment]
> So having ruled out the project setup and authentication, I'm wondering if the user you are trying to authenticate as maybe doesn't have access to the SPV project. Try the Permission helper as an admin account to verify that you actually have permission over the project: https://confluence.atlassian.com/adminjiraserver/jira-admin-helper-938847791.html#JiraAdminHelper-PermissionHelper
> 
> FYI: This is not an issue with the migrator, so if we cannot help you here, you might have better luck with the atlassian support :)

I have got it to work, not sure why this worked, I changed log level to debug and removed this line completely "download-options": 7,
works perfect now, thank you so much for the help and looking into this

**Comment by Alexander-Hjelm** [comment]
The download-options field specifiec wether to download additional issues or not (such as parents, linked items, etc...) not caught by the query. See the reference here:
https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#download-options

It might have been that you had linked items outside you user's access area?

Regardless, glad that it worked out for you :)
