### ISSUE TITLE
Azure pipeline build failed

### ISSUE THREAD

**Issue by Ashok2781** [solidify/jira-azuredevops-migrator#428]
Hello, 

Good day to you all.

Im getting below error while trying to run the azure pipeline yaml file on Azure DevOps.

A task is missing. The pipeline references a task called 'richardfennellBM.BM-VSTS-Versioning-Task.Version-Assemblies-Task.VersionAssemblies'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2, job 'Job', step ''.)

A task is missing. The pipeline references a task called 'TfxInstaller'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 1, job 'Job', step ''.)

A task is missing. The pipeline references a task called 'PackageAzureDevOpsExtension'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2, job 'Job', step ''.)

AB#6143

**Comment by Alexander-Hjelm** [comment]
If you wish to build the jira migrator in an Azure Pipeline, you will need to install some additional tasks from the marketplace:
- https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks&ssr=false#overview

**Comment by Alexander-Hjelm** [comment]
Closing support ticket due to inactivity. Feel free to open the issue again if the issue persists :)
