### ISSUE TITLE
Value for custom date field isn't migrating correctly in AzDO

### ISSUE THREAD

**Issue by rambaliga** [solidify/jira-azuredevops-migrator#435]
While trying to migrate a custom date field from jira to custom date/time field in AzDO, values aren't migrating correctly.
In the export JSON, the value for this date field is as below:
![image](https://user-images.githubusercontent.com/45536124/161922724-c6070e8e-451b-4f92-8a37-e423671e0ac3.png)

However, when this field is migrated , the date and time value gets imported as below:
![image](https://user-images.githubusercontent.com/45536124/161922817-521d45a7-ecc9-42ac-b407-5fb7c95d6c9f.png)

The time zone settings in Azure organization and in Profile settings are same as in JIRA server. Values for standard date fields are migrated correctly on the UI. The difference is observed only for custom fields.

Kindly help.

**Comment by Alexander-Hjelm** [comment]
What does the mapping look like in the config file? And what is the type of the Custom.InQADate field?

**Comment by rambaliga** [comment]
Mapping done in config file is as below:
{
	"source": "customfield_12010",
        "target": "Custom.InQADate"
    },

The API call gives below values

{
   "expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
   "id":"317717",
   "self":"https://<site>/rest/api/latest/issue/317717",
   "key":"NWNA-13651",
   "fields":{
      "customfield_12010":"2020-07-06",
      "customfield_13220":null,
      "customfield_13102":null}

Custom.InQADate field type in AzDO is Date/Time.

**Comment by Alexander-Hjelm** [comment]
Not sure, but it sounds like the date format is wrong, Azure DevOps uses ISO 8601 UTC, with "YYYY-MM-DD" accepted, for example.

As per #408, try the following and see if any of them work:

- Try adding "type": "datetime" to your mapping
- Try adding "source-type": "id" to your mapping

**Comment by rambaliga** [comment]
@Alexander-Hjelm do you mean like this?

```
{
		"source": "customfield_12010",
		"source-type": "id",
                "target": "Custom.InQADate",
		"type": "datetime"
    }
```

With this the tool doesn't pick the value at all in the export json. 
Without "type": "datetime" the value is picked but still facing the same issue.

**Comment by tung-nt-niteco** [comment]
@rambaliga Not sure but I think source-type should be "name" in your case.

**Comment by Alexander-Hjelm** [comment]
Is the error systematic? Is the date always being offset by 21.5 hours as in your example? If so, then it's an indicator that it could still be due to the time zone settings in your TFS or Jira.

Does mapping the custom field to a String field in AzDO give better results? If not, what value gets stored on the AzDO side? Is it a ISO 8601 UTC-string or just YYYY-MM-DD?

**Comment by rambaliga** [comment]
Hi @Alexander-Hjelm , sorry I missed to update here- this was fixed by setting the time zone in Azure Devops same as that of JIRA. Although after changing the time zone settings it took quite a while for the changes to reflect correctly across projects.

**Comment by Alexander-Hjelm** [comment]
Ok, glad to hear that it worked :)
