### ISSUE TITLE
Sprint value not getting mapped

### ISSUE THREAD

**Issue by rambaliga** [solidify/jira-azuredevops-migrator#438]
Hi Team,

Need support on the below issue,
   ```
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WorkItemImport.Agent.EnsureClasification(String fullName, TreeStructureGroup structureGroup)
---> (Inner Exception #0) Microsoft.VisualStudio.Services.Common.VssServiceException: VS402371: Classification node name Hybris API Sprint 6 is already in use by a different child of parent classification node 254f284f-15f6-4639-9f8a-ac3f990a94fa. Choose a different name and try again.
```
The iteration **Hybris API Sprint 6** is already created when a work item was migrated. However it is giving error when a new work item with same sprint value is getting imported. This new work item should have been mapped to the existing iteration if my understanding is not wrong. Please advise.

Below is my config file ( I have added it as text file as I did not want to copy the content in the comment )

[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/8488243/config.txt)

**Comment by Alexander-Hjelm** [comment]
Looks like the sprint name is already in use somewhere else in the Iteration hierarchy? Could this be the problem? Try to delete or rename the already existing iteration and try again
