### ISSUE TITLE
Comments are assigned to whoever runs the import tool

### ISSUE THREAD

**Issue by emanuellimabr** [solidify/jira-azuredevops-migrator#443]
**Describe the bug**
When I run the import command all the imported comments in DevOps shows me as author or whoever runs the import tool. 
I am using Jira Cloud and mapping the users by email since when I tried to use JiraID I get the error "Could not find user identity in user map". I read the comments in this issue #194  but I could not solve my problem.

**Comment by emanuellimabr** [comment]
> Can you share your configuration and check it against the example configuration here? https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md
> 
> Spcifically for comments it should be this mapper:
> 
> ```lisp
> {
>   "source": "comment",
>   "target": "System.History",
>   "mapper":"MapRendered"
> },
> ```
> 
> @MOlausson , @madkoo , is this behavior expected?

Bellow is my configuration file, and yes, it is using the right mapper.
`{
  "source-project": "WFMKYNRPTS",
  "target-project": "CIO IT - WFM Reports",
  "query": "project = WFMKYNRPTS ORDER BY Rank ASC",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport-Hub-Reports\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      { 
        "source": "Child", 
        "target": "System.LinkTypes.Hierarchy-Forward" 
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "User Story"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "Task"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },
      {
        "source": "Change Request",
        "target": "Issue"
      },
      {
        "source": "Incident",
        "target": "Issue"
      },
      {
        "source": "Maintenance",
        "target": "Issue"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "Ready",
              "target": "Ready"
            },
            {
              "source": "Researching",
              "target": "Researching"
            },
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Awaiting Feedback",
              "target": "Awaiting Feedback"
            },
            {
              "source": "Blocked",
              "target": "Blocked"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Reviewing",
              "target": "Reviewing"
            },
            {
              "source": "Testing",
              "target": "Testing"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            },
            {
              "source": "Done",
              "target": "Closed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Bug,Epic,Feature,User Story",
        "mapping": {
          "values": [
            {
              "source": "Ready",
              "target": "Ready"
            },
            {
              "source": "Researching",
              "target": "Researching"
            },
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Awaiting Feedback",
              "target": "Awaiting Feedback"
            },
            {
              "source": "Blocked",
              "target": "Blocked"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Reviewing",
              "target": "Reviewing"
            },
            {
              "source": "Testing",
              "target": "Testing"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            },
            {
              "source": "Done",
              "target": "Resolved"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Issue",
        "mapping": {
          "values": [
            {
              "source": "Ready",
              "target": "Closed"
            },
            {
              "source": "Researching",
              "target": "Active"
            },
            {
              "source": "To Do",
              "target": "Active"
            },
            {
              "source": "Awaiting Feedback",
              "target": "Active"
            },
            {
              "source": "Blocked",
              "target": "Active"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Reviewing",
              "target": "Active"
            },
            {
              "source": "Testing",
              "target": "Active"
            },
            {
              "source": "Cancelled",
              "target": "Closed"
            },
            {
              "source": "Done",
              "target": "Closed"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}
`

**Comment by emanuellimabr** [comment]
> Which version of the jira migrator are you running? Latest?

Yes!

**Comment by tung-nt-niteco** [comment]
It seems that you got the same problem like mine here: https://github.com/solidify/jira-azuredevops-migrator/discussions/415
I only got the problem on 1 AzureDevOps org and I finished all the work a couple of months ago, so I did not dig in further to understand why.

**Comment by emanuellimabr** [comment]
> It seems that you got the same problem like mine here: #415 I only got the problem on 1 AzureDevOps org and I finished all the work a couple of months ago, so I did not dig in further to understand why.

So you are saying that it can be something related with the MS account?

**Comment by emanuellimabr** [comment]
Hey guys, I just notice that in the history tab the comments are assigned to the right author, however, in the "Details" tab under the "Discussion" section it shows me as the author. Any thoughts on that?

**Comment by tung-nt-niteco** [comment]
@emanuellimabr For your question, you can read the details in https://github.com/solidify/jira-azuredevops-migrator/discussions/415
It was not MS account in my case, it happened on a specific Azure DevOps org.

**Comment by RoyalWulf** [comment]
I have the same issue.  All comments are under my name and the date of the comment is the date I ran the import.

**Comment by RoyalWulf** [comment]
I have this in my configuration:
            {
                "source": "comment",
                "target": "System.History",
                "mapper": "MapRendered"
            },
in ADO the history looks better, has the right user making the comment, but the date is wrong, it is today
the comment can be seen in the Discussion section and has me as the user and today as date (both wrong)

**Comment by emanuellimabr** [comment]
> I have this in my configuration: { "source": "comment", "target": "System.History", "mapper": "MapRendered" }, in ADO the history looks better, has the right user making the comment, but the date is wrong, it is today the comment can be seen in the Discussion section and has me as the user and today as date (both wrong)

You have the same problem as me. Probably is something related to ADO, I tried using the ADO REST API and the behavior was the same.

**Comment by RoyalWulf** [comment]
Interestly this is working now.  So something has changed in Jira or ADO.

**Comment by emanuellimabr** [comment]
> Interestly this is working now. So something has changed in Jira or ADO.

Yes! Somehow it got fixed!

**Comment by jozolo** [comment]
I am also having this problem.  I am trying to export from Jira Server to Azure DevOps Cloud.  I've confirmed that the correct user and date are getting exported from Jira into the .json file, but they are all getting attributed to me in ADO, with current timestamp, when I run the tool.  

I do have the comment mapper section as detailed above.  My project is setup as Agile in ADO and Agile in the config file, with the default Agile column mappings.  Also, I checked and unlike the users above, my History tab is showing the same thing as the comments under the Discussion section of the Details tab.  In both tabs, the comments are attributed to me and the date of the comment is the date I ran the import. 

The comments I am trying to add are attributed to a mixture of named users in ADO from within our Active Directory and some that are without an AD login.  In all cases, I've mapped the users in the user mapping file, but neither type will get attributed.  In testing, I have created a comment using the rest api, and that does successfully attribute a comment to whatever email address I specify.  

I am using the most recent version of code, I branched it a couple of months ago and just re-branched it today.  Both versions had the same problem.  But one other oddity is that it tells me that it is version 0.0.1 when it starts.  But I assume that is nothing to do with the comments problem, but just thought I should mention.  I've also tried disabling the "New Boards Hubs" setting as mentioned in [this post](https://github.com/solidify/jira-azuredevops-migrator/discussions/415#discussioncomment-2829673), but it didn't change anything.  

[jira.config.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9366198/jira.config.json.txt)

**Comment by omustapasa** [comment]
@Alexander-Hjelm Any news on the topic?

I have recently checked-out the latest code from master.
Exporter seems to produce the correct results as per the JSON files generated.
Importer however creates all related history and attachments with the same account the application runner uses (token owner in my case)

I am not sure if this is caused by a change on ADO API or it is somewhat a side effect of having some preview features on/off and/or used access token for importer execution not having certain rights.

It would be great to have it resolved as my migration is quite dependent on this at this stage.
I would like to know if this is a limitation as per ADO API or something else.

**Comment by RoyalWulf** [comment]
I am getting this issue now.  It was working sometime last year.  Not sure if it is an ADO issue or migration issue. json file looks ok though.
