### ISSUE TITLE
[System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. Parameter name: startIndex

### ISSUE THREAD

**Issue by punyautkalika** [solidify/jira-azuredevops-migrator#445]
I am getting the below error and unable to proceed .
[System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex

{
  "source-project": "FX",
  "target-project": "Target_Migration_AzDp",
  "query": "project = FX  order BY key ASC",
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "using-jira-cloud": false,
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Debug",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "squad titan",
  "base-iteration-path": "migrated/squad titan",
  "ignore-failed-links": false,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
        },
        {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
        },
        {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
        },
               
        {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
        }

    ]
  },
  "type-map":{
    "type": [
   
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Theme",
        "target": "Epic"
      },
      {
        "source": "New Feature",
        "target": "Feature"
      },
      {
        "source": "Slice",
        "target": "Epic"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Product Backlog Item"
      },
      {
        "source": "Spike",
        "target": "Product Backlog Item"
      },
      {
        "source": "OPEN",
        "target": "Product Backlog Item"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Bug-task",
        "target": "Task"
      },
      {
        "source": "Task",
        "target": "Task"
      },
      {
        "source": "Kanban Item",
        "target": "Product Backlog Item"
      },
      {
        "source": "Impediment",
        "target": "Impediment"
      },
      {
        "source": "Improvement",
        "target": "Product Backlog Item"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },
      {
        "source": "General Task",
        "target": "Product Backlog Item"
      },
      {
        "source": "User story",
        "target": "Product Backlog Item"
      },  
      {
        "source": "Technical Task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "None",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {  
              "source": "Approved",
              "target": "To Do"
            },          
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "Open",
              "target": "To Do"
            },
            {
              "source": "Closed",
              "target": "Done"
            },
            {
              "source": "On Hold/Blocked",
              "target": "To Do"
            },
            {
              "source": "ready for verification",
              "target": "To Do"
            },
            {
              "source": "Ready for sprint",
              "target": "To Do"
            },
            {
              "source": "verification",
              "target": "To Do"
            },
            {
              "source": "verifying",
              "target": "To Do"
            },
            {
              "source": "Analyzing",
              "target": "To Do"
            },
            {
              "source": "analyzing for business case",
              "target": "To Do"
            },
            {
              "source": "Prioritized",
              "target": "To Do"
            },
            {
              "source": "Reopened",
              "target": "To Do"
            },
            {
              "source": "Resolved",
              "target": "Done"
            },    
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Bug,Product Backlog Item",
        "mapping": {
          "values": [
            {
              "source": "Accepting",
              "target": "Committed"
            },
            {
              "source": "Analyzing",
              "target": "New"
            },
            {
              "source": "analyzing for business case",
              "target": "New"
            },
            {
              "source": "Closed",
              "target": "Done"
            },
            {
              "source": "high level impacting",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "Committed"
            },
            {
              "source": "On Hold/Blocked",
              "target": "Approved"
            },
            {
              "source": "Open",
              "target": "New"
            },
            {
              "source": "prepared for analysis",
              "target": "New"
            },
            {
              "source": "Prioritized",
              "target": "New"
            },
            {
              "source": "Prepared for high level analysis",
              "target": "New"
            },
            {
              "source": "ready for acceptance",
              "target": "Committed"
            },
            {
              "source": "ready for implementation",
              "target": "Committed"
            },
            {
              "source": "ready for poker",
              "target": "Approved"
            },
            {
              "source": "Ready for sprint",
              "target": "Approved"
            },
            {
              "source": "Resolved",
              "target": "Done"
            },
            {
              "source": "Reopened",
              "target": "New"
            },
            {
              "source": "ready for verification",
              "target": "Committed"
            },
            {
              "source": "Reviewing",
              "target": "Approved"
            },
            {
              "source": "verifying",
              "target": "Committed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Epic,Feature",
        "mapping": {
          "values": [
            {
              "source": "Accepting",
              "target": "In Progress"
            },
            {
              "source": "Analyzing",
              "target": "New"
            },
            {
              "source": "analyzing for business case",
              "target": "New"
            },
            {
              "source": "Closed",
              "target": "Done"
            },
            {
              "source": "high level impacting",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            },
            {
              "source": "On Hold/Blocked",
              "target": "New"
            },
            {
              "source": "Open",
              "target": "New"
            },
            {
              "source": "prepared for analysis",
              "target": "New"
            },
            {
              "source": "Prioritized",
              "target": "New"
            },
            {
              "source": "Prepared for high level analysis",
              "target": "New"
            },
            {
              "source": "ready for acceptance",
              "target": "In Progress"
            },
            {
              "source": "ready for implementation",
              "target": "In Progress"
            },
            {
              "source": "Ready for sprint",
              "target": "New"
            },
            {
              "source": "ready for verification",
              "target": "In Progress"
            },
            {
              "source": "Reviewing",
              "target": "New"
            },
            {
              "source": "verifying",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "not-for": "Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      },

{
        "source": "customfield_10700",
        "target": "Microsoft.VSTS.Common.AcceptanceCriteria"
       
      }

    ]
  }
}

**Comment by punyautkalika** [comment]
Please suggest me a workaround to proceed

**Comment by Alexander-Hjelm** [comment]
Can you paste the whole log?

**Comment by punyautkalika** [comment]
@Alexander-Hjelm  please find the below :
2022-05-02T07:53:15.4560162Z [D][07:53:15]    Mapped value '[CCECARDSTP-212] Card Handling Integration and Modernization Program' to field 'System.Title'.
2022-05-02T07:53:15.5032320Z [D][07:53:15]    Mapped value '4' to field 'Microsoft.VSTS.Common.Priority'.
2022-05-02T07:53:15.5037121Z [D][07:53:15]    Mapped value '' to field 'System.IterationPath'.
2022-05-02T07:53:15.5041579Z [D][07:53:15]    Mapped value 'New' to field 'System.State'.

2022-05-02T07:53:15.5346870Z [D][07:53:15]    Mapping revision 1.
2022-05-02T07:53:15.5825936Z [D][07:53:15]    Mapping revision 2.
2022-05-02T07:53:15.7850338Z [E][07:53:15] Unexpected migration error.
2022-05-02T07:53:15.7851129Z [System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
2022-05-02T07:53:15.7851690Z Parameter name: startIndex
2022-05-02T07:53:15.7852103Z    at System.String.Substring(Int32 startIndex, Int32 length)
2022-05-02T07:53:15.7852675Z    at JiraExport.JiraMapper.MapEpicChildLink(JiraRevision r, List`1 links, String field, String type)
2022-05-02T07:53:15.7853209Z    at JiraExport.JiraMapper.MapLinks(JiraRevision r)
2022-05-02T07:53:15.7853679Z    at JiraExport.JiraMapper.MapRevision(JiraRevision r)
2022-05-02T07:53:15.7854284Z    at JiraExport.JiraMapper.<>c__DisplayClass10_0.<Map>b__2(JiraRevision r)
2022-05-02T07:53:15.7854778Z    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
2022-05-02T07:53:15.7855278Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2022-05-02T07:53:15.7855759Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2022-05-02T07:53:15.7856204Z    at JiraExport.JiraMapper.Map(JiraItem issue)
2022-05-02T07:53:15.7856892Z    at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): 
2022-05-02T07:53:15.7857607Z    at System.String.Substring(Int32 startIndex, Int32 length)
2022-05-02T07:53:15.7858244Z    at JiraExport.JiraMapper.MapEpicChildLink(JiraRevision r, List`1 links, String field, String type)
2022-05-02T07:53:15.7858993Z    at JiraExport.JiraMapper.MapLinks(JiraRevision r)
2022-05-02T07:53:15.7859448Z    at JiraExport.JiraMapper.MapRevision(JiraRevision r)
2022-05-02T07:53:15.7859959Z    at JiraExport.JiraMapper.<>c__DisplayClass10_0.<Map>b__2(JiraRevision r)
2022-05-02T07:53:15.7860484Z    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
2022-05-02T07:53:15.7861004Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2022-05-02T07:53:15.7862003Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2022-05-02T07:53:15.7862451Z    at JiraExport.JiraMapper.Map(JiraItem issue)
2022-05-02T07:53:15.7863240Z    at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)

**Comment by Alexander-Hjelm** [comment]
Looks like this is an open bug, similar to: https://github.com/solidify/jira-azuredevops-migrator/issues/345

The bug was apparently resolved by this PR: https://github.com/solidify/jira-azuredevops-migrator/pull/276

We will try and merge the open PRs and create a new release soon. We can't give any dates yet, likely it is still some time away :)

In the meantime you can try and check out PR 276 and build the project in Visual Studio yourself, and see if it helps!

**Comment by reallyandrew** [comment]
Is there any update on when a new release will be available containing this fix?

**Comment by Alexander-Hjelm** [comment]
Hi @reallyandrew. This fix is merged into master already, but the master branch is largely untested at the moment, therefore we haven't released yet. Feel free to clone the master branch yourself and build the tool in visual studio :)
