### ISSUE TITLE
JIRA migrator, Releases

### ISSUE THREAD

**Issue by PerSundqvist** [solidify/jira-azuredevops-migrator#452]

**Comment by PerSundqvist** [comment]
Add functionality in the migrator to:
configure what work item type in ADO is to be target for Releases/Versions in JIRA
configure workitem mappings for release in JIRA with Release Item in ADO
- JIRA Release Start Date = ?? in ADO on Release Item
- JIRA Release Release Date ?? IN ADO on Release Item
- Release Name -> Should be Title in ADO on Release Item
configure workitem status mappings for release in JIRA with Release Item in ADO
- i think Releases in JIRA has 3 Statuses ( Unreleased,  Released, Archived )

Create new Release Item in ADO during migration, if a ticket in JIRA has a release connected through fix version attribute
Connect migrated associated tickets from JIRA in ADO to the related Release Item with related link

**Comment by Alexander-Hjelm** [comment]
Write a custom mapper that maps releases to a given work item type

**Comment by Alexander-Hjelm** [comment]
https://solidifydemo.atlassian.net/projects/AGILEDEMO/versions/10004/tab/release-report-all-issues
