### ISSUE TITLE
Migrating multiple JIRA projects at once to azure DevOps 

### ISSUE THREAD

**Issue by jdewa** [solidify/jira-azuredevops-migrator#456]
Just wanted to know if it is possible to migrate multiple JIRA projects at once using the configuration JSON file to azure DevOps using the jira to azure DevOps/TFS work item tool - since the example provided only shows one project's work items being migrated.

**Comment by Alexander-Hjelm** [comment]
Nope, you will have to script your own solution for generating a config file + running the migrator for each project :)

To migrate the issues of several projects into one ADO project, you can include multiple JIRA projects in your query like this:

![image](https://user-images.githubusercontent.com/10683896/169503029-491938b1-f4d2-4f40-9b4f-4f3fa187de6e.png)

Just make sure that your JIRA token has access to all of the specified projects
