### ISSUE TITLE
Migrated shows "Closed" as first state

### ISSUE THREAD

**Issue by gnimor** [solidify/jira-azuredevops-migrator#491]
I am trying to import our JIRA server entries to Azure Devops. The migration completed without error, but I have a strange behaviour. In the history of all imported entries the first state is "Closed" instead of "Proposed" or "Active". I have attached the history of an imported item:

History in Azure Devops:
![devops](https://user-images.githubusercontent.com/14901306/177506010-77442a07-f2f1-498b-889d-af419a52c89f.png)

Original history in Jira:
![jira](https://user-images.githubusercontent.com/14901306/177506407-c3b801ac-39bf-4b19-b03f-107012e5cf4b.png)

and the state mapping is as follows:

		    {
              "source": "Pending",
              "target": "Proposed"
            },
			{
              "source": "IN PROGRESS",
              "target": "Active"
            },
		    {
              "source": "VERIFIED",
              "target": "Closed"
            },
		    {
              "source": "Open",
              "target": "Active"
            },	
			{
              "source": "RESOLVED",
              "target": "Resolved"
            },
			{
              "source": "Closed",
              "target": "Closed"
            },			
			{
              "source": "Reopened",
              "target": "Active"
            },
			{
              "source": "UNDER TEST",
              "target": "Test"
            },			
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "In Progress",
              "target": "Doing"
            },
            {
              "source": "Done",
              "target": "Done"
            }

**Comment by Alexander-Hjelm** [comment]
Strange behavior indeed. Marking this as a bug.

Any chance you can share the migration log file as a pastebin? @gnimor

**Comment by gnimor** [comment]
@Alexander-Hjelm: What log files do you need? wi-import or jira-export log?

**Comment by Alexander-Hjelm** [comment]
Both if possible!
________________________________

**Comment by gnimor** [comment]
Sure..

[jira-export-log-220706-082414.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9054851/jira-export-log-220706-082414.txt)

[wi-import-log-220706-082605.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9054854/wi-import-log-220706-082605.txt)

**Comment by rambaliga** [comment]
Hi @Alexander-Hjelm , any idea if there will be a fix for this anytime soon? We are facing the same issue with the tool.

**Comment by Alexander-Hjelm** [comment]
@rambaliga 
No estimate unfortunately. Since we don't have any direct funding for the jira-azdo migration tool, we can only work on it as soon as time allows us to. But we always welcome community fixes :)

If you are in urgent need, or if we can help you with your migration in some other way, you are always welcome to make a business inquiry to Solidify AB, Sweden.

**Comment by Alexander-Hjelm** [comment]
I have tried to reproduce this behavior, but haven't been successful. Everything seems to works fine. so I'm relabeling this as a support issue.

@gnimor , @rambaliga . Do you have any additional info that could help with reproducing this issue? Have you identified any patterns, whether this issue happens for some work items but not for others?

Have you tried both the latest Release and the latest version on the master branch?
