### ISSUE TITLE
Cannot add a new link because one of work items being linked will exceed 1000 link limit

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#500]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/497

<div type='discussions-op-text'>

<sup>Originally posted by **NarendraBabuTR** July 25, 2022</sup>
Hello,
   We are hitting a problem with link exceeding 1000 limit for one of the test case which does not seems to have any links exceeding 1000. This has just 4 links only. Is there a solution to overcome this issue? Also trying to understand at how is the tool counting to arrive at 1000 link limit?

![image](https://user-images.githubusercontent.com/89962970/180729775-914756e1-049f-45e8-a108-5fe1c115d5c6.png)
</div>

**Comment by Alexander-Hjelm** [comment]
@NarendraBabuTR, please post the migration configs and the contents of the .json file for the problematic work item

**Comment by NarendraBabuTR** [comment]
Hello @Alexander-Hjelm ,
  The problematic work item Json details as below.
  {
  "Type": "Test Case",
  "OriginId": "GCMSQABANG-1968",
  "WiId": -1,
  "Revisions": [
    {
      "Author": "himabindu.goteti@thomsonreuters.com",
      "Time": "2017-06-30T10:11:40+00:00",
      "Index": 0,
      "Fields": [
        {
          "ReferenceName": "System.CreatedBy",
          "Value": "himabindu.goteti@thomsonreuters.com"
        },
        {
          "ReferenceName": "System.Title",
          "Value": "[GCMSQABANG-1968] TC01 -Relationships - Add product massive - Aranzadi - Display - Add"
        },
        {
          "ReferenceName": "System.Tags",
          "Value": "ARZ"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": "3"
        },
        {
          "ReferenceName": "System.IterationPath",
          "Value": null
        },
        {
          "ReferenceName": "System.State",
          "Value": "Design"
        },
        {
          "ReferenceName": "Custom.CategoryA",
          "Value": "RelationShip"
        },
        {
          "ReferenceName": "Custom.CategoryB",
          "Value": "GCMS"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "himabindu.goteti@thomsonreuters.com",
      "Time": "2017-12-12T08:37:52+00:00",
      "Index": 1,
      "Fields": [
        {
          "ReferenceName": "System.Tags",
          "Value": "ARZ;GCMSARZ"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "himabindu.goteti@thomsonreuters.com",
      "Time": "2017-12-12T08:47:40+00:00",
      "Index": 2,
      "Fields": [
        {
          "ReferenceName": "System.Tags",
          "Value": "GCMSARZ"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "sarath.1@thomsonreuters.com",
      "Time": "2017-12-18T06:49:40+00:00",
      "Index": 3,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "nirjasa.nayak@thomsonreuters.com",
      "Time": "2018-08-23T05:58:30+00:00",
      "Index": 4,
      "Fields": [
        {
          "ReferenceName": "System.Tags",
          "Value": "GCMSARZ;GCMSGulf"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "javier.munoz@thomsonreuters.com",
      "Time": "2019-05-30T12:29:06+00:00",
      "Index": 5,
      "Fields": [
        {
          "ReferenceName": "System.Tags",
          "Value": "GCMS2.0;GCMSARZ;GCMSGulf;LEGISLATION"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "Arun.Karthikeyan@thomsonreuters.com",
      "Time": "2022-05-25T14:34:53.244+00:00",
      "Index": 6,
      "Fields": [
        {
          "ReferenceName": "System.Tags",
          "Value": "GCMS2.0;GCMSARZ;GCMSGulf;LEGISLATION;SECURITY_TEST_PLAN"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },
    {
      "Author": "Arun.Karthikeyan@thomsonreuters.com",
      "Time": "2022-06-14T07:52:32.519+00:00",
      "Index": 7,
      "Fields": [
        {
          "ReferenceName": "System.Tags",
          "Value": "GCMS2.0;GCMSARZ;GCMSARZ_Auto;GCMSGulf;LEGISLATION;SECURITY_TEST_PLAN"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    }
  ]
}


I don't see any links in this JSON file which is of concern but this "TEST CASE" has a "TEST EXECUTION" mentioned in JIRA which has a TEST SUITE which has Related links count to "1000". We are guessing this is what the limit is hit and hence not allowing to insert anything above this. But we aren't migrating this and unsure what's pulling this in.

Is there a way to control this from not coming thru? Please let me know your comments.

**Comment by Alexander-Hjelm** [comment]
Use the "query" field in the configuration file to regulate which items are migrated and not.

Maybe it's worth assigning the offending test case to a separate tag, and excluding that tag from the query, just for debugging purposes?

A quick way to see if the test case was exported or not would be to just open the folder with your exported issues in any IDE and do a project-wide search for the test case title, or any other information that uniquely identifies the test case

**Comment by Alexander-Hjelm** [comment]
Send the migration log as a pastebin as well, if possible

**Comment by NarendraBabuTR** [comment]
Hello @Alexander-Hjelm , we see the test case coming thru as the query in the configuration is just to pull the "Test case" only as below.

project = 'GCMSQABANG' and (ID='GCMSQABANG-1968') ORDER BY id ASC",

But like I mentioned, this test case has a "Test execution" mentioned in JIRA and how this is getting pulled ( we dont have a mapping ) is the question. The one highlighted in yellow.

![image](https://user-images.githubusercontent.com/89962970/181695388-4679cb83-10b3-47ea-973b-83a841c5115d.png)


![image](https://user-images.githubusercontent.com/89962970/181695278-60cb9f2e-c84e-4dcc-8ddc-3768868fc63d.png)

**Comment by Alexander-Hjelm** [comment]
The query you posted should only find one issue, correct?

Is the jira exporter truly exporting only one work item? Or does it export the executions as well?

What are the contents of your workspace? Is only the test case there or are there more items? Maybe delete the offending test execution manually?

Have a look in the config file and play around with the Download-options flag maybe?
- https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#download-options

**Comment by NarendraBabuTR** [comment]
The output is just one JSON file. There is no whereabouts of "Test execution" at all as part of JIRA export. Unsure how its pulling in "Test Execution". 

I can delete the offending Test execution manually, but if it creates again as part of migration, this is something we dont know.

I think instead of "7" download option we can try "3" ( 1 + 2 + 0). But if we ignore "4", would it ignore any links which is suppose to come thru as well?
![image](https://user-images.githubusercontent.com/89962970/181697615-772fc889-6abd-4859-9dd4-81df515c65ff.png)

**Comment by Alexander-Hjelm** [comment]
I think your only choices are to ignore the link to the test execution, delete it manually, or reduce the number of links. Either way Azure DevOps will not be able to import work items with link count > 1000. Which option do you prefer?

**Comment by NarendraBabuTR** [comment]
Hello @Alexander-Hjelm , how to ignore the link to "Test execution". What modification I can do in the above attached JSON file for the Work item.

**Comment by NarendraBabuTR** [comment]
You mean select the "Download" option to be "( 1 + 2 + 0 = 3) and then try it out?

**Comment by Alexander-Hjelm** [comment]
I would say start with setting download-options to be 0 to see if that does any change, and then go higher.

But what's wrong with just letting the migration run to the finish and then deleting the work item manually in Azure DevOps? AFAK it won't affect the rest of your data negatively.

**Comment by NarendraBabuTR** [comment]
okay @Alexander-Hjelm . The migration completes good, but there are 1000 of test case which are missing the 'Test steps" data coming thru because of this issue.

We will try with "0" and go higher.

**Comment by Alexander-Hjelm** [comment]
Ah ok!
