### ISSUE TITLE
[System.OutOfMemoryException] System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#502]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/501

<div type='discussions-op-text'>

<sup>Originally posted by **KumarNSR** July 28, 2022</sup>
@Alexander-Hjelm 

While Importing to Azure getting error message as below
[E][23:42:24] Failed to import revisions for '0'.
[System.OutOfMemoryException] System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

Could you pls help </div>

**Comment by Alexander-Hjelm** [comment]
@KumarNSR, please share the config file and migration log. Share the json file for the offending work item if possible

**Comment by KumarNSR** [comment]
@Alexander-Hjelm ,

Config file

{
  "source-project": "SAP HRMS Change Management",
  "target-project": "SAPHRMSCM",
  "query": "project=HRMSCM AND type = Change Request",
  "query": "project = HRMSCM AND status = Done ORDER BY created DESC",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 15,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "CMMI",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Subtasks",
        "target": "System.LinkTypes.Child"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Service Ticket",
        "target": "Issue"
      },
      {
        "source": "Incident",
        "target": "Bug"
      },
      {
        "source": "Change Request",
        "target": "Change Request"
      },
      {
        "source": "Story",
        "target": "User Story"
      },
      {
        "source": "Epic",
        "target": "Feature"
      },
      {
        "source": "Approval",
        "target": "Approval"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },
      {
        "source": "Package",
        "target": "Requirement"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "contributor",
        "target": "Microsoft.VSTS.TCM.Custom.Contributor",
        "mapper": "MapUser"
      },
      {
        "source": "interested party",
        "target": "Microsoft.VSTS.TCM.Custom.InterestedParty",
        "mapper": "MapUser"
      },
      {
        "source": "countries",
        "source-type":"name",
        "target": "Custom.Countries",
        "mapper": "MapArray"
      },
      {
        "source": "geo",
        "source-type":"name",
        "target": "Custom.GEO",
        "mapper": "MapArray"
      },
      {
        "source": "business justification",
        "source-type":"name",
        "target": "Microsoft.VSTS.CMMI.Justification",
        "for": "Change Request"
      },
      {
        "source": "business justification",
        "source-type":"name",
        "target": "Microsoft.VSTS.TCM.Justification",
        "for": "Bug"
      },
      {
        "source": "business justification",
        "source-type":"name",
        "target": "Microsoft.VSTS.TCM.Justification",
        "for": "Issue"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "Target end",
        "Data type"  :"DateTime",  
        "target": "Microsoft.VSTS.Scheduling.TargetDate"
      },
      {
        "source": "Acceptance Criteria",
        "source-type":"name",
        "target": "Microsoft.VSTS.Common.AcceptanceCriteria"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "fixversions",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Change Request,Requirement,Issue,Bug",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "Proposed"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "In Review",
              "target": "In Review"
            },
            { 
              "source": "Testing",
              "target": "Testing"
            },
            {
              "source": "In Development",
              "target": "In Development"
            },
            {
              "source": "Squad Planning",
              "target": "Squad Planning"
            },
            {
              "source": "Researching",
              "target": "Researching"
            },
            {
              "source": "Researching",
              "target": "Researching"
            },
            {
              "source": "Under Review",
              "target": "Under Review"
            },
            {
              "source": "Ready",
              "target": "Ready"
            },
            {
              "source": "Blocked",
              "target": "Blocked"
            }, 
            {
              "source": "Awaiting Approval",
              "target": "Awaiting Approval"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Ready to Deploy",
              "target": "Ready to Deploy"
            },
            {
              "source": "Deployment",
              "target": "Deployment"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            },
            {
              "source": "Awaiting Feedback",
              "target": "Awaiting Feedback"
            },
            {
              "source": "UAT",
              "target": "UAT"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "Proposed"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "In Review",
              "target": "In Review"
            },
            { 
              "source": "Testing",
              "target": "Testing"
            },
            {
              "source": "In Development",
              "target": "In Development"
            },
            {
              "source": "Squad Planning",
              "target": "Squad Planning"
            },
            {
              "source": "Researching",
              "target": "Researching"
            },
                   {
              "source": "Under Review",
              "target": "Under Review"
            },
            {
              "source": "Ready",
              "target": "Ready"
            },
            {
              "source": "Blocked",
              "target": "Blocked"
            }, 
            {
              "source": "Awaiting Approval",
              "target": "Awaiting Approval"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Ready to Deploy",
              "target": "Ready to Deploy"
            },
            {
              "source": "Deployment",
              "target": "Deployment"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            },
            {
              "source": "Awaiting Feedback",
              "target": "Awaiting Feedback"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Approval",
        "mapping": {
          "values": [
            {
              "source": "Requested",
              "target": "Proposed"
            },
            {
              "source": "Approved Request",
              "target": "Closed"
            },
            {
              "source": "Denied Request",
              "target": "Removed"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            }
          ]
        }
        },  
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Bug,Task,Approval"
      },
      {
        "source": "environment",
        "source-type": "name",
        "target": "Microsoft.VSTS.TCM.SystemInfo",
        "for": "Bug,Change Request,Issue"
      }
    ]
  }
}

[wi-import-log-220728-170436_1.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9213894/wi-import-log-220728-170436_1.txt)

**Comment by Alexander-Hjelm** [comment]
I see a lot of this error:

> [Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException: TF26027: A field definition Microsoft.VSTS.TCM.Justification in the work item type definition file does not exist. Add a definition for this field or remove the reference to the field and try again.

Which means that you are trying to import some custom field that does not exist in your work item definition. Have a look at which field it could be.

Otherwise it could be that maybe your migration job has too much data and your machine just isn't beefy enough to hold it all in memory at once?

You could try to split up the migration job in two parts but moving the non-migrated items to a new folder, although this will mess up the links
