### ISSUE TITLE
Rendered field contains unparsable type Null, using text error message

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#504]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/503

<div type='discussions-op-text'>

<sup>Originally posted by **C-F-Palmer** July 30, 2022</sup>
Hi,

I have successfully exported and imported one issue from Jira to Azure DevOps but not all fields in my mapping have come across. The fields that are not exporting are showing the following error:

![image](https://user-images.githubusercontent.com/92213401/181865070-e323a22e-6afe-4068-8403-0d8890d57a45.png)

For example, the line in the log that states "Rendered field customfield_10061 refers to this section of my mapping file:

{
        "source": "Affects Build Number",
	"source-type": "name",
        "target": "Custom.AffectedBuildNumber",
      },      

I have tried many different ways to load this data such as adding the source-type "name" and also "id" and also without this line in the file. I can't seem to get it to work.

Any help here would be greatly appreciated.

Chris</div>

**Comment by Alexander-Hjelm** [comment]
@C-F-Palmer, have a look in the exported work item .json file. Does the Custom.AffectedBuildNumber field appear there? If so then it's a problem with the exporter. Otherwise it's a problem with the importer. Let me know what you find out.

**Comment by C-F-Palmer** [comment]
@Alexander-Hjelm , yes it does:
![image](https://user-images.githubusercontent.com/92213401/181935767-b46fc216-f929-4dd2-a993-e73c8b5b4840.png)

**Comment by Alexander-Hjelm** [comment]
Then likely an issue with the work item model in Azure DevOps. Does the field ”Custom.AffectedBuildNumber” exist on the work item type that you are trying to import into?
________________________________

**Comment by C-F-Palmer** [comment]
Hi Alexander, thanks for replying so promptly on a weekend. Below is a screen shot from the ADO environment I am trying to migrate to. The field is there and I can't see anything obvious that would be stopping it from coming across:

![image](https://user-images.githubusercontent.com/92213401/181996506-4ccec954-c334-4663-bde0-701e4f490819.png)

Thanks
Chris

**Comment by Alexander-Hjelm** [comment]
Not sure, I’ll look into it. Meanwhile it seems that for some people it has helped to remove the source-type property in the config file for your fields. Maybe try that? See: https://github.com/solidify/jira-azuredevops-migrator/issues/316
________________________________

**Comment by C-F-Palmer** [comment]
Hi Alexander, I just tried again with using the following:

{
        "source": "Affects Build Number",
	"source-type": "name",
	"target": "Custom.AffectedBuildNumber"
      },      
      
      It has worked this time. Not sure what has happened here except that I removed comma at the end of the "target" line.
      
      Thanks again for all your help.

**Comment by Alexander-Hjelm** [comment]
Aha! I didn’t catch that ^^

But it makes sense. JSON doesn’t allow trailing commas, so there could be issues with parsing the config file in that case.

But glad that it worked for you. I would go over the whole config file and ensure that there are no trailing commas in any json object or array. Maybe use a json linter!
________________________________

**Comment by ViswaMohan88** [comment]
Hi Alex and Palmer,
Even i am facing the similar issue. I am not getting errors during the export and some of the customfeilds are not making any entry in json file. Can you please suggest on this.

**Comment by Alexander-Hjelm** [comment]
@ViswaMohan88 Please open a new support issue and include the migration log file
