### ISSUE TITLE
Hi Team, Do we have any code to migrate Filters and dashboards from Jira to Azure. Please let me know if we have anything.

### ISSUE THREAD

**Issue by ViswaMohan88** [solidify/jira-azuredevops-migrator#506]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ViswaMohan88** [comment]
Do we have any code to migrate Filters and dashboards from Jira to Azure. Please let me know if we have anything.

**Comment by Alexander-Hjelm** [comment]
Nope, this tool only migrates the issues. Nothing more and nothing less :)

**Comment by ViswaMohan88** [comment]
Hi Alex, Thank you for the quick response. Do you have any idea on how to migrate the filters and dashboards. Or any other applications or plugins which can do this?

**Comment by Alexander-Hjelm** [comment]
Not on the top of my head, sadly. It should be possible to write such a migrator but the challenges are mapping the JQL syntax to the Azure DevOps WorkItem Query Languange (for filters) and provisioning individual widgets in Azure Dashboards that may or may not completely match the features of JIRA widgets, if any corresponding widget exists at all. Another question is how you would migrate custom widgets.

In our typical business scenarios, the customer wants to migrate only the issue data and no "supporting" data. I think that Solidify has done dashboard migrations before though. If we can assist you in the migration in any way, you are welcome to make a business inquiry to Solidify AB.

**Comment by ViswaMohan88** [comment]
Thanks for your inputs Alex.

**Comment by ViswaMohan88** [comment]
And do we have any code or tool to migrate Confluence to Azure WIKI?

**Comment by Alexander-Hjelm** [comment]
At Solidify we provide Confluence->AzDO Wiki migrations as a paid service :)

**Comment by ViswaMohan88** [comment]
Ohh. May I know the charges for that.

**Comment by Alexander-Hjelm** [comment]
Of course, shoot me an email at alexander.hjelm@solidify.dev and I'll send you the rates :)

**Comment by ViswaMohan88** [comment]
Thanks for the Email Alex. We will think about it.
I have one doubt in Jira Migration. Can we pass a customfield value to Azure using Config file? 
Note: That custom field is not present in Jira.
For Example: there is a Custom field called Area in Azure. While doing the export and import, I need to give the value as DevOps . Is that possible?

**Comment by Alexander-Hjelm** [comment]
You can map custom JIRA fields yes :) Check the docs: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

**Comment by ViswaMohan88** [comment]
Alex, I am asking about the field which is not present in Jira. We need to pass a value to Azure Devops using Config file.
Is that possible?

**Comment by Alexander-Hjelm** [comment]
Don’t think that is possible today. You can either write your own mapper that only takes one target ADO field, or write your own rest api integration that populates your ADO work items with a field and value, based on a WIQL query
________________________________
