### ISSUE TITLE
Which port is the tool using?

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#508]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/507

<div type='discussions-op-text'>

<sup>Originally posted by **dacula** August  3, 2022</sup>
Hello together,
i'm not very skilled with network administration but it looks like the application is blocked by our firewall. 
Can you tell me which port i need to open to get access? 

Kind regards
dacula</div>

**Comment by Alexander-Hjelm** [comment]
For on-prem use cases, the server where you run the jira migrator will need openings to these:
- Your Azure DevOps Server Instance
- Your JIRA Server instance

**Comment by dacula** [comment]
Our Jira Server instance is behind an Akamai CDN with Microsoft OAuth Authentication. Is there a way to Authenticate with Microsoft OAuth?

**Comment by Alexander-Hjelm** [comment]
Nope, you need a valid JIRA API token to authenticate :)

**Comment by dacula** [comment]
i tried it with an API token but it just gives me an outh http page back 

Jira Exporter v2.3.117
Copyright (c) Solidify
[I][09:34:32] Connecting to Jira...
[I][09:34:32] Retrieving Jira fields...
[E][09:34:32] Unexpected migration error.
[System.AggregateException] System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: 
<!DOCTYPE html>
<html dir="ltr" class="" lang="en">
<head>
    <title>Sign in to your account</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <link rel="preconnect" href="https://aadcdn.msftauth.net" crossorigin>
<meta http-equiv="x-dns-prefetch-control" content="on">
<link rel="dns-prefetch" href="//aadcdn.msftauth.net">
<link rel="dns-prefetch" href="//aadcdn.msauth.net">

    <meta name="PageID" content="ConvergedSignIn" />
    <meta name="SiteID" content="" />
    <meta name="ReqLC" content="1033" />
    <meta name="LocLC" content="en-US" />

        <meta name="referrer" content="origin" />

        <meta name="format-detection" content="telephone=no" />

    <noscript>
        <meta http-equiv="Refresh" content="0; URL=https://login.microsoftonline.com/jsdisabled" />
    </noscript>



<meta name="robots" content="none" />

<script type="text/javascript">//<![CDATA[
$Config={"fShowPersistentCookiesWarning":false,"urlMsaSignUp":"https://login.live.com/oauth20_authorize.srf?response_type=code\u0026client_id=51483342-085c-4d86-bf88-cf50c7252078\u0026scope=openid+profile+email+offline_access\u0026response_mode=form_post\u0026redirect_uri=https%3a%2f%2flogin.microsoftonline.com%2fcommon%2ffederation%2foauth2msa\u0026state=rQQIARAA42Kwss8oKSkottLXT8kvTc9JLNbNKE3Sy8lPz8zTS8_XS8xOzE3M1E1MTk4tLtZLzs_VL07MzdEvLtAvSi0uyM8rTi0S4hK4lWNw2U6M33NGmb9s-cvNn2YxcsbnZJalgjSsYqTUhkOMivFOlqamxm7GLoYGTq4GzuaOpkZuxq6Wbq7mzo4GJoZmJhcYGV8wMt5iYg0Gajb6xWRaWpRnlZ9YnFlslZeYm1psVZJsFezo62NlqGcIFslM0U3LL8pNLLEqzSsuSE3OTMtMTZnFLGxobmRuZGxiYGpuYW5kamJoYWKxiVnFzMwwxdDAwkDXwNjUWNcEaKNuoqmZhW6ahWmaUYpJmlFamukFFp4fLIyLWIHhUVY68XRGdafHdPbJCzP8EhhOsepnehU56heGFGqbJhr4uDoVm5WZFHlkByRaWLj4G7t5lIeUmfhHuppnRbpE2ppZGU5g4z3FxvCBjbGDnWEWO8MBTsYNPIwHeBl-8PXMm3pn5ZK5bz0A0\u0026estsfed=1\u0026uaid=d3306cda163e490f98764f1d77e9b3f2\u0026signup=1\u0026lw=1\u0026fl=easi2\u0026fci=https%3a%2f%2fdouglas-hub.login.go.akamai-access.com%2fsaml%2fsp%2fresponse","urlMsaLogout":"https://login.live.com/logout.srf?iframed_by=https%3a%2f%2flogin.microsoftonline.com","urlOtherIdpForget":"https://login.live.com/forgetme.srf?iframed_by=https%3a%2f%2flogin.microsoftonline.com","showCantAccessAccountLink":true,"urlGitHubFed":"https://login.live.com/oauth20_authorize.srf?response_type=code\u0026client_id=51483342-085c-4d86-bf88-cf50c7252078\u0026scope=openid+profile+email+offline_access\u0026response_mode=form_post\u0026redirect_uri=https%3a%2f%2flogin.microsoftonline.com%2fcommon%2ffederation%2foauth2msa\u0026state=rQQIARAA42Kwss8oKSkottLXT8kvTc9JLNbN...

**Comment by Alexander-Hjelm** [comment]
Then I can't really say, sadly. The rest API token is the preferred way to access the rest API, so that's how we have implemented it. To my knowledge there is no native way to authenticate with the rest API using OAuth tokens. So if you cannot authenticate to the API, how to you expect to be able to run the tool? :)

**Comment by dacula** [comment]
Alright, i think i used a PAT not an API token, i will try it again with an API token, sorry and thank you!
The API token has to be used as password right?

**Comment by Alexander-Hjelm** [comment]
Yup! You can find some usage examples in the docs. :)

Here is an article that shows you how to manages API tokens in case you need it: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

**Comment by dacula** [comment]
Thanks a lot!

**Comment by Alexander-Hjelm** [comment]
No worries :)
