### ISSUE TITLE
Issue when exporting work items

### ISSUE THREAD

**Issue by hasithamgh** [solidify/jira-azuredevops-migrator#51]
I'm trying to export multiple work items from JIRA and when I execute the export tool I recive following issue. I was only able to export one work item from JIRA.
image
![image](https://user-images.githubusercontent.com/12080391/57269014-6fd94180-70a3-11e9-87f1-d78a7279ce98.png)

[D][15:38:12] Mapped value 'Committed' to field 'System.State'.
[D][15:38:12] Exported as type 'Product Backlog Item'.
[E][15:38:12] Unexpected migration error.
[Newtonsoft.Json.JsonException] Newtonsoft.Json.JsonException: Unexpected end while parsing path.
at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List1 filters, Int32 currentPartStartIndex, Boolean query) at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain() at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression) at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch) at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path) at JiraExport.JiraItem.get_EpicParent() at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext() at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh): at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List1 filters, Int32 currentPartStartIndex, Boolean query)
at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain()
at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression)
at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch)
at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
at JiraExport.JiraItem.get_EpicParent()
at JiraExport.JiraProvider.d__21.MoveNext()
at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
[I][15:38:12] Export complete. Exported 49 items (1 errors, 1 warnings) in 00:00:06.

appreciate your inputs on this issue.

thanks,
Hasitha

**Comment by MOlausson** [comment]
Thanks for reporting @hasithamgh. Can you share a little more context regarding your structure. Which issue types are you using? Which process? Do you use parent epics at all?

**Comment by hasithamgh** [comment]
Thanks @MOlausson for looking in to this. I'm totally new to JIRA but I need to do a work item migration from JIRA to AzureDevOps. I'm currently using a test jira instance where it contains few users stories, tasks and bugs. I used the default config file given with the tool and just renamed the project names. I can grant you permission to the JIRA instance if you could provide your email address.`

`{
  "source-project": "SampleProject",
  "target-project": "JiraMigration",
  "query": "project = SampleProject ORDER BY Rank ASC",
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "customfield_10008",
  "sprint-field": "customfield_10007",
  "batch-size": 20,
  "log-level": "Debug",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Migrated",
  "base-iteration-path": "Migrated",
  "ignore-failed-links": true,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Product Backlog Item"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "Product Backlog Item"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "customfield_10007",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Bug,Product Backlog Item",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "Committed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Epic,Feature",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "customfield_10004",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "for": "Epic,Feature,Product Backlog Item,Bug",
        "type": "double"
      },
      {
        "source": "remainingEstimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "for": "Bug,Task",
        "type": "double"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}`

above is the config file used.

thanks,
Hasitha

**Comment by srijampani** [comment]
@MOlausson , i am also running into the same issue, In our JIRA project we have Epics, Stories, bugs, tasks, sub tasks. EPIC's have tasks present under them. 
![image](https://user-images.githubusercontent.com/43587506/57302740-7ebef480-70a1-11e9-8e4b-001c66cb9639.png)

**Comment by MOlausson** [comment]
Fixed in v2.2.21.
