### ISSUE TITLE
Jira export crashes with NullReferenceException in GetCustomId

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#511]
**Describe the bug**
Latest version of Jira export (master branch) crashes with NullReferenceException.

```
----- Export Jira issues -----
Jira Exporter v2.3.3
Copyright (c) Solidify
Wow, there's a newer release out (v2.3.117)! We recommend downloading it for latest features and fixes.
[I][14:20:56] Connecting to Jira...
[I][14:20:56] Retrieving Jira fields...
[I][14:20:56] Retrieving Jira link types...
[I][14:20:57] Export started. Exporting 19 items.
[E][14:20:57] Unexpected migration error.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraProvider.GetCustomId(String propertyName)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at JiraExport.JiraProvider.GetCustomId(String propertyName)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][14:20:57] Export complete. Exported 19 items (1 errors, 0 warnings) in 00:00:01.
```
The version in this log may be ignored, I used the included azure-pipelines.yaml to build the master branch.

This has been raised earlier by @nk111 as comment on the commit [here](https://github.com/solidify/jira-azuredevops-migrator/commit/fce48f0f26f468be4a3fd34f435b4d40b4e369d8#r78648927), but that might not be sufficiently visible.

**To Reproduce**
1. Build the latest version of the Jira Export tool.
2. Configure config.json
3. For me it crashes when trying to find the configured "epic-link-field" [here](https://github.com/solidify/jira-azuredevops-migrator/blob/bd2335c6509552cf36b303af0a6fdc3975e9b2b8/src/WorkItemMigrator/JiraExport/JiraCommandLine.cs#L103)

**Expected behavior**
Release 2.3.117 (latest release on github) works correctly and does not crash.

**Comment by Alexander-Hjelm** [comment]
Good find! Did your PR solve the issue?

**Comment by moerketh** [comment]
> Good find! Did your PR solve the issue?

Yes, works for me
