### ISSUE TITLE
WorkItemMigrator Azure pipelines artifact is missing a dependency

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#513]
**Describe the bug**
Latest version of Work Item Importer (master branch) crashes because it is missing a required assembly when build with the included azure-pipelines.yaml

The error is:
```
Work Item Importer v2.3.3
Copyright (c) Solidify
Wow, there's a newer release out (v2.3.117)! We recommend downloading it for latest features and fixes.
[W][15:10:40] User mapping file 'C:\temp\Jira\WorkItemMigrator-latest\Output\users.txt' not found, ignoring mapping user identities.
[I][15:10:41] Connecting to Azure DevOps/TFS...
[E][15:10:42] Unexpected migration error.
[System.IO.FileNotFoundException] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Services.Client.Interactive, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Services.Client.Interactive, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at WorkItemImport.WitClientWrapper..ctor(String collectionUri, String project)
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
:
   at WorkItemImport.WitClientWrapper..ctor(String collectionUri, String project)
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][15:10:42] Import complete. Imported 0 items, 0 revisions (1 errors, 1 warnings) in 00:00:01.
```
The version in this log may be ignored, I used the included azure-pipelines.yaml to build the master branch.

**To Reproduce**
1. Build the jira-azuredevops-migrator with the azure-pipelines.yaml
2. Download the buildartifact
3. Extract the buildartifact
4. Run the Work Item Importer
5. See the error

**Comment by Alexander-Hjelm** [comment]
Hi Thomas! Good find :) Does your PR solve the issue?

If you find yourself waiting, you can always use the latest stable Release here: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v2.3.117

If you opt for going with the latest version on the master branch, please report any findings through the GitHub issues. We would love to get it tested more thoroughly :)

**Comment by moerketh** [comment]
This fixed the error, yes. However I've since learned that Microsoft.VisualStudio.Services.Client was used because the WitClientWrapper.cs was not using the configured PAT. So I'm closing this in favor of issue #515 with PR #516

**Comment by moerketh** [comment]
@Alexander-Hjelm just a question regarding your comment. The latest release is 2 years old at this time. Will I miss a lot of functionality\bugfixes when I go with this release compared to the master branch? What would you say is the main difference?

**Comment by Alexander-Hjelm** [comment]
The only difference is a couple of bugfixes related to rendering HTML fields and images. If the migrator is running smoothly for you with in 2.3.117, then likely the master branch will work just as well.
