### ISSUE TITLE
Mappers

### ISSUE THREAD

**Issue by ViswaMohan88** [solidify/jira-azuredevops-migrator#520]
Hi team,

Please help me how to map Number fields, Datetime fields, and dropdown fields.
I am trying to map with the help of reference document, but it is not working for me. Please suggest.

Regards

**Comment by Alexander-Hjelm** [comment]
Hi ViswaMohan :)

Usually you can find information like this in the docs (config.md) or by searching old support issues here in GitHub Issues. I have looked up some relevant reading here:

See this issue for mapping datetime values: https://github.com/solidify/jira-azuredevops-migrator/issues/435

Dropdowns should just be regular name mappings, if I'm not mistaken. See: https://github.com/solidify/jira-azuredevops-migrator/issues/271

Of course, if you want an equivalent dropdown menu on the work item form in Azure DevOps, you have to implement this yourself in the process model.

 For numbers, simply leave the mapping property empty, like this (see config.md in docs):
 ```json
{
  "source": "Story Points",
  "source-type": "name",
  "target": "Microsoft.VSTS.Scheduling.Effort",
  "not-for": "Task"
},
```

**Comment by ViswaMohan88** [comment]
Hi Alex, I am able to import Drop down and number fields now. 
But i am not able to import Date and time fields. Please find the export log below. and can you please help me how to export fix versions and affects version as well.

I][15:53:33] Connecting to Jira...
[I][15:53:33] Retrieving Jira fields...
[I][15:53:35] Retrieving Jira link types...
[I][15:53:36] Export started. Exporting 1 items.
[I][15:53:37] Initializing Jira field mapping...
[I][15:53:38] Processing 1/1 - 'TDT-46'.
[W][15:53:40] Email is not public for user '62da8a127654479e0609bef3' in Jira, using usernameOrAccountId '62da8a127654479e0609bef3' for mapping.
[W][15:53:40] Could not find user '62da8a127654479e0609bef3' identity in user map. Using original identity '62da8a127654479e0609bef3'.
[E][15:53:40] Error mapping field 'Custom.CycleStart' on item 'TDT-46'.
[System.InvalidCastException] System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.String'.
   at JiraExport.JiraMapper.<>c__DisplayClass18_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r): 
   at JiraExport.JiraMapper.<>c__DisplayClass18_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)
[E][15:53:40] Error mapping field 'Custom.CycleFinish' on item 'TDT-46'.
[System.InvalidCastException] System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.String'.
   at JiraExport.JiraMapper.<>c__DisplayClass18_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r): 
   at JiraExport.JiraMapper.<>c__DisplayClass18_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r).
[I][15:53:40] Export complete. Exported 1 items (2 errors, 3 warnings) in 00:00:07.

Configuration for date and time fields are as below
 {

        "source": "Customfield_10077",

        "target": "Custom.CycleStart"

      },

      {

        "source": "Customfield_10078",

        "target": "Custom.CycleFinish"

      },


Configuration for Affects version and fix versions are as below
{

        "source": "fixVersion",

        "target": "Custom.FixVersions"
      },

      {

        "source": "affectedVersion",

        "target": "Custom.AffectsVersions"
      },

**Comment by Alexander-Hjelm** [comment]
Try adding "type": "datetime" to your mapping?
Try adding "source-type": "id" to your mapping?

**Comment by ViswaMohan88** [comment]
It worked Alex. Thanks a lot.
Can you please help on how to import fix versions and Affects version.
And if you see the log above, It is showing that the user is not public in jira. and it is copying some ID instead of Name

Regards
Viswa Mohan

**Comment by Alexander-Hjelm** [comment]
What are the contents of your user map? You should set it up smth like this:
```
JiraAccountID=Some.AzureDevOpsUser@domain.com
```

For fix-version, See: https://github.com/solidify/jira-azuredevops-migrator/issues/217

Again, check the docs and search the old issues before asking. Probably you will find the right answer without having to wait for me :)

**Comment by ViswaMohan88** [comment]
It worked Alex. Thanks a lot.
Sure, from next time i will look for the old issues before posting it here.

**Comment by Alexander-Hjelm** [comment]
Great! :) Closing
