### ISSUE TITLE
Time estimates mapping

### ISSUE THREAD

**Issue by ViswaMohan88** [solidify/jira-azuredevops-migrator#521]
Hi Team,

I am trying to map Original Estimate, Time Remaining and Time spent to ADO.
Unfortunately,  Original Estimate and Time Spent are converting into Seconds instead of Hours. Time Remaining is copying as it is in hours.
I tried looking for a solution in the previous questions but i did not found anything related to this.
Please help to resolve this issue.

**Comment by Alexander-Hjelm** [comment]
What mapper are you using for each field?

Check the all the fields are of the same type, both in JIRA and ADO?

You can always use the Work Items - Update API to correct the data post-migration: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/update?view=azure-devops-rest-6.0

**Comment by ViswaMohan88** [comment]
@Alexander-Hjelm Please find the below Mappers and Json output.

Mapping

	{
	"source": "aggregatetimeoriginalestimate",
	"target": "Microsoft.VSTS.Scheduling.OriginalEstimate",
    "mapper": "MapOriginalEstimate",
	},    
    {
	"source": "timeEstimate",
	"target": "Microsoft.VSTS.Scheduling.RemainingWork",
    "mapper": "MapRemainingWork",
	},    
    {
	"source": "TimeSpent",
	"target": "Microsoft.VSTS.Scheduling.CompletedWork",
    "mapper": "MapCompletedWork",
	},

Json Output


{          
"ReferenceName": "Microsoft.VSTS.Scheduling.OriginalEstimate",          
"Value": "36000"        
},

{          
"ReferenceName": "Microsoft.VSTS.Scheduling.RemainingWork",          
"Value": 1.5        
},        
{          
"ReferenceName": "Microsoft.VSTS.Scheduling.CompletedWork",          
"Value": "30600"        
}

The actual values should be like 26.5H, 1.5H and 25H

**Comment by Alexander-Hjelm** [comment]
"MapOriginalEstimate" and "MapCompletedWork" are not valid mappers afaik, unless you wrote them yourself?

Try MapRemainingWork for all 3?

See https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#mappers for the available mappers out of the box

**Comment by ViswaMohan88** [comment]
It is working fine if we map everything to MapRemainingWork Alex. Thank you.
And if we have two different sprints for 2 tickets in jira, only one sprint is getting mapped and the other is mapping under base iteration. can you please help me how to over come this.

**Comment by Alexander-Hjelm** [comment]
Area/Iteration paths can be defaulted to a specific value when they don't exist in the target project.

Make sure the sprint field is set correctly in the config file, e.g.: `"sprint-field": "Sprint"`

And check your sprint mapping, e.g.:

```
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
```

**Comment by ViswaMohan88** [comment]
Mapping is correctly mentioned as suggested. And Base iteration path is also mentioned which is already available in the target project.

ex: My project name is Viswa.
and my iteration path is Reddy which was already created in the target location.

**Comment by ViswaMohan88** [comment]
@Alexander-Hjelm it is working fine now. you close this request.
Thank you.

And will this migration work in Linux?

**Comment by Alexander-Hjelm** [comment]
Not quite sure what you mean? You can try to build the tool yourself with the dotnet SDK on linux, but this is officially unsupported. :)

**Comment by Alexander-Hjelm** [comment]
For information on how to migrate the work log, including timespent and timeestimate fields, see the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#6-how-to-migrate-the-work-log-time-spent-remaining-estimate-fields
