### ISSUE TITLE
Is it possible to map Labels and Components as tags using the migrator tool?

### ISSUE THREAD

**Issue by tlbonds2** [solidify/jira-azuredevops-migrator#529]
**Describe the bug**
Currently we are trying to map labels and component names as tags in the AzDO work items.  Is this possible using the following json mappings?:
{
"source": "labels",
"target": "System.Tags",
"mapper": "MapTags"
},
{
  "source": "Component",
  "target": "System.Tags",
  "mapper": "MapTags"
}

When we try this we get the following warnings?
[W][10:48:28] Ignoring target mapping with key: 'System.Tags', because it is already configured.

**To Reproduce**
1. Configure the json with the above source/target/mapper.
2. Run the export

**Expected behavior**
Labels and Component names get mapped as tags

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Comment by Alexander-Hjelm** [comment]
Good guess! But sadly no, today we don't support complex mappings. You can only map each field once.

If neccessary, you can always script an ADO Rest API solution yourself, that goes over all Work Items in the target project and adds the Component and Labels fields as tags, and run it post-migration.

See the Get and Update endpoints here: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/
