### ISSUE TITLE
Improve export performance

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#533]
**Is your feature request related to a problem? Please describe.**
For my current customer the export and import process is currently taking too much time. I've looked at what the export is doing and noticed it is spending the bulk of it's time in [JiraProvider.GetCustomId(string propertyName)](https://github.com/solidify/jira-azuredevops-migrator/blob/b53403bcf4e7eaa39a26ea79a0ea073dab12ec62/src/WorkItemMigrator/JiraExport/JiraProvider.cs#L405). There may be two separate problems here.

First, the method is called very often. This seems to originate from the JiraMapper where it sets a lamda expression [here ](https://github.com/solidify/jira-azuredevops-migrator/blob/b53403bcf4e7eaa39a26ea79a0ea073dab12ec62/src/WorkItemMigrator/JiraExport/JiraMapper.cs#L111)to call GetCustomId for a lot of fields in every jira issue. This may or may not be desired functionality.

Second, this function (for the number of times that it is called) is too slow because it calls a Jira fields API for every time it is called. There are no parameters given and I would not expect the response of the fields-api to change during a migration. A single query would be sufficient.

**Describe the solution you'd like**
I have currently worked around this by using a cache and calling the fields-api only on the first call. This change has cut the total export time in half. I will share a draft PR with this code. Perhaps you can share your thoughts on this?

**Comment by Alexander-Hjelm** [comment]
Great idea! :)

It should be as simple as implementing a cache in the same way as for UserEmail, something like this:

```csharp
readonly Dictionary<string, string> _propertyCustomIdCache = new Dictionary<string, string>();
```

and then get the cached property id with:

```csharp
if (_propertyCustomIdCache.TryGetValue(propertyName, out string propertyCustomId))
{
    return propertyCustomId;
}
```

Please base your draft PR on the `master` branch, since it has a lot of refactoring since the v2.3.117 release. This will make merging a lot easier :)

**Comment by Alexander-Hjelm** [comment]
PR merged :)
