### ISSUE TITLE
Export Command Returning System.InvalidOperationException: Response Status Code: 500

### ISSUE THREAD

**Issue by kkagwade** [solidify/jira-azuredevops-migrator#535]
Hi,
I am trying to Migrate jira FSC project to Azure DevOps where I am facing issue while exporting data from jira, using command
jira-export -u user -p pwd --url https://xxxx/projects/ --config config-scrum.json --force

The config file for this is,
[config-scrum.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9532434/config-scrum.txt)

when I am running command I am getting error,
[I][20:34:53] Connecting to Jira...
[I][20:34:53] Retrieving Jira fields...
[E][20:34:54] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 500. Response Content: <html>
<head><title>JIRA &mdash; Internal Server Error</title>
<meta name="decorator" content="none"/>
</head><body>
<h1>JIRA &mdash; Internal Server Error</h1>
<p>Error reference: 17d2d68b-d5f7-414e-aecd-64e6680334ee</p>
<p>Unable to render full error details at this time.
Please consult the error logs for more information.</p> ...

check the attachment for complete logs,
[jira-export-log-220908-211525.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9532440/jira-export-log-220908-211525.txt)

Kindly guide to solve this problem

**Comment by Alexander-Hjelm** [comment]
Hi @kkagwade! :)

Please read through and follow our Getting Started (https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md) and Config file (https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md) documentation if you haven't already. Usually you can find mosty common questions answered here already :)

Are we talking about JIRA Server or JIRA Cloud?

Some immediate points I noticed (you can also find these answers in the docs):

- The --url parameter should be the base path to your JIRA instance (e.g. https://solidifydemo.atlassian.net)
- The source project name in your config file should be the the **Short name** or **Key** of your project, not the full project name (this also goes for the query).

**Comment by kkagwade** [comment]
I am using jira Server.
When I use Jira url with my creds, I am getting Unauthorized (401).
For our Jira server we have Multifactor Authentication, is this the cause of getting 401?

I am sharing logs .
[jira-export-log-220909-113154.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9532728/jira-export-log-220909-113154.txt)

**Comment by Alexander-Hjelm** [comment]
Make sure you are using a JIRA API token for the -p parameter :)

**Comment by kkagwade** [comment]
I am using API token still I am getting the same issue -Unauthorized (401).
[jira-export-log-220909-114010.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9532794/jira-export-log-220909-114010.txt)

**Comment by Alexander-Hjelm** [comment]
Shouldn't matter. And -u is your full email?

You can make REST API calls using username and the API token generated by the app. That will bypass the MFA.

Can you try a bsaic REST call via Postman, python, powershell, or something like that, to verify that you have the proper access?

Try for instance this basic python script to get all issue fields (add your own email, api token and jira url):

```python
import requests
from requests.auth import HTTPBasicAuth
import json

# Config
url = "https://solidifydemo.atlassian.net"
email = "alexander.hjelm@solidify.dev"
api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# End config

api = url + "/rest/api/3/field"
auth = HTTPBasicAuth(email, api_key)
headers = {
   "Accept": "application/json"
}

response = requests.request(
   "GET",
   api,
   headers=headers,
   auth=auth
)

print(response.text)
```

**Comment by kkagwade** [comment]
Hi,
I have created personal access token using my Jira profile because we have separate FCS team to provide us Jira which is not complete Jira Server.
With this API key If I trying to login with API key is returning success, But with basic Auth I am getting 401. Refer images in attachment.
![API_Key_Img](https://user-images.githubusercontent.com/113122333/189292445-7a427a84-a958-454c-89e6-6630158a221f.JPG)
![Basic_Auth_Img](https://user-images.githubusercontent.com/113122333/189292457-8bcbf36e-080d-4a7d-b8c9-a7da1e689e67.JPG)

If it is Jira Cloud instead of jira server then what will be difference?

**Comment by Alexander-Hjelm** [comment]
Ok! In that case you will need to go through the JIRA support. If your authentication scheme is not set up to allow connections to the Rest API, then you will not be able to use our tool, and we cannot help any further :)
________________________________
