### ISSUE TITLE
WI Import errors TF400324

### ISSUE THREAD

**Issue by vpordis** [solidify/jira-azuredevops-migrator#536]
![image](https://user-images.githubusercontent.com/113185174/189362548-c4d82eaf-d6ea-45b7-bc88-47d44d458b9c.png)

Running into issue on import to On-premise Azure DevOps Server 2020 1.2.  Import appears to be working then crashes when trying. Has anyone seen this yet?

**Comment by Alexander-Hjelm** [comment]
Typical issue with proxy authentication, or if you are unable to establish a connection via the shell to your ADO Server instance. You will have to debug your connection, and the team cannot help you here sadly :)

**Comment by vpordis** [comment]
Thanks
