### ISSUE TITLE
Downloads from Jira are broken

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#548]
**Describe the bug**
Attachment downloads from Jira are broken when using the master branch.

All files are 1kb and contain a server error:
`<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Invalid URI: noSlash</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class="line" /><h3>Apache Tomcat</h3></body></html>`
There are no errors or warnings in the logfile.

**To Reproduce**
Run the Jira export against a Jira server for an issue that contains an attachment

**Expected behavior**
Correctly downloaded attachment

I suspect a similar problem is happening here https://github.com/solidify/jira-azuredevops-migrator/issues/510#issuecomment-1219751730 (uploaded file size is 0kb).

For me it is fixed when I remove this line: https://github.com/solidify/jira-azuredevops-migrator/blob/a5f8c67757b40a372feafc398794b9d6a9e92cde/src/WorkItemMigrator/JiraExport/JiraProvider.cs#L150

**Comment by Alexander-Hjelm** [comment]
Ok! Will investigate next week :)

**Comment by Alexander-Hjelm** [comment]
Needs to be fixed ahead of the 3.0 release

**Comment by Alexander-Hjelm** [comment]
The file contents seems to be an html error page, not the actual file:

```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Oops, you&#39;ve found a dead link. - JIRA</title><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'><script src='/static-assets/metal-all.js'></script><meta name="decorator" content="none" /></head><body class=" error-page error404"><script type="text/javascript">document.body.className += " js-enabled";</script><div id="page"><header id="header" role="banner"></header><!-- #header --><section id="content" role="main"><div class="aui-page-panel"><div class="aui-page-panel-inner"><section class="aui-page-panel-content lowerContent"><div id="error-state"><span class="error-type"></span><h1>Oops, you&#39;ve found a dead link.</h1><ul><li>Go back to the <a href="javascript:window.history.back()">previous page</a></li><li>Go to the <a href="/secure/MyJiraHome.jspa">Home Page</a></li></ul></div></section><!-- .aui-page-panel-content --></div><!-- .aui-page-panel-inner --></div><!-- .aui-page-panel --></section><!-- #content --><footer id="footer" role="contentinfo"><section class="footer-body">


<ul class="atlassian-footer">
    <li>
        Atlassian JIRA <a class="seo-link" href="https://www.atlassian.com/software/jira">Project Management Software</a>

                                    
                        
        <span id="footer-build-information">(v1001.0.0-SNAPSHOT#100207-<span title='1c92a42278ca3d773804961d926813b1c02585cb' data-commit-id='1c92a42278ca3d773804961d926813b1c02585cb}'>sha1:1c92a42</span>)</span>
    </li>
    <li>
        <a id="about-link" href="/secure/AboutPage.jspa">About JIRA</a>
    </li>
    <li>
                        <a id="footer-report-problem-link" href="/secure/ContactAdministrators!default.jspa">Report a problem</a>
    </li>
</ul>
<div id="footer-logo"><a href="http://www.atlassian.com/" rel="nofollow">Atlassian</a></div></section></footer><!-- #footer --></div><!-- #page --></body></html>
```

**Comment by Alexander-Hjelm** [comment]
Fixed by: https://github.com/solidify/jira-azuredevops-migrator/pull/551
