### ISSUE TITLE
Attachments are created twice

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#556]
**Describe the bug**
When an attachment is added in a revision is it saved on [line 114](https://github.com/solidify/jira-azuredevops-migrator/blob/08d5ff8f14d4d02f40a7082ae0b5eac027a17bc2/src/WorkItemMigrator/WorkItemImport/Agent.cs#L114).

However if the description is updated in CorrectDescription, the workitem is saved again on [line 129](https://github.com/solidify/jira-azuredevops-migrator/blob/08d5ff8f14d4d02f40a7082ae0b5eac027a17bc2/src/WorkItemMigrator/WorkItemImport/Agent.cs#L129)

Because the saved workitem was discarded on line 114, the attachment still has a WorkItemRelation with a "filePath" attribute and it will be added again, with the same name.

**Expected behavior**
Attachments should not be added twice

**Suggested fix**
If workitem variable is updated with the result of the "SaveWorkItem" method the problem should be resolved.

**Additional context**
This bug is possibly rooted in the Jira Export. For the best result the "description" field is "MappedRendered" here so the the HTML transfers nicely to Azure DevOps. However, the changelog returned from API "/rest/api/2/issue/issuekey?expand=changelog" does not contain "renderedFields". Therefor no history is available for the description field and the "latest" version of the description will be exported as part of revision 0.

When this description in revision 0 is parsed by the workitem import tool, it already contains links (hyperlinks, images) to attachments that do not exist until later revisions.

**Comment by Alexander-Hjelm** [comment]
The SaveWorkItem() call on 114 will upload the attachment again, when only the Description needs to be updated

Ideally we should call the Work Item update endpoint with only the description field.

I will create a fix for this :)

**Comment by moerketh** [comment]
Also the workitem that was saved on line 114 needs to be used by the rest of the method, that line should look like this:
`wi = _witClientUtils.SaveWorkItem(rev, wi);`

Otherwise there may be a missing attachment in the CorrectDescription and CorrectComment methods. Specifically it would have a WorkItemRelation without the properties that were populated by Azure DevOps.

**Comment by Alexander-Hjelm** [comment]
Yes, good find!
________________________________
