### ISSUE TITLE
Migrated JIRA item with image in description does not display images correctly in ADO work item

### ISSUE THREAD

**Issue by omustapasa** [solidify/jira-azuredevops-migrator#562]
**Describe the bug**
When a work item from JIRA which has attachments is migrated to ADO, attachment file is created with a name (e.g: !image-20220718-075723.png) and can be seen in the attachments section only.

However on JIRA related attachment is visible as a part of the description as an image.
Currently when ADO migration is done, work item description refers to the migrated attachment e.g : !image-20220718-075723.png|width=952,height=481! however the image is not displayed.

**To Reproduce**
1. Migrate a JIRA item with an image as a part of the description to ADO
2. Open the details of related ADO ticket
3. Image is not visible in the description tab but a reference to image attachment name and size is present as text.
4. Go to attachments on ADO, attachments are there.

**Expected behavior**
With a previous version of the tool the images were visible as a part of the description by default.
I am not sure if this is a bug which is a side effect of a fix or a missing feature.

**Comment by Alexander-Hjelm** [comment]
Hi @omustapasa!

Could this be related to this issue? https://github.com/solidify/jira-azuredevops-migrator/issues/510

**Comment by omustapasa** [comment]
@Alexander-Hjelm 
Looks similar indeed.
File name is no longer the fullPath that has been fixed I assume.
In the comments I also see Imported from Jira <fullPath> which is okay.

However in the ADO text instead of the image I only see the file name with height and width.
As in  !image-20220718-075723.png|width=952,height=481!
where image-20220718-075723.png is available in the attachment tab.

I got the latest source last Friday and ran a trial and reported this bug.
As far as I am concerned displaying part of the image in the description is still not fixed.

**Comment by Alexander-Hjelm** [comment]
The **text** property of the generated comment should have the following format: 
```
"<div><img src=\"https://solidifydemo.visualstudio.com/94f1c2da-b226-4e75-b1f7-c828b6c168b4/_apis/wit/attachments/5df3bccb-f390-4aa6-a5eb-cc8053e3e12d?fileName=obama_beer_600x400-873212330.png\" alt=obama_beer_600x400-873212330.png><br> </div>"
```

**Comment by grvs08** [comment]
Having the same issue, any solution?
