### ISSUE TITLE
Epic and Parent links incorrectly show up in revision 0

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#563]
**Describe the bug**
Currently only "Issue Links" are parsed for revisions. Epic Links and Parent Child relations are not currently removed from the latest revision and thus they always show up in the initial issue (revision 0). This causes errors during import, because the target workitem of the link does not exist yet in Azure DevOps.

**To Reproduce**
1. Create a Jira Issue and save it
2. Add a Epic Link a Parent link or both
3. Export the issues with the tool
4. Notice the link is present in the revision 0 instead of the revision it was added in.

**Expected behavior**
Historical items in the issue changelog of type "Epic Link", "Parent" should be handled in JiraItem.BuildRevisions and removed from the initial revision.

It's possible for an issue to have an Epic Link and a Parent link. That would logically both translate to a "Parent-Child" relationship in Azure DevOps, I'm not sure if\how that case is currently handled.

**Comment by madkoo** [comment]
To be honest I don't follow the issue here. Can you give concrete examples?

**Comment by moerketh** [comment]
See https://github.com/solidify/jira-azuredevops-migrator/pull/564#discussion_r1004660876
