### ISSUE TITLE
Attachments get parsed as workitem links causing migration errors

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#565]
**Describe the problem**
WorkItem attachments are accidentally parsed as WorkItem Links causing the following error in the log:
`[E][18:05:00] Input string was not in a correct format.`

**To Reproduce**
1. Create and save an issue in Jira
2. Add an attachment and save
3. Create another issue in Jira
4. Add a link to the first issue
5. Export to json
6. Import to devops

**Tool version**
master

There is complex "DetectCycle" code that is parsing the WorkItemRelations present on the target (linked) workitem. However since attachments are also WorkItemRelations they should be excluded. This eventually causes the last part of the  attachment Url (a guid) to be parsed as integer by "GetRelatedWorkItemIdFromLink" and causes an exception. The exception is caught and logged by "AddAndSaveLink".

WorkItemRelations that are links have an Url that looks like: https://dev.azure.com/org/project-guid/_apis/wit/workItems/828
WorkItemRelations that are attachments have an Url that looks like: https://dev.azure.com/org/project-guid/_apis/wit/attachments/e23bbe29-8d3d-4ede-94ec-9b8ac848759b

I'll add a PR with unittest demonstrating the problem, and a suggested fix.

**Comment by Alexander-Hjelm** [comment]
Fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/577
