### ISSUE TITLE
Will the migrator create links in Azure DevOps for 'Issues in Feature' 

### ISSUE THREAD

**Issue by tlbonds2** [solidify/jira-azuredevops-migrator#569]
**Describe the problem**
Hello Team, 
We are attempting to migrate Features from Jira to Azure DevOps.  We are currently using a 3rd party Jira plugin called 'SAFe EPIC to Feature Translator for Jira'.  Within the Features there is a section called "Issues In Feature"  where you can link stories and bugs: 
![image](https://user-images.githubusercontent.com/7121218/195084807-21d55119-c0e8-4a4f-8588-87debc615ad4.png)

When we attempt to migrate the Features, the links to the stories and bugs are not being created in Azure DevOps.  Does the Solidify migration tool support this linking in Azure DevOps?

**Comment by Alexander-Hjelm** [comment]
We need more information here :)

What kind of data does the plugin generate? Regular issue links? Links will be migrated, provided that you have mapped them properly.
