### ISSUE TITLE
Workitem save fails when attempting to update readonly fields

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#572]
**Describe the problem**
An exception is thrown when updating readonly fields on the workitem save:
```
[E][13:32:42] TF401326: Invalid field status 'ReadOnly' for field 'System.BoardColumn'.
[E][13:32:42] Work Item 2792 failed to save.
```

This seems dependent on specific configuration in Azure DevOps, sometimes "System.BoardLane", "System.BoardColumn" and/or "System.BoardColumnDone" are returned but these fields are readonly and cannot be set on save.

Also see: https://stackoverflow.com/questions/58862961/azure-devops-rest-apis-for-swimlane

**To Reproduce**
1. Configure team boards in Azure DevOps
2. Make sure imported workitems become part of the team, see the error on save in the log.

**Tool version**
master

**Comment by omustapasa** [comment]
Also fixes https://github.com/solidify/jira-azuredevops-migrator/issues/568 which I have reported.

**Comment by Alexander-Hjelm** [comment]
Perfect! I probably won't have time to look at your PRs and issues this week, so will schedule some time next week :) Maybe you can incorporate your own fixes manually for now? :) @moerketh @omustapasa
