### ISSUE TITLE
Can we have new custom field similar to State field 

### ISSUE THREAD

**Issue by AmarnathReddyN** [solidify/jira-azuredevops-migrator#574]
In my Jira board there is a custom field as "Change Status" with list of values , so in config-basic.json file  already there is a Status field as default field. I tried same way using mapping below along with default status field .
        "source": "Change Status",
        "target": "Custom.Change Status",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "Approved",
              "target": "Approved"
            },
            {
              "source": "Completed",
              "target": "Completed"
            },
            {
              "source": "Pending Approval",
              "target": "Pending Approval"
            }
          ]
        }

But its not working and not showing in export.
Also I tried using MapArray but still not working.
      {
        "source": "Change Status",
        "target": "Custom.Change Status",
        "mapper": "MapArray"
      }, 

Looking for help

**Comment by Alexander-Hjelm** [comment]
Check the field name: Custom.Change Status. I'm pretty sure you cannot have spaces in field keys in ADO.

**Comment by AmarnathReddyN** [comment]
That didn't work after removing spaces as "Custom.ChangeStatus" by d way it worked with custom.refid.
By  d way what  is "source-type"  and what value  have to be mention.

**Comment by Alexander-Hjelm** [comment]
That's not my point, again:
> Check the field name: Custom.Change Status

**Comment by AmarnathReddyN** [comment]
Thanks got it.
