### ISSUE TITLE
Ability to map JIRA Versions and Components to ADO Tags

### ISSUE THREAD

**Issue by izzy32457** [solidify/jira-azuredevops-migrator#581]
**Is your feature request related to a problem? Please describe.**
I have several projects that use Versions and Components. This doesn't appear to be supported in DevOps, so an alternative could be to allow mapping these extra items to Tags.
Currently it is not possible to map multiple things to Tags (causes a duplicate mapping warning during export).

**Describe the solution you'd like**
It would be good if multiple sets of mappings could be applied to tags.

**Describe alternatives you've considered**
I have considered mapping to Areas, but it would seem I get errors as JIRA can assign multiple Versions and Components, but an area is a 1-many relationship.

**Additional context**
N/A

**Comment by Alexander-Hjelm** [comment]
For such use cases we generally recommend creating a custom placeholder field in the target WIT process model, migrating to that, and then use the bulk edit functionality in Azure DevOps queries or Rest API to migrate to the correct field. Does this solve your issue?

**Comment by izzy32457** [comment]
Also, I am wondering what API this is using to retrieve the issue details? As I will likely need to figure out how to pull the ProjectVersion property to be able to map it.

**Comment by Alexander-Hjelm** [comment]
MapArray should be your friend here. Check the docs!

We use the Jira SDK for dotnet (https://www.nuget.org/packages/Jira.SDK). It probably uses the standard REST endpoint for issues.

**Comment by izzy32457** [comment]
Thanks, managed to get it working to a custom field now.
