### ISSUE TITLE
jira item number retain on ado

### ISSUE THREAD

**Issue by csaket** [solidify/jira-azuredevops-migrator#589]
I am attempting to migrate from Jira server 8.6 to ado boards.
I have noticed that the numbering does not get retained with the migration.
Example: ABC-2460 will be mapped to 283128 on ado.

Is there a way to ensure the item will get created in ado with the same number 2460 ?

**Comment by Alexander-Hjelm** [comment]
No, and neither is this a desired functionality. Our recommendation is to map the issue ID to a custom number field in your ADO Process, for traceability. You can call it something like "Custom.ReflectedWorkItemID"

**Comment by omustapasa** [comment]
@csaket 
Alternative to what @Alexander-Hjelm is suggesting:
it is also possible to map that ABC-2460 to the Title of the ticket on ADO.
As an example the title of Azure DevOps WorkItem with ID 283128 can be:
"[ABC-2460] Original Text of the ticket on JIRA here" so it can help you on search options on Azure DevOps in multiple places (Queries, Backlog etc)

**Comment by Alexander-Hjelm** [comment]
Yes, this is the default behavior :)
________________________________

**Comment by csaket** [comment]
ok thanks, I can see the default behavior showing that.
