### ISSUE TITLE
date mapping issue

### ISSUE THREAD

**Issue by csaket** [solidify/jira-azuredevops-migrator#590]
**Describe the problem**
When attempting to map the created/createdDate fields in jira to Microsoft.VSTS.Common.CreatedDate I get cast errors.

Error mapping field 'Microsoft.VSTS.Common.CreatedDate' on item 'NCT-16343'.
[System.InvalidCastException] System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.String'.

Here is my mapping:
```
{
        "source": "created",
        "source-type": "name",
        "target": "Microsoft.VSTS.Common.CreatedDate",
        "comment": "created date"
}
```
I am using the latest code from the master branch.

**Comment by Alexander-Hjelm** [comment]
Try the following fixes first, and report back on the result:
- https://github.com/solidify/jira-azuredevops-migrator/issues/346
- https://github.com/solidify/jira-azuredevops-migrator/issues/435
- https://github.com/solidify/jira-azuredevops-migrator/issues/408

**Comment by csaket** [comment]
@Alexander-Hjelm - Is there a list somewhere of all the possible fields? It would make the mapping task easier.

**Comment by Alexander-Hjelm** [comment]
You can find a list of the basic WIT fields here: https://learn.microsoft.com/en-us/azure/devops/boards/work-items/guidance/basic-field-reference?view=azure-devops
________________________________

**Comment by csaket** [comment]
Tried:
Mapping:
```     
{
        "source": "created",
        "target": "System.CreatedDate",
        "type": "datetime"
},
```
Export log:
```[D][16:10:16]    Mapped value '10/21/2022 1:07:07 PM' to field 'System.CreatedDate'.```

Import log:
no mention

ADO item:
```
Created Date
10/28/2022 9:11 PM
```

**Comment by csaket** [comment]
does anyone have any suggestions? the created date is showing up as the date/time when the import is done

**Comment by Alexander-Hjelm** [comment]
Not sure, other than playing around with the mapping.

Did you check the old issues I sent you? And did you try all possible fixes?

See #435 for example:

> Try adding "type": "datetime" to your mapping
Try adding "source-type": "id" to your mapping
