### ISSUE TITLE
Value in Jira field is being cut off in export

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#594]
I have a field in Jira called Fixed Version. This is a Version Picker (single version) field in Jira. It seems to be cutting off some of the number upon export. For example:

The field in Jira looks like this:

Fixed Version: 2021.2.0.296

The export file looks like this:

        {
          "ReferenceName": "Custom.FixedVersion",
          "Value": "2021.2"
        },
It seems to be cutting off the .0.296?

The other odd thing with this field is in the mapping file I have to use the "source-type" of "id" for it to work. If I use the source-type "name" the field is ignored in the export.

**Comment by Alexander-Hjelm** [comment]
That's strange... I'll try to replicate on my end as soon as I have time

**Comment by Alexander-Hjelm** [comment]
Created a custom Short text field in our installation, will proceed to set up a migration

![image](https://user-images.githubusercontent.com/10683896/200588366-4cf05ae6-c2ab-4927-82e2-fe3c1c6a46ae.png)

**Comment by Alexander-Hjelm** [comment]
Created a custom version picker field in our installation. Proceeding to set up some tests

![image](https://user-images.githubusercontent.com/10683896/200589230-1e4d8406-3f4b-48da-a134-2201bde1c742.png)

**Comment by C-F-Palmer** [comment]
Hi Alexander,

I am not using a ReferenceName or Value field in my config-scrum.json file. Is this what you are referring too?

**Comment by C-F-Palmer** [comment]
Just tried with your config and got the same issue.  It only works using "id" as the source type and not "name" like the other fields. Is it a problem with the field in Jira?

**Comment by Alexander-Hjelm** [comment]
Shouldn't matter. Are you sure that your custom field is a Version Picker (single version)?

Is it possible for you to debug the tool locally? If so, try and set a breakpoint here to catch the Custom.FixVersion field, and see what the mapped value becomes: https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/RevisionUtils/FieldMapperUtils.cs#L48

**Comment by C-F-Palmer** [comment]
![image](https://user-images.githubusercontent.com/92213401/200823169-71c489f4-4477-4c02-a9c9-8449690f2cc5.png)
