### ISSUE TITLE
unable to add a entry for jira project in "query": "project = 'jiraproject" in config.json 

### ISSUE THREAD

**Issue by ravindrai** [solidify/jira-azuredevops-migrator#598]
**Describe the problem**
We are trying to migrate jira projects to azure devops , while doing that when adding a project name in the jira query we are getting the error.
**To Reproduce**

**Tool version**
 we've used: jira-azuredevops-migrator-2.3.117

**Attachments**

Please attach the following files:

- config.json
[jira-export-log-221108-123926.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9959362/jira-export-log-221108-123926.txt)

**Screenshots**
I
![image](https://user-images.githubusercontent.com/107991579/200519861-2a601100-489a-48d9-9f89-f86eb04764dc.png)

**Comment by Alexander-Hjelm** [comment]
@ravindrai, check your config file and make sure that the source-project and query contain **project key** and not the **project name**

**Comment by Alexander-Hjelm** [comment]
@ravindrai I highly recommend that you refer to our documentation. Read through our Overview at https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md to save some headache searching for answers to common problems.

**Comment by Alexander-Hjelm** [comment]
closing

**Comment by ravindrai** [comment]
Hi Alexander,

We’re trying to map source and target types in config.json, but we’re ending up in some errors could you please kindly help here.

Errors:

***@***.***


Config-agile.json: Attached as an attachment.


Could you please kindly help in resolving the issue.

Thanks & Regards
Ravindra Induri


From: Induri, Ravindra (Contractor)
Sent: 08 November 2022 15:44
To: solidify/jira-azuredevops-migrator ***@***.***>; solidify/jira-azuredevops-migrator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [solidify/jira-azuredevops-migrator] unable to add a entry for jira project in "query": "project = 'jiraproject" in config.json (Issue #598)

Hi Team,

Thanks it is working now, we’ll let you know if we’ve further issues.

Thanks & Regards
Ravindra Induri
