### ISSUE TITLE
Authentication issue on export

### ISSUE THREAD

**Issue by AssafVerona** [solidify/jira-azuredevops-migrator#599]
**Describe the problem**
I'm trying to export JIRA data, but i'm getting an error referring to "Basic authentication with passwords is deprecated".

[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Response Content: Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/

**To Reproduce**
jira-export -u user@domain.com -p PWD --url https://domain.atlassian.net --config config-agile-SF.json --force

**Tool version**
 - Version 2.3.117

**Attachments**

Please attach the following files:
I attached the config file and log from TEMP.
I can't find "jira-export-log.txt" or "wi-import-log.txt"
[config-agile-SF.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9959642/config-agile-SF.json.txt)

[jira-export-log-221108-111816.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9959628/jira-export-log-221108-111816.txt)

**Screenshots**

![Export Error](https://user-images.githubusercontent.com/117722997/200527570-c80c608c-8deb-4e68-a7db-d9d85741b2fa.jpg)

**Comment by Alexander-Hjelm** [comment]
Basic authentication is not supported by the JIRA rest API, you have to use a Jira Api token instead (generated from your user settings).

I highly recommend that you refer to our documentation. Read through our Overview at https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md before you try your hand at using the tool. The docs have answers to the most common questions :)

**Comment by AssafVerona** [comment]
Thanks Alexander.

Running the command seemed straight forward.
Your solution works, thanks.

**Comment by Alexander-Hjelm** [comment]
No worries, closing :)
