### ISSUE TITLE
Comments created under account of PAT token

### ISSUE THREAD

**Issue by VincentVerweij** [solidify/jira-azuredevops-migrator#603]
**Describe the problem**
I have cloned the repository and am on the master branch. So I have the latest version as of today.
I did export a single issue from Jira and imported it into Azure DevOps, to test the functionality.
The configuration is defined as follows:
[config-agile.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9963162/config-agile.json.txt)

I checked open/closed issues and found this one to be very similar to my case: #547
When checking the work item's `History` tab, I see the following:
![image](https://user-images.githubusercontent.com/41574930/200621003-cafeb091-9bdf-445a-9fad-90ed1f2f3257.png)
This result is the same as what was shown by @Alexander-Hjelm where the History tab shows it all properly.
To me this seems to be fine.

Now, when looking at the work item's `Details`, there is where I see the issue with the comments:
![image](https://user-images.githubusercontent.com/41574930/200621719-a0578888-265d-444d-83be-ca36c4eca267.png)

The history shows that the "MB" user has added a comment, but the comment was actually added by my account.

When checking the exported/imported JSON issue, we see this in the revision:
![image](https://user-images.githubusercontent.com/41574930/200622266-4132796f-2700-454a-a9da-4ff2d3112d1f.png)
I blurred out the user, but it is the MB user.

While debugging I see it is added to the API as one of the patch documents:
![image](https://user-images.githubusercontent.com/41574930/200622994-b928876e-77c1-4ea4-ae12-df37990c794d.png)

I have not seen in the issue mentioned above whether it is expected behaviour that the comments itself (so not the history) are created by the account behind the PAT, and not as mentioned in the history tab.

**Tool version**
- Commit 4da119b91ce8b34388521c549700e8e6dbc62eed

**Comment by Alexander-Hjelm** [comment]
@VincentVerweij, try the solution here: https://github.com/solidify/jira-azuredevops-migrator/issues/443

**Comment by omustapasa** [comment]
Hi @VincentVerweij ,

I am using the latest version from master.
I think the fix has been merged to master branch but not yet released with an official version.

If you download the latest code on your device, build and run; you should be able to have it working ;)

**Comment by Alexander-Hjelm** [comment]
OK! Good catch :)

It will be worth looking into. I'll create a separate issue for compatibility with the New Boards Hub update. Once the feature goes public, it's likely that this issue will resurface again.
