### ISSUE TITLE
State,Link,Type mapping issues in jira to azure devops migration.

### ISSUE THREAD

**Issue by ravindrai** [solidify/jira-azuredevops-migrator#604]
**Describe the problem**
We're doing Jira to Azure devops migration using solidify, while mapping the  types, states, links we're running into some issues.
**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool 2.3.117

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
[jira-export-log-221109-140153.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9969144/jira-export-log-221109-140153.txt)
[wi-import-log-221109-140548.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9969147/wi-import-log-221109-140548.txt)

Kindly help in mapping these things within the config.json file

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
See the docs for a guide on mapping fields, and a few examples: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md
