### ISSUE TITLE
Support mapping of Jira LexoRank

### ISSUE THREAD

**Issue by izzy32457** [solidify/jira-azuredevops-migrator#606]
**Is your feature request related to a problem? Please describe.**
When importing issues from Jira into WorkItems in ADO, the backlog ordering is not copied and the imported items appear in the order they were imported.
When migrating a project it should be possible to map the Jira ranking field (which is configured as a custom field for each Jira instance).
Having to manually order the backlog when there are a lot of items is very time consuming.

**Describe the solution you'd like**
For the current LexoRank field in Jira to be converted to the appropriate type for importing into ADO "Backlog Priority" or "Stack Priority" fields.

**Describe alternatives you've considered**
The only option appears to be manually updating the backlog after import. Or using a custom field to hold the LexoRank and then manually attempting to order items via Bulk Update (which I can't seem to get right).

**Additional context**
I have added a PR(#605)  for a possible feature to resolve this issue (including any warnings to enable Jira admins to fix broken LexoRank values).

**Comment by moerketh** [comment]
Awesome feature, I would really like to use it. On my side the export looks good, I got only two errors (on 1k items):
```
[W][20:26:44] Duplicate rank detected for different LexoRank values. You may need to re-balance the JIRA LexoRank. see: https://confluence.atlassian.com/adminjiraserver/managing-lexorank-938847803.html
[E][20:26:44] Error mapping field 'Microsoft.VSTS.Common.StackRank' on item 'ISSUE-21674'.
[System.ArgumentException] System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at JiraExport.FieldMapperUtils.MapLexoRank(String lexoRank) in C:\repos\jira-azuredevops-migrator\src\WorkItemMigrator\JiraExport\RevisionUtils\FieldMapperUtils.cs:line 195
   at JiraExport.JiraMapper.<>c__DisplayClass13_0`1.<IfChanged>b__0(JiraRevision r) in C:\repos\jira-azuredevops-migrator\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 356
   at JiraExport.JiraMapper.MapFields(JiraRevision r) in C:\repos\jira-azuredevops-migrator\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 277:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at JiraExport.FieldMapperUtils.MapLexoRank(String lexoRank) in C:\repos\jira-azuredevops-migrator\src\WorkItemMigrator\JiraExport\RevisionUtils\FieldMapperUtils.cs:line 195
   at JiraExport.JiraMapper.<>c__DisplayClass13_0`1.<IfChanged>b__0(JiraRevision r) in C:\repos\jira-azuredevops-migrator\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 356
   at JiraExport.JiraMapper.MapFields(JiraRevision r) in C:\repos\jira-azuredevops-migrator\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 277
```

The import also works, except that the result for my dataset is better, but not great. My dataset has the following stackranks in the export result:
```
1087964484.66296082827793
1087964484.66296082827791
1087964484.66296082825917
1087964484.66296082825916
1087964484.66296082827792
```

That's all the same to Azure DevOps, it seems to ignore everything past the 7th digit right of the decimal point.

I created a testset to reproduce this case: [export.zip](https://github.com/solidify/jira-azuredevops-migrator/files/10071062/export.zip)
By filename it has the order: ISSUE-1, ISSUE-2, ISSUE-3
By timestamp it has the order: ISSUE-1, ISSUE-3, ISSUE-2
By stackrank it has the order: ISSUE-3, ISSUE-1, ISSUE-2

The import orders by timestamp, and logs the following:
```
[I][21:54:40] Import started. Importing 3 items with 3 revisions.
[I][21:54:41] Processing 1/3 - wi '2834', jira 'ISSUE-1, rev 0'.
[I][21:54:41] Processing 2/3 - wi '2835', jira 'ISSUE-3, rev 0'.
[I][21:54:42] Processing 3/3 - wi '2836', jira 'ISSUE-2, rev 0'.
[I][21:54:42] Import complete. Imported 3 items, 3 revisions (0 errors, 1 warnings) in 00:00:06.
```

The backlog result is this:
![image](https://user-images.githubusercontent.com/1309462/203421518-f33ad301-7abb-4719-bea3-7dc32a5aa98e.png)

The query result sorted by stackrank ascending is:
![image](https://user-images.githubusercontent.com/1309462/203422030-70f0686e-00ba-46ba-ad63-86a94570bb6e.png)

The query result sorted by stackrank descending is (the same):
![image](https://user-images.githubusercontent.com/1309462/203422100-3b13e2cc-f0de-494b-acda-4f6e528c5f38.png)

Do you think it makes sense to cut off at 7 digits past the decimal point, and start throwing errors for duplicates from there? That would give me a larger but probably more realistic number of errors.

I'm on Jira Server, btw. I have not looked at Jira Rank rebalancing yet, might do that if time permits.

**Comment by izzycoding** [comment]
I believe the issue might be to do with the underlying type. I think it is supposed to be a ‘decimal’ but is calculated as a ‘double’. I could have that backwards. Not sure without looking at the code on my work laptop.

I would suggest doing the rebalance in jira, as after that you will most likely find all the decimal values become “0”. This is due to the balancing being a background process that is scheduled. In order to facilitate ordering the LexoRank is just a value half way between the item before and after where you “drop” the issue. This means in Jira world that could get exponentially long in decimal places until the next balance occurs.

I will however add some additions and your suggestions to my branch when I am back in the office tomorrow.

**Comment by izzycoding** [comment]
I also think I know where that exception is coming from and will resolve that too when back in the office.

I will likely pull in latest main branch too as apparently that has changed my branch doesn’t. 😃

**Comment by izzy32457** [comment]
Latest version of my branch now includes the precision changes and exception fix. Should be good to test again.

Btw, I am also using Jira Server for my implementation and testing, so I can say it works on that version too.
