### ISSUE TITLE
The number of exported issues is underreported

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#610]
**Describe the problem**
The export tool is underreporting the number of items it exported. It's not a big issue, but I find myself verifying the actual number of json files often. Currently it is reporting this:

```
[I][15:43:50] Processing 70/70 - 'ISSUE-10152'.
[I][15:43:50] Export complete. Exported 70 items (0 errors, 114 warnings) in 00:03:36.
```
However, because my import-config.json contains `"download-options": 7` it has actually downloaded 423 files\issues because it also successfully exported parents, epics and sub-tasks.

I would suggest reporting the actual number like this:
```
I][15:43:50] Processing 70/70 - 'ISSUE-10152'.
[I][15:43:50] Export complete. Exported 423 items (0 errors, 114 warnings) in 00:03:36.
```

That way you have both numbers in view, the number of issues selected by the query (70), and the actual number exported (423).

**Tool version**
master

**Comment by Alexander-Hjelm** [comment]
@moerketh Finally got around to merging this one. Thanks for the great contribution!
