### ISSUE TITLE
Error migrating deleted attachment

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#612]
**Describe the problem**
I'm seeing multiple attachment warnings\errors during export and import:

During export:
```
[W][19:42:54] Cannot find info for attachment '86152', skipping. Reason 'Response Content: {"errorMessages":["The attachment with id '86152' does not exist"],"errors":{}}'.
```

Now a remove change exists for an attachment that never got added:
```
{
      "Author": "someauthor",
      "Time": "2021-02-03T09:26:15.327+01:00",
      "Index": 32,
      "Fields": [],
      "Links": [],
      "Attachments": [
        {
          "Change": 1,
          "FileName": null,
          "Comment": "Imported from Jira",
          "AttOriginId": "86152",
          "FilePath": null
        }
      ],
      "AttachmentReferences": true
    },
```

During import this throws an error:
```
[E][20:00:21] Could not find migrated attachment '[Removed] 86152/'.
[W][20:00:21] ''ISSUE-22170', rev 12' - not all changes were saved.
[W][20:00:21] Skipping saving attachment 86152, since that attachment was not found.
```

This happens when:
An attachment has been added on the issue and has been removed later. This means the attachment is not present on the 'latest' version of the issue, and thus cannot be downloaded. The result is a warning on export (this is fine with me) and an error plus warnings on import. I would prefer the import to be free of errors that I cannot fix.

Since this case cannot be solved by the migration tool (the attachment is deleted and can only possibly be recovered from the filesystem on the Jira server or from back-up, see: https://confluence.atlassian.com/jirakb/how-to-restore-a-single-attachment-to-an-issue-608731471.html My suggestion is to not try to migrate attachments that are not currently present on the issue.

The same is true for Jira Cloud. An uploaded attachment gets a URL like https://someaccount.atlassian.net/2aea5cdc-96c2-46c8-8a15-4a4b9558cc25 after deleting it from the issue, the link immediately goes dead.

**To Reproduce**
1. Add an issue and save
2. Add an attachment and save
3. Remove the attachment and save
4. See error during migration

**Tool version**
master

**Comment by Alexander-Hjelm** [comment]
I'll look at your PR as soon as i have time after the upcoming 3.0 release :)

**Comment by Alexander-Hjelm** [comment]
The same issue happens for SCRUM-13 in https://solidifydemo.atlassian.net/jira/software/c/projects/SCRUM

![image](https://user-images.githubusercontent.com/10683896/201897829-9c21ed9e-5281-4ceb-aeee-d8b3a2730bd1.png)

![image](https://user-images.githubusercontent.com/10683896/201897739-3cbfffbf-4436-4d01-af80-f3d5b72ef492.png)

TODO for @Alexander-Hjelm: reproduce the issue in AGILEDEMO so that the integration tests catch it, then validate https://github.com/solidify/jira-azuredevops-migrator/pull/613

**Comment by Alexander-Hjelm** [comment]
PR already merged, closing
