### ISSUE TITLE
Work items dates is set to date/time when tool runs

### ISSUE THREAD

**Issue by VincentVerweij** [solidify/jira-azuredevops-migrator#614]
**Describe the problem**
Tool creates work item with created datetime set to now instead of what is in the JSON's Time field. Same goes for the history that also contains `Just Now`.

In one of the JSON files I see a `Time` with value 2022-07-25T12:29:12.436+02:00
But when the tool executes, I see this reflected nowhere in the work item.

Is this expected behavior?

I was looking in the issues here, but I don't find anyone complaining about this.  
So might be that something is wrong at my side, not sure what though.

I have a colleague who is using [nkdAgility](https://github.com/nkdAgility/azure-devops-migration-tools) for a migration from TFS to DevOps, and in there all the datetimes are properly migrated.  
The difference I see between that tool and this one, is that nkgAgility is using the TFS SDKs for some things, and this tool is using the Azure DevOps REST API with patch documents.

*UPDATE: I did not check the tool thoroughly enough, but you guys also use the SDKs in the backend.*

**Tool version**
- Direct pull from master branch (as of this morning)

**Comment by Alexander-Hjelm** [comment]
This is intended behavior. ADO does not let you modify the `System.ChangedDate` work item field from the REST API, AFAIK. And even if you somehow could through some hacky solution, it must be larger than the CreatedDate of the work item, so we run into the problem that we cannot replay history with accuracy to the date and time of the issue changes :)

**Comment by ravindrai** [comment]
Hi @VincentVerweij ,

Could you please kindly help us here in the code change that you've made, even we're facing the same issue.

Would be helpful for us , because it is a blocker for our migration activity.

**Comment by ravindrai** [comment]
Hi Vincent,

Thanks for the response.

Could you please ping your fork URL so that we can fork the code which is working for you.

Thanks & Regards
Ravindra Induri
Adv Leave Notification: Dec 23rd  - Dec 29th

**Comment by ShellyNoll** [comment]
@VincentVerweij I also have this issue, so I updated the code to set the created by and created date on the POST that creates the work item, but I haven't figured out how to make the comment history reflect the correct dates. Do you have any hints on how to make that part work?

**Comment by ShellyNoll** [comment]
@VincentVerweij Thank you so much!!! Using your changes my comments are being recorded at the correct dates, but I do have some that are getting an error from Azure DevOps on import now. It seems to be a time zone issue - the error is that the dates must be increasing with each revision. For most of the work item revisions, the changed date is being sent with the offset (like 2022-08-05T10:18:27.801-04:00), but some are randomly being set to UTC and not converted correctly for my offset (so it's sending something like 2022-08-05T12:18:37.33Z when it should actually be 2022-08-05T10:18:37.33-4:00). I think this is occurring when additional milliseconds are being added to the date, but I'm having trouble narrowing down where exactly this is happening.

I appreciate your work on this. It really saved me some time.

**Comment by Alexander-Hjelm** [comment]
Some of our users have previously issues when the timezone setting differs between their ADO and JIRA instances. Long shot, but maybe this could be related? :)

// Alexander
________________________________

**Comment by ShellyNoll** [comment]
@VincentVerweij @Alexander-Hjelm @ravindrai I figured out my problem. The issue I saw was being caused by the date logic in NextValidDeltaRev in the RevisionUtility. In my case, the times of the revisions I receive from the JIRA API are in local time but the changed dates coming back from the Azure DevOps API are UTC. Because of that, there were some cases where my instance of rev.Time was in UTC while the wiItem.Revisions[].Time was local. The call to RevisionUtility.NextValidDeltaRev was not returning the expected value if my 2 dates were different kinds. I added a call ToUniversalTime when calling that method and now all of my JIRA items import correctly.

**Comment by Alexander-Hjelm** [comment]
Cool! Can you raise a PR when you have tested your solution and you think it works well enough? Will the datetimes be adjusted for the Jira instance’s time zone? Or will all times be in UTC?
________________________________

**Comment by ShellyNoll** [comment]
@VincentVerweij In WitClientUtils.CorrectImagePath, I set lines 576 and 578 to convert the dates passed into RevisionUtility.NextValidDeltaRev to UTC like this:
`                if (wiItem.Revisions.Count > rev.Index + 1)
                    changedDate = RevisionUtility.NextValidDeltaRev(rev.Time.ToUniversalTime(), wiItem.Revisions[rev.Index + 1].Time.ToUniversalTime());
                else
                    changedDate = RevisionUtility.NextValidDeltaRev(rev.Time.ToUniversalTime());`

I suppose this change could be made in RevisionUtility.NextValidDeltaRev instead, but this did the trick and required a less extensive change.

I think I can commit this change to your pull request if you want? Or at least I can try.
