### ISSUE TITLE
Detected unicode characters, removed.  (perhaps not a migration file?)

### ISSUE THREAD

**Issue by omustapasa** [solidify/jira-azuredevops-migrator#619]
@Alexander-Hjelm  @madkoo
I see 2 years ago [this ](https://github.com/solidify/jira-azuredevops-migrator/issues/227) was an open ticket and closed but this is still an issue with the master branch.

**To Reproduce**
When exported json file has unicode characters which are longer than 4 characters, source code does not match the string to replace hence migration is not completed.

**Tool version**
 - Latest master

**Description**

I checked the source code and see that there's a regex to clean up such unicode before the JSON is parsed and converted into a WorkItem object however checking my own import log, I see there are exported files which have failed due to having some unicode being escaped which does not match the source code.

`serialized = Regex.Replace(serialized, @"\\u[0-F]{4}", "");`
only seeks for values like "\u2026" however a few of my recent items (bugs including stacktrace) has values like "\u00602" hence 5 characters instead of 4.

`Exception of type \\u0027System.OutOfMemoryException\\u0027 was thrown. at System.Collections.Concurrent.ConcurrentBag\\u00601.ToArray() at System.Collections.Concurrent.ConcurrentBag\\u00601.GetEnumerator()`

You might like to update the RegexReplace string value to something with "\u[0-F]{4,5}" or "\u[0-F]{4,}"

This is also another issue if the work item description has regex included :)

**Comment by Alexander-Hjelm** [comment]
Noted! Will work on it as soon as I find the time :)
