### ISSUE TITLE
How to pass workspace path in config.json as a runtime parameter.

### ISSUE THREAD

**Issue by ravindrai** [solidify/jira-azuredevops-migrator#624]
**Describe the problem**
1.) While exporting jira issues, we've to update the workspace path every time for a new run, do we have the provision of passing the path as a runtime paramter. KIndly please suggest.

2) Can we increase the batch size to 50 , will that work while exporting the issues. 

**To Reproduce**

**Tool version**
  jira-azuredevops-migrator tool 2.3.117

**Attachments**

![image](https://user-images.githubusercontent.com/107991579/202619556-4e708656-d995-4774-8d2a-5cd263d1c1c9.png)

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
1) Not possible to pass the workspace path as an argument. You will have to script a solution yourself.

2) I suppose so. Don't see why not
