### ISSUE TITLE
The number of attachments exceeded the limit

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#626]
**Describe the problem**
Here is a fun one. The maximum amount of attachments on an issue in Jira is larger than on a workitem in Azure DevOps. When more than 100 attachments are added the following exception occurs during import:

```
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Services.Common.VssServiceException: VS403313: The number of attachments exceeded the limit. One work item should contain no more than 100 attachments.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

```

We fixed this on the Jira side. However I found this pretty late in the process.  The sooner this problem is raised the sooner it can be fixed. Possibly this should throw an error on the export. I also think this could be part of a "validation" stage before export/import. Thoughts?

Update: Link to service limits: https://learn.microsoft.com/en-us/azure/devops/user-guide/service-limits?view=azure-devops

**To Reproduce**
1. Create an issue
2. Add more then 100 attachments
3. Export using the tool (no issues here)
4. Import using the tool -> see the exception

**Tool version**
master

**Attachments**
Yes, a lot of them

**Comment by Alexander-Hjelm** [comment]
We will have to think about how to handle this case :)
