### ISSUE TITLE
MapTitle mapper makes System.Title longer than the maximum field length

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#627]
**Describe the problem**
The maximum length of the summary field in Jira is 255. The maximum length of the System.Title field in Azure DevOps is also 255. When the "MapTitle" mapper is used the title is prefixed with the Jira issuekey taking the field length beyond the maximum of 255 characters. This causes the following exception on import:
```
[E][15:39:16] TF401324: Value for field 'System.Title' is too long.
[E][15:39:16] Work Item 40989 failed to save.
```

I see a few improvements here:
* Change the default title mapper. Possibly a better default option is to add a tag
* The user should be made aware of this problem before an import exception occurs. Possibly by throwing an error on the export. I also think this could be part of a "validation" stage before export/import. 

What are your thoughts?

**To Reproduce**
1. Create an issue
2. Use the full title length of 255 characters
4. Use the MapTitle mapper for the summary field
5. Export using the tool
6. Import using the tool -> see the error

**Tool version**
master

**Comment by Alexander-Hjelm** [comment]
We should probably truncate the issue title in the title mapper. Let's say the following title:
`My super long issue title`
Becomes something like:
`[Project key] My super long issue ti...`
And then log a warning. The user will have to make a decision about what to do with these work items.

**Comment by Alexander-Hjelm** [comment]
For future reference, you can use the MapTitleWithoutKey mapper to map an issue summary without inserting the issue key :)
