### ISSUE TITLE
Migrate JIRA WIKI to Azure DevOps WIKI

### ISSUE THREAD

**Issue by vishwanathk26071981** [solidify/jira-azuredevops-migrator#63]
Hi All,

Can we migrate JIRA WIKI to Azure DevOps WIKI using this tool? If yes, can you please help in this.
I did not find any documentation for this. It will be helpful if someone can share the documentation for the same.

**Comment by MOlausson** [comment]
Do you mean Atlassian Confluence? If so, no, we don't support that yet.

**Comment by MOlausson** [comment]
We'll have to close this, good idea but would be a Confluence and not Jira migration tool.
