### ISSUE TITLE
Getting System.NullReferenceException while importing in ADO

### ISSUE THREAD

**Issue by harrydmaina** [solidify/jira-azuredevops-migrator#634]
I am facing null reference error while importing to Jira.

[E][23:10:41] Failed to import 'DBA2-1278/-1, 7'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[E][23:10:41] Error when creating new Work item: One or more errors occurred.

We are using agile inherit process in ADO with custom fields.
Please find attached import, export log and config file.

Please let me know the correct steps to fix this.

**Tool version**
 - Version of the jira-azuredevops-migrator tool [jira-azuredevops-migrator-3.0.54]

**Attachments**

Please attach the following files:

- config.json
[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10088587/config.txt)

- jira-export-log.txt
- [jira-export-log-221124-194100.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10091685/jira-export-log-221124-194100.txt)

- wi-import-log.txt
- [wi-import-log-221124-203352.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10091686/wi-import-log-221124-203352.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
@harrydmaina, hard to say without a stacktrace, but definitely a bug.

Do you have the possibility of building the tool locally from source code? Then you could set up your migration job in the debugger and find out where in the code the exception is raised.

Labeling as bug

**Comment by DaceZv** [comment]
@harrydmaina Getting the same on import, Do you any luck on solving this or at least finding the cause?

**Comment by zxjon22** [comment]
Just come across this myself today when doing a test migration.

We're using a custom scrumm process inherited from the standard Scrumm.

When running under the debugger, this fails returning `null` causing the exception later when trying to log the newly created Work Item's details.

https://github.com/solidify/jira-azuredevops-migrator/blob/196a39c9eb77686c5dfb6a2011bc102fe7c45182/src/WorkItemMigrator/WorkItemImport/WitClient/WitClientWrapper.cs#L48

On further inspection, there are various validation errors (e.g. `Description is required`) being returned from ADO.

I worked around it by replacing `bypassRules:false` with `bypassRules:true` which allowed the skeleton Work Item to be created.

Hope that helps.

**Comment by Alexander-Hjelm** [comment]
@zxjon22. the `bypassRules` flag has been set to `true` on this PR: https://github.com/solidify/jira-azuredevops-migrator/pull/628

You can try to build the source branch and see if this resolves your issue @harrydmaina @DaceZv

**Comment by anfisrz** [comment]
I faced similar issue. We are using a custom process with mandatory fields (e.g. Description) then the placeholder creation fails and succeeding actions (resulting in null pointer exceptions as well and missing links to not created work items).
I tested with older version 2.3.117 and it worked. (bypassRules:true) in following call creating placeholder work item.
this latest version is not usable for any project with mandatory fields resp. ADO project defined with process having work items with mandatory fields.

`     wiOut = WitClient.CreateWorkItemAsync(document:patchDoc, project:TeamProject.Name, type:wiType, bypassRules:false, expand:WorkItemExpand.All).Result;`

Additionally the resulting logging of the error is giving no additional error information at all (it would be very helpful to have exception type/name and detail message or additional information):
   Logger.Log(LogLevel.Error, "Error when creating new Work item: " + e.Message);
causes logging:

> [E][11:25:42] Error when creating new Work item: **One or more errors occurred.**
> [E][11:25:42] Failed to import 'CASHMGMT-1480/-1, 0'.
> [System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
> 

I can not use for my future migration project to migrate to these custom process with the latest version. I am not able to compile/rebuild from source and this is urgent/important to me to have a solution for this.

**Comment by harrydmaina** [comment]
Hi All,

To overcome this problem. We are using different approach to fix the problem.

1. Create config file with all the system and custom field.
2. In ADO create inherit process(Agile or Scrum).**After that please don't add any custom field to any work item type**.
3. Complete import/export using tool.
4. Now you can add required custom filed in ADO for all work item(It will display the value in work item).

Note :- There may be question like how we can add target for custom filed in config file. For that before migration you can add(copy reference) and delete custom field in any other test process so at the time of actual adding you can just select from existing fields.

Let me know if it is useful or any issue you are facing.

**Comment by anfisrz** [comment]
Hi harrydmaina
this is not really useful/applicable to me as I am working in an environment where I do not have direct admin/edit rights on changing process for ADO project nor changing the process itself (e.g. field definitions etc.) on my own. I have to go thru a painful request process. so my current option is to use the old version only.

**Comment by Alexander-Hjelm** [comment]
Relabeled as support issue, as the issue is likely due to mismapping of custom fields.

You can read more about mapping custom fields in the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

In order to migrate a custom fields, you must know the field name in both JIRA and ADO (Full name, e.g. Custom.MyCustomString). You must also import into an ADO project whose Process supports the desired field.

**Comment by anfisrz** [comment]
It's a bug introduced by forcing bypassRules:false when creating the placeholder. This will not work with any process defined and mandatory fields at any time.
Please create a test case on your side with a process with mandatory fields. I did check your docu and you do not mention somewhere how to handle mandatory (custom) fields.

**Comment by Alexander-Hjelm** [comment]
@anfisrz OK! Then as I said, we are working on a fix in #628 . You can pull that branch and see if you get better results.

**Comment by anfisrz** [comment]
Thank you @Alexander-Hjelm, as mentioned, I can not compile/build the project myself so will wait for a future patch/update.

**Comment by omustapasa** [comment]
@Alexander-Hjelm I planned my migration for the long weekend and I am facing this as well.
Half of the issues are not being migrated as I use custom fields.
I am trying to revert the changes I have applied to be able to have something solid.

Pretty bad situation I am in right now.

**Comment by Alexander-Hjelm** [comment]
Revert to the last stable version (2.x) if neccessary
________________________________
