### ISSUE TITLE
Work items with title "[Placeholder Name]" created due to large attachments

### ISSUE THREAD

**Issue by bameije** [solidify/jira-azuredevops-migrator#638]
In our project (>500 Work Items), we have about 60 'large' attachments >4MB.
They are exported from Jira Cloud properly, but fail to be imported in DevOps Server as the upload limit is 4MB:
`TF237082: The file you are trying to upload exceeds the supported file upload size (4.000 MB(s)). Instead of uploading the file, add the file to version control or to the team project web site, and then link the file to the work item.`

The work items to which these large attachments are linked are not imported correctly: for each such Jira-issue, 2 work items are created in DevOps:
- one work item without content at all, title "[Placeholder Name]"
- one work item with the desired content, but title is also "[Placeholder Name]", and description is missing (it seems like the revision that created the work item is not imported)

When I remove the reference to the large attachment from the work item's json file, the import process is working properly.

Double issue:
- first: if I don't care about the large attachments, the migrator should be able to import the issue properly while ignoring the large attachment error.
- second: for people who do care about the large attachments, the migrator might list the large attachments and allow to link to them after uploading them using the ways described in DevOps' error message.

Version: Work Item Importer v3.0.54
I can attach a some files to replicate the issue upon request.
Thanks.

**Comment by Alexander-Hjelm** [comment]
For TFS Servver you should edit the maximum attachment upload size :)

**Comment by bameije** [comment]
Thanks for your response. That's a valid solution if the TFS Server settings can be modified.
But still I think it's a bug that the importer makes a mess when this is the case.

I looked around in the code and found the **issue**:
When the upload-attachment error is thrown, all remaining code in Agent.ImportRevision() is skipped. Because the attachments are in the first revision of the workItem, the created workItem is left empty. Importing the following revisions triggers another workItem to be created, but this will not contain title, description and all other fields that were defined only in the first revision.

**Solution**:
I added a try-catch around the import of attachments, and now the importer imports the workItems smoothly, just skipping the attachments that were blocked by the TFS server.

My **code**, feel free to ignore or add to the application: (Note that this is based on PR[#628](https://github.com/solidify/jira-azuredevops-migrator/pull/628))
![image](https://user-images.githubusercontent.com/18261782/204523566-addbfbbd-da49-48c7-8b1e-005a72d8f5a3.png)

**Comment by Alexander-Hjelm** [comment]
Yep! We should implement this on the main branch as well. Could you create a PR with your changes into the main branch? :)

**Comment by bameije** [comment]
Done, see PR #640

**Comment by Alexander-Hjelm** [comment]
Cool! I’ll take a look as soon as I have time. Likely I will merge it into a feature branch of thw main repo first to run some tests :)
________________________________
