### ISSUE TITLE
Import with original time to DevOps

### ISSUE THREAD

**Issue by bameije** [solidify/jira-azuredevops-migrator#639]
Importing the generated json file into DevOps using the Work Item Importer v3.0.54.
All our issues and revisions are imported with time created == the time of the conversion (=now), instead of the time when they were originally created in Jira.

From documentation I had understood that the original time will be preserved in DevOps, but I can't find where I read that so maybe I made that up.

Can you please inform what's the designed behaveour?
If the time in DevOps should reflect the original times from Jira, then I have an issue/bug. I that case I will upload files to replicated. The json files do contain the original times from Jira, so if it is an issue, it will be on the Importer side of things (or my configuration of course).

Thanks.

**Comment by Alexander-Hjelm** [comment]
Try this PR and see if it has the change you requested: https://github.com/solidify/jira-azuredevops-migrator/pull/628

**Comment by bameije** [comment]
Yes, that's exactly what I needed, and it works as expected.
It uses original time when importing, + extra bonus: the "created by" field now contains the original user as well.

Thanks for referencing the PR, thumbs up to have it merged :)
