### ISSUE TITLE
Replicate backlog priority in Azure Devops

### ISSUE THREAD

**Issue by Chintunie** [solidify/jira-azuredevops-migrator#64]
Hi,

Is it possible for the work items in Azure DevOps (in backlogs) to appear in the same order as in JIRA.
Currently, the open work items in Azure DevOps are are ordered based on the creation date in JIRA.

**Comment by MOlausson** [comment]
Good point and that makes sense. We'll investigate.

**Comment by dan-miller** [comment]
Is this planned to be done anytime in the near future? We'd like to do a heavy migration from Jira to ADO, but this is a big blocker for my organization.

**Comment by MOlausson** [comment]
We're planning for an update in a couple of weeks, I'll investigate this tomorrow and see if we can get this done soon(ish). I assume you are using the default rank to order the backlog in Jira and have that come over to Azure DevOps?

**Comment by dan-miller** [comment]
Correct. What seems to happen is that the ADO tickets are ordered by the Jira ticket # (i.e. by created date, ascending)

**Comment by MOlausson** [comment]
I took a look at this and it looks pretty straight-forward to convert the string value the rank has in Jira (using a form of lexicographical ordering) to a number. We could then just use that value as the backlog ordering and the Jira order will be preserved. It may however conflict with other Azure DevOps items in the backlog when existing and new items are merged in the backlog list. But I think that's ok in this scenario, you can easily import the Jira issues to an isolated area path and then figure out how to merge with existing items.

**Comment by dan-miller** [comment]
Can you elaborate a bit more on the conflicts? When we've used this migrator, we always put the migrated items into an isolated area path. If I'm interpreting what you're saying correctly, that means we shouldn't have too much to worry about.

**Comment by MOlausson** [comment]
Exactly, if you use an isolated area then it would work just right. If not then existing items may potentially have the same rank or new items may get inserted between existing items which for a large backlog will be less ideal I suppose. But I don't think that's a particularly big problem and we would make this an opt-in behavior in the tool so you could choose if you want the original order or not. Makes sense?

**Comment by dan-miller** [comment]
Sounds good to me.

**Comment by rhundhausen** [comment]
Did this get implemented? Is there a setting in config.json to enable it?

**Comment by rhundhausen** [comment]
Maybe this is too simplistic, but I've started adding `ORDER BY Rank ASC` to my JQL statements and that seems to have solved this.

  "query": "project = FOO **ORDER BY Rank ASC**",
