### ISSUE TITLE
Unable to map issue type link "metionded in" from Jira to Azure DevOps

### ISSUE THREAD

**Issue by Prathush** [solidify/jira-azuredevops-migrator#642]
Hi Team,

we. are using latest version of migration tool. In our Jira stories, we do have remote links mentioned in Issue Links section. However, unable to map them to Azure DevOps board. Please let me know if there is a way to include them.

**Comment by Alexander-Hjelm** [comment]
@Prathush, remote links are not supported today. You would have to write a solution yourself :)
