### ISSUE TITLE
Related links

### ISSUE THREAD

**Issue by jus062** [solidify/jira-azuredevops-migrator#652]
Hi,

We are still using Tool version : 2.3.117 as we experienced a lot of issues with v3.

I'm struggling to understand why related links are not coming over. The line in the log file I'm assuming indicates that the link has been added: 

- Undone link 'Added [Related ] MSUP-858->MSUP-619'. 

However, no related links are present at all after migration and there should be loads.

Also seeing this line

- Link with description 'This issue is related to MSUP-858' is either not found or this issue (MSUP-619) is not inward issue. 

I don't use Jira so not sure what an inward issue is, but are our difficulties related to bug report: https://github.com/solidify/jira-azuredevops-migrator/issues/495 and if so, is there an ETA on a fix and if not, am I missing something in the configuration.

We are on Jira Server 8.7.1 and link map in the config file has this
      {
        "source": "Related Task",
        "target": "System.LinkTypes.Related"
      },

**Comment by Alexander-Hjelm** [comment]
Shouldn't be related to #495 since this is about related links and not subtasks.

I'm wondering about this message:

> Undone link 'Added [Related ] MSUP-858->MSUP-619'.

Seems like the link has been removed sometime in the history of the JIRA issue. Is this correct?

Are the two issues in the same project or is it an external link?

**Comment by jus062** [comment]
Yes, I don't understand the Undone link message either. I don't use Jira at all, but my understanding is that none of the "Related task" and "Is related to" were removed at any point. They all have links like in the image below.

<img width="53" alt="image" src="https://user-images.githubusercontent.com/94574483/210283413-7052737e-9fcb-45ab-b2f2-b7f70c548e66.png">

They are in the same project.

**Comment by Alexander-Hjelm** [comment]
@jus062 is this issue possibly related to https://github.com/solidify/jira-azuredevops-migrator/issues/656?

**Comment by jus062** [comment]
@Alexander-Hjelm, I have just done another test and only migrated tickets that were definitely related and no related links appear in the Devops proejct.

WRT to #656 , we do see the same error.

[E][09:13:36] '[Added] MSUP-398/55607->MSUP-328/-1 [System.LinkTypes.Hierarchy-Forward]' - target work item for Jira 'MSUP-328' is not yet created in Azure DevOps/TFS.

Although not sure the two are related.

**Comment by Alexander-Hjelm** [comment]
OK!

I did a test run with the default Agile config, and as far as I can see, related links are being successfully migrated. See the below image for an example in ADO.

![image](https://user-images.githubusercontent.com/10683896/210454781-e7e30ed8-f686-4124-aa4a-9f45048131a2.png)

So it looks like you might be dealing either with an invalid config or a weird edge case.

Have you mapped the correct Jira link type?

I have the following mapper in my config:

```json
{
  "source": "Relates",
  "target": "System.LinkTypes.Related"
},
```

Otherwise, could you send screenshots of both the linked issues in Jira to assist with reproducing? Preferably also a copy of both the issues from the `rest/api/2/issue/` rest api endpoint as well, if possibly. You may obfuscate any sensitive data of course :)

**Comment by jus062** [comment]
Yes, I believe the mapping is correct.
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      }, 
We do use a custom process that is inherited from Agile, so I reran the test using the vanilla agile process, but no difference. Note that due to the sheer volume of Jira tickets, I am only testing with a handful. so the query is like this:

"query": "key in (MDME-550, MSUP-858, MDME-1154, MSUP-619)",

The first item from the quert (550) has 20 related Tasks and these are of type Sprint Backlog Item, which is mapped to User Story in Devops.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/94574483/210459126-e9ac10a2-bf4c-494b-ba4a-a184027a04aa.png">

In devops, some of the related issues have been migrated, but not linked.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/94574483/210459436-0de4afdc-43ec-4795-a665-e8ce72638ce4.png">

Not sure if this helps, but can't get you the info from the endpoint as not a dev...

**Comment by jus062** [comment]
@AlexTurff , thanks for the suggestion.
@Alexander-Hjelm , please see findings below


I have run the test several times on version 2.3.117 with the changes suggested for the config.
[I][09:28:34] Export complete. Exported 19 items (0 errors, 61 warnings) in 00:00:43.3.0.54
[I][09:57:14] Import complete. Imported 41 items, 2551 revisions (94 errors, 107 warnings) in 00:28:21.

This has partially resolved the issue but if I audit the work items, only Tasks are getting set (and they are only being related to other tasks). User Stories still have no related work item.


I have also run the test on version 3.0.54
[I][09:42:16] Export complete. Exported 19 items (0 errors, 62 warnings) in 00:00:44.
[I][10:36:42] Import complete. Imported 41 items, 2551 revisions (279 errors, 108 warnings) in 00:24:01.

Although it reports importing 41 items being imported, only 22 are present in the project and no Tasks have come over, so I cannot confirm whether the config change works in the latest version.

There were 279 errors on the import, mostly like this:

[E][10:28:36] Error when creating new Work item: One or more errors occurred.
[E][10:28:36] Failed to import 'MDME-1066/-1, 0'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): 
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)

It would appear that the items that could not be created were Tasks. I will note that this Jira project has multiple Tasks types, but they have all been mapped to Task in Devops. Not sure if that is causing any issues?

      {
        "source": "Defect Task",
        "target": "Task"
      },
      {
        "source": "Regression Task",
        "target": "Task"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }

and this

[E][10:13:17] '[Added] MSUP-398/56773->MSUP-365/-1 [System.LinkTypes.Hierarchy-Forward]' - target work item for Jira 'MSUP-365' is not yet created in Azure DevOps/TFS.

**Comment by Alexander-Hjelm** [comment]
Check my config and compare it to your. When i run the migrator with this config for an Agile-based project, everything works fine. Just in case you can identify something that is obviously wrong:

https://pastebin.com/JBT6yyz5

Otherwise, the process model in ADO looks fine? All the expected work item types are present?

**Comment by jus062** [comment]
Hi @Alexander-Hjelm 

I created a brand new project from the agile process and after reviewing your config, just note the following minor differences.

* We are on a very old version of Jira Server (8.7.1), not Jira Cloud
* Your config still has the mapping from earlier discussion
        {
          "source": "Relates",   <--- not related
          "target": "System.LinkTypes.Related"
        },
	
In the end I used both in just in case, assuming it would ignore ones that didn't match.

* We do have more card types, states and priorities mapped, but none of these cause any issues.

  "using-jira-cloud": false,
  "workspace": "C:\\Temp\\JiraExport\\", 
    "epic-link-field": "Epic Link",
    "sprint-field": "Sprint",
    "download-options": 7,
    "batch-size": 20,
    "attachment-folder": "Attachments",
    "user-mapping-file": "users.txt",
    "base-area-path": "Migrated",
    "base-iteration-path": "Migrated",
    "ignore-failed-links": true,

I reviewed one of the JSON files that I know has 19 related items and System.LinkTypes.Related does not appear anywhere in the file. I would assume that the issue is down to the mapping syntax and perhaps our version of Jira?

	  { "source": "Related", 
	    "target": "System.LinkTypes.Related" 
	  },
	  {
        "source": "Relates",
        "target": "System.LinkTypes.Related"	
	}

As an aside, this is working correctly.
	  { 
	    "source": "Cloners", 
	    "target": "System.LinkTypes.Related"
	  },

From this image, you can see the related stories and sub tasks in Jira

<img width="562" alt="image" src="https://user-images.githubusercontent.com/94574483/211676906-bc77a9ff-931a-4d19-85b5-7d7ef1abaa62.png">

and here are the correctly migrated child tasks in devops

<img width="581" alt="image" src="https://user-images.githubusercontent.com/94574483/211677166-e93037d4-fdf2-4bac-b662-301a5bbcd8f2.png">

**Comment by jus062** [comment]
I'm just going through the export log and not sure if this offers any insight. But can see loads of these messsages that reference related issues that are not being added.

	Line 43915: [D][10:16:00]    Downloaded issue: MDME-550 changelog.
	Line 43919: [D][10:16:00]    Undone link 'Added [Related ] MDME-550->**MSUP-358'.**
	Line 43920: [D][10:16:00]    Undone link 'Added [Related ] MDME-550->MSUP-623'.
	Line 43921: [D][10:16:00]    Undone link 'Added [Related ] MDME-550->MSUP-945'.
	Line 43923: [D][10:16:00]    Undone link 'Added [Related ] MDME-550->MSUP-876'.
	Line 43924: [D][10:16:00]    No link to undo for 'Added [Related ] MDME-550->MSUP-811'

When looking at the files that were downloaded as part of the export, I didn't see one for **msup-358** (I'm testing with an explicit query) so added that one in. When I re-review the log file, I now see this:

	Line 40169: [D][10:30:05]    Downloaded issue: **MSUP-358** changelog.
	Line 40172: [D][10:30:05]    Link with description 'This issue is related to MDME-550' is either not found or this issue (MSUP-358) is not inward issue.
	Line 40173: [D][10:30:05]    Undone link 'Added [Related ] MSUP-358->MSUP-1201'.
	Line 45051: [D][10:30:14]    Undone link 'Added [Related ] **MDME-550->MSUP-358'.**

Not sure if that sheds any light?

**Comment by Alexander-Hjelm** [comment]
Looks like the link types may have changed between your JIRA version and the current LTS version.

I noticed that the link type gets logged as `[Related ]`, with an extra space between "Related" and the closing bracket. Could it be that you have added a space by mistake somewhere in the config?

Otherwise, my advice would be to first review the issue via the REST API (see https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-getIssue). Check the names and values of the links, link types and relevant fields, and verify that your config is compliant.

**Comment by jus062** [comment]
Hi @Alexander-Hjelm 

No space in the config.

	  { "source": "Related", 
	    "target": "System.LinkTypes.Related" 
	  },
	  {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },

I'll have a look at the link you sent through and see what else I can find.

**Comment by jus062** [comment]
Hi @Alexander-Hjelm ,

I have made some partial progress. Your last comment gave me an idea and so I added the space into the config.
	  { "source": "Related ", 
	    "target": "System.LinkTypes.Related" 
	  },

and I now see this in the json file for the work item.

      "Links": [
        {
          "Change": 0,
          "TargetOriginId": "MSUP-756",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Related"
        }
      ],
It does appear to be picking up the correct links now, however, the related items are not being downloaded as part of the export unless I explicitly have them in the query.

Is there any way I can force the Jira export to download them as it does with the child items?

**Comment by Alexander-Hjelm** [comment]
Strange finding. Maybe the link type is misnamed in your jira organization?

You could try specifying the issue IDs directly in the `query` of your config.

Some JQL examples if you are not already familiar: https://support.atlassian.com/jira-software-cloud/docs/example-jql-queries-for-board-filters/

**Comment by jus062** [comment]
Hi, yes it would appear to be misconfigured, but at least I can get around it.

But I can confirm that related issues are not downloaded at all unless I use this function as part of the query
OR issueFunction in linkedIssuesOf('(project =

**Comment by jus062** [comment]
No, everything is in the same project.

If I extract all and use the IssueFunction, there 4.5k work items and 180k revisions. If I limit the work items returned, it is problematic to get all the related items.

**Comment by Alexander-Hjelm** [comment]
Potentially fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/1072
