### ISSUE TITLE
How to map timestamp field type in json?

### ISSUE THREAD

**Issue by prachi1902** [solidify/jira-azuredevops-migrator#653]
**Describe the problem**
A clear and concise description of what the problem/bug is.
How to map the timestamp field type in JIRA? What source type should be used in the json file for timestamp type of field?
**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
3.0.54 version I am using.
[jira-export-log-221214-150521.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10226472/jira-export-log-221214-150521.txt)
[wi-import-log-221214-150605.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10226473/wi-import-log-221214-150605.txt)

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/76516327/207562792-4d216db0-b408-425e-bd56-79e901383f65.png">
<img width="927" alt="image" src="https://user-images.githubusercontent.com/76516327/207562995-7e21be53-cbf3-46da-8de1-a31be4879e99.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/76516327/207563078-acba627b-df66-437a-93cd-46162cff5433.png">

**Comment by prachi1902** [comment]
@Alexander-Hjelm Thanks for responding. But by giving datetime as source type of JIRA for timestamp it is not working.

**Comment by prachi1902** [comment]
I am trying to migrate the field with type TimeStamp in JIRA to ADO (datetime field). @Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
@prachi1902 Have you tried with `"source-type": "name",`, or omitting `source-type`? I'm pretty sure `"source-type": "datetime",` is not implemented
