### ISSUE TITLE
Wrong EPIC link in v3.0.54

### ISSUE THREAD

**Issue by AssafVerona** [solidify/jira-azuredevops-migrator#656]
I'm testing importing JIRA to ADO and the records don't map to the EPICs correctly.
It worked in the previous version i used earlier today.

The **TargetOriginId** attribute was changed from v2.3.117 to v3.0.54.
Before under **Links** it was:
        {
          "Change": 0,
          "TargetOriginId": "AS-14",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Related"
        },
        {
          "Change": 0,
          "TargetOriginId": "AS-12",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        }

Now it is:
        {
          "Change": 0,
          "TargetOriginId": "AS-14",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Related"
        }

The EPIC reference is now at a different place, and instead of "AS-12" it states the ID.
      "Author": "xxx.com",
      "Time": "2022-12-13T15:59:41.786+02:00",
      "Index": 3,
      "Fields": [],
      "Links": [
        {
          "Change": 0,
          "TargetOriginId": "15652",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        }
If i manually change 15652 to "AS-12" it mapping is OK.

I'm using the same config file.
[config-agile.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10309702/config-agile.json.txt)

These are the exports of the same item in the old/ new versions:
[Old.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10309703/Old.json.txt)
[New.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10309704/New.json.txt)

export logs:

[jira-export-log-221227-184635.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10309708/jira-export-log-221227-184635.txt)
[jira-export-log-221227-184639.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10309710/jira-export-log-221227-184639.txt)

**Comment by AssafVerona** [comment]
Is it possible i'm missing something else ?
If i import record #2 while #1 is an epic, i get an error.
f i import record #2 while #3 is an epic, it is OK.

If i import EPIC record first and in a separate process the STORY, i get an error "'[Added] AS-15/4640->AS-12/-1 [System.LinkTypes.Hierarchy-Reverse]' - target work item for Jira 'AS-12' is not yet created in Azure DevOps/TFS." even tough "AS-12" already exists in ADO.

What is the proper way of importing records with "parent" and "epic" links ?

**Comment by Cuk3ncd** [comment]
I had the same error:
[E][08:54:12] '[Removed] B4DPBBANCA-22/7410->B4BDBBANCA-20/-1 [System.LinkTypes.Hierarchy-Reverse]' - target work item for Jira 'B4BDBBANCA-20' is not yet created in Azure DevOps/TFS
[E][08:54:12] '[Added] B4DPBBANCA-22/7410->B4BDBBANCA-20/-1 [System.LinkTypes.Hierarchy-Reverse]' - target work item for Jira 'B4BDBBANCA-20' is not yet created in Azure DevOps/TFS.

**Comment by Alexander-Hjelm** [comment]
**TargetOriginId** for Epic links are being set to issue ID instead of issue key.

Bug has been identified but not yet repoduced. We will work on a solution as soon as possible :) 

@AssafVerona, if possible, include a screenshot of the **epic issue** and the **issue with the epic link** to help with bug reproduction. Make sure that the epic link is visible.

**Comment by AssafVerona** [comment]
@Alexander-Hjelm no problem.
here are the images of the EPIC and child story.
![Epic](https://user-images.githubusercontent.com/117722997/210507312-640e3d3d-4cae-40eb-acd1-f3e80259737d.jpg)
![Child](https://user-images.githubusercontent.com/117722997/210507318-3a487ab9-4ffa-4992-927b-511fb7bb0268.jpg)

**Comment by Alexander-Hjelm** [comment]
@AssafVerona! Looks about the same as my test run. I'm able to migrate epic links without problems.

Here is an example:

![image](https://user-images.githubusercontent.com/10683896/210513967-73acaa9e-3dd0-4561-9d8c-a1a4e8cd9fd4.png)

Your config looks the same as mine with regards to the epic link field and the link mapper for Epics, so I think we can rule that out.

Has the epic link field changed name in your Jira installation? The default is "Epic Link"

**Comment by AssafVerona** [comment]
Hi,

The config i uploaded was wrong.
The "download-options" was set to 0.

You can close.

**Comment by Alexander-Hjelm** [comment]
OK, great to hear! :)
