### ISSUE TITLE
The value for field 'Activated Date' must be empty.

### ISSUE THREAD

**Issue by bientt210** [solidify/jira-azuredevops-migrator#659]
**Describe the problem**
When I run import item, I get some info log as:
[I][11:50:53] Field 'Microsoft.VSTS.Common.ActivatedDate' was null on the work item. Omitting...
[I][11:50:53] Field 'Microsoft.VSTS.Common.ActivatedBy' was null on the work item. Omitting...

On Azure Boards work items, on title show warning **The value for field 'Activated Date' must be empty.**
And I cannot do anything on this work items.

Can anyone help me how to fix this problem
Thanks you so much

**Tool version**
 - Version of the jira-azuredevops-migrator tool [3.0.54]

**Comment by Alexander-Hjelm** [comment]
Strange. This would mean that some of your workitems have the `ActivatedDate` field set to **null**, and they shouldn't be imported.

Can you check your relevant workitem .json-files and see if this is the case? If so, try and remove the ActivatedDate-fields, save the work items and run the import again.

**Comment by jus062** [comment]
I have also seen this issue and for me it came down to an incorrect mapping for a Jira state (or lane) to Azure Devops state.

It was similar to this. I originally had the Jira lane "In Review" mapped to New.

            {
              "source": "In Review",
              "target": "Active"
            },

You can get around by setting the ticket back to the New state in Devops.
