### ISSUE TITLE
AreaPath migration

### ISSUE THREAD

**Issue by ShadowXVII** [solidify/jira-azuredevops-migrator#66]
Is there any support/sample configuration for migrating Jira Components => DevOps Area Path?

**Comment by quadmig** [comment]
I don't know if this helps, but I coded mine in the config to use another field.
		{
		"source": "components",
		"target": "Custom.MigratedComponent"
		},

That said, you should be able to something like
      {
        "source": "components",
        "target": "System.AreaPath"
      },

That should work although I can't test it now because it will mess up my migration in progress.

**Comment by ShadowXVII** [comment]
Ah, I tried 

```
      {
        "source": "component",
        "target": "System.AreaPath"
      },
```

will try components :)

**Comment by ShadowXVII** [comment]
The following does work and includes the new area path. I was able to include some mapping logic to take into account the area path. 
```
      {
        "source": "components",
        "target": "System.AreaPath",
        "mapping": {
          "values": [
            {
              "source": "Jira Component Name",
              "target": "Project\\Area Path\\Component Name"
            }
          ]
        }
      },
```
