### ISSUE TITLE
Facing issue in importing tickets to Azure

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#660]
I have exported tickets of a dummy project. And using import command jira-export -u jiraaccount@some.domain -p xxxxxxx --url https://my.jira.url --config config-scrum.json --force, tried to import them. But its giving some error in cmd . 

![Capture](https://user-images.githubusercontent.com/121940137/210537323-bc942632-ae52-4ab0-9daa-45b8755d8678.PNG)

I have not altered two fields in config file: epic-link-field and sprint-field. Maybe this could be the reason for error. I don't know how from where and how to get these values from JIRA.

![Capture1](https://user-images.githubusercontent.com/121940137/210537858-6dac7bfe-5729-4b6b-b119-b5838b657355.PNG)

Only Epic is getting imported that too with no sub issues and details

![Screenshot (6)](https://user-images.githubusercontent.com/121940137/210538081-758044d6-3b5a-4100-9dd6-505b33031ec6.png)

**Comment by Alexander-Hjelm** [comment]
Epic link is by default with capital letters, like this: `Epic Link`.

But it's impossible to point the error out without more info. Please include your config file, a copy of the full log and a copy of the relevant workitem json file if possible.

**Comment by Bikrammabzone** [comment]
Hey, thanks for response. Actually, I used default values "epic-link-field": "Epic Link",
"Sprint-field": "Sprint", still getting same error. I am zipping and adding config file, log files and exported JSON tickets for your reference.
[config-scrum.zip](https://github.com/solidify/jira-azuredevops-migrator/files/10350947/config-scrum.zip)
[export logs.zip](https://github.com/solidify/jira-azuredevops-migrator/files/10350971/export.logs.zip)

**Comment by Bikrammabzone** [comment]
Facing same issue. Only epic gets imported that too with no issues and details. 
![Screenshot (14)](https://user-images.githubusercontent.com/121940137/210938398-ce6d26e0-edd4-4dff-a665-de7ea44e37c4.png)


If I add no epic in project, no issue gets imported

**Comment by Bikrammabzone** [comment]
@Alexander-Hjelm.

**Comment by Alexander-Hjelm** [comment]
Is it possible for you to debug the tool locally with Visual Studio? This could provide us with useful info on where in the code the exception is thrown

**Comment by Alexander-Hjelm** [comment]
@Bikrammabzone We've just released https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.85, where we added more logging for exceptions raised by the **workitem create** endpoint. Using this, we managed to solve a related issue that my colleague ran into.

Try it and see if you can get more details about the error. Most likely it is due to some misconfiguration on the ADO process :)
