### ISSUE TITLE
'jira-export' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by dinesh-duraisamy** [solidify/jira-azuredevops-migrator#661]
Hi All,
I am unable to run the below command in windows command prompt.
jira-export -u jiraaccount@some.domain -p xxxxxxx --url https://my.jira.url --config config-scrum.json --force

Do i need to install the **Jira CLI** or something like that.
while running from command prompt i am getting the below error, can someone please advise

c:\Temp\jira-azuredevops-migrator-3.0.54>jira-export -u jiraaccount@some.domain -p xxxxxxx --url https://my.jira.url --config config-scrum.json --force
'jira-export' is not recognized as an internal or external command,
operable program or batch file.

c:\Temp\jira-azuredevops-migrator-3.0.54>

**Comment by Alexander-Hjelm** [comment]
Try specifying the full path to the `jira-export.exe`? Check the docs and the FAQ, they usually have the answers you are looking for.
