### ISSUE TITLE
Bypass Permission change causes import exceptions

### ISSUE THREAD

**Issue by AlexTurff** [solidify/jira-azuredevops-migrator#662]
Setting the bypass rule flag to true (Merged in #628 ) results in the following error for me:
"TF401322: You don't have bypass rules permission. Please contact your collection administrator to grant this permission for enabling this action."

Setting it back to false results in the import working (but with me as the creator of all the tickets/comments). At a minimum I would suggest this needs to be a parameter so users can toggle it to get basic functionality without having to clone, edit and build. If this is required for the usernames to be recorded correctly, then it would be good if text could be added to the comments (and ticket description?) indicating the original author of the content.

I imagine this is an organization level block on my side - or is there an additional permission that needs to be granted on the access token?

The access token I am using for the import has the following permissions:
Work Items: Read, write and manage
User Profile: Read and write

**Tool version**
I'm using a copy I cloned at the start of this week (638d32a083c6dd542bf7a703ec6e46f892050871)

**Comment by Alexander-Hjelm** [comment]
You will need the **Bypass rules on work item updates ** permission on the Project level. This permission is not included for any groups or users by default, so you might have to enable it manually.

**Comment by AlexTurff** [comment]
Thanks Alex, that worked - I don't think that was in any of the documentation anywhere - could it be added? (and ideally added to this blog post: https://solidify.dev/blog/jira-azure-devops-migration - not sure if your a Solidify employee?)

**Comment by Alexander-Hjelm** [comment]
We should add it to the overview at least. Not sure who wrote that blog post, but I can try an find out :)

**Comment by Alexander-Hjelm** [comment]
Closing, continued in #663
