### ISSUE TITLE
Can we also migrate assigned date and comment dates with tickets?

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#667]
Can assigned dates be shown up with migrated tickets?

**Comment by Bikrammabzone** [comment]
@Alexander-Hjelm I am unable to replicate date/time of tickets. Its showing imported time not real created date/time or assigned time/date.

**Comment by Alexander-Hjelm** [comment]
@Bikrammabzone Try the new 3.0.78 release. We shipped a bugfix that should solve this problem: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.78

**Comment by Bikrammabzone** [comment]
Thanks @Alexander-Hjelm Its works !

**Comment by Alexander-Hjelm** [comment]
Perfect, closing!
