### ISSUE TITLE
Images in PNG format are broken when imported in azure. But JPG works. Does it support only JPG format?

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#668]
Images in PNG format are broken when imported in azure. But JPG works. Does it support only JPG format?

Image in PNG format is broken , Same image when converted into JPG gets visible 

![Screenshot (45)](https://user-images.githubusercontent.com/121940137/212665375-93235108-22f9-4375-9a1d-2a14cbdcb038.png)

**Comment by Alexander-Hjelm** [comment]
What is the image URL on the ADO work item? Does it correspond with what you expect?

**Comment by Bikrammabzone** [comment]
Not sure. Please check. Image name was screenshot(38). This is how it  appears on clicking on the broken image.

![Screenshot (46)](https://user-images.githubusercontent.com/121940137/212671873-85b136d0-91bd-4122-8a17-1acf84b16f98.png)

**Comment by Alexander-Hjelm** [comment]
Looks like the attachment is being mapped wrongly. Here is an example of a functioning attachment URL:

`https://solidifydemo.visualstudio.com/94f1c2da-b226-4e75-b1f7-c828b6c168b4/_apis/wit/attachments/eec776b8-3a64-482d-974c-10d1472f18e5`

It should be:

`https://dev.azure.com/organization/projectName/_apis/wit/attachments/attachmentID`

I see that the attachment ID has been replaced with the file name in your case, and also the organization name seems to be **secure**. Is this correct?

Does the import log tell you anything relevant?

Is there an attachment present on the target work item?

Can you post the link of a simliar working .png attachment? Let's see what the difference is in format.

**Comment by Bikrammabzone** [comment]
@Alexander-Hjelm Here is the link for JPG image after converting the format. Its working

https://dev.azure.com/bikramjeet0322/15bf596e-6536-4557-857d-323c23761132/_apis/wit/attachments/5e023808-268c-4a39-b559-cb6debaf9495

**Comment by Alexander-Hjelm** [comment]
Strange! So the attachment gets migrated, but the image in the comments gets the wrong link. Anything else that separates the two attachments in JIRA? Other than the file extension?

**Comment by Bikrammabzone** [comment]
No, actually for both attachment and as well as for comment some images are broken. Unable to find the cause @Alexander-Hjelm

**Comment by GBRacerX1** [comment]
Was this ever solved, seeing the same issue with .115

**Comment by Bikrammabzone** [comment]
@GBRacerX1 This was not solved but a hack for it is to check the attachments. We can see the images in attachments, and they are not broken there
