### ISSUE TITLE
Acceptance Criteria not being passed

### ISSUE THREAD

**Issue by Dustinparkes08** [solidify/jira-azuredevops-migrator#67]
It is not passing the acceptance criteria for User Stories or PBIs.  
 
 "field-map": {
    "field": [
{
 "source": "Acceptance Criteria",
 "target": "System.AcceptanceCriteria"
},

Tried mapping other fields to the acceptance criteria and errors in log claiming acceptance criteria isn't defined.  Is the target not correct for acceptance criteria?

**Comment by MOlausson** [comment]
Can you check how the acceptance criteria is defined in Jira? You can probably map it by name and not key (a custom field will be called customfield_ something) and the name of the Azure DevOps field probably has the default reference name Microsoft.VSTS.Common.AcceptanceCriteria.

"field": [
{
"source": "Acceptance Criteria",
"source-type": "name",
"target": "Microsoft.VSTS.Common.AcceptanceCriteria"
},

**Comment by Dustinparkes08** [comment]
How I was mapping the target was the issue.  Copied your field mapping and all acceptance criteria is now being passed.  Thank you!
