### ISSUE TITLE
Can't Map the "Type" field in Jira to a custom field in ADO

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#670]
Hi,

I have been unsuccessful in mapping the "Type" field in our Jira version to a custom field in ADO. The field looks like this in Jira:

![image](https://user-images.githubusercontent.com/92213401/212773199-1afd9778-2b80-4017-a1c3-dfb0dce95868.png)

I have this field mapped in the config file under "type-map" as below:

"type-map": {
    "type": [
      {
        "source": "Defect",
        "target": "Bug"
      },
      {
        "source": "Defect - Workaround",
        "target": "Bug"
      },
      {
        "source": "Exception",
        "target": "Bug"
      },
      {
	"source": "Inconsistency",
        "target": "Bug"
      },
      {
	"source": "Trivial",
        "target": "Bug"
      },
    ]
  },

But I am unable to map the "source" name to the custom field in ADO.

As everything is exporting as BUG I was just trying to catch this information too.

Any suggestions as to where/why I am going wrong?

Thanks

Chris

**Comment by Alexander-Hjelm** [comment]
Hi!

The type map will only control the mapping between the issue type in JIRA and the work item type in ADO.

If you want to map the issue type as a field, you will have to set up a custom field mapper. See https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

Not sure what the name of the issueType field would be. Look at the API response of an issue to find out.

Another way would be to set up a rule in ADO which sets your custom field to a default value for each workitem type.

**Comment by C-F-Palmer** [comment]
Hi Alexander,

Thanks again for your prompt reply. 

I have tried mapping this field using the below mapping:
{
        "source": "issuetype",
	"source-type": "name",
	"target": "Custom.JiraIssueType"
      },

However I get the below error message:

[E][10:30:09] Error mapping field 'Custom.JiraIssueType' on item 'DEF-16030'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraMapper.<>c__DisplayClass13_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r):
   at JiraExport.JiraMapper.<>c__DisplayClass13_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)

If I change the "source-type" to "id" I no longer get the error message but the field does not export.

Thanks

**Comment by Alexander-Hjelm** [comment]
Looks the `issuetype` field is not a string literal, but in fact an **issue type picker**.

For example:
```json
"issuetype":{"self":"https://solidifydemo.atlassian.net/rest/api/2/issuetype/10001","id":"10001","description":"A user story. Created by Jira Software - do not edit or delete.","iconUrl":"https://solidifydemo.atlassian.net/images/icons/issuetypes/story.svg","name":"Story","subtask":false,"hierarchyLevel":0},
```

So looks like we would have to implement a new mapper to support this use case.

Relabling as feature request

**Comment by Alexander-Hjelm** [comment]
`issuetype` has previously been exposed for mapping, see: https://github.com/solidify/jira-azuredevops-migrator/pull/827

Closing. Reopen if issue persists.
