### ISSUE TITLE
Can not ignore duplicated Work Items

### ISSUE THREAD

**Issue by D-saif** [solidify/jira-azuredevops-migrator#672]
For testing the migration, I need to run the script multiple times.
So I would like the script to ignore importing the existing issues to AzureDevOps.
I've checked the Docs but looks like this feature isn't available, unless I miss something.
@Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
This should be taken care of by the MigrationJournal. If not, you could manually fix it by deleting the work item json-files for the items that have already been imported, inside the migration workspace.
