### ISSUE TITLE
Migrated work items in Azure DevOps getting created with current time instead of actual time from Jira

### ISSUE THREAD

**Issue by kalyanreddy1992** [solidify/jira-azuredevops-migrator#673]
**Describe the problem**
Migrated work items in Azure DevOps getting created with current time instead of actual time from Jira

**To Reproduce**
I am trying to migrate work items from Jira to Azure DevOps cloud project created with an Agile template. After migration, noticed that the work item has updated/closed dates as the current date of migration instead of actual date from Jira. Kindly help me understand if I missed to configure something.

**Tool version**
 - jira-azuredevops-migrator-3.0.54

**Comment by Bikrammabzone** [comment]
Same issue I am facing @Alexander-Hjelm , Please look into

**Comment by Alexander-Hjelm** [comment]
@kalyanreddy1992 @Bikrammabzone Try the new 3.0.78 release. We shipped a bugfix that should solve this problem: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.78

**Comment by Alexander-Hjelm** [comment]
Duplicate of https://github.com/solidify/jira-azuredevops-migrator/issues/667

**Comment by Alexander-Hjelm** [comment]
@kalyanreddy1992 . Sounds strange. Only for tasks or other issue types also? Does the problem happen for every task or just one/a few?

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm, problem seen only with migrated tasks. 
![image](https://user-images.githubusercontent.com/86415609/214384671-e207492b-f5da-4447-936c-3ce841e9001a.png)

**Comment by Alexander-Hjelm** [comment]
@kalyanreddy1992 Strange, we added a fix here: https://github.com/solidify/jira-azuredevops-migrator/commit/b5b892227aad5c010d278ce9619c62a1a366bbf3

Can you please debug and verify that the following conditional block is actually entered for your execution:

https://github.com/solidify/jira-azuredevops-migrator/blob/9e0270eb83f244eac76080c930c6bf0bc7fbed20/src/WorkItemMigrator/WorkItemImport/WitClient/WitClientUtils.cs#L585-L592

Can you also verify that the final state of your tasks in JIRA is indeed "Done", and not something else?

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm , I have customized the sample agile file https://github.com/solidify/jira-azuredevops-migrator/blob/9e0270eb83f244eac76080c930c6bf0bc7fbed20/docs/Samples/config-agile.json (line #161) in which Status(System. State) has been mapped "Done" -> "Closed". As a result, the state is ending up as "Closed" in task specific Json file. 
![image](https://user-images.githubusercontent.com/86415609/214546231-2635d71d-58b0-486a-ad73-fdb9d1b0021e.png)
´
I have also tried by updating config-agile.json, changed the mapping to "Done" -> "Done", as expected the following is the issue.
![image](https://user-images.githubusercontent.com/86415609/214546669-a3629d95-47ff-41b9-8785-e1395f5e12ab.png)

**Comment by Alexander-Hjelm** [comment]
Ok! I know what's wrong. Working on a fix.

I'll send you a link with the feature branch once it's ready, so you can test it out and see if it resolves your issue.

Do you have the possibility of building the jira-ado-migrator locally in Visual Studio? Or would you prefer if I send you a prerelease with the tool as an .exe?

**Comment by Bikrammabzone** [comment]
@Alexander-Hjelm I am also not able to migrate DONE issues to DONE state in azure. For moving them, I had to change state to DOING for azzure. DONE=DOING. Don't know what is the cause

**Comment by Alexander-Hjelm** [comment]
@Bikrammabzone This would be a separate problem. Please create a new issue

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm , please share it as an .exe , thank you !

**Comment by Alexander-Hjelm** [comment]
[Debug.zip](https://github.com/solidify/jira-azuredevops-migrator/files/10499129/Debug.zip)

@kalyanreddy1992 Here is a bundle of the WI importer with the fix. Try it and report the results!

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm , I have executed only wi-import with the above shared bundle,  but it's still the same issue. Kindly let me know if any changes needed to the config file.

**Comment by Alexander-Hjelm** [comment]
Strange. shouldn't have to make any more edits.

Can you share the json file of the Task that is failling? Including all revisions.

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm , please find the json file of a test task attached 
[ABC-894.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10499552/ABC-894.txt)

**Comment by Alexander-Hjelm** [comment]
I noticed this section, seems you have some faulty mappings, including Priority and State:


       {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": null
        },
        {
          "ReferenceName": "System.State",
          "Value": null
        }

Check your config and make sure you have covered all possible Jira issue states in your state mapping (including any custom states)

// Alexander
________________________________

**Comment by Alexander-Hjelm** [comment]
And what is the state workflow of your task? Any states you could possibly have missed mapping?
________________________________

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm , we have few other states as well but we don't use them and none of the tasks are in those states. We have transition enabled to all the states from any state. 

I gave a try by adding mappings to all the states but still seeing the same issue.
       {
          "ReferenceName": "System.State",
          "Value": null
        }
