### ISSUE TITLE
is t possible to migrate work log from jira to ADO?

### ISSUE THREAD

**Issue by shwshind** [solidify/jira-azuredevops-migrator#675]
**Describe the problem**
I am migrating a project from Jira server to ADO using solidify and there is a requirement for work log migration as well.So how i can do this?

**Comment by Alexander-Hjelm** [comment]
@shwshind, I've never tried before, but it should be possible by mapping the **timeSpent** field to a custom field of your choice in ADO. Check the Docs and FAQ to read more about mapping custom fields.

Source: https://community.atlassian.com/t5/Jira-questions/Jira-REST-API-get-total-logged-time-for-one-issue/qaq-p/1119215
