### ISSUE TITLE
Not able to move Tickets in DONE states under DONE states in azzure

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#676]
@Alexander-Hjelm When I map DONE WITH DONE, all tickets under done state never move or show up in azzure. To migrate those tickets, I had to change mapping to doing or To Do. DONE= DOING. Then only I am able to move those tickets under DOING state in azzure. 
Do you know the cause and fix for it?

**Comment by Alexander-Hjelm** [comment]
Which process template are you using in your target ADO project, and what issue types are you migrating? Make sure that the target process template supports the DONE state. It could be named something else, like CLOSED or RESOLVED

**Comment by Alexander-Hjelm** [comment]
Also make sure that the capitalization is correct :)

**Comment by Bikrammabzone** [comment]
@Alexander-Hjelm I am using Scrum process in ADO.
I am migrating issue types like bugs, product backlog, task.
Also, the target template process (Scrum) supports "Done". I don't find any other term getting used.
