### ISSUE TITLE
New work item types not populating all information in ADO

### ISSUE THREAD

**Issue by Dustinparkes08** [solidify/jira-azuredevops-migrator#68]
I created two new work item types in ADO (Maintenance and Enhancement).  After migrating each it appears the Title, Assignee, State, Description and comments are not being passed.  It does appear that created date and attachments are being passed.  Please see attached files and logs. 

[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3472443/config.txt)
[log.c082af4e-7685-4d5a-b02c-f92cf62c9c66.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3472447/log.c082af4e-7685-4d5a-b02c-f92cf62c9c66.txt)
[log.6dc7c70d-135e-4757-a9f3-49b507c810cd.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3472448/log.6dc7c70d-135e-4757-a9f3-49b507c810cd.txt)
[itemsJournal.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3472449/itemsJournal.txt)
[attachmentsJournal.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3472450/attachmentsJournal.txt)

**Comment by RubenOuwerkerk** [comment]
Check, I have the same issue.

**Comment by ShadowXVII** [comment]
See #59

**Comment by MOlausson** [comment]
Fixed in v.2.2.88.
