### ISSUE TITLE
is there a way to map cascading picklist from jira to ado.I am able to map parent field but struggling with level1 value mapping

### ISSUE THREAD

**Issue by shwshind** [solidify/jira-azuredevops-migrator#680]
is there a way to map cascading picklist from jira to ado.I am able to map parent field but struggling with level1 value mapping

**Comment by Alexander-Hjelm** [comment]
@shwshind Not that I know if. Picklists are most likely not supported today.

Older issues I found on the same topic:
- https://github.com/solidify/jira-azuredevops-migrator/issues/251
- https://github.com/solidify/jira-azuredevops-migrator/issues/509
