### ISSUE TITLE
"System.NullReferenceException: Object reference not set to an instance of an object" when importing to Azure.

### ISSUE THREAD

**Issue by Jonas1244521** [solidify/jira-azuredevops-migrator#682]
I am trying to import my Jira export to my Azure Organization.

I am using this command (of course with my variables in it.): 
"wi-import --token personal-access-token-here --url https://yourorganisation.visualstudio.com --config config.json --force"

But for every item in my export list I get this error: 
"[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)"

I am not sure what the problem is and hope someone can help me here.

[wi-import-log-230127-131717.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10518830/wi-import-log-230127-131717.txt)
[config.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10518843/config.json.txt)

**Comment by Alexander-Hjelm** [comment]
@Jonas1244521 Not sure at the moment.

Verify that the target ADO project is using the Agile process.

Are you able to debug the tool in Visual Studio or VS code? That would be helpful in providing us with more info on where the exception is raised.

**Comment by Alexander-Hjelm** [comment]
@Jonas1244521 We've just released https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.85, where we added more logging for exceptions raised by the **workitem create** endpoint. Using this, we managed to solve a related issue that my colleague ran into.

Try it and see if you can get more details about the error. Most likely it is due to some misconfiguration on the ADO process :)

**Comment by Jonas1244521** [comment]
@Alexander-Hjelm 
Hi, Thanks for you answer, I had to change the target ADO project to use the Agile process. That fixed the errors.

**Comment by Alexander-Hjelm** [comment]
Perfect, cloding :)
