### ISSUE TITLE
wi-import, TF400813: Resource not available for anonymous access

### ISSUE THREAD

**Issue by volfgast** [solidify/jira-azuredevops-migrator#685]
**Describe the problem**
Dear Colleagues,

I'm trying to migrate from Jira to Azure DevOps Server 2019 and I have problems.
I tried to solve this problem but unsuccessful.
We have usual classic Windows domain with Active Directory.
I run this command line from Windows 10 computer (member of domain) and have the following error:

wi-import --token ****** --url https://domain.lan/tfs/DefaultCollection/TargetProject --config config-agile.json --force

Please below:
Work Item Importer v3.0.78
Copyright (c) Solidify
[I][14:03:27] Connecting to Azure DevOps/TFS...
[E][14:03:30] Unexpected migration error.
[Microsoft.VisualStudio.Services.Common.VssUnauthorizedException] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()

**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool 3.0.78

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**
[wi-import-output.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10578840/wi-import-output.txt)

**Comment by Ejo2001** [comment]
Hello! 

What do you use as your token? Are you using a PAT (Personal Access Token)?
