### ISSUE TITLE
System.AggregateException: One or more errors occurred. ---> SysSecurity.Authentication.AuthenticationException: Response Content: Basic authentication with passwords is deprecated.  

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#690]
Issue exporting from Jira cloud
i execute this:
jira-export -u john.edwards@canterbury.ac.nz -p APIToken --url https://ucdigitalsms.atlassian.net --config config-agile.json --force

Looking at previous support issue solutions on this site I see I have 
[jira-export-log-230209-145514.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10692797/jira-export-log-230209-145514.txt)
to create an API token, I have done this and use the very long api token after the -p in the command parameters.  I still get the error.  How can i see where it is going wrong?  When I look at my Atlassian account it says  API token has never been Accessed.

**Comment by Ejo2001** [comment]
Hello!

It would seem that you haven't provided the right authorization credentials in order for the code to work. Are you sure that you are using the correct email address, and can you see your API token in this list? https://id.atlassian.com/manage-profile/security/api-tokens

Also, have you double checked your config file so that it is mapped to the right project?

**Comment by RoyalWulf** [comment]
Hi,
I have given it the correct email address, john.edwards@canterbury.ac.nz:
![image](https://user-images.githubusercontent.com/103555625/217958226-d7b7d23b-bc62-41ad-821a-f8362e183a54.png)


url and project is correct
![image](https://user-images.githubusercontent.com/103555625/217958832-0f15c808-212c-4ef0-adcb-bac429968b70.png)

i can see the API token in the list:
![image](https://user-images.githubusercontent.com/103555625/217959270-05218a5b-2e5d-4ae5-a430-39453c053ade.png)

Note I am using the long API token string as a parmeter not the label
I am not an admin in Jira is that an issue?

This is my config file:
[config-agile.zip](https://github.com/solidify/jira-azuredevops-migrator/files/10702307/config-agile.zip)

**Comment by RoyalWulf** [comment]
FYI, I am away next week so my not respond to your reply / questions

**Comment by RoyalWulf** [comment]
I don't believe we do - it never asked me for an authentication when i log into Jira.  I can check in a week.

**Comment by bedazbedaz** [comment]
I have the same issue and have confirmed all the fields and token are correct.

We don't get prompted for 2FA, however we are using single sign on - I don't know exactly how this works we enter our email address in (don't click one of the buttons below) and it says something along the lines of "redirecting to single sign on", then logs us in.

**Comment by bedazbedaz** [comment]
Okay so a few updates. I have it working now, and after trying a lot of things, what I did to fix it was revoke and recreate the API token on my JIRA account. I also happened to get prompted for 2FA for the first time when logging into the create api token site.

Anyway, I copied and pasted the new API key carefully, pasting into a text editor first and checking the start and end characters to make sure I hadn't cropped anything (I just used the inbuilt copy button last time). Lo and behold it works now. I don't want to say user error, but this was probably user error.. Unless there's something wrong with the copy function on the Jira site.

**Comment by Ejo2001** [comment]
> I don't believe we do - it never asked me for an authentication when i log into Jira. I can check in a week.

Alright! 👍

**Comment by Ejo2001** [comment]
> Okay so a few updates. I have it working now, and after trying a lot of things, what I did to fix it was revoke and recreate the API token on my JIRA account. I also happened to get prompted for 2FA for the first time when logging into the create api token site.
> 
> Anyway, I copied and pasted the new API key carefully, pasting into a text editor first and checking the start and end characters to make sure I hadn't cropped anything (I just used the inbuilt copy button last time). Lo and behold it works now. I don't want to say user error, but this was probably user error.. Unless there's something wrong with the copy function on the Jira site.

It sounds like user error. It could be the copy button on Jira, but I am not sure that would be the issue unless it bugged out and didn't copy the whole thing, or if it didn't copy at all. Tough to say 😬

**Comment by RoyalWulf** [comment]
I am away from work but i tried the jira copy and it copied correctly.
I will try creating a new one when i get back home - currently in the middle of Cyclone Gabrielle here in NZ

**Comment by Ejo2001** [comment]
Alrighty! Stay safe!

> I am away from work but i tried the jira copy and it copied correctly. I will try creating a new one when i get back home - currently in the middle of Cyclone Gabrielle here in NZ

Alright! Until then, stay safe!

**Comment by RoyalWulf** [comment]
Going on holiday did the trick.
Came back didn't change anything and now it works
Cheers

**Comment by RoyalWulf** [comment]
works now
