### ISSUE TITLE
Allow Concatination of Fields in the Configuration File

### ISSUE THREAD

**Issue by rolandstirnimann** [solidify/jira-azuredevops-migrator#691]
This tool is fantastic and saved me a lot of time!

As far as I see from the documentation it is not possible to concatenate fields. In my case I wanted to bring the labels and components from Jira together in Azure DevOps as Tags. In principle something like this:
```
      {
        "source": "{{components}} + {{labels}}",
        "target": "System.Tags",
        "mapper": "MapArray"
      }
```

Alternatively, I can edit the extracted JSON files of every issue but this costs more time.
Would it be possible to implement something like that for the future?

**Comment by Alexander-Hjelm** [comment]
See this feature request: https://github.com/solidify/jira-azuredevops-migrator/issues/105

No plan to implement this feature at the moment :)

**Comment by Alexander-Hjelm** [comment]
@rolandstirnimann 

A new mapper with the ability to concatinate fields into a single field has been implemented in PR https://github.com/solidify/jira-azuredevops-migrator/pull/693.

If applicable in your case, could you give this PR a try and let us know if the new mapper solves your needs?

We have not yet created an Array-mapper with concatenation abilities. I will need to discuss with my manager whether this feature should be prioritized and if so, how we can best implement it. You are of course welcome to use my work in this PR to create your own mapper if the need is urgent :)

**Comment by rolandstirnimann** [comment]
This is already great and helps me to bring "Reason for priority" and "Description" together into one field. The need for the array-mapper is not that urgent for me, since I have not that many tickets where it would be relevant. So, in my case I can easily fix that manually after the import.
However, thank you for your quick response and the improvement.

**Comment by Alexander-Hjelm** [comment]
Perfect!

Unfortunately I was informed by my TL that we will roll back this PR and instead offer complex feature mapping as a paid feature. I will revert this change sometime in the upcoming days, but feel free to keep it locally for now. :(

**Comment by Alexander-Hjelm** [comment]
Reverted PR. This feature will be available through paid engagements with Solidify,

**Comment by andyfisher100** [comment]
@Alexander-Hjelm what is the best way to contact Solidify to pay for this functionality?

**Comment by Alexander-Hjelm** [comment]
@andyfisher100 Email me at alexander.hjelm@solidify.dev and I will put you in contact with sales :)
