### ISSUE TITLE
Due Date migration issue

### ISSUE THREAD

**Issue by shwshind** [solidify/jira-azuredevops-migrator#692]
While migrating the Due date from jira to ADO it is getting imported as D-1

{
        "source": "DueDate",
         "source-type": "id",
		
        "target": "Microsoft.VSTS.Scheduling.DueDate",
        "for": "Task,sub Task,Bug,Issue,User Story,Epic"
      }

eg. If the due date is 30-Oct-2022 in Jira then it is getting migrated as 29-Oct-2022. Please suggest a solution for this

**Comment by Alexander-Hjelm** [comment]
Time zone offset between your JIRA server and ADO server?

**Comment by shwshind** [comment]
I think so

**Comment by shwshind** [comment]
I am using central us time zone for ADO.

**Comment by shwshind** [comment]
Timezone is same for Jira and ADO that sis central US time zone

**Comment by Alexander-Hjelm** [comment]
Which version of the tool are you using? If possible, try the latest release.

Also you can search for old issues related to datetime field mapping. Maybe you can find an older solution that could help?
