### ISSUE TITLE
Jira export response not recognized as JSON.

### ISSUE THREAD

**Issue by Jonas1244521** [solidify/jira-azuredevops-migrator#695]
Hi, I am trying to run the Jira export command like this: "jira-export.exe -u username -p password --url url --config config-agile.json" of course using the right variables instead of the placeholders.

The problem is, that I get a response as HTML instead of JSON. 
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html>

[jira-export-log-230213-102052.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10721035/jira-export-log-230213-102052.txt)

[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10721038/config.txt)

**Comment by Ejo2001** [comment]
Hello! 

What are you passing along to password? Are you using a Jira API key?

**Comment by Jonas1244521** [comment]
No I am currently using my login password. But I already tried using the API Key and there is no difference.

**Comment by whiteserval** [comment]
I have exactly the same issue here. System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html>

**Comment by Ejo2001** [comment]
This error usually means that there is some authentication issue or permission error. Are you sure that you are using the right credentials when running the migration script? And also, do you have the right permissions required for migrating the project?

**Comment by whiteserval** [comment]
I was just using the wrong url

It works fine now. Thanks for the reply

**Comment by Ejo2001** [comment]
> I was just using the wrong url It works fine now. Thanks for the reply
> […](#)
> Op 14 feb. 2023 om 12:18 heeft Erik J Olsson ***@***.***> het volgende geschreven: ﻿ This error usually means that there is some authentication issue or permission error. Are you sure that you are using the right credentials when running the migration script? And also, do you have the right permissions required for migrating the project? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.



I'm happy to hear that it is working for you! 😄

**Comment by Jonas1244521** [comment]
Hi, I'm still having the same issue. I tried using different credentials.  I was able to run it a few weeks ago so I don't think it has to do with credentials. Maybe I have a problem with the URL too. Where can I get the URL from?

**Comment by Ejo2001** [comment]
To get the URL, go to your Jira project, then copy the URL of that and use it with the migration tool. It should look something like this: https://**YOUR-NAME-OR-ORG**.atlassian.net/

**Comment by Jonas1244521** [comment]
Ok, I think in this case I think I already have the right URL. 
I noticed, that I can see everything, that should be exported, in the error message but as HTML. 
So the script has access to the data but in the wrong format?

**Comment by Ejo2001** [comment]
It all sounds strange. Are you using Jira Server or Jira Cloud? If you are using Jira Server, could you tell me which version?

Are you also able to provide the command you are using (Blur out the password and other sensible data), and maybe a screenshot of your Jira instance?

**Comment by Jonas1244521** [comment]
I am using Jira Server and this command: 
"jira-export -u bachmaj8 -p ******** --url https://jira.roche.com/jira/projects/KNOXAPI/summary --config config-agile.json"

Here is a screenshot of the Jira instance.
![image](https://user-images.githubusercontent.com/123741153/220279499-bf05c3c1-2dca-4ed0-ac55-1d0282539bfe.png)

**Comment by Ejo2001** [comment]
I think I see the problem, you are using the wrong link (Or well, you are using too much of the link). Instead of "https://jira.roche.com/jira/projects/KNOXAPI/summary", try "https://jira.roche.com"

**Comment by Jonas1244521** [comment]
No, this doesn't seem to work. Now I get an different error. 
And I just want to migrate the KNOXAPI project.
[jira-export-log-230221-140214.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10793765/jira-export-log-230221-140214.txt)

**Comment by Ejo2001** [comment]
I believe you have to change the "source-project" field in your config file from "K-POP" to KNOXAPI in that case, could you try that? 😄

**Comment by Jonas1244521** [comment]
No sadly this doesn't work either. I think its kind of weird that I get a HTML response with all the Data which means that the authentication works and it gets the right Data.
[jira-export-log-230222-112140.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10802594/jira-export-log-230222-112140.txt)

**Comment by Alexander-Hjelm** [comment]
@Jonas1244521 I had a look at your files but not super sure where the problem is either. Has there been any configuration made on your Jira server that could possibly obstruct access to the rest API services?

Could an alternative be for you to set up a free Jira Cloud organization and try setting up a few migrations as an exercise? That way you could potentially learn more about the tool/problem, and we can rule out any invalid configuration on your end.

**Comment by SNathan78** [comment]
I have same issue.. Please let me know if there is any solution found..

**Comment by Ejo2001** [comment]
> I have same issue.. Please let me know if there is any solution found.. My api call works fine though..

Are you using Jira Server or Jira Cloud?

**Comment by SNathan78** [comment]
> > I have same issue.. Please let me know if there is any solution found.. My api call works fine though..
> 
> Are you using Jira Server or Jira Cloud?

I am using JIRA cloud

**Comment by Jonas1244521** [comment]
I just noticed that I am only able to authenticate by using username + password. The API token doesn't work anymore. For my coworker it doesn't work at all because his credentials are denied.

After trying out all available options I have the problem, that I can't authenticate anymore even though I use the exact same command that worked before. and I haven't changed the config file.

Maybe you could show us how to authenticate using the API Token.

[jira-export-log-230224-135637.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10824263/jira-export-log-230224-135637.txt)

**Comment by Ejo2001** [comment]
> > > I have same issue.. Please let me know if there is any solution found.. My api call works fine though..
> > 
> > 
> > Are you using Jira Server or Jira Cloud?
> 
> I am using JIRA cloud

What's you config and command to export data?

**Comment by Ejo2001** [comment]
> I just noticed that I am only able to authenticate by using username + password. The API token doesn't work anymore. For my coworker it doesn't work at all because his credentials are denied.
> 
> After trying out all available options I have the problem, that I can't authenticate anymore even though I use the exact same command that worked before. and I haven't changed the config file.
> 
> Maybe you could show us how to authenticate using the API Token.
> 
> [jira-export-log-230224-135637.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10824263/jira-export-log-230224-135637.txt)

This is the command I used to export data from Jira:

.\jira-export.exe -u *EMAIL* -p *API-TOKEN* --url https://*URL*.atlassian.net/ --config *config-file* --force

I have only tried migrating a project from Jira Cloud on my personal Jira account, but I have talked with @Alexander-Hjelm and he said it should be the same for Jira server. Does my command differ from yours?

**Comment by Ejo2001** [comment]
> My issue got resolved without any additional effort. Another person tried from his end and asked me to run again, it ran without any issues..

I'm happy to hear that you got it working!
