### ISSUE TITLE
Jira sprint value with (for AzDo) invalid Iteration Path characters in combination with spaces throws exception TF401347

### ISSUE THREAD

**Issue by VincentVerweij** [solidify/jira-azuredevops-migrator#696]
**Describe the problem**
> I don't really know what constraints we have in Jira in case of `Sprint` field, so it might be that this is configurable and that what I will say below is not correct.

In Jira it seems to be perfectly valid to have a `Sprint` field which contains something like `1. Sprint 01 / 02`.
This will work perfectly in that it will put this as a `ReferenceName` in the issue's JSON file during the export phase.

When importing it does not work as expected.
In method `EnsureClasification` of class `Agent` we see that it gets chopped by using the `/` character.
So, in this scenario it would create an iteration in Azure DevOps which has name Sprint 01 and a child with name 02.
When it calls the following line:  
https://github.com/solidify/jira-azuredevops-migrator/blob/55c3bd3b2dd084dff6e58eb7c67d4735c23f1b83/src/WorkItemMigrator/WorkItemImport/Agent.cs#L471

It would then replace the forward slashes with backward slashes.
Until this point, everything goes fine.

Now, when it calls the `SaveWorkItemFields` method here:
https://github.com/solidify/jira-azuredevops-migrator/blob/55c3bd3b2dd084dff6e58eb7c67d4735c23f1b83/src/WorkItemMigrator/WorkItemImport/Agent.cs#L123

Things are going in the wrong direction.
It throws exception: `TF401347: Invalid tree name given for work item 4877, field 'System.IterationPath'.`

When it wants to update the work item over here:
https://github.com/solidify/jira-azuredevops-migrator/blob/55c3bd3b2dd084dff6e58eb7c67d4735c23f1b83/src/WorkItemMigrator/WorkItemImport/WitClient/WitClientUtils.cs#L514

I am seeing that the patchDocument has the following value `My project\\Migrated\\1. Sprint 01 \\ 02` for path `/fields/System.IterationPath`.
I does not find this because my Iteration path looks like this:
<img width="120" alt="image" src="https://user-images.githubusercontent.com/41574930/218441230-76b8f55e-1bf0-4db0-9ca8-f152afbcbf61.png">
It does not contain the spaces that it is looking for.
This is the parent that was created, which is trimmed at the end:
<img width="71" alt="image" src="https://user-images.githubusercontent.com/41574930/218441351-85e3255f-6b17-41fd-8823-570e2dc26780.png">
And this is the child that was created:
<img width="87" alt="image" src="https://user-images.githubusercontent.com/41574930/218441415-df64e0e0-a2e2-4214-8248-e1a848ce2efb.png">

When trying the same but without spaces, like this: `1. Sprint 01/02`, it works without throwing errors.

If we search for valid names of an Iteration Path in Azure DevOps, we come across [this article](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/about-areas-iterations?view=azure-devops#naming-restrictions).
Here we can see the following:
> - Special characters for nodes
>   - Must not contain characters prohibited by the local file system. For more information about Windows character restrictions, see [Naming Files, Paths, and Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file).
  
This basically says that it cannot contain something like a forward slash.

I think the root cause of this issue is that we should clean the `Sprint`'s value in the exporting phase.

**Tool version**
- https://github.com/solidify/jira-azuredevops-migrator/commit/55c3bd3b2dd084dff6e58eb7c67d4735c23f1b83

**Comment by Alexander-Hjelm** [comment]
We have an old fix for this here: https://github.com/solidify/jira-azuredevops-migrator/pull/453

Never ended up merging it because the solution ended up in over-engineering territory. The idea was to let the user map the invalid special characters.

Would the ability to map the special characters be of use to you? Or would it be enough to simply remove them?

**Comment by Alexander-Hjelm** [comment]
@VincentVerweij I opened this PR: https://github.com/solidify/jira-azuredevops-migrator/pull/702

Let me know what you think of the soluion

My idea is that by default we will remove any invalid characters. If the user wants to modify the sprint names then, they can always do it post-migration. At least this takes take of the error.

**Comment by Alexander-Hjelm** [comment]
@VincentVerweij Perfect. I'll write some unit tests and merge https://github.com/solidify/jira-azuredevops-migrator/pull/702 later. Thanks for helping out with this issue :)
