### ISSUE TITLE
Links are not migrating to ADO...   Links are being undone or 'is not inward issue' message...  Only 'Related' Links are migrating

### ISSUE THREAD

**Issue by jstras17** [solidify/jira-azuredevops-migrator#701]
[LM.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10743751/LM.json.txt)
[jira-export-log-230215-085851.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10743752/jira-export-log-230215-085851.txt)
[wi-import-log-230215-085904.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10743753/wi-import-log-230215-085904.txt)
![Jira-migration](https://user-images.githubusercontent.com/68659481/219049625-07f6e711-f219-4bda-a93b-b96d3cfc2bc1.JPG)

**Describe the problem**
Links are not migrating to ADO..   
Links are being undone or getting message 'is not an inward issue'
Only 'Related' Links are migrating
Have tried different target LinkTypes
System.LinkTypes.Hierarchy-Forward
System.LinkTypes.Hierarchy-Reverse
System.LinkTypes.Related

**To Reproduce**
ONLY 'Related to' links are working when migrating to ADO
Other links are being undone or getting message 'is not an inward issue'
Example:
============
[D][08:58:53]    Undone link 'Added [Related] LM-7323->LM-7322'.
[D][08:58:53]    Link with description 'This issue is blocked by LM-7322' is either not found or this issue (LM-7323) is not inward issue.
[D][08:58:53]    Undone link 'Added [Cloners] LM-7323->LM-7322'.
[D][08:58:53]    Undone link 'Added [Blocks] LM-7323->LM-7322'.
=============

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 3.0.97]

**Attachments**

Please attach the following files:

- LM.json.txt
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
From your config:

```json
{
  "source": "blocks",
  "target": "System.LinkTypes.Related"
},
{
  "source": "is blocked by",
  "target": "System.LinkTypes.Hierarchy-Forward"
},
```

It seems to me that that you are telling ADO that your blocking issues should be treated as related, whereas the blockedBy issues should be treated as parents (Hierarchy-Forward?

Have you tried using "Related" for both link types? Or Hierarchy-Forward/Hierarchy-Reverse?

**Comment by jstras17** [comment]
Have tried using many different combinations of LinkTypes 
Related, and Hierarchy-Forward/Hierarchy-Reverse for each of these below
The only LinkType that is working is 'Related'


      {
        "source": "is cloned by",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "blocks",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "is blocked by",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "is related to",
        "target": "System.LinkTypes.Related"
      },
      
      
  
  Looking at the logs, can you help explain what is happening here with 'Undone link' and 'is not inward issue' ?    
      ---------------------------
[D][13:19:52]    Undone link 'Added [Related] LM-7323->LM-7322'.
[D][13:19:52]    Link with description 'This issue is blocked by LM-7322' is either not found or this issue (LM-7323) is not inward issue.
[D][13:19:52]    Undone link 'Added [Cloners] LM-7323->LM-7322'.
[D][13:19:52]    Undone link 'Added [Blocks] LM-7323->LM-7322'.
      ---------------------------
      
Thank you

**Comment by Alexander-Hjelm** [comment]
Looks like either LM-7322 is not picked up by the migrator, or it's true that LM-7323 is not inward. It could mean many things. The issueTypes could be incompatible for that linkType, for example.

Here is a description of inward/outward issues:

> The Inward/Outward refers to the directionality of the relationship as it is stored in the database. The table that stores issue links (issuelink) has a source issue id and a destination issue id. The outward relationship refers to the relation from source to destination, and the inward relationship refers to the relation from destination to source.
> 
> The outward relationship tends to be the relationship that is the causal direction, meaning the source issue is taking action on the destination issue.
> 
> i.e. the source issue can block, clone, duplicate, relate, resolve etc.
> 
> The inward relationship tends to describe the issue that was acted upon. 
> 
> i.e. the destination issue was blocked by, cloned by, duplicated by, related to, and resolved by etc. 

Source: https://community.atlassian.com/t5/Jira-questions/Issue-links-what-is-the-meaning-of-quot-inward-quot-and-quot/qaq-p/839095

**Comment by Alexander-Hjelm** [comment]
Potentially fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/1072
