### ISSUE TITLE
NullReferenceException due to sprint field being an empty string

### ISSUE THREAD

**Issue by VincentVerweij** [solidify/jira-azuredevops-migrator#708]
**Describe the problem**
I get a `System.NullReferenceException: 'Object reference not set to an instance of an object.'` exception.

When running method `MapSprint`, it returns null because `iterationPathsString` is an empty string.
This causes the following line to have null for the `value` variable, while `include` is true.

https://github.com/solidify/jira-azuredevops-migrator/blob/eeb195c7e653c26f6e349434607a18895f7aacda/src/WorkItemMigrator/JiraExport/JiraMapper.cs#L274

Due to this the following line throws the exception because the `ToString` method is invoked on a null object.
https://github.com/solidify/jira-azuredevops-migrator/blob/eeb195c7e653c26f6e349434607a18895f7aacda/src/WorkItemMigrator/JiraExport/JiraMapper.cs#L278

I first thought it was due to my new Jira query, but when trying it on a previously working configuration file, it does seem to be an issue with the code (or my configuration file).

I think it must be related to this commit:
https://github.com/solidify/jira-azuredevops-migrator/commit/04a5d5707678ae11ec0aca1b3874a3f04f8f930e

Or maybe something fundamentally changed in the configuration file, did not check it though.

**Tool version**
https://github.com/solidify/jira-azuredevops-migrator/commit/eeb195c7e653c26f6e349434607a18895f7aacda

**Comment by Alexander-Hjelm** [comment]
That's an issue indeed. Solving the exception would be as easy as TryParsing `value` as a string.

Will release a patch for this as soon as I have time.

But why is `value` null here? Could be indicative of a bigger problem.

**Comment by Alexander-Hjelm** [comment]
Yep! You can disable it for now, but might run into trouble with long (255+ chars) issue summaries, just FYI :)
________________________________

**Comment by ididitmyway** [comment]
Hi I see the same Issue here. 
In Version 3.0.85 there is no Issue, but in Version 3.0.109.

Kind Regards
Ben 
And really thank you for sharing the tool.

**Comment by pengliangyou** [comment]
Hi I see the same Issue.
is there a new fix for this? 
Kind Regards
Thank you

**Comment by Alexander-Hjelm** [comment]
PR created here: https://github.com/solidify/jira-azuredevops-migrator/pull/724

@VincentVerweij @ididitmyway @pengliangyou , could either of you try out the PR and verify that it fixes your problem? :)

**Comment by pengliangyou** [comment]
sorry i can not download this fix, because i do not have authority to
“Solidify AB”  “
https://dev.azure.com/solidify/Internal/_build/results?buildId=11501&view=results
”

Alexander Hjelm ***@***.***> 於 2023年3月8日 週三 下午5:23寫道：

**Comment by Alexander-Hjelm** [comment]
Perfect. Mergeing PR and closing this issue. The fix will be included in the release later today :)
