### ISSUE TITLE
Unable to map Target Start Date and Target Completion Date in Jira with Planned Start and End Date in Azure DevOps. 

### ISSUE THREAD

**Issue by mohammed-isahak** [solidify/jira-azuredevops-migrator#712]
I'm looking to migrate a large number of work items from Azure to Jira and am not able to map the start and completion date. Below are the lines that I've been using. The dates do not reflect on the exported json and there is no error which is generated as well. 

      {
        "source": "Target start",
        "type": "datetime",
        "target": "Custom.PlannedStartDate",
        "for": "User Story"
      },
      {
        "source": "Target Completion Date",
        "type": "datetime",
        "target": "Custom.PlannedEndDate",
        "for": "User Story"
      }

Tool Version - 2.3.117

**Comment by Ejo2001** [comment]
Have you tried using the latest version? https://github.com/solidify/jira-azuredevops-migrator/releases

Also, just to clarify, are you trying to migrate from Jira to Azure DevOps, or from Azure DevOps to Jira?

**Comment by mohammed-isahak** [comment]
We have a few customizations done in ADO due to which the latest version doesn't work and is throwing errors. 

I'm trying to migrate from Azure DevOps to Jira.

**Comment by Alexander-Hjelm** [comment]
This tool only supports migrating from Jira to ADO :)

**Comment by mohammed-isahak** [comment]
I'm sorry, I meant Jira to ADO. And I was able to fix the issue. Below is what I have used. 

      {
        "source": "Target start",
        "source-type": "name",
        "target": "Custom.PlannedStartDate",
        "for": "User Story"
      },
      {
        "source": "Target end",
        "type": "name",
        "target": "Custom.PlannedEndDate",
        "for": "User Story"
      }

**Comment by Alexander-Hjelm** [comment]
Perfect, closing :)

**Comment by angierieger77** [comment]
@mohammed-isahak  --- thank you so much, this was bothering me today and your solution worked.  I appreciate you!
