### ISSUE TITLE
Unable to get attachments from Jira for few work items 

### ISSUE THREAD

**Issue by mohammed-isahak** [solidify/jira-azuredevops-migrator#713]
I'm working to export a huge number of work items from Jira to AzDo. There are a few work items where the attachments do not get exported. The only common factor I was able to find for such work items is that they are ".msg". 

Tool Version which is used - 2.3.117

There is a mismatch between the Attachments Journal, the log and Attachments Folder. 

AttachmentsJournal.txt and Attachments Folder: 
482832;12948709
485070;12948710

Error from the log - Import: 
[W][04:08:59] Cannot find info for attachment '482659', skipping. Reason 'Response Content: {"errorMessages":["The attachment with id '482659' does not exist"],"errors":{}}'.
[W][04:09:00] Cannot find info for attachment '482660', skipping. Reason 'Response Content: {"errorMessages":["The attachment with id '482660' does not exist"],"errors":{}}'.

Error from the log - Export: 
[E][04:19:23] Could not find migrated attachment '[Removed] 482659/'.
[E][04:19:24] Could not find migrated attachment '[Removed] 482660/'.

**Comment by Ejo2001** [comment]
Hello!

Have you tried to run the latest version of the migration tool? 

https://github.com/solidify/jira-azuredevops-migrator/releases
