### ISSUE TITLE
Use jira-azuredevops-migrator on apple devices

### ISSUE THREAD

**Issue by philipp-kremer** [solidify/jira-azuredevops-migrator#714]
Hey Guys, i saw your migrator is only working on windows devices. Is It possible to create something like this for apple devices?

I tried some stuff with Wine Crossover but it didn't work as expected.

**Comment by Ejo2001** [comment]
Hello!

I have not tried running the migration tool on a Mac personally, but I will talk with the maintainer of this project on Monday and see if the project can run on an Apple device. In the meantime, could you tell me more about your experience trying to run the migrator using Wine Crossover? 😄

**Comment by Alexander-Hjelm** [comment]
The tool should be buildable/runnable under Mac-based systems using the .NET Core CLI. But we do not officially support the macOS platform yet  :)
