### ISSUE TITLE
When migrating multiple JIRA Projects - Mapping Project to Area Path

### ISSUE THREAD

**Issue by jstras17** [solidify/jira-azuredevops-migrator#715]
**Describe the problem**
We have multiple JIRA Projects with Issues linked between projects
For this reason, we will be migrating multiple JIRA projects to 1 ADO project at the same time

**Is it possible to map JIRA Project (or ProjectKey) field to different Area Paths?**
Or, do we need to use the base-area-path?

The work around will be to do bulk updates of ADO WIs after the migration import is completed based on Issue Key

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 3.0.109]

**Comment by Alexander-Hjelm** [comment]
@jstras17

Please not the cross-project migrations are not supported today, and we don't guarantee that the cross-project links will be preserved.

Mapping areaPaths is not a common use case, most would probably let the tool generate the required area paths and then bulk move the relevant work items on the ADO side. I imagine however, that it could be done by editing your config file to something like this:

```json
      {
        "source": "<source field>",
        "source-type": "name",
        "target": "System.AreaPath",
        "mapping": {
          "values": [
            {
              "source": "sprint1",
              "target": "MyProject\\Area1"
            },
            {
              "source": "sprint2",
              "target": "MyProject\\Area2"
            },
            {
              "source": "sprint3",
              "target": "MyProject\\Area3"
            }
          ]
        }
```

It should be feasible in theory, but I have never tried before personally :)

**Comment by pelinture** [comment]
Do we need to apply this to the files we export as well? That's why I'm asking, I'm exporting with 7 different jsons and importing with a single import json. What should be the jql in this import file, should it be a jql that will cover all exports? Or can I import it with any json I exported?
