### ISSUE TITLE
User picker custom field not being exported after using suggested work around

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#716]
User picker custom field not being exported (reference #179) #191

Hi,

I am having the same issue as raised in #179 and #191. I have followed the suggested work around but can only get it to work if I change the name in the field to something else and then save. Then change the name back to the original name. This would be ok if I only had small number of issues with this infomation but I have approx 40k issues to update.

Is their another way to get this to work?

Regards

Chris

**Comment by Alexander-Hjelm** [comment]
@C-F-Palmer

Please not the cross-project migrations are not supported today, and we don't guarantee that the cross-project links will be preserved.

Mapping areaPaths is not a common use case, most would probably let the tool generate the required area paths and then bulk move the relevant work items on the ADO side. I imagine however, that it could be done by editing your config file to something like this:

```json
      {
        "source": "<source field>",
        "source-type": "name",
        "target": "System.AreaPath",
        "mapping": {
          "values": [
            {
              "source": "sprint1",
              "target": "MyProject\\Area1"
            },
            {
              "source": "sprint2",
              "target": "MyProject\\Area2"
            },
            {
              "source": "sprint3",
              "target": "MyProject\\Area3"
            }
          ]
        }
```

It should be feasible in theory, but I have never tried before personally :)

**Comment by Alexander-Hjelm** [comment]
I don't quite follow what the issue is.

> can only get it to work if I change the name in the field to something else and then save

What do you mean here by "change the name in the field"?

**Comment by C-F-Palmer** [comment]
Hi Alexander,

For the export to pick up that field i needed to change the text in the field to something else then save. Then it would capture this info in the export. So to get the correct name (text) I needed to change it back. It wouldn't work if I updated the field with the same details. The field in question captured the Customer name.

Thanks

Chris

**Comment by Alexander-Hjelm** [comment]
Strange behavior. Are you able to verify if there is any difference in the Issue Rest API response before/after changing the field?

**Comment by C-F-Palmer** [comment]
Will try and check that but in the interim I think the behaviour is related to the audit trail in Jira. It seems the tool relies on there being some record of the change in Jira to work. You cant just use the same name(details) and save. See extract from the Export log file:
[D][11:44:19]    Mapped value '[RDS-40800] Checkshot CRD' to field 'System.Title'.
[W][11:44:19] Could not find user 'xxxxxx@ikonscience.com' identity in user map. Using original identity 'xxxxx@ikonscience.com'.
[D][11:44:19]    Mapped value 'xxxxxx@ikonscience.com' to field 'System.AssignedTo'.
[D][11:44:19]    Mapped value '2021.1' to field 'Custom.AffectedVersion'.
[D][11:44:19]    Mapped value 'RokDoc (generic)' to field 'Custom.SoftwareComponents'.
[D][11:44:19]    Mapped value 'name.name' to field 'Custom.ReportedBy'.
[D][11:44:19]    Mapped value 'Ikon Science' to field 'Custom.Company'.
[D][11:44:19]    Mapped value 'Internal' to field 'Custom.Region'.
[D][11:44:19]    Mapped value 'Well Data' to field 'Custom.Category'.
[D][11:44:19]    Mapped value 'PLATFORM' to field 'Custom.LicenseFeatures'.
[D][11:44:19]    Mapped value '2021-03-16' to field 'Custom.DateReported'.
[W][11:44:19] User 'customer name' not found in Jira, using username 'customer name' for mapping.
[W][11:44:19] Could not find user 'customer name' identity in user map. Using original identity 'customer name'.
**[D][11:44:19]    Mapped value 'customer name' to field 'Custom.Customer'.**
[D][11:44:19]    Mapped value 'email' to field 'System.Tags'.

[D][11:44:19]    Mapping revision 3.
[W][11:44:20] Could not find user 'cpalmer@ikonscience.com' identity in user map. Using original identity 'cpalmer@ikonscience.com'.
[D][11:44:20]    Mapping revision 4.
[D][11:44:20]    Mapping revision 5.
[W][11:44:20] User 'Chris Palmer' not found in Jira, using username 'Chris Palmer' for mapping.
[W][11:44:20] Could not find user 'Chris Palmer' identity in user map. Using original identity 'Chris Palmer'.
[D][11:44:20]    Mapped value 'Chris Palmer' to field 'Custom.Customer'.
[D][11:44:20]    Mapping revision 6.
**[D][11:44:20]    Mapped value 'customer name' to field 'Custom.Customer'.**
[D][11:44:20]    Exported as type 'Support'.
[I][11:44:20] Export complete. Exported 1 items (0 errors, 8 warnings) in 00:00:01.

Thanks

Chris
