### ISSUE TITLE
Assignee incorrectly set

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#717]
**Tool version**
 3.0.109

**Describe the problem**
In Jira (cloud) the assignee for the issue is Unassigned
In its history it was assigned to somebody but final state Unassigned
When I export it I get:
[E][12:07:34] Error mapping field 'System.AssignedTo' on item 'US-23770'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraMapper.MapFields(JiraRevision r): 
   at JiraExport.JiraMapper.MapFields(JiraRevision r)

When I import it, it has a value for Assigned To of the person who it was **last** assigned to 

**Attachments**
[jira-export-log-230306-120731.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10893218/jira-export-log-230306-120731.txt)

[wi-import-log-230306-120924.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10893220/wi-import-log-230306-120924.txt)

[config-agile-json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10893225/config-agile-json.txt)

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Labeling as bug

**Comment by RoyalWulf** [comment]
looks like it is fixed with version 3.0.115?

**Comment by Alexander-Hjelm** [comment]
@RoyalWulf I think to too.

Ran some tests for an Agile project and can confirm that the issue no longer occurs:

![image](https://user-images.githubusercontent.com/10683896/233838833-5430013b-27c9-4302-b6f8-959b766263c6.png)

![image](https://user-images.githubusercontent.com/10683896/233838777-18f2a4f4-498a-4031-929a-4e2e4b720d52.png)

Let's close this one?

**Comment by RoyalWulf** [comment]
Issue fixed
