### ISSUE TITLE
Importing JIRA Sprints to AzDO Iteration Paths

### ISSUE THREAD

**Issue by jstras17** [solidify/jira-azuredevops-migrator#719]
**Describe the problem**
1. Does the migration tool import Sprints from JIRA to AzDO Iteration Paths?
2. Can you map JIRA Sprints to AzDo Iteration Paths in .json mapping file?

**Tool version**
 - Version of the jira-azuredevops-migrator tool 3.0.109

**Attachments**

**Comment by Alexander-Hjelm** [comment]
@jstras17 

Sprints will be automatically converted into ADO Iteration paths, and the required iteration paths for your migrations will be created by the tool.

Mapping sprint>iterationPath is not a common use case, but I imagine it could be done by editing your config file to something like this:

```json
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapping": {
          "values": [
            {
              "source": "sprint1",
              "target": "MyProject\\Sprint1"
            },
            {
              "source": "sprint2",
              "target": "MyProject\\Sprint2"
            },
            {
              "source": "sprint3",
              "target": "MyProject\\Sprint3"
            }
          ]
        }
```

It should be feasible in theory, but I have never tried before personally :)
