### ISSUE TITLE
Failed to retrieve fields from Jira (Response was not recognized as JSON)

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#720]
**Describe the problem**
Can not export Jira issues from Jira Server (not cloud for this support call)

First few lines of error:
Failed to retrieve fields from Jira (Response was not recognized as JSON). This usually indicates a problem with authentication or authorization. Check your Jira credentials and permissions.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Response Content: <html>

<head>
    <title>Forbidden (403)</title>

**To Reproduce**
run 
jira-export -u jge22 -p UsernamePassword --url https://jira.canterbury.ac.nz --config config-agile-eServ.json --force
not using Jira api as that is only for Jira in the cloud

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
3.0.109

**Attachments**

Please attach the following files:

- config.json
[config-agile-eServ json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10905246/config-agile-eServ.json.txt)

- jira-export-log.txt
[jira-export-log-230307-164806.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10905235/jira-export-log-230307-164806.txt)

- wi-import-log.txt
n/a

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
@RoyalWulf The issue is exactly what is says in the warning message:

```log
Failed to retrieve fields from Jira (Response was not recognized as JSON). This usually indicates a problem with authentication or authorization. Check your Jira credentials and permissions.
```

Check your jira token and your permissions

**Comment by RoyalWulf** [comment]
@Alexander-Hjelm Please note, I am doing two migrations at the moment.  One from jira cloud and one from Jira Server. This issue is from Jira Server. Am I correct in thinking, Jira Server does not use jira api tokens?  If it doesn't then i should use username / password?

**Comment by Alexander-Hjelm** [comment]
I'm pretty sure email+api token is the way to go, but depending on how your Jira Server is set up then other alternatives could maybe work as well. Try and see!

**Comment by RoyalWulf** [comment]
I have tried both user id + api token and user id + password

**Comment by RoyalWulf** [comment]
This article here
https://community.atlassian.com/t5/Jira-Software-questions/How-can-I-create-an-API-token-on-JIRA-server/qaq-p/1520133
says 
"API tokens are not available for on premises "flavor" of Atlassian applications, you can always use a Basic auth to initiate a session"
and
"For Jira cloud basic authentication is deprecated as of the article you have cited.
For Jira on-premise (Server) the basic auth is not deprecated."

@Alexander-Hjelm if i put in username+password should it use basic auth?
In my previous migrations a year ago, it worked with username+password

**Comment by RoyalWulf** [comment]
IDK this started working today with username+password
Frustratingly wit authorizations it seems to work the next day or two and i have done nothing

**Comment by RoyalWulf** [comment]
Working now
