### ISSUE TITLE
How to retreive just the FixVersion releaseDate

### ISSUE THREAD

**Issue by GBRacerX1** [solidify/jira-azuredevops-migrator#721]
Is there a way to map just the FixVersion releaseDate to a custom date field?  I can get the name of the fixversion but need just the releaseDate now to map and can't figure out how to retrieve it out of the array.

**Comment by Alexander-Hjelm** [comment]
See https://github.com/solidify/jira-azuredevops-migrator/issues/344 for migrating FixVersion

Pretty sure there is no support for FixVersion.ReleaseDate as of today. Labeling as feature request.

See https://github.com/solidify/jira-azuredevops-migrator/issues/40 for the jira response content, incl. fixVersions and ReleaseDate

**Comment by Alexander-Hjelm** [comment]
Releases (incl. release dates) are now supported in the Jira Azure DevOps Migration PRO version. Read more here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-azure-devops-migrator-pro
