### ISSUE TITLE
Failed to load json file - due to invalid characters

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#726]
**Describe the problem**
Error in importing
[I][15:20:49] Building execution plan...
[W][15:20:50] Detected unicode characters, removed.
[W][15:20:50] Failed to load 'ESERV-719.json' (perhaps not a migration file?).

This work iem has a file but not migrated

**To Reproduce**
run
wi-import

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
3.0.115

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
[config-agile-eServ1-json (2).txt](https://github.com/solidify/jira-azuredevops-migrator/files/10938227/config-agile-eServ1-json.2.txt)

[jira-export-log-230310-151316.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10938230/jira-export-log-230310-151316.txt)
[wi-import-log-230310-152048.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10938231/wi-import-log-230310-152048.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Can you attach the contents of `ESERV-719.json`?

**Comment by RoyalWulf** [comment]
[ESERV-719 - json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10974755/ESERV-719.-.json.txt)

**Comment by Alexander-Hjelm** [comment]
The issue stems from the migrator not being able to parse the work item .json file, not sure why.

Is the item imported as expected or not?

Maybe try saving `ESERV-719.json` with a different encoding and try again?

**Comment by RoyalWulf** [comment]
THe item wasn't imported. My work around was to take out the offending characters in the json file

**Comment by Alexander-Hjelm** [comment]
@RoyalWulf Which were the offending characters? :)

**Comment by RoyalWulf** [comment]
ESERV-719.json has this in it:

    {
      "Author": "Donna Barber",
      "Time": "2023-01-09T14:36:37.203+13:00",
      "Index": 3,
      "Fields": [
        {
          "ReferenceName": "System.History",
          "Value": "<style>div {\r\n    display: block;\r\n}\r\n\r\ntable.confluenceTable {\r\n    border-collapse: collapse;\r\n    margin: 5px 0 5px 2px;\r\n    width: auto;\r\n}\r\n\r\ntable {\r\n    display: table;\r\n    border-collapse: separate;\r\n    border-spacing: 2px;\r\n    border-color: grey;\r\n}\r\n\r\ntbody {\r\n    display: table-row-group;\r\n    vertical-align: middle;\r\n    border-color: inherit;\r\n}\r\n\r\ntr {\r\n    display: table-row;\r\n    vertical-align: inherit;\r\n    border-color: inherit;\r\n}\r\n\r\nth.confluenceTh {\r\n    border: 1px solid #ccc;\r\n    background: #f5f5f5;\r\n    padding: 3px 4px;\r\n    text-align: center;\r\n}\r\n\r\nth {\r\n    font-weight: bold;\r\n    text-align: -internal-center;\r\n}\r\n\r\ntd, th {\r\n    display: table-cell;\r\n    vertical-align: inherit;\r\n}\r\n\r\n    td.confluenceTd {\r\n        border: 1px solid #ccc;\r\n        padding: 3px 4px;\r\n    }\r\n\r\ndfn, cite {\r\n    font-style: italic;\r\n}\r\n\r\n    cite:before {\r\n        content: \"\\2014 \\2009\";\r\n    }\r\n</style><p>Done in /data/vufind/local/import/translation_maps/language_map.properties</p>\n\n<p>Added:</p>\n\n<p>mao = Te reo M\\u0101ori</p>"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },

I replaced
<p>mao = Te reo M\\u0101ori</p>
with
<p>mao = Te reo Maori</p>

**Comment by Alexander-Hjelm** [comment]
Ok! Relabeling as bug report. We will look into it.

**Comment by Alexander-Hjelm** [comment]
Fixed by: https://github.com/solidify/jira-azuredevops-migrator/commit/15e574101c41a8fe9ef19769931982e6340b1111
@RoyalWulf , can you verify that this commit fixes your issue?

Smoke tests: https://dev.azure.com/solidify/Internal/_build/results?buildId=12194&view=results

**Comment by Alexander-Hjelm** [comment]
New smoke tests: https://dev.azure.com/solidify/Internal/_build/results?buildId=12468&view=results

**Comment by Alexander-Hjelm** [comment]
Issue resolved, closing.

Please reopen if the problem persists.
