### ISSUE TITLE
Items exported is not matching with item imported into Azure Devops

### ISSUE THREAD

**Issue by kiranramagiri** [solidify/jira-azuredevops-migrator#727]
I am using a JIRA query in config.json file for both exporting the data and importing into JSON. When I ran the export command, the tool is exporting 15 issues, which is same as what  query returned in JIRA. But when I import data into Azure Dev ops, there are 28 items are imported. If there is a parent child relationship that is causing the extra imports, shouldn't they have been exported too?

**Query used:**
project = XXXX AND issuetype = Bug AND assignee in (XXXXXX) AND text ~ 'flag' ORDER BY created DESC

Above query is exporting 3 JSON files: 2 bugs and 1 EPIC linked to those bugs. But when I import the same config file into Azure devops. there were 53 items imported, and most of them are stories having no relation with 2 bugs exported.

**Comment by Alexander-Hjelm** [comment]
Very strange. Can you attach the following files:
- config file
- export log
- import log

**Comment by kiranramagiri** [comment]
@Alexander-Hjelm PFA. Unable to add the log files due to confidential data.
[config-scrum.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10992870/config-scrum.txt)
<img width="289" alt="Export counts" src="https://user-images.githubusercontent.com/63720100/225679000-cc216bb3-6f67-48c4-9a74-0656a433ebeb.PNG">
<img width="445" alt="Import count" src="https://user-images.githubusercontent.com/63720100/225679012-01637369-954b-45ce-a052-f5e386f20144.PNG">

**Comment by kiranramagiri** [comment]
@Alexander-Hjelm Another example:
Query: project in (XXXX) AND issuetype = Bug AND reporter in (64100c667222b08f3e705767) ORDER BY created DESC exporting one bug but import command says 59 items are being imported. 
I did an import before this which imported 58 items. Is it some cache(58 previous items+1 current item) by the tool? 
<img width="571" alt="Import issue" src="https://user-images.githubusercontent.com/63720100/225829067-2a6c2292-7ebd-4068-9710-ddd910cca423.PNG">

**Comment by Alexander-Hjelm** [comment]
Have you looked at the target ADO org and checked which the extra items are? Duplicate work items? Attachments?

**Comment by kiranramagiri** [comment]
Guess I am using the same export folder for multiple imports which is causing the issue. If I clean the export folder before each export and import, it's working fine.

**Comment by Alexander-Hjelm** [comment]
Yes of course. If you have old export data in your workspace, then that data will be migrated as well
