### ISSUE TITLE
link type (System.LinkTypes.Dependency) does not exist in project

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#729]
**Describe the problem**
A clear and concise description of what the problem/bug is.
I am getting thes errors:

[I][15:21:06] Processing 35/5040 - wi '44165', jira 'ESERV-17, rev 3'.
[E][15:21:06] '[Added] ESERV-17/44165->ESERV-18/44166 [System.LinkTypes.Dependency]' - link type (System.LinkTypes.Dependency) does not exist in project
[W][15:21:06] ''ESERV-17', rev 3' - not all changes were saved.

[I][15:21:09] Processing 46/5040 - wi '44165', jira 'ESERV-17, rev 5'.
[E][15:21:09] '[Added] ESERV-17/44165->ESERV-19/44167 [System.LinkTypes.Dependency]' - link type (System.LinkTypes.Dependency) does not exist in project
[W][15:21:09] ''ESERV-17', rev 5' - not all changes were saved.

[E][15:21:10] '[Added] ESERV-17/44165->ESERV-20/44168 [System.LinkTypes.Dependency]' - link type (System.LinkTypes.Dependency) does not exist in project
[W][15:21:10] ''ESERV-17', rev 6' - not all changes were saved.

The result is these 3 link do not appear in ADO for wi '44165'

**To Reproduce**
run
wi-import

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
3.0.115

**Attachments**
Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
[config-agile-eServ1-json (2).txt](https://github.com/solidify/jira-azuredevops-migrator/files/10961971/config-agile-eServ1-json.2.txt)
[wi-import-log-230310-152
[jira-export-log-230310-151316.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10961982/jira-export-log-230310-151316.txt)
048.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10961979/wi-import-log-230310-152048.txt)

**Screenshots**

**Comment by RoyalWulf** [comment]
FYI in Jira these links are Blocks
![image](https://user-images.githubusercontent.com/103555625/224862751-22f40512-ff23-48c4-8bac-20cf6d2491f6.png)

**Comment by Alexander-Hjelm** [comment]
System.LinkTypes.Dependency is Successor/Predecessor links

Could you use AZ CLI or WITadmin to find out wether or not these link types are enabled for your ADO organization/collection?

See:
- https://learn.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops#example
- https://learn.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops#witadmin-listlinktypes

**Comment by RoyalWulf** [comment]
![image](https://user-images.githubusercontent.com/103555625/225167816-34535a2b-54df-49ab-b9cb-aeee6aae6197.png)

does this mean that Blocks

I have this
{
        "source": "Blocks",
        "target": "System.LinkTypes.Dependency"
    }
should it be
{
        "source": "Blocks",
        "target": "System.LinkTypes.Dependency-Reverse"
    }
?

**Comment by RoyalWulf** [comment]
I put in {
"source": "Blocks",
"target": "System.LinkTypes.Dependency-Reverse"
}
and now it works
THank you
