### ISSUE TITLE
How to access the latest version of the tool

### ISSUE THREAD

**Issue by jagritdewan** [solidify/jira-azuredevops-migrator#731]
Hello, 

How can i use the latest release of the tool instead of the previous one? Do i need to delete the previous one off my desktop? 
@Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
Latest release here: https://github.com/solidify/jira-azuredevops-migrator/releases

**Comment by jagritdewan** [comment]
I downloaded the latest version and ran the export but it still uses the previous release of the tool. @Alexander-Hjelm
