### ISSUE TITLE
Custom field mapping in json file

### ISSUE THREAD

**Issue by pelinture** [solidify/jira-azuredevops-migrator#732]
Hi,

I am able to export-import from Jira to Azure by following your instructions. However, we have custom fields with the same name on Jira. I need to use field id in json. I cannot change the field names on Jira so as not to affect the process.
Ex: It does not accept "Epic Link (customfield_10532)" or "customfield_10532".

Can you assist me on how to do this?

Thanks in advance.

**Comment by Alexander-Hjelm** [comment]
See the FAQ for info on mapping custom fields: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

**Comment by pelinture** [comment]
Hi,
I want to elaborate a little more. As the Epic Link field, we use a custom issue picker field instead of the system field in Jira. For this reason, I wanted to add this custom field to the Epic Link field, which is mandatory at the beginning of the json. But I'm having a problem because their names are the same.

The format I tried afterward is as follows, unfortunately it didn't work.

  "epic-link-field": {
    "source-type": "id",
    "source": "customfield_10532",
    "custom": "true",
    "target": "Epic Link",
    "mapper": ""
  },

**Comment by Alexander-Hjelm** [comment]
Yeah that won't work, the `epic-link-field` property has to be a `string` value.

Not sure if this use case is supported yet tbh. The Epic Link property should simply be the identifier of your Epic Link field in Jira.
