### ISSUE TITLE
Access newest version of the migration tool

### ISSUE THREAD

**Issue by jagritdewan** [solidify/jira-azuredevops-migrator#733]
Hello, how can we access the latest release of the tool to conduct the migration? Do I have to delete the previous release file off my desktop?
Whenever I run the export, it still uses the previous release even though I have the newest version downloaded.  
@Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
Question already answered here: https://github.com/solidify/jira-azuredevops-migrator/issues/731

Please do not repost
