### ISSUE TITLE
"A field cannot be updated more than once in the same update." Error

### ISSUE THREAD

**Issue by pelinture** [solidify/jira-azuredevops-migrator#734]
Hi,

I have a single select custom field called Request Type in Jira. When migrating this field to Azure I get the following error in User Stories:
"A field cannot be updated more than once in the same update."

However, I can move this field from Jira to the child Tasks connected to the User Story. What would be the reason?

Thanks 

![Screenshot 2023-03-17 at 3 33 19 PM](https://user-images.githubusercontent.com/127928622/225905694-449cdbdc-62cc-47b7-8852-8cc5cfccc01f.png)

![Screenshot 2023-03-17 at 3 33 39 PM](https://user-images.githubusercontent.com/127928622/225905769-ab0eae4c-54f9-4f32-a8a1-46709b48a758.png)

**Comment by Alexander-Hjelm** [comment]
Verify that the source field ID is really "Talep Türü". It looks like this could be the displayName and not the identifier. Check the Rest API response for the relevant issue if you are unsure.

**Comment by pelinture** [comment]
This is a test project, we don't have any important data. I just deleted Author and Path fields from json. Thank you for your support :) 
[TA-1.json.zip](https://github.com/solidify/jira-azuredevops-migrator/files/11050336/TA-1.json.zip)

**Comment by pelinture** [comment]
Hi @Alexander-Hjelm , are there any updates on this issue?

**Comment by Alexander-Hjelm** [comment]
I noticed that in your `Fields` block you seem to have a lot of strange ReferenceNames. Are you sure that these are valid fields in your ADO instance? Field reference names cannot have spaces in them, I think:

```json
      "Fields": [
        {
          "ReferenceName": "System.Title",
          "Value": "[TA-1] Test 1"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": "2"
        },
        {
          "ReferenceName": "Önceliklendirme Açıklaması",
          "Value": "önceliklendirme açıkalaması 1"
        },
        {
          "ReferenceName": "İş İçin Gereksinim Listesi Kabul Kriterleri",
          "Value": "İş için gereksinim listesi kabul"
        },
        {
          "ReferenceName": "Kapsam Dışı Maddeler",
          "Value": "kapsam dışı maddeler 1"
        },
        {
          "ReferenceName": "Branş",
          "Value": "AZURE"
        },
        {
          "ReferenceName": "İş Hedefleri",
          "Value": "İş hedefleri"
        },
        {
          "ReferenceName": "Etkilenecek Uygulamalar",
          "Value": "Etkilenecek uygulamalar "
        },
        {
          "ReferenceName": "Projede entegrasyon var mı",
          "Value": "Hayır"
        },
...
```
