### ISSUE TITLE
Duplicate Epics are created in Azure Dev ops

### ISSUE THREAD

**Issue by kiranramagiri** [solidify/jira-azuredevops-migrator#736]
I've imported all the Epics into the system in the first run successfully. When I import user stories, I see a warning that Duplicate work item is being created and skipping the record, but still a duplicate Epic is created. So What is the ideal way to import work items into Azure? Is it a bad idea to import all the Epics first since Solidify is creating them again when a child story is created?

**Comment by Alexander-Hjelm** [comment]
The ideal way is to let the migration tool import all of your work items, since it handles the epic-story links
