### ISSUE TITLE
System.Iteration is Null in Bugs with Iteration assigned at creation

### ISSUE THREAD

**Issue by kiranramagiri** [solidify/jira-azuredevops-migrator#737]
I am using below mentioned snippet in config file to map the sprint as Iteration path. When exported, System.iterationPath for bugs is populated as Null, and import does not have the sprint either. However, it's working fine for User stories. Please advise.
Config file:
{
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "for": "Bug, User Story",
        "mapper": "MapSprint"
}
Exported Bug file:
{
"target":"System.iterationPath",
"value": null
}

**Comment by kiranramagiri** [comment]
Any update on this?

**Comment by kiranramagiri** [comment]
@Alexander-Hjelm Nothing in Export log, but I see a pattern here. For bugs that have sprint added while creating it in JIRA(Added the screenshot), System.iteration is populated as Null. For bugs that have Sprint added after creating the bug, value is being populated in the History and tool is tagging the right sprint to the item exported. A bug in the tool?

Steps followed: 

Created a bug by tagging sprint from below window:

<img width="484" alt="Create Bug Pop up" src="https://user-images.githubusercontent.com/63720100/227471740-09d5a784-31e6-4a2b-a969-e0972a5304fc.PNG">

When I exported the Bug:

{
          "ReferenceName": "System.IterationPath",
          "Value": null
        },

Now I created a bug without tagging sprint from Create Issue window. Tagged the sprint after creating the bug and exported the bug. And the Imported record has right sprint tagged to it.
Export file data:

{
      "Author": "61ba5ab283476e006983fa61",
      "Time": "2023-03-23T18:54:28.062+05:30",
      "Index": 1,
      "Fields": [
        {
          "ReferenceName": "System.AreaPath",
          "Value": "R9.0 - UAT"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },

**Comment by kiranramagiri** [comment]
@Alexander-Hjelm Any Update in this?

**Comment by Alexander-Hjelm** [comment]
Ok! Good find. Relabeling as Bug report.

Sadly I have no indication that we will work on this in the immediate future. We are always welcoming community contributions, or you are welcome to register for the preview of Jira Migrator PRO (paid service), where we offer priority support.

**Comment by Alexander-Hjelm** [comment]
Fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/762

@kiranramagiri, can you confirm that this PR resolves your issue?

**Comment by sgtwilko** [comment]
Hiya @Alexander-Hjelm ,
I've spotted that a field with `mapping` values doesn't work sometimes.
If I remove the `mapping` the value is always populated.

The times I've seen it work is if the field changes (revision>0), but it doesn't seem to get populated on Revision 0.

Is this change likely to fix this issue too?

**Comment by sgtwilko** [comment]
Ignore my comment, I've opened PR #773 which fixes my issue.

**Comment by Alexander-Hjelm** [comment]
@sgtwilko Perfect, I will review and merge as soon as there is time
