### ISSUE TITLE
IssueType field intermittently being picked up by migration tool

### ISSUE THREAD

**Issue by jstras17** [solidify/jira-azuredevops-migrator#738]
**Describe the problem**
issuetype field in JIRA is mapped to Requirement Type field in ADO

======================
Type mapping:  Improvement --> Requirement

      {
        "source": "Improvement",
        "target": "Requirement"
      },

Field mapping:  issuetype --> Requirement Type

	  {
        "source": "issuetype",
        "target": "Microsoft.VSTS.CMMI.RequirementType",
      },
======================

**To Reproduce**
Run Export and import for 2 JIRA Improvements
issuetype field is being picked up in only 1 of the 2 JIRAs

**  See in attached 'issuetype' field is only showing up in GPPWEB-2662.json file (attached)

**Tool version**
 - Version of the jira-azuredevops-migrator tool 3.0.115

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
- GPPWEB-2681.json
- GPPWEB-2662.json

**Screenshots**
[jira-export-log-230322-140820.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11043414/jira-export-log-230322-140820.txt)
[wi-import-log-230322-140825.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11043416/wi-import-log-230322-140825.txt)

[json.zip](https://github.com/solidify/jira-azuredevops-migrator/files/11043423/json.zip)

**Comment by Alexander-Hjelm** [comment]
Why set RequirementType=Task? This does not seem to be a valid value for `Microsoft.VSTS.CMMI.RequirementType`.

From MSDN:

![image](https://user-images.githubusercontent.com/10683896/227156986-e7309cb5-ae37-4efe-8bac-d2f1d389d304.png)

No errors in the export log, so not sure what is going on.

Are both the issues Tasks?

**Comment by Alexander-Hjelm** [comment]
See the above comment. You are trying to set `Microsoft.VSTS.CMMI.RequirementType` to e.g. Task och Requirement, with is not compliant with the Work Item object model.

**Comment by FokkoVeegens** [comment]
As far as I have seen, the IssueType field is only filled when a Jira issue changes type. So it's of no use in the mapping.
