### ISSUE TITLE
JIRA cloud Basic authentication with passwords is deprecated error

### ISSUE THREAD

**Issue by yogeshmoodoo** [solidify/jira-azuredevops-migrator#739]
Hello

The application is throwing this error on JIRa cloud login:

System.Security.Authentication.AuthenticationException: Response Content: Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()

when using:

jira-export -u jiraaccount@some.domain -p xxxxxxx --url https://my.jira.url --config config-scrum.json --force

Is there a fix for this?

**Comment by Alexander-Hjelm** [comment]
Duplicate of https://github.com/solidify/jira-azuredevops-migrator/issues/740
