### ISSUE TITLE
Story Points Not Imported

### ISSUE THREAD

**Issue by GBRacerX1** [solidify/jira-azuredevops-migrator#741]
Story Points are available in json file but not imported into system using latest v115

    {
      "Author": "xxxxxxxxx",
      "Time": "2023-01-31T14:31:17.195-05:00",
      "Index": 4,
      "Fields": [
        {
          "ReferenceName": "Microsoft.VSTS.Scheduling.Effort",
          "Value": "5"
        }
      ],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
    },

**Comment by Alexander-Hjelm** [comment]
Migration log and config file?
