### ISSUE TITLE
Can't Authenticate to a Private Jira Server

### ISSUE THREAD

**Issue by UromPLAt** [solidify/jira-azuredevops-migrator#744]
**Describe the problem**
Hi everyone, I'm getting a 403 when authenticating with a Personal Access Token (PAT), the same token works from Postman.
I'm not sure what the issue is.
This is being run from my work computer, the same one I'm accessing via Chrome (albeit authenticating with SAML from there).
Created a PAT, using the username, not the email..

The exact error is:

> Basic Authentication Failure - Reason : AUTHENTICATION_DENIED

Command:

`PS > .\jira-export.exe -u <just username> -p <PAT> --url <URL> --config <config>`

Any idea?

Jira Exporter v3.0.115
Jira 8.20.11 (local, not cloud)

**Files**

[jira-export.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11118694/jira-export.txt)
[config-basic.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11118696/config-basic.json.txt)

**Comment by Alexander-Hjelm** [comment]
Duplicate of https://github.com/solidify/jira-azuredevops-migrator/issues/730?

**Comment by UromPLAt** [comment]
> Duplicate of #730?

I don't know, they're getting a 401, I'm getting a 403.

Attempted to check the traffic with Fiddler, but I'm finding it hard to capture the traffic on this new work computer, I'm not an expert at networking, so currently I have no logs of the request.
I'm wondering if I can debug from Visual Studio Code, although I've never run a Visual Studio project - I can find a friend to show me around if it can advance me in this..

**Comment by UromPLAt** [comment]
Amazing! Thank you.
I'll do that and post more information later.

**Comment by Yanni8** [comment]
I'm getting error when trying to parse a `--token` flag. Am I using the wrong version (newest release)?

**Comment by UromPLAt** [comment]
> @Alexander-Hjelm I'm getting error when trying to parse a `--token` flag. Am I using the wrong version (newest release)?

The --token argument is for import into Azure, not for export from Jira, as far as I understand from the master code..

**Comment by Alexander-Hjelm** [comment]
The token parameter is for running `wi-import.exe`. See the documentation for a full list of CLI parameters and additional examples.

Here are a couple of examples:

```
.\src\WorkItemMigrator\JiraExport\bin\Debug\jira-export.exe -u alexander.hjelm@solidify.dev -p xxx --url https://solidifydemo.atlassian.net/ --config C:\dev\jira-azuredevops-migrator\docs\Samples\config-scrum.json --force
.\src\WorkItemMigrator\WorkItemImport\bin\Debug\wi-import.exe --token xxx --url https://dev.azure.com/solidifydemo --config C:\dev\jira-azuredevops-migrator\docs\Samples\config-scrum.json --force
```

**Comment by Yanni8** [comment]
@Alexander-Hjelm 
So is it true that you can't authentificate on a Jira server with a `Baere` token?

**Comment by Alexander-Hjelm** [comment]
Don't know what a bearer token would be. Use the Jira Api Token.

**Comment by Yanni8** [comment]
@Alexander-Hjelm A api token is a Bearer token you parse it in the header with

````
Authorization: Bearer <Token>
````

**Comment by Alexander-Hjelm** [comment]
Manage API tokens for your Atlassian account:

https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

**Comment by UromPLAt** [comment]
@Yanni8 I just feel like it's not related to this Jira issue, for me, this issue is about authentication to Jira using the documented way (Personal Access Token, not Bearer) and having troubles around that.
I feel like your inquires belong in a Jira discussion, a new one...owned by you, not related to this issue, it's unneeded clutter in my opinion..🤷

**Comment by UromPLAt** [comment]
@Alexander-Hjelm Let's keep things separated :)

I still haven't given up on this issue, I'll get to get some info..

**Comment by Alexander-Hjelm** [comment]
Nah, the Jira authentication would be here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraCommandLine.cs#L86
