### ISSUE TITLE
Attachment download failed. Reason -  Buffer cannot be null

### ISSUE THREAD

**Issue by polakko1** [solidify/jira-azuredevops-migrator#749]
**Describe the problem**
When trying to export Jira there is warning regarding Attachment download. Folders Attachments with proper attachment number is empty. It applies for every attachment 

**Tool version**
 - Version of the jira-azuredevops-migrator tool 3.0.115

**Screenshots**
Screenshot added with warning message
<img width="814" alt="attachmentwarning" src="https://user-images.githubusercontent.com/102855886/229276210-218061b9-6882-43a2-87b2-1684b439a64e.png">

Any idea how to fix it?

**Comment by Alexander-Hjelm** [comment]
Any information that could help us reproduce your issue? What kind of file is it?

**Comment by krishna-adusumalli** [comment]
@Alexander-Hjelm Same issue. We are also unable to download any of the attachment files, whether they are jpg, png, xlsx, pdf, etc. I can download them through the rest API (for example, https://<jira-server-url>/secure/attachment/389643/myfile.pdf).

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm As stated by Krishna above, even I am facing the same issue, we have been using migration tool from solidify to export issues from Jira, we are unable to export the attachments, we are getting the same error as posted in this ticket.

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm could you please address this issue in the priority..

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm we are awaiting for your response, could you please share us any workaround for this issue, its causing delay in the data migration from jira to ADO.

**Comment by Alexander-Hjelm** [comment]
Attachments are still migrated as expected in our tests for an Agile Jira projects. See the results below.

### Jira view:

![image](https://user-images.githubusercontent.com/10683896/231096923-760f8cad-7a88-468d-81ab-2ec580695d4b.png)

### ADO view:

![image](https://user-images.githubusercontent.com/10683896/231096896-7f455419-9198-4dd8-b85b-9bed05cc04b1.png)

Could you share more information about the attachments you are trying to migrate? Specifically:

- File extension
- File size (kB)
- File name (Maybe non-supported characters?)

Also ensure that you can download the attachment manually. You can test this out like this: https://support.atlassian.com/jira-software-cloud/docs/download-an-attachment-from-an-issue/. What does the file name become after downloading the issue vs the file name in Jira?

Let me know the attachment info and the results of the manual download!

**Comment by Alexander-Hjelm** [comment]
Also you could try downloading the attachments directly via the Jira Rest API. Try this and let me know the results. See this discussion for example:
https://community.atlassian.com/t5/Jira-questions/Need-to-export-all-attachments-from-a-single-Project-JIRA-Cloud/qaq-p/717930

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm  Please take a look below for the attachment file type/size/ext, also I am able to doenload the attachment manually but some how its failing via migration tool. The same export was working atleast before 10 days but not now.
![image](https://user-images.githubusercontent.com/130134555/231129710-822af915-2e1d-4b41-b315-a98b1092a714.png)

![image](https://user-images.githubusercontent.com/130134555/231130325-2bf2fbd9-bd51-49ef-be66-16aeff5ad658.png)

**Comment by Alexander-Hjelm** [comment]
@SHALINI11-maker Can you confirm that you are running on a Windows x64 system?

Any possibility of trying on a different machine and see if the results are different?

**Comment by SHALINI11-maker** [comment]
Yes @Alexander-Hjelm  I am using Windows x64 machine, i have been doing this action since February, complete export worked well as expected, for some reason attachments failed to get exported when I noticed it on early last week. even my colleague @krishna-adusumalli has tried in his WIN system, we are facing similar issue.

**Comment by polakko1** [comment]
@Alexander-Hjelm  yes, I am also using Widows x64.  With which Jira version it is tested? Issue is there for 
License Information for Jira
Jira v8.20.3

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm  Even we are using Jira Software 8.20.3

**Comment by Alexander-Hjelm** [comment]
Jira v8.x should be supported.

Maybe you fare better if you try v 2.x of our tool? Try e.g.: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/untagged-99b7827246f744fa1909, and let me know the result!

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm  Unable to open this link  https://github.com/solidify/jira-azuredevops-migrator/releases/tag/untagged-99b7827246f744fa1909 , says 404.

**Comment by Alexander-Hjelm** [comment]
Can you see version 2.x if you head over to the Releases page on the main repo page?

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm  As i mentioned before, I have tried both v 2.x/3.x , no luck..

**Comment by Alexander-Hjelm** [comment]
@SHALINI11-maker Have you tried isolating the offending issues in a JQL query? Maybe you are hitting the rate limit with too many requests, and then focusing on only a few issues should work better

// Alexander

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm My JQL query is very simple, i am just querying 1 jira issue which consists of attachments, i tried with different jira issue too, it fails..

**Comment by Alexander-Hjelm** [comment]
Not sure. Without being able to reproduce it's hard to tell at the moment

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm  can we have working session on this please? so that I can replicate and show you.

**Comment by SHALINI11-maker** [comment]
@Alexander-Hjelm  Awaiting for your response on this.
