### ISSUE TITLE
Unexpected migration error. [System.ArgumentNullException] System.ArgumentNullException

### ISSUE THREAD

**Issue by jfloubet** [solidify/jira-azuredevops-migrator#752]
**Describe the problem**
Hi,
I try to use this script to migration from an on prem Jira to Azure devops. When I launch the jira-export script, it works fine until it reaches the end of the json config file, and then, I have this error : 

**To Reproduce**
no easy way to reproduce, I assume the error has to be related that there is something missing in the configuration file, compared to our jira implementation, but i dont know where to find it

**Tool version**
Latest v3.0.115

**Attachments**

Please attach the following files:

- config.json github won't accept a json file, so i renamed it with a text extension
- jira-export-log.txt
- wi-import-log.txt no import, as the export is not working

**Screenshots**
[config-basic-github.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11157234/config-basic-github.json.txt)
[jira-export-log-230405-111814.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11157260/jira-export-log-230405-111814.txt)

**Comment by Alexander-Hjelm** [comment]
All I can tell by the error message is that the tool fails when trying to add or remove a link to/from issue IRIS-60338 to the output work item.

Can you identify anything funny going on with the links of the 60338 issue?

Issue occurs here:

https://github.com/solidify/jira-azuredevops-migrator/blob/16f7e99ac9ecdea6b1111753297142c928a9413e/src/WorkItemMigrator/JiraExport/RevisionUtils/LinkMapperUtils.cs#L44-L95

**Comment by Alexander-Hjelm** [comment]
Also you could try downloading the attachments via the Jira Rest API. See this discussion for example: https://community.atlassian.com/t5/Jira-questions/Need-to-export-all-attachments-from-a-single-Project-JIRA-Cloud/qaq-p/717930

Let me know what result this produces.

**Comment by eisemakr** [comment]
Did anyone find the solution for this problem? I have the same issue and even by deleting the link in Jira I could not fix it. 

[D][16:47:25]    Mapped value '4' to field 'Microsoft.VSTS.Common.Priority'.
[D][16:47:25]    Mapped value 'New' to field 'System.State'.
[E][16:47:25] Unexpected migration error.
[System.ArgumentNullException] System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: field
   bei JiraExport.LinkMapperUtils.AddRemoveSingleLink(JiraRevision r, List`1 links, String field, String type, ConfigJson config)
   bei JiraExport.JiraMapper.MapLinks(JiraRevision r)
   bei JiraExport.JiraMapper.MapRevision(JiraRevision r)
   bei JiraExport.JiraMapper.<>c__DisplayClass5_0.<Map>b__2(JiraRevision r)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei JiraExport.JiraMapper.Map(JiraItem issue)
   bei JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   bei JiraExport.LinkMapperUtils.AddRemoveSingleLink(JiraRevision r, List`1 links, String field, String type, ConfigJson config)
   bei JiraExport.JiraMapper.MapLinks(JiraRevision r)
   bei JiraExport.JiraMapper.MapRevision(JiraRevision r)
   bei JiraExport.JiraMapper.<>c__DisplayClass5_0.<Map>b__2(JiraRevision r)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei JiraExport.JiraMapper.Map(JiraItem issue)
   bei JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][16:47:25] Export complete. Exported 206 items (1 errors, 1 warnings) in 00:00:01.
