### ISSUE TITLE
How to migrate 2 or more fields on the same field in Azure DevOps, by appending those data? 

### ISSUE THREAD

**Issue by abhishek-prog7** [solidify/jira-azuredevops-migrator#753]
Its A question 

How to migrate 2 or more fields on the same field in Azure DevOps, by appending those data? Is it possible through this tool? Basically, I want to map custom fields in Azure DevOps or tfs. Since we may have a lot of custom fields which may not be available in azure devops.

Do we have ay way to achieve this?

**Comment by Alexander-Hjelm** [comment]
This feature is part of our Pro offering. The pro version of the tool is still in the making, but we can offer this feature as a part of our migration-as-a-service offering. Let me know if that sounds interesting and I'll give you the contact information :)

**Comment by abhishek-prog7** [comment]
> This feature is part of our Pro offering. The pro version of the tool is still in the making, but we can offer this feature as a part of our migration-as-a-service offering. Let me know if that sounds interesting and I'll give you the contact information :)

Can I know more about Pro featuring?

**Comment by Alexander-Hjelm** [comment]
Sure, I answered your discussion here :) https://github.com/solidify/jira-azuredevops-migrator/discussions/774
