### ISSUE TITLE
Exporter error when timeestimate or timeoriginalestimate is set to empty in Jira

### ISSUE THREAD

**Issue by FokkoVeegens** [solidify/jira-azuredevops-migrator#756]
We have mapped the timeestimate field in Jira to Microsoft.VSTS.Scheduling.RemainingWork in Azure DevOps. We have a revision in Jira where the timeestimate field is emptied. This results in an error message in the log. 

**To Reproduce**

The revision in the changelog in Jira looks like this (I put *** to anonymize the data):
```json
{
   "id": "1589***",
   "author": {
      "self": "https://***/jira/rest/api/2/user?username=***",
      "name": "***",
      "key": "***",
      "emailAddress": "***@***",
      "avatarUrls": {
         "48x48": "https://***/jira/secure/useravatar?ownerId=***&avatarId=***",
         "24x24": "https://***/jira/secure/useravatar?size=small&ownerId=***&avatarId=***",
         "16x16": "https://***/jira/secure/useravatar?size=xsmall&ownerId=***&avatarId=***",
         "32x32": "https://***/jira/secure/useravatar?size=medium&ownerId=***&avatarId=***"
      },
      "displayName": "***",
      "active": true,
      "timeZone": "Europe/Berlin"
   },
   "created": "2020-12-17T11:24:22.000+0100",
   "items": [
      {
         "field": "timeestimate",
         "fieldtype": "jira",
         "from": "3600",
         "fromString": "3600",
         "to": null,
         "toString": null
      },
      {
         "field": "timeoriginalestimate",
         "fieldtype": "jira",
         "from": "3600",
         "fromString": "3600",
         "to": null,
         "toString": null
      }
   ]
}
````

The error we get is:
```
[D][11:43:24]    Mapping revision 33.
[E][11:43:24] Error mapping field 'Microsoft.VSTS.Scheduling.RemainingWork' on item '***-***'.
[System.ArgumentNullException] System.ArgumentNullException: Value cannot be null.
Parameter name: seconds
   at JiraExport.FieldMapperUtils.MapRemainingWork(String seconds)
   at JiraExport.JiraMapper.<>c__DisplayClass13_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r): 
   at JiraExport.FieldMapperUtils.MapRemainingWork(String seconds)
   at JiraExport.JiraMapper.<>c__DisplayClass13_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)
```

This is because, this piece of code does not actually process NULL input:
https://github.com/solidify/jira-azuredevops-migrator/blob/16f7e99ac9ecdea6b1111753297142c928a9413e/src/WorkItemMigrator/JiraExport/RevisionUtils/FieldMapperUtils.cs#L17-L24

**Tool version**
 - Version of the jira-azuredevops-migrator tool: 3.0.115

**Attachments**

I think the above provides enough context to replicate the issue.

**Screenshots**

-

**Comment by Alexander-Hjelm** [comment]
Thanks! @FokkoVeegens 

Issue is related to JiraExport.

Will apply a fix as soon as time permits.

**Comment by Alexander-Hjelm** [comment]
@FokkoVeegens How did you manage to set `timeestimate` to `null` through the Jira web UI?

**Comment by FokkoVeegens** [comment]
Hi @Alexander-Hjelm, I did not set the value myself. We're running a pretty big migration for a customer of ours and all I know is that they have been customizing Jira quite a lot in history and the instance is already pretty dated. I can imagine that these type of issues have historically grown.

**Comment by Alexander-Hjelm** [comment]
PR: https://github.com/solidify/jira-azuredevops-migrator/pull/761

@FokkoVeegens, can you confirm that this PR fixes your issue?

**Comment by FokkoVeegens** [comment]
@Alexander-Hjelm Thanks for fixing this so quickly! There is one small issue with your solution; the value will become 0 in Azure DevOps where it is **null** in Jira. As far as I know, we can add a **null** value in Azure DevOps without issues.

**Comment by Alexander-Hjelm** [comment]
That might be the case! Simply returning `null` from `MapRemainingWork` in the event that `seconds` is `null` would work, do you think?
