### ISSUE TITLE
Importing multiple jsons

### ISSUE THREAD

**Issue by pelinture** [solidify/jira-azuredevops-migrator#757]
Hi, 

I export with 3 different jsons from Jira, I have to do this because the path and area fields of all of them are in different Azure environment. They all have different jqls but I can also aggregate them in a single jql.

3 different json's are exported to JiraExport folder. When I import only one json, it imports all the outputs in JiraExport to Azure. However, the path and area fields are whatever is written in the import json.

I also tried emptying JiraExport each time, this time custom links between issues are not created.

Looking forward to your support, thank you.

**Comment by Alexander-Hjelm** [comment]
You can either map the areapath, similar to https://github.com/solidify/jira-azuredevops-migrator/issues/715

Or an easier fix would be to transform your exported issue .json files manually and set the correct areapath
