### ISSUE TITLE
Adding filters to move only Epics from different projects.

### ISSUE THREAD

**Issue by vishwanathk26071981** [solidify/jira-azuredevops-migrator#76]
Can we move only list of  epics from different projects in JIRA to Azure boards? If yes can you please let me know how to apply the filter for this.

**Comment by MOlausson** [comment]
Yes, customize the JQL query in the config file to include the issuetype, for instance

  "query": "project = SCRUM and issuetype = Epic ORDER BY Rank ASC",

**Comment by MOlausson** [comment]
@vishwanathk26071981 did you manage to get this working? I'm closing the issue, feel free to re-open if you find any issues with the JQL implementation.
