### ISSUE TITLE
Failed to get item count using query: 'project=XXX ORDER BY assignee ASC'

### ISSUE THREAD

**Issue by ramakanth-slk** [solidify/jira-azuredevops-migrator#765]
Connecting to Jira...
Retrieving Jira fields...
Retrieving Jira link types...
Failed to get item count using query: 'project=XXX ORDER BY assignee ASC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'XXX' does not exist for the field 'project'.","Not able to sort using field 'assignee'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'XXX' does not exist for the field 'project'.","Not able to sort using field 'assignee'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
[I][15:44:25] Export started. Exporting 0 items.
[W][15:44:26] Epic link field missing for config field 'cf[10007]'.
[W][15:44:26] Sprint link field missing for config field 'cf[10006]'.
[W][15:44:26] User mapping file 'C:\Temp\JiraExport\users.txt' not found, ignoring mapping user identities.
[I][15:44:26] Initializing Jira field mapping...
[E][15:44:26] Failed to retrieve issues

**Comment by ramakanth-slk** [comment]
Can someone help on this?

**Comment by Alexander-Hjelm** [comment]
You should replace `XXX` with your project key in the query:

` 'project=XXX ORDER BY assignee ASC'`

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm For security reasons I didn't mention the name here, but in actual I'm using my project name instead of XXX in the query.

**Comment by Alexander-Hjelm** [comment]
Not the project name, but the project key

**Comment by ramakanth-slk** [comment]
What will be the Project Key? Means how can I find it?

**Comment by Alexander-Hjelm** [comment]
In the URL for example:

`https://solidifydemo.atlassian.net/jira/software/c/projects/AGILEDEMO/boards/7`

Here the project key is `AGILEDEMO`

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm I think I'm using Project key only but still it's throwing the same error.

**Comment by Alexander-Hjelm** [comment]
Try like this?
`  "query": "project = \"AGILEDEMO\" ORDER BY created DESC",`

**Comment by ramakanth-slk** [comment]
I tried like this as well but still the issue is not resolved. Do I need to do anything in the config file?

**Comment by ramakanth-slk** [comment]
[jira-export-log-230508-182009.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11421259/jira-export-log-230508-182009.txt)


Here is my log file

**Comment by Alexander-Hjelm** [comment]
It still seems to complain that there is no project with the given key.

Attach your config file as well?

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm Could you please help with the issue?

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm @Jura @chekkan @webmonger @madkoo can someone please help on this?

**Comment by Alexander-Hjelm** [comment]
The project name and key are both "SLKGT" in jira?

**Comment by Alexander-Hjelm** [comment]
@ramakanth-slk Please keep the discussion to solidify employees only, and do not bring in community contributors without any reason

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm  Sorry, my bad I thought they are also belongs to Solidify. 
My project name is different, key is "SLKGT" in JIRA

**Comment by Alexander-Hjelm** [comment]
The `source-project` property in your config should be the project name, not the project key

**Comment by ramakanth-slk** [comment]
I have tried with the name also but still not working. Please find the below updated config file
[config-file.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11477612/config-file.txt)

**Comment by Alexander-Hjelm** [comment]
Not sure what could be the issue here, other than wrong input of the jira project name or key, or missing user access to your jira project maybe.

**Comment by madkoo** [comment]
@ramakanth-slk  I would change the query: 
from: `"query": "project=SLKGT"` to `"query": "project = SLKGT"`

Do notice the spaces in the query.

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm I have product owner access to my Jira project, do I need any other specific access?

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm Yeah, but still I'm not i'm getting the issue

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm Now I'm able to export the JIRA data but while importing into ADO nothing is happening, terminal is not showing any errors
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/59635521/88aed17c-667c-443d-a296-3fe1e3529003)

**Comment by Alexander-Hjelm** [comment]
The importer cannot find any issue files. Are you sure you are running the correct import command? Same workspace?

**Comment by ramakanth-slk** [comment]
I'm using the below command 
wi-import --token XXXX --url XXXX --config config-agile.json --force

**Comment by ramakanth-slk** [comment]
This is my log file after the Export, is anything wrong in this file while exporting?
[jira-export-log-230523-130504.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11541949/jira-export-log-230523-130504.txt)

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm Could you please check the log file once and let me know if I need to change anything.

**Comment by Alexander-Hjelm** [comment]
Yeah some field is "Null" when it shouldn't be, as indicated by the error message:

System.ArgumentNullException: Value cannot be null

Will relabel as a bug, but currently lacking enough information to reproduct the issue

**Comment by Alexander-Hjelm** [comment]
Nah that looks fine. Fetch the issue over the Issues Rest API and check if you have any fields that are unset or null maybe?

**Comment by ramakanth-slk** [comment]
OK, I'll check

**Comment by Alexander-Hjelm** [comment]
Issue reported separately through support mailbox. See email from Miroslav Koutny (CZ), Thu 5/25/2023 7:12 PM

**Comment by Alexander-Hjelm** [comment]
@ramakanth-slk That was just for internal issue tracking :)

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm Ok, is there any update on this issue?

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm Is there any update on this issue?

**Comment by Alexander-Hjelm** [comment]
Not yet, but will work on it as soon as time allows

**Comment by Alexander-Hjelm** [comment]
Additional details:

Any change in the field 
 "epic-link-field": "Epic Link",
Trying to enter custom field name ended up in above error

**Comment by ramakanth-slk** [comment]
Hi @Alexander-Hjelm No I'm using default Epic Link only. 
I'm able to export and import data now, not sure what was the issue but the tool is working after trying recent release([v3.0.139](https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.139))

Thanks a lot for the support.

**Comment by Alexander-Hjelm** [comment]
Glad to hear! Reopen this issue if the problem should persist
