### ISSUE TITLE
Tasks/Stories added to Issue links of a Jira "Story" are not getting migrated

### ISSUE THREAD

**Issue by kalyanreddy1992** [solidify/jira-azuredevops-migrator#769]
**Describe the problem**
We are trying to migrate Stories from Jira for ADO cloud. We noticed the associated EPIC and sub-tasks are getting migrated but not the other stories/tasks added to issue links as "Associates with" and "Depends on". I have tried adding these sources under "link-map" section in config file but no luck, kindly help us understand in case we missed something here.

**To Reproduce**
1. A Jira story with an issue link(story/task) added as "Associate with" or "Depends on"
2. Export
3. import

**Tool version**
 - jira-azuredevops-migrator-3.0.115

**Comment by Alexander-Hjelm** [comment]
Check this issue for mapping depends-on maybe? https://github.com/solidify/jira-azuredevops-migrator/issues/557

Are the Stories/Tasks in the same project? Have you also set up the type mapping?

Are the Stories/Tasks exported as expected?

**Comment by kalyanreddy1992** [comment]
Hi @Alexander-Hjelm , Yes , the Stories are from same project and also we did setup the type mapping. All the stories are migrated but the relations (Associates with, has to be done before...) are missing for some reason. 

"link-map": {
    "link": [{
      "source": "Epic",
      "target": "System.LinkTypes.Hierarchy-Reverse"
    },
    {
      "source": "Parent",
      "target": "System.LinkTypes.Hierarchy-Reverse"
    },
    {
      "source": "Relates",
      "target": "System.LinkTypes.Related"
    },
    
    {
      "source": "Duplicate",
      "target": "System.LinkTypes.Duplicate-Forward"
    }]
  },
  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "User Story"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "Task"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },{
        "source": "Issue Links",
        "target": "Task"
      }
    ]
  },

**Comment by kalyanreddy1992** [comment]
Hi @Alexander-Hjelm , Any update on this?

**Comment by Alexander-Hjelm** [comment]
Looks like you might have to add an entry for `Associates with` in your link map then? Or what is otherwise the missing link type? Make sure it is in the link map.

**Comment by kalyanreddy1992** [comment]
@Alexander-Hjelm , I tried adding the following but did not work, please let me know if I missed something here
    {
      "source": "Associates with",
      "target": "System.LinkTypes.Related"
    },
