### ISSUE TITLE
Export crashing: 'JsonReaderException: Could not convert string to DateTime'

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#77]
I've noticed it happens when I try to export Jira tickets that its creation date is in the last 7 days.
In the Jira GUI when It happens I see in the creation date something like -
'6 days ago' or  '1 week ago'
And when it works as expected and doesn't crush I see in the creation date something like-
'22/Aug/19 5:18 PM'

Attached sample log,
[jira-export-log-190904-100254.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3574617/jira-export-log-190904-100254.txt)

**Comment by MOlausson** [comment]
@AmitNaveh23 can you share a scrubbed version of an export file that doesn't work for you so I can have a look at the exported date values?

**Comment by AmitNaveh23** [comment]
@MOlausson the export json file is not created, only the export log.

Here is a json file (and its export log) of Item that it's export works- 
[JiraExport.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3587394/JiraExport.zip)

**Comment by MOlausson** [comment]
@AmitNaveh23 got it, the export fails. Can you share a screenshot and export the jira using the rest api (https://your-jira-instance.atlassian.net/rest/api/latest/issue/YOUR-ISSUE-ID?expand=all) and share the json with me? DM me if it's easier.

**Comment by AmitNaveh23** [comment]
I sent you an email (to mathiaso@solidify.se) with all the information. thank you!

**Comment by AmitNaveh23** [comment]
I had it again but now the creation date is not in the past week and the error is a bit more detailed. 

the really bad thing is that it crashes the whole run in the middle, writes that it exported everything but only 4 out of 56 were exported 

here is the issue from API response and the export log. (no json file was created for that issue)
[JiraExport_Crashing.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3760799/JiraExport_Crashing.zip)

**Comment by AmitNaveh23** [comment]
I can't move forward because it happens every time if changes were made in the past week and the whole thing crashes.
"Could not convert string to DateTime: Yesterday 11:48 AM. Path '[3].created', line 150, position 35."

**Comment by AmitNaveh23** [comment]
@MOlausson do you think it has to do with my Jira server version (6.4.12)?

**Comment by AmitNaveh23** [comment]
I've managed to solve it, my workaround was configuring in Jira to stop using relative dates. 
instructions to do this:
https://confluence.atlassian.com/jirakb/display-standard-dates-in-jira-server-414187622.html?_ga=2.46870692.2091321814.1572945866-2109192200.1572945866
