### ISSUE TITLE
Description isn't loaded by different mappings

### ISSUE THREAD

**Issue by ACLF2406** [solidify/jira-azuredevops-migrator#770]
**Describe the problem**
If I try to use different mappings for description like this:  {
            "source": "customfield_12308",
            "target": "System.Description",
            "for": "User Story",
            "mapper": "MapRendered"
        },

        {
            "source": "Decription",
            "target": "System.Description",
            "for": "Sub-Task, Epic, Activity",
            "mapper": "MapRendered"
    
  ADO only add description for User Story and Sub-Task, Epic, Activity remain in blanks

**Tool version**
Tool version : 3.0.115

**Comment by Alexander-Hjelm** [comment]
Does the `Activity` issue type actually contain a description field, or could it be named something else?
