### ISSUE TITLE
Multiple fields found for comment. Selecting comment.

### ISSUE THREAD

**Issue by fernfrost** [solidify/jira-azuredevops-migrator#771]
I am getting continuous warnings about "multiple fields found for comment".
What does that mean?

**Tool version**
 - 3.0.115

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/59344851/4f5e2beb-b01b-4532-99ae-5eea842967ff)

**Comment by Alexander-Hjelm** [comment]
It means that revision contains multiple fields which candidate for the same mapping entry. It could be for example that you have two fields named `comment` and `Comment`, with only casing differing. The migrator will select whatever candidate comes first.

Full code segment:

```cs
        private string GetItemFromFieldCache(string propertyName, ILookup<string, string> cache)
        {
            string customId = null;
            var query = cache.FirstOrDefault(x => x.Key.Equals(propertyName.ToLower()));
            if (query != null)
            {
                customId = query.Any() ? query.First() : null;
                if (query.Count() > 1)
                {
                    Logger.Log(LogLevel.Warning, $"Multiple fields found for {propertyName}. Selecting {customId}.");
                }
            }
            return customId;
        }
```
