### ISSUE TITLE
Migration in stages

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#776]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/722

<div type='discussions-op-text'>

<sup>Originally posted by **RoyalWulf** March  8, 2023</sup>
When migrating, can i migrate in stages?
If I migrate **all** on Monday, When i come to continue on Friday, without the --force, will it migrate only Jira issues created since Monday?
Will it also migrate any issues **changed** since Monday?</div>

**Comment by Alexander-Hjelm** [comment]
Are we talking jira-export or wi-import here?

For Jira export, you can simply amend your `query` in the config file to order your issues based on CreatedDate and in any subsequent runs only include items past a certain date.

For the wi-import, you can do something similar by manually deleting a subset of your export .json issue files. This will cause the import to skip these items. Make sure to only delete items who's revisions have been fully imported.

**Comment by RoyalWulf** [comment]
talking about WI-import i suppose. My users are using it all the time so prefer not to delete but yes that it the work around.
It would be nice to have a flag that says override not duplicate. Duplicate is what happens if you don't delete first.  This is not a big issue just a suggestion for a feature.

**Comment by Alexander-Hjelm** [comment]
I don't mean deleting the issues on your source jira instance, just deleting the interim json files taht are created by `jira-export`

**Comment by Alexander-Hjelm** [comment]
Confirmed that you can pick up an old migration if running the importer without `--force`. This should work as long as the `ItemsJournal.txt` file is kept around in the workspace. You should even be able to migrate multiple projects into the same workpace, one after another. As long as the items journal file is left intact, all the history and links will be preserved.

Closing this issue. Repoen if you have more questions or the issue persists!
