### ISSUE TITLE
Activation Date / By not updating if issue state changes from in progress to new / to do

### ISSUE THREAD

**Issue by annamarieHelberg** [solidify/jira-azuredevops-migrator#78]
Good day

I am trying to migrate my parked jira issues to Azure Devops work items. This means that the history of the issue usually follows a flow of: New / To Do -> In Progress -> New / To Do. 
![history](https://user-images.githubusercontent.com/36559294/64515328-ad1d3c80-d2ec-11e9-9d1a-99a4374bd3c1.png)

When the tool is used the states do get updated correctly, but the Activated Date and Activated By attributes don't get updated. 
![not_update](https://user-images.githubusercontent.com/36559294/64515572-18ffa500-d2ed-11e9-8942-71856e86808e.png)

This is causing me to get an error in Azure Devops.
![error](https://user-images.githubusercontent.com/36559294/64514926-edc88600-d2eb-11e9-9c66-73e89a5a293b.PNG)

When you update the state using Azure Devops UI, the Activated Date and Activate By attributes are correctly updated:
![update](https://user-images.githubusercontent.com/36559294/64515685-55cb9c00-d2ed-11e9-8a0d-154021512ec2.png)

I have tried to use the Azure Devops python API to change these values but I couldn't find a solution. Is there a way to add this functionality to the current migrator code? Or, are you familiar with another way for me to update the Activated Date and By attributes?

Thank you in advance.

**Comment by MOlausson** [comment]
Hi @annamarieHelberg, thanks for reporting this. Do you have an exported issue (json) file you can share with me for troubleshooting?

**Comment by annamarieHelberg** [comment]
Hi @MOlausson. Thank you for getting back to me in such a short time. Here is the json for an exported issue that causes that error message. This issue was exported using the default/example config file.

`
{
    "Type": "Bug",
    "OriginId": "SCRUM-13",
    "WiId": -1,
    "Revisions": [
        {
            "Author": "author@email.com",
            "Time": "2019-05-30T04:58:33.374+02:00",
            "Index": 0,
            "Fields": [
                {
                    "ReferenceName": "System.Title",
                    "Value": "[SCRUM-13] As a developer, I can update details on an item using the Detail View >> Click the \"SCRUM-13\" link at the top of this card to open the detail view"
                },
                {
                    "ReferenceName": "System.AssignedTo",
                    "Value": "author@email.com"
                },
                {
                    "ReferenceName": "System.Description",
                    "Value": "*Editing using the Detail View*\n\nMany of the fields in the detail view can be inline edited by simply clicking on them. \n\nFor other fields you can open Quick Edit, select \"Edit\" from the cog drop-down."
                },
                {
                    "ReferenceName": "Microsoft.VSTS.Common.Priority",
                    "Value": "3"
                },
                {
                    "ReferenceName": "System.IterationPath",
                    "Value": "Sample Sprint 2"
                },
                {
                    "ReferenceName": "System.State",
                    "Value": "New"
                },
                {
                    "ReferenceName": "Microsoft.VSTS.TCM.ReproSteps",
                    "Value": "<style>div {\r\n    display: block;\r\n}\r\n\r\ntable.confluenceTable {\r\n    border-collapse: collapse;\r\n    margin: 5px 0 5px 2px;\r\n    width: auto;\r\n}\r\n\r\ntable {\r\n    display: table;\r\n    border-collapse: separate;\r\n    border-spacing: 2px;\r\n    border-color: grey;\r\n}\r\n\r\ntbody {\r\n    display: table-row-group;\r\n    vertical-align: middle;\r\n    border-color: inherit;\r\n}\r\n\r\ntr {\r\n    display: table-row;\r\n    vertical-align: inherit;\r\n    border-color: inherit;\r\n}\r\n\r\nth.confluenceTh {\r\n    border: 1px solid #ccc;\r\n    background: #f5f5f5;\r\n    padding: 3px 4px;\r\n    text-align: center;\r\n}\r\n\r\nth {\r\n    font-weight: bold;\r\n    text-align: -internal-center;\r\n}\r\n\r\ntd, th {\r\n    display: table-cell;\r\n    vertical-align: inherit;\r\n}\r\n\r\n    td.confluenceTd {\r\n        border: 1px solid #ccc;\r\n        padding: 3px 4px;\r\n    }\r\n\r\ndfn, cite {\r\n    font-style: italic;\r\n}\r\n\r\n    cite:before {\r\n        content: \"\\2014 \\2009\";\r\n    }\r\n</style><p><b>Editing using the Detail View</b></p>\n\n<p>Many of the fields in the detail view can be inline edited by simply clicking on them. </p>\n\n<p>For other fields you can open Quick Edit, select \"Edit\" from the cog drop-down.</p>"
                }
            ],
            "Links": [],
            "Attachments": [],
            "AttachmentReferences": true
        },
        {
            "Author": "author@email.com",
            "Time": "2019-05-30T04:58:33.374+02:00",
            "Index": 1,
            "Fields": [],
            "Links": [],
            "Attachments": [],
            "AttachmentReferences": false
        },
        {
            "Author": "author@email.com",
            "Time": "2019-05-30T04:58:33.374+02:00",
            "Index": 2,
            "Fields": [
                {
                    "ReferenceName": "System.History",
                    "Value": "Joined Sample Sprint 2 7 days 9 hours 10 minutes ago"
                }
            ],
            "Links": [],
            "Attachments": [],
            "AttachmentReferences": false
        },
        {
            "Author": "author@email.com",
            "Time": "2019-06-06T14:10:29.229+02:00",
            "Index": 3,
            "Fields": [
                {
                    "ReferenceName": "System.State",
                    "Value": "Committed"
                }
            ],
            "Links": [],
            "Attachments": [],
            "AttachmentReferences": false
        },
        {
            "Author": "author@email.com",
            "Time": "2019-06-06T14:10:30.389+02:00",
            "Index": 4,
            "Fields": [
                {
                    "ReferenceName": "System.State",
                    "Value": "New"
                }
            ],
            "Links": [],
            "Attachments": [],
            "AttachmentReferences": false
        }
    ]
}
`

**Comment by wasser-winfried** [comment]
This not only happens on  New / To Do -> In Progress -> New / To Do.
In my case, its also happening in CMMI process for Requirements, Tasks, ... in situations where I go back in lifecycle e.g. Proposed -> Active -> Proposed (ActivatedDate, ActivatedBy) or Proposed -> Active -> Resolved -> Active ( ResolvedDate, ResolvedBy)

I tried to modify exported issue (json) file by adding this fields with empty value on such back transitions but without effect.

Seems to me, that there is a deletion of the field required to solve this problem.

**Comment by annamarieHelberg** [comment]
@wasser-winfried  That is correct. It seems that the migration tool does not remove the attributes when you move the state from committed / in development, etc. back to open (I am specifically referring to a SCRUM project).

I have spent some time looking into how to do it manually via a python script and I got it to work.  However, having it built into the tool would be much easier.

Here is the script if anyone needs a quick fix:
```python
from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication

from azure.devops.v5_1.work_item_tracking.models import JsonPatchOperation

project = '<enter project name here>'
pat = '<enter azure personal access token here>'
org_url = '<enter azure organization url here>'

def establish_connection():
    personal_access_token = pat
    organization_url = org_url

    credentials = BasicAuthentication('', personal_access_token)
    return Connection(base_url=organization_url, creds=credentials)

def create_client():
    connection = establish_connection()
    return connection.clients_v5_1.get_work_item_tracking_client()

def retrieve_all_work_items(client, project_name, desired_ids):
    wit_client = client

    work_items = wit_client.get_work_items(ids=desired_ids, project=project_name, error_policy="omit", expand="All")

    return work_items

def update_activated_date(client, project_name, _work_item_id):
    wit_client = client

    json_patch = []

    doc = JsonPatchOperation()
    doc.op = "remove"
    doc.path = "/fields/Microsoft.VSTS.Common.ActivatedDate"

    doc2 = JsonPatchOperation()
    doc2.op = "remove"
    doc2.path = "/fields/Microsoft.VSTS.Common.ActivatedBy"

    json_patch.append(doc)
    json_patch.append(doc2)

    wit_client.update_work_item(document=json_patch, id=_work_item_id, project=project_name, validate_only=None, bypass_rules=None, suppress_notifications=None, expand="All")
    print("Successfully updated work item " + str(_work_item_id))

def main():
    client = create_client()

    ids = range(1,2) #or use a list or ids (max = 200)
    workitems = retrieve_all_work_items(client, project_name = project, desired_ids = ids)

    for wi in workitems:
        wi_id = wi.fields["System.Id"]
        update_activated_date(client, project, wi_id)

if __name__ == "__main__":
    main()
```
