### ISSUE TITLE
Imported images not showing in ADO work item (image using Jira API URL)

### ISSUE THREAD

**Issue by GaryHutson** [solidify/jira-azuredevops-migrator#780]
**Describe the problem**
The imported work item in ADO is not showing images inside rich text field like Description.  The image outline shows, but the path to the image file is incorrect.

Note that the image as an attachment is uploaded correctly in the import, however inside the rich text elements it does not display due to the incorrect URL e.g. has the image url is formatted with Jira rest API like "**/rest/api/3/attachment/content/83611**" (while the attachment URL format which is something like "**/68a356fa-9439-5105-87e2-2132d2608581/_apis/wit/attachments/3b1d2b86-8f42-5c2a-c036-b17de537b483?fileName=image.jpg**")

This was working a week ago, and seems to have stopped working, not sure if there is a change somewhere causing this.

**To Reproduce**
1. Set up Jira ticket with image in rich text field (see screenshot)
2. Run the export and import to generate ADO item
3. View work item in ADO
4. Rich text Description field does not show image (see screenshot)

**Tool version**
3.0.129

**Attachments**
- migrate-config.txt (original .json wouldn't upload here)
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**
Jira Description field screenshot
![Screenshot 2023-05-26 152615 - Jira](https://github.com/solidify/jira-azuredevops-migrator/assets/134711354/f77ac1dd-7e16-4744-b43d-ba01b399a98d)

ADO Description field screenshot 
![Screenshot 2023-05-26 163335 - ADO](https://github.com/solidify/jira-azuredevops-migrator/assets/134711354/b845b094-b980-4ae1-8d81-0f3504dd0f26)

[jira-export-log-230526-151422.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11576150/jira-export-log-230526-151422.txt)
[wi-import-log-230526-151500.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11576151/wi-import-log-230526-151500.txt)
[migrate-config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11576159/migrate-config.txt)

**Comment by Alexander-Hjelm** [comment]
Can confirm that the issue seems to happen here:

https://dev.azure.com/solidifydemo/AzureDevOps-Jira-Migrator-Smoke-Tests/_workitems/edit/183363/

Some images render correctly, while others do not. Examples:

- (Correct) https://dev.azure.com/solidifydemo/94f1c2da-b226-4e75-b1f7-c828b6c168b4/_apis/wit/attachments/bcba5af0-8c5b-4b04-9dd0-88a91124ae5d
- (Incorrect) https://dev.azure.com/secure/attachment/10130/10130_image-20230215-175940+%28fbfc1e1a-d0ba-4dfc-94a4-96006b9c8fa2%29.png

**Comment by Alexander-Hjelm** [comment]
@GaryHutson , try the previous release to go around this issue

**Comment by GaryHutson** [comment]
@Alexander-Hjelm - yes it is not working in v3.0.115 - which is odd.

**Comment by Alexander-Hjelm** [comment]
I will see if I can free up some time next week to look into this one. In the meantime, is it possible for you to remediate the issue by backtracking to an earlier release?

**Comment by GaryHutson** [comment]
Hi @Alexander-Hjelm - I have tried v3.0.78 and v3.0.109  
I still have the image url problem on each of those versions.

**Comment by Alexander-Hjelm** [comment]
Ok! Will look into the issue this week.

**Comment by Alexander-Hjelm** [comment]
@GaryHutson I fixed the issue so that the images are showing correctly, at least on end.

Is it possbile for you to verify the fix? Or should I make a release for you to try out?

PR: https://github.com/solidify/jira-azuredevops-migrator/pull/785

**Comment by GaryHutson** [comment]
@Alexander-Hjelm - can you make a release for me to try?
Thanks

**Comment by Alexander-Hjelm** [comment]
Absolutely, I will create a prerelease today :)

**Comment by Alexander-Hjelm** [comment]
[Release.zip](https://github.com/solidify/jira-azuredevops-migrator/files/11686285/Release.zip)

@GaryHutson Here is a preview with the fix applied. Try it and let me know if it fixes your issue

**Comment by GaryHutson** [comment]
Hi @Alexander-Hjelm - the contents of Release.zip are different from normal releases, e.g. there is no jira-export.exe file - I'm not sure how to run this

**Comment by Alexander-Hjelm** [comment]
Just take the `wi-import.exe` and run that instead of your old one :)

**Comment by GaryHutson** [comment]
@Alexander-Hjelm - sorry it didn't work for me; I just copied the wi-import application from the Releases.zip and replaced the one in jira-azuredevops-migrator-3.0.129 

Ran export, and then import and same results for me with the Jira rest API url not being replaced.

**Comment by Alexander-Hjelm** [comment]
[Release.zip](https://github.com/solidify/jira-azuredevops-migrator/files/11686963/Release.zip)

@GaryHutson Try this release instead, in the same manner as before

**Comment by GaryHutson** [comment]
@Alexander-Hjelm  - sorry same result: ADO image link in this format: https://dev.azure.com/rest/api/3/attachment/content/73900

**Comment by Alexander-Hjelm** [comment]
@GaryHutson try v3.0.136, it should be up in a minute

**Comment by GaryHutson** [comment]
@Alexander-Hjelm - thanks. Partial success for me. Not sure what changed from the experiment above but most of the images are working again.

However I have one field where the Jira API is not replaced - it is a custom Jira field on our end configured to populate the Acceptance Criteria - see image....
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/134711354/146e15ad-4e09-4773-82e0-d0a8480a8b66)

The image URL is https://dev.azure.com/rest/api/3/attachment/content/73651


The config for that custom field:

	  {
               "source": "Acceptance Criteria (Rio)",
                "target": "Microsoft.VSTS.Common.AcceptanceCriteria",
		"source-type": "name",
		"mapper": "MapRendered"
      },

**Comment by Alexander-Hjelm** [comment]
Ok, that's strange. Will have to take a look at what causes image links to not map for custom fields. But glad that at least comments are working now. Feels like a step in the right direction.

**Comment by Alexander-Hjelm** [comment]
Issue closed with merge of PR https://github.com/solidify/jira-azuredevops-migrator/pull/918, please reopen the issue and tag me if the problem persists.
