### ISSUE TITLE
The Value does not exist for the field project

### ISSUE THREAD

**Issue by robertgxschulze** [solidify/jira-azuredevops-migrator#781]
[**Describe](url) the problem**
using (among others)
  "query": "project = ITM",
  "using-jira-cloud": true,
in the config (the jira is on cloud)

the attempt to call the tool results in 
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'ITM' does not exist for the field 'project'."],"warningMessages":[]}

i am unable to determine if this is a rights problem or something else, the query works on the web frontend, the username is "Robert Schultze" as that was the best example of a username i could find, and the -p is my API-key

**To Reproduce**

unclear

**Tool version**
 3.0.155

**Attachments**
[jira-export-log-230530-131038.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11599366/jira-export-log-230530-131038.txt)

**Comment by Alexander-Hjelm** [comment]
Make sure that in your config, **source-project** is your **Jira Project Name**, and **query** contains the **Project Key**, otherwise the export will not work
