### ISSUE TITLE
Issue while downloading JIRA workitems to my local

### ISSUE THREAD

**Issue by varun173** [solidify/jira-azuredevops-migrator#784]
**Issue1 When i run the CMD line, it gives me error regards to User Mapping which ends up showing UNASSIGNED, but other work items under same user maps fine.**

**Issue2 No Target Type 'Defect' is set, field status cannot be mapped**

**Below is my traget type for issue#2**
{
"source": "status",
"target": "System.State",
"for": "Defect",
"mapping": {
"values": [
{
"source": "Open",
"target": "New"
},
{
"source": "Requirement Signed Off",
"target": "New"
},
{
"source": "Ready for Sprint Planning",
"target": "New"
},
{
"source": "In Progress",
"target": "Active"
},
{
"source": "In Development",
"target": "Active"
},
{
"source": "Ready for Testing",
"target": "Resolved"
},
{
"source": "Ready for Delivery",
"target": "Resolved"
},
{
"source": "In Analysis",
"target": "Active"
},
{
"source": "In Testing",
"target": "Resolved"
},
{
"source": "Ready for Sign-off",
"target": "Resolved"
},
{
"source": "Closed",
"target": "Closed"
},
{
"source": "CLOSED",
"target": "Closed"
},
{
"source": "More Info",
"target": "Active"
},
{
"source": "More info",
"target": "Active"
},
{
"source": "Dropped",
"target": "Closed"
},
{
"source": "On Hold",
"target": "New"
},
{
"source": "Invalid",
"target": "Closed"
}
]
}

**Comment by Alexander-Hjelm** [comment]
> Issue1 When i run the CMD line, it gives me error regards to User Mapping which ends up showing UNASSIGNED, but other work items under same user maps fine.

Need more details here. Otherwise check the docs for more information on user mapping: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md

>Issue2 No Target Type 'Defect' is set, field status cannot be mapped

This means that you need to provide a type mapping for the "Defect" jira issue type in your config. See the config samples in the docs :)

**Comment by varun173** [comment]
thank you for the response. 

Issue 1 seems to be solved for me.

Issue 2 - i didnt already add type map (screenshot below) but still i get this error.
[I][07:32:48] Initializing Jira field mapping...
[W][07:32:48] No target type 'Defect' is set, field status cannot be mapped.
[W][07:32:48] No target type ' Issue' is set, field status cannot be mapped.
[W][07:32:48] No target type 'Story' is set, field status cannot be mapped.
[W][07:32:48] No target type ' User Story' is set, field status cannot be mapped.
[W][07:32:48] No target type 'Studio Job' is set, field status cannot be mapped.
[W][07:32:48] No target type ' Dependency' is set, field status cannot be mapped.
[W][07:32:48] No target type 'Defect' is set, field acceptance criteria cannot be mapped.


this is my type map in the config - 

 "type-map": {
                "type": [
                    {
                        "source": "Epic",
                        "target": "Epic"
                    },
                    {
                        "source": "Feature",
                        "target": "Feature"
                    },
                    {
                        "source": "Story",
                        "target": "User Story"
                    },
                    {
                        "source": "Content Update",
                        "target": "User Story"
                    },
                    {
                        "source": "Backlog",
                        "target": "User Story"
                    },
                    {
                        "source": "Defect",
                        "target": "Bug"
                    },
                    {
                        "source": "Issue",
                        "target": "Bug"
                    },
                    {
                        "source": "Risk",
                        "target": "Issue"
                    },
                    {
                        "source": "Dependency",
                        "target": "Issue"
                    },
                    {
                        "source": "Task",
                        "target": "Task"
                    },
                    {
                        "source": "Assumption",
                        "target": "Task"
                    },
                    {
                        "source": "Key Decision",
                        "target": "Task"
                    },
                    {
                        "source": "Change request",
                        "target": "Task"
                    },
                    {
                        "source": "Studio Task",
                        "target": "Task"
                    },
                    {
                        "source": "Studio Job",
                        "target": "Task"
                    },
                    {
                        "source": "Sub-task",
                        "target": "Task"
                    },
                    {
                        "source": "Sub task",
                        "target": "Task"
                    },
                    {
                        "source": "Test Case",
                        "target": "Test Case"
                    },
                    {
                        "source": "Test Suite",
                        "target": "Test Suite"
                    },
                    {
                        "source": "Test Plan",
                        "target": "Test Plan"
                    }
                ]

**Comment by Alexander-Hjelm** [comment]
That is the status mapping, not the type-map. The type-map should be further up in your config. Look at the config samples if you are unsure.

**Comment by varun173** [comment]
the one i shared above is the type-map and i have also compared with the sample config and it is the same.

My Type-Map

            **"type-map": {
                "type": [**
                    {
                        "source": "Epic",
                        "target": "Epic"
                    },
                    {
                        "source": "Feature",
                        "target": "Feature"
                    },
                    {
                        "source": "Story",
                        "target": "User Story"
                    },
                    {
                        "source": "Content Update",
                        "target": "User Story"
                    },
                    {
                        "source": "Backlog",
                        "target": "User Story"
                    },
                    {
                        "source": "Defect",
                        "target": "Bug"
                    },
                    {
                        "source": "Issue",
                        "target": "Bug"
                    },
                    {
                        "source": "Risk",
                        "target": "Issue"
                    },
                    {
                        "source": "Dependency",
                        "target": "Issue"
                    },
                    {
                        "source": "Task",
                        "target": "Task"
                    },
                    {
                        "source": "Assumption",
                        "target": "Task"
                    },
                    {
                        "source": "Key Decision",
                        "target": "Task"
                    },
                    {
                        "source": "Change request",
                        "target": "Task"
                    },
                    {
                        "source": "Studio Task",
                        "target": "Task"
                    },
                    {
                        "source": "Studio Job",
                        "target": "Task"
                    },
                    {
                        "source": "Sub-task",
                        "target": "Task"
                    },
                    {
                        "source": "Sub task",
                        "target": "Task"
                    },
                    {
                        "source": "Test Case",
                        "target": "Test Case"
                    },
                    {
                        "source": "Test Suite",
                        "target": "Test Suite"
                    },
                    {
                        "source": "Test Plan",
                        "target": "Test Plan"
                    }
                ]
            },


From Sample Config - 

  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "Feature"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "User Story"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]

**Comment by varun173** [comment]
I didnt get you - 

I do have type-map and status-map, which one should i look into ? because i have the above target-type and status as well in the config. Also compared with the sample config and it matches.

Here are all the Maps - 

"link-map": {
                "link": [
                    {
                        "source": "Epic",
                        "target": "System.LinkTypes.Hierarchy-Reverse"
                    },
                    {
                        "source": "Parent",
                        "target": "System.LinkTypes.Hierarchy-Reverse"
                    },
                    {
                        "source": "Child",
                        "target": "System.LinkTypes.Hierarchy-Forward"
                    },
                    {
                        "source": "Relates",
                        "target": "System.LinkTypes.Related"
                    },
                    {
                        "source": "Duplicate",
                        "target": "System.LinkTypes.Duplicate-Forward"
                    }
                ]
            },
            "type-map": {
                "type": [
                    {
                        "source": "Epic",
                        "target": "Epic"
                    },
                    {
                        "source": "Feature",
                        "target": "Feature"
                    },
                    {
                        "source": "Story",
                        "target": "User Story"
                    },
                    {
                        "source": "Content Update",
                        "target": "User Story"
                    },
                    {
                        "source": "Backlog",
                        "target": "User Story"
                    },
                    {
                        "source": "Defect",
                        "target": "Bug"
                    },
                    {
                        "source": "Issue",
                        "target": "Bug"
                    },
                    {
                        "source": "Risk",
                        "target": "Issue"
                    },
                    {
                        "source": "Dependency",
                        "target": "Issue"
                    },
                    {
                        "source": "Task",
                        "target": "Task"
                    },
                    {
                        "source": "Assumption",
                        "target": "Task"
                    },
                    {
                        "source": "Key Decision",
                        "target": "Task"
                    },
                    {
                        "source": "Change request",
                        "target": "Task"
                    },
                    {
                        "source": "Studio Task",
                        "target": "Task"
                    },
                    {
                        "source": "Studio Job",
                        "target": "Task"
                    },
                    {
                        "source": "Sub-task",
                        "target": "Task"
                    },
                    {
                        "source": "Sub task",
                        "target": "Task"
                    },
                    {
                        "source": "Test Case",
                        "target": "Test Case"
                    },
                    {
                        "source": "Test Suite",
                        "target": "Test Suite"
                    },
                    {
                        "source": "Test Plan",
                        "target": "Test Plan"
                    }
                ]
            },
            "field-map": {
                "field": [
                    {
                        "source": "summary",
                        "target": "System.Title",
                        "mapper": "MapTitle"
                    },
                    {
                        "source": "assignee",
                        "target": "System.AssignedTo",
                        "mapper": "MapUser"
                    },
                    {
                        "source": "description",
                        "target": "System.Description",
                        "mapper": "MapRendered"
                    },
                    {
                    "source": "acceptance criteria",
                    "target": "System.Acceptance Criteria",
                    "mapper": "MapRendered"
                    },
                    {
                        "source": "priority",
                        "target": "Microsoft.VSTS.Common.Severity",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Blocker",
                                    "target": "1 - Critical"
                                },
                                {
                                    "source": "P1 - Blocker",
                                    "target": "1 - Critical"
                                },
                                {
                                    "source": "Critical",
                                    "target": "1 - Critical"
                                },
                                {
                                    "source": "P2 - Critical",
                                    "target": "1 - Critical"
                                },
                                {
                                    "source": "Highest",
                                    "target": "1 - Critical"
                                },
                                {
                                    "source": "Major",
                                    "target": "2 - High"
                                },
                                {
                                    "source": "High",
                                    "target": "2 - High"
                                },
                                {
                                    "source": "Medium",
                                    "target": "2 - High"
                                },
                                {
                                    "source": "Low",
                                    "target": "3 - Medium"
                                },
                                {
                                    "source": "Lowest",
                                    "target": "4 - Low"
                                },
                                {
                                    "source": "P3 - Major",
                                    "target": "4 - Low"
                                },
                                {
                                    "source": "P4 - Minor",
                                    "target": "4 - Low"
                                },
                                {
                                    "source": "P5 - Trivial",
                                    "target": "4 - Low"
                                },
                                {
                                    "source": "Trivial",
                                    "target": "4 - Low"
                                }
                            ]
                        }
                    },
                    {
                        "source": "labels",
                        "target": "System.Tags",
                        "mapper": "MapTags"
                    },
                    {
                        "source": "comment",
                        "target": "System.History",
                        "mapper": ""
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Task",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "OPEN",
                                    "target": "New"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "IN PROGRESS",
                                    "target": "Active"
                                },
                                {
                                    "source": "Not Ready",
                                    "target": "New"
                                },
                                {
                                    "source": "NOT READY",
                                    "target": "New"
                                },
                                {
                                    "source": "Ready",
                                    "target": "New"
                                },
                                {
                                    "source": "READY",
                                    "target": "New"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "New"
                                },
                                {
                                    "source": "ON HOLD",
                                    "target": "New"
                                }
                            ]
                        }
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Bug",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "Requirement Signed Off",
                                    "target": "New"
                                },
                                {
                                    "source": "Ready for Sprint Planning",
                                    "target": "New"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Development",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Delivery",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "In Analysis",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Sign-off",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "More Info",
                                    "target": "Active"
                                },
                                {
                                    "source": "More info",
                                    "target": "Active"
                                },
                                {
                                    "source": "Dropped",
                                    "target": "Closed"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "New"
                                },
                                {
                                    "source": "Invalid",
                                    "target": "Closed"
                                }
                            ]
                        }
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Defect",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "Requirement Signed Off",
                                    "target": "New"
                                },
                                {
                                    "source": "Ready for Sprint Planning",
                                    "target": "New"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Development",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Delivery",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "In Analysis",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Sign-off",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "More Info",
                                    "target": "Active"
                                },
                                {
                                    "source": "More info",
                                    "target": "Active"
                                },
                                {
                                    "source": "Dropped",
                                    "target": "Closed"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "New"
                                },
                                {
                                    "source": "Invalid",
                                    "target": "Closed"
                                }
                            ]
                        }
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Issue",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "Requirement Signed Off",
                                    "target": "New"
                                },
                                {
                                    "source": "Ready for Sprint Planning",
                                    "target": "New"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Development",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Delivery",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "In Analysis",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Sign-off",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "More Info",
                                    "target": "Active"
                                },
                                {
                                    "source": "More info",
                                    "target": "Active"
                                },
                                {
                                    "source": "Dropped",
                                    "target": "Closed"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "New"
                                },
                                {
                                    "source": "Invalid",
                                    "target": "Closed"
                                }
                            ]
                        }
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Story, User Story",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "Planning",
                                    "target": "New"
                                },
                                {
                                    "source": " Client Reopen",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "Pending Product Review",
                                    "target": "Active"
                                },
                                {
                                    "source": "Pending Business Review",
                                    "target": "Active"
                                },
                                {
                                    "source": "Pending Legal Review",
                                    "target": "Active"
                                },
                                {
                                    "source": "IN PROGRESS",
                                    "target": "Active"
                                },
                                {
                                    "source": "Requirement Signed off",
                                    "target": "New"
                                },
                                {
                                    "source": "Ready for Sprint Planning",
                                    "target": "New"
                                },
                                {
                                    "source": "READY FOR WORK",
                                    "target": "New"
                                },
                                {
                                    "source": "In Analysis",
                                    "target": "New"
                                },
                                {
                                    "source": "In Development",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "In Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Pending Authoring",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for PT",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Staging",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Production",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Sign-off",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Close",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Requirement Signed Off",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Ready for Delivery",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "More Info",
                                    "target": "Active"
                                },
                                {
                                    "source": "More info",
                                    "target": "Active"
                                },
                                {
                                    "source": "Dropped",
                                    "target": "Removed"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "New"
                                }
                            ]
                        }
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Studio Job,Dependency",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "Planning",
                                    "target": "New"
                                },
                                {
                                    "source": " Client Reopen",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "Pending Product Review",
                                    "target": "Active"
                                },
                                {
                                    "source": "Pending Business Review",
                                    "target": "Active"
                                },
                                {
                                    "source": "Pending Legal Review",
                                    "target": "Active"
                                },
                                {
                                    "source": "IN PROGRESS",
                                    "target": "Active"
                                },
                                {
                                    "source": "Requirement Signed off",
                                    "target": "New"
                                },
                                {
                                    "source": "Ready for Sprint Planning",
                                    "target": "New"
                                },
                                {
                                    "source": "READY FOR WORK",
                                    "target": "New"
                                },
                                {
                                    "source": "In Analysis",
                                    "target": "New"
                                },
                                {
                                    "source": "In Development",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "In Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Pending Authoring",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for PT",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Staging",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Production",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Sign-off",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Close",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Requirement Signed Off",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Ready for Delivery",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "More Info",
                                    "target": "Active"
                                },
                                {
                                    "source": "More info",
                                    "target": "Active"
                                },
                                {
                                    "source": "Dropped",
                                    "target": "Removed"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "New"
                                }
                            ]
                        }
                    },
                    {
                        "source": "status",
                        "target": "System.State",
                        "for": "Epic,Feature",
                        "mapping": {
                            "values": [
                                {
                                    "source": "Open",
                                    "target": "New"
                                },
                                {
                                    "source": "Closed",
                                    "target": "Closed"
                                },
                                {
                                    "source": "ON HOLD",
                                    "target": "Closed"
                                },
                                {
                                    "source": "On Hold",
                                    "target": "Closed"
                                },
                                {
                                    "source": "In Progress",
                                    "target": "Active"
                                },
                                {
                                    "source": "IN PROGRESS",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Analysis",
                                    "target": "Active"
                                },
                                {
                                    "source": "Requirement Signed Off",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Sprint Planning",
                                    "target": "New"
                                },
                                {
                                    "source": "Backlog",
                                    "target": "Active"
                                },
                                {
                                    "source": "CLOSED",
                                    "target": "Closed"
                                },
                                {
                                    "source": "Funnel",
                                    "target": "Closed"
                                },
                                {
                                    "source": "In Development",
                                    "target": "Active"
                                },
                                {
                                    "source": "More info",
                                    "target": "Active"
                                },
                                {
                                    "source": "Ready for Testing",
                                    "target": "Resolved"
                                },
                                {
                                    "source": "Ready for Sign-off",
                                    "target": "Active"
                                },
                                {
                                    "source": "In Testing",
                                    "target": "Resolved"
                                }
                            ]
                        }
                    },

**Comment by Alexander-Hjelm** [comment]
The `for` property should contain the ADO work item type, not the jira issue type

**Comment by varun173** [comment]
Found it, seems like i added Defect in the below "for" - removed it and worked!

Thanks a lot Alex :)
