### ISSUE TITLE
Unable to import from cloud JIRA using the module

### ISSUE THREAD

**Issue by msplmansit98** [solidify/jira-azuredevops-migrator#787]
**Describe the problem**
The document https://solidify.dev/blog/jira-azure-devops-migration says to get the username. However even after inspecting i was not able to get my username. Is there any other way I can export

**Tool version**
 - 3.0.136

**Attachments**
By using the email id, The HTML page gets loaded and says can't detect JSON and says maybe it is an authentication issue

`[E][09:06:36] Failed to retrieve fields from Jira (Response was not recognized as JSON). This usually indicates a problem with authentication or authorization. Check your Jira credentials and permissions.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response was not recognized as JSON. Content: <!DOCTYPE html>
<html lang="en">
<head>`

**Comment by Alexander-Hjelm** [comment]
The `--username` and `--password` arguments for `jira-export.exe` should be your jira account email (unique user id should work too I think) and the password should be either your login password or Jira API token. We advise you to try all possible combinations of these!

**Comment by msplmansit98** [comment]
I tried with all of this, but still the same problem
