### ISSUE TITLE
Mapping issue: Cannot migrate Related links

### ISSUE THREAD

**Issue by bob09555** [solidify/jira-azuredevops-migrator#789]
Hello ! 
I'm new to Azure....
I've run migration script import. I'm migrating well tickets with Child and Parent relationships - MAGIC !
I really need to migrate all other relations type of Jira (blocks, duplicated, tested by etc..) to be displayed in Related bucket in Azure. Now those are ignored. 

Can you pls tell me what is wrong (as I can see my mapping logic is not good) in my conf : 
(only in Bold works well)

"process-template": "Agile",
    "link-map": {
    "link": [
      {
        **"source": "Lien d'épopée",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
	   {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },**
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
	  {
        "source": "bloque",
        "target": "System.LinkTypes.Related"
      },
	   {
        "source": "valide",
        "target": "System.LinkTypes.Related"
      },
	    {
        "source": "est bloquée par",
        "target": "System.LinkTypes.Related"
      },
	    {
        "source": "blocks",
        "target": "System.LinkTypes.Related"
      },
	  
	    {
        "source": "blocked by",
        "target": "System.LinkTypes.Related"
      },
	    
	     {
        "source": "created",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "created by",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "déploie",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "est déployée par",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "has to be finished together with",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "has to be done before",
        "target": "System.LinkTypes.Predecessor"
      },
	     {
        "source": "has to be done after",
        "target": "System.LinkTypes.Successor"
      },
	     {
        "source": "earliest end is start of",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "start is earliest end of",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "has to be started together with",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "est liée",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "recharge",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "est rechargée par",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "tests",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "tested by",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "valide",
        "target": "System.LinkTypes.Related"
      },
	     {
        "source": "est validée par",
        "target": "System.LinkTypes.Related"
      },
	     
	  
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Related"
      },
	     
	  
      {
        "source": "clone",
        "target": "System.LinkTypes.Related"
      }, 
         {
        "source": "est clonée par",
        "target": "System.LinkTypes.Related"
      },     

	    {
        "source": "is cloned by",
        "target": "System.LinkTypes.Related"
      },   
	  
      {
        "source": "clones",
        "target": "System.LinkTypes.Related"
      },

 {
        "source": "duplique",
        "target": "System.LinkTypes.Related"
      },
 {
        "source": "est dupliquée par",
        "target": "System.LinkTypes.Related"
      },

{
        "source": "relates to",
        "target": "System.LinkTypes.Related"
      },

**Comment by Alexander-Hjelm** [comment]
Your config looks fine as far as I can see.

I would advice querying the IssueLinkTypes API and verifying that the `name` property of the LinkTypes matches with what you have written in your config: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-link-types/#api-rest-api-3-issuelinktype-get

**Comment by Alexander-Hjelm** [comment]
And ensure that your import job actually includes both the source and target issues
