### ISSUE TITLE
Epic Links not showing up

### ISSUE THREAD

**Issue by csaket** [solidify/jira-azuredevops-migrator#790]
**Tool version**
 - Latest master branch built locally

**Describe the problem**
We have a locally hosted Jira server 8.6.
I am trying with a small subset of data as we have a ton of items in Jira.

For an epic in Jira, migrating to ADO creates the epic.
What does not get migrated is the Issues in Epic section. This section on Jira lists all the stories that have their "Epic Link" set to the epic in question.

The query is for 1 epic only, but download-options is set to 7. Shouldn't that have resulted in the linked items being downloaded?

The config is using the default "epic-link-field": "Epic Link", as that is what shows up for me in Jira.

<details>

<summary>For the link map, I have the following setup also from the sample:</summary>

  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  }

</details>

I do not have any errors reported by the export or import.

I have seen people bring up similar issues, but not able to use the suggestions given.

In the export log I see such messages 

Undone link 'Added [Relation] ABC-123 -> ABC-456'.
Undone link 'Added [Relation] ABC-123 -> ABC-457'.
Undone link 'Added [Relation] ABC-123 -> ABC-458'.

These links are the ones missing in the migration. 
The tool seems to be removing them for some reason.

**Comment by Alexander-Hjelm** [comment]
The agile configuration sample has worked fine in my latest migrations, and Epic Links are included as well.

Maybe this issue is specific to older versions of Jira Server?

Are there any clues in the import log as to those links are undone?

**Comment by csaket** [comment]
It looks like the JQL I used limited to the past few weeks but these other links were all created before that time.
I wonder if its possible to have a query that will limit the time as far as the main ticket is concerned but will include the child items.
