### ISSUE TITLE
post migration from jira to azure devops , we're seeing lot of html tags along with commnets.

### ISSUE THREAD

**Issue by ravindrai** [solidify/jira-azuredevops-migrator#791]
**Describe the problem**
post migration from jira to azure devops , we're seeing lot of html tags along with commnets.

Error:
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/107991579/08ce67ed-6155-444d-9771-2eef92244792)

**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
See: https://github.com/solidify/jira-azuredevops-migrator/issues/764
