### ISSUE TITLE
Lots of warnings for List

### ISSUE THREAD

**Issue by csaket** [solidify/jira-azuredevops-migrator#792]
What does this warning indicate?

[W][14:40:12] Changelog ACC-1597: System.Collections.Generic.List`1[Newtonsoft.Json.Linq.JObject].

I get a ton of these when running the jira export.

I am running the latest master branch built locally.

**Comment by Alexander-Hjelm** [comment]
No idea. I had a look in the source code but cannot find any warning statements that resemble the above.

If the migration proceeds smoothly without errors, then it is likely that everything is fine

**Comment by csaket** [comment]
My mistake @Alexander-Hjelm !
I had added this locally in while debugging a few months back.
Sorry!
