### ISSUE TITLE
Jira comments are not exporting

### ISSUE THREAD

**Issue by tbbeasley** [solidify/jira-azuredevops-migrator#796]
**Describe the problem**
My export completed after the 3rd time and I have imported several items to Azure. However, none of the Jira comments section is imported in Azure work items. After checking the JSON files, I have not been able to find any of the comments.

**To Reproduce**
config file 
            {
                "source": "comment",
                "target": "System.History",
                "mapper": "MapRendered"
            },

**Tool version**
 - Version of the jira-azuredevops-migrator tool [v3.0.136]

**Attachments**

[jira-export-log-230626-164934.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11882808/jira-export-log-230626-164934.txt)

[wi-import-log-230623-205839.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11854371/wi-import-log-230623-205839.txt)
[config-scrum.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11854372/config-scrum.txt)

[UL-4909.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11882823/UL-4909.json.txt)

**Screenshots**
<img width="1458" alt="azure-history" src="https://github.com/solidify/jira-azuredevops-migrator/assets/61984602/2bf144b0-2e18-4b33-adf5-91a3e7d4b3c1">
<img width="851" alt="jira-comments" src="https://github.com/solidify/jira-azuredevops-migrator/assets/61984602/a261f268-d24b-4b60-abd0-43f906602921">
![jira-comments](https://github.com/solidify/jira-azuredevops-migrator/assets/61984602/87bd9afc-6bb8-432b-a28a-9bde9994fd93)

**Comment by tbbeasley** [comment]
Can anyone help me here? Are the comments on the tickets not exportable? There is usually valuable information that the developers and QA discuss.

**Comment by Alexander-Hjelm** [comment]
The comments should be migrated with the following field map:

```json
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
```

**Comment by tbbeasley** [comment]
That's what I have in my config. Additionally, for the JSON export item I attached there are at least 9 comments with text and images that did not get exported. I already tried to import almost 900 items of the 4500 total and all are missing comments. I am clearing out everything and going to run export again.

**Comment by Alexander-Hjelm** [comment]
Not sure what is going on here :)

Comments should migrate out of the box, and it works fine in all of our tests. Check the export log and see if you can identify any issues?

Do the comments appear in your issue .json files or not?

**Comment by tbbeasley** [comment]
After clearing the entire jiraexport folder and re-running the export, it looks like comments are now in the JSON files. Very strange, original export did not have comments. When I deleted only a few JSON files and ran export again, still no comments. Days later and clearing out all files, I now have comments.
