### ISSUE TITLE
Unrecognized command or argument 'jira-export.exe'

### ISSUE THREAD

**Issue by vishalsharma1993** [solidify/jira-azuredevops-migrator#799]
**Describe the problem**
When I run the Jira-export application using  visual studio it is showing below screen shot :

**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool 3.0.136

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/115527481/bcf330e4-4e72-475a-a0b4-01b8ad8fb0ee)

**Comment by Alexander-Hjelm** [comment]
Hard to tell. What arguments did you supply to the debugger?
