### ISSUE TITLE
Custom field, old value migrated rather than null

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#801]
**Describe the problem**
A clear and concise description of what the problem/bug is.

Custom field in Jira called FixVersons had a value of "V45", this value was removed in Jira so now it has no value, but V45 was migrated as final value.

**To Reproduce**
run Jira-export and WI-Import 

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
 3.0.136

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
- 
Config.jso
[config-agile_SMS2.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11973913/config-agile_SMS2.json.txt)

WI json file
[US-26755 - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11973920/US-26755.-.Copy.json.txt)

WI import log
[wi-import-log-230707-115001.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11973922/wi-import-log-230707-115001.txt)

Jira export file
[jira-export-log-230707-114749.txt](https://github.com/solidify/jira-azuredevops-migrator/files/11973923/jira-export-log-230707-114749.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
I think we need more repro steps here.

How did you go about deleting the version? Did you delete the release itself, or did you clear the value of the fixesVersion field?

**Comment by RoyalWulf** [comment]
Just cleared the value of the fix Versions field
![Screenshot 2023-07-10 091122](https://github.com/solidify/jira-azuredevops-migrator/assets/103555625/64c9bbac-2b36-4076-ac7f-6618f5cc1dac)

**Comment by Alexander-Hjelm** [comment]
OK! Will look into it in the upcoming 2 weeks :)

**Comment by Alexander-Hjelm** [comment]
Fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/811. Reopen if the problem persists

**Comment by RoyalWulf** [comment]
When will this fix be released?

**Comment by Alexander-Hjelm** [comment]
We released version 3.0.159 yesterday :)
