### ISSUE TITLE
deleted label migrated

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#802]
**Describe the problem**
A clear and concise description of what the problem/bug is.

Jira issue had a label "NEW", it was then removed, NEW was migrated

**To Reproduce**

run Jira export and WI-Import

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]

 3.0.136

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

[US-20013 - Copy.json.txt]
(https://github.com/solidify/jira-azuredevops-migrator/files/11973966/US-20013.-.Copy.json.txt)

[config-agile_SMS2.json.txt]
(https://github.com/solidify/jira-azuredevops-migrator/files/11973954/config-agile_SMS2.json.txt)

[wi-import-log-230707-115001.txt]
(https://github.com/solidify/jira-azuredevops-migrator/files/11973951/wi-import-log-230707-115001.txt)

[jira-export-log-230707-114749.txt]
(https://github.com/solidify/jira-azuredevops-migrator/files/11973949/jira-export-log-230707-114749.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
@RoyalWulf, I will take week 29 to go over as many of the open bug reports as possible, including yours. Right now struggling to free up time from my other engagements. :)

**Comment by Alexander-Hjelm** [comment]
Issue sucessfully reproduced, working on a fix
