### ISSUE TITLE
Not getting images in comment section for a project

### ISSUE THREAD

**Issue by ramakanth-slk** [solidify/jira-azuredevops-migrator#805]
**Describe the problem**
I'm not getting images in comment section while migrating for one of my projects. Could you please help on resolving this issue.

**Tool version**
 - Version of the jira-azuredevops-migrator tool [v3.0.139](https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.139)

**Attachments**

Please attach the following files:]
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/59635521/58020020-19eb-4386-ad37-b0da5062fef9)

- config.json
I'm using the same config files that I used for my other projects.

**Comment by Alexander-Hjelm** [comment]
How have you mapped your `comment` field?

**Comment by ramakanth-slk** [comment]
The below field right?
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/59635521/fec70dc8-3482-4342-8d4d-29bd82dc6f35)

**Comment by ramakanth-slk** [comment]
@Alexander-Hjelm I have mapped comment field as above.
