### ISSUE TITLE
Jira Export unable to map the parent issue correctly

### ISSUE THREAD

**Issue by srikardeshmukh** [solidify/jira-azuredevops-migrator#806]
**Describe the problem**
A clear and concise description of what the problem/bug is.
I am trying to export the custom project from Jira to Azure DevOps. While creating the export the parent issue/epic is being mapped with the issue id instead of the issue reference. But, as the origin id contains the reference, the actual parent is not being mapped.

The following are details of the issue. ( P.S. modified the name of the project for security constraints)
When I export the JIRA issue to xml, the parent field is shown as follows:
\<parent id="111210"\>MyProj-282\</parent\>

My config file has following link mapping:
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },    

After export, the issue contains the following value:
     "Links": [
        {
          "Change": 0,
          "TargetOriginId": "111210",
          "TargetWiId": 0,
          "WiType": "System.LinkTypes.Hierarchy-Reverse"
        }
      ],

Where as the files are created as MyProj-282.json

Hence, when performing the import, the import utility is unable to find "111210" file. So, it is not linking the parent epic.
I tried other ways by adding source-type. But, the link mapping does not support source-type.

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 3.0.139]

**Comment by anurao98** [comment]
Hi Team,

We have been encountering issues with Parent/Child links while migrating issues from JIRA to ADO for the Team managed project types. Migration Tool version: v3.0.139 used.

The epic link field and the link map in JSON file is provided like:

"epic-link-field": "Epic Link",

"link-map": {
     "link": [
       {
         "source": "Epic",
         "target": "System.LinkTypes.Hierarchy-Reverse"
       },
       {
         "source": "Parent",
         "target": "System.LinkTypes.Hierarchy-Reverse"
       },
       {
         "source": "Child",
         "target": "System.LinkTypes.Hierarchy-Forward"
       },
       {
         "source": "Relates",
         "target": "System.LinkTypes.Related"
       },
       {
         "source": "Blocks",
         "target": "System.LinkTypes.Related"
       },
       {
         "source": "Cloners",
         "target": "System.LinkTypes.Related"
       },
       {
         "source": "is duplicated by",
         "target": "System.LinkTypes.Related"
       },
       {
         "source": "Duplicate",
         "target": "System.LinkTypes.Duplicate-Forward"
       }
     ]
   }

If we check the JSON of the child item for the parent the link, it maps:

"Links": [
       {
         "Change": 0,
         "TargetOriginId": "xxxxx",
         "TargetWiId": 0,
         "WiType": "System.LinkTypes.Hierarchy-Reverse"
       }
The same migration if done with the 2.3.117 version, it works fine- but we end up encountering issues with broken inline images.

Could you help us to get this fixed or any alternate solutions available?

**Comment by Alexander-Hjelm** [comment]
Maybe related to https://github.com/solidify/jira-azuredevops-migrator/issues/772?

**Comment by anurao98** [comment]
Hi @Alexander-Hjelm,

Yes. Could you try reproducing this issue and help us out on getting them resolved?
