### ISSUE TITLE
link type (System.LinkTypes.Dependency) does not exist in project

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#813]
**Describe the problem**
A clear and concise description of what the problem/bug is.
Getting error:
[I][15:57:11] Processing 121/57276 - wi '62192', jira 'US-3469, rev 2'.
[E][15:57:11] '[Added] US-3469/62192->US-3470/62193 [System.LinkTypes.Dependency]' - link type (System.LinkTypes.Dependency) does not exist in project
[W][15:57:11] ''US-3469', rev 2' - not all changes were saved.

**To Reproduce**

run wi-import

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
3.0.139

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
[US-3470 - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156084/US-3470.-.Copy.json.txt)

[US-3469 - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156086/US-3469.-.Copy.json.txt)
[jira-export-log-230721-143348.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156088/jira-export-log-230721-143348.txt)
[wi-import-log-230721-155604.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156089/wi-import-log-230721-155604.txt)
[config-agile_SMS3 - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156090/config-agile_SMS3.-.Copy.json.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Issue is exactly what the error message is saying. :)
