### ISSUE TITLE
A field cannot be updated more than once in the same update

### ISSUE THREAD

**Issue by RoyalWulf** [solidify/jira-azuredevops-migrator#814]
**Describe the problem**
A clear and concise description of what the problem/bug is.

[I][15:58:57] Processing 518/57276 - wi '62222', jira 'US-5831, rev 16'.
[E][15:58:57] VS403691: Update to work item 62222 had two or more updates for field with reference name 'Custom.FoundinwhatPhase'. A field cannot be updated more than once in the same update.
[E][15:58:57] Work Item 62222 failed to save.

**To Reproduce**

run wi-import

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]

3.0.139

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
[jira-export-log-230721-143348.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156599/jira-export-log-230721-143348.txt)
- wi-import-log.txt
[wi-import-log-230721-155604.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156600/wi-import-log-230721-155604.txt)

[US-5831 - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156607/US-5831.-.Copy.json.txt)

[config-agile_SMS3 - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12156614/config-agile_SMS3.-.Copy.json.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
See: https://github.com/solidify/jira-azuredevops-migrator/issues/723
