### ISSUE TITLE
Only one values migrated for Components and fixVersions fields

### ISSUE THREAD

**Issue by jfallot** [solidify/jira-azuredevops-migrator#820]
**Describe the problem**
In case multiple values are defined in the Components or FixVersions fields of Jira, only one value get imported to a custom ADO field in Azure DevOps.
It seems that these multiple current values at the issue level are ignored by the tool and only the individual updates through revisions are processed as a single value updated.

**Information provided to illustrate the issue**
1. File DE-1881-fromJira.json.txt is the complete Json issue details from Jira
2. config.txt is the configuration used. Multiple tests have been made with or without "source-type" or "Mapper" attributes, no improvements
3. DE-1881.json.txt is the Json generated by the export
4. Both export and import log files are attached
5. Screenshot DE-1881-DevOps.jpg focuses on the result in DevOps

**Tool version**
 - 3.0.139

**Attachments**
[wi-import-log-230803-140302.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12251665/wi-import-log-230803-140302.txt)
[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12251666/config.txt)
[DE-1878.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12251667/DE-1878.json.txt)
[DE-1881.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12251668/DE-1881.json.txt)
[DE-1881-fromJira.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12251669/DE-1881-fromJira.json.txt)
[jira-export-log-230803-140250.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12251670/jira-export-log-230803-140250.txt)

**Screenshots**
![DE-1881-DevOps](https://github.com/solidify/jira-azuredevops-migrator/assets/1005875/c205318e-4efc-47e9-8f34-a839f6018847)

**Comment by Alexander-Hjelm** [comment]
Marking as a bug until we know what is going on. Should be relatively straightforward to reproduce.

Have you tried using the `MapArray` mapper, as described in https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#mappers?

Note that the FixVersions field is not officially supported in the Open Source version of the tool. Our Jira Azure DevOps Migrator PRO offering has much better support for migrating releases and the FixesVersion field.

**Comment by eplnde** [comment]
Yes, tried MapArray as well, same problem then
(answering for "jfallot" who is on vacation)

**Comment by Alexander-Hjelm** [comment]
This is the `components` field that you want to migrate, correct?

```
"components":[
   {
      "self":"https://xxx.atlassian.net/rest/api/2/component/11967",
      "id":"11967",
      "name":"Jira",
      "description":"Jira Management (project, users...)"
   },
   {
      "self":"https://xxx.atlassian.net/rest/api/2/component/11965",
      "id":"11965",
      "name":"Misc"
   }
]
```

What do you expect the output to be in your ADO workitem field?

**Comment by eplnde** [comment]
Correct, that is one example
I expect the output to be in the format of "Jira;Misc"

Just like the initial value of FixVersion (which then gets messed up in the Changelog handling)
[D][14:02:54]    Mapped value 'latest;main' to field 'Custom.FixVersions'.

**Comment by Alexander-Hjelm** [comment]
I suspect that this operation is not possible today. We would need a new mapper, similar to the one discussed in https://github.com/solidify/jira-azuredevops-migrator/issues/824, but taking a JSON array as input and producing a semicolon-delimited string. I will create a feature request for this so that we can track it.

Writing your own mapper is relatively straightforward, if you wish to have a crack at it yourself! Simply add a new condition to the switch at https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraMapper.cs#L87C27-L87C27, and write your own logic

**Comment by Alexander-Hjelm** [comment]
Closing. Feature is now implemented in the Jira Migrator PRO Offering
