### ISSUE TITLE
Is it possible to assign target field values based on JIRA Type values, please advise, thanks?

### ISSUE THREAD

**Issue by johnwanng** [solidify/jira-azuredevops-migrator#822]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/821

<div type='discussions-op-text'>

<sup>Originally posted by **johnwanng** August 15, 2023</sup>
Hi,

I have 2 **JIRA** Types namely **SIT BUG** and **UAT BUG** which are to be migrated to the single DevOps type of **BUG**. If their JIRA statuses values are both **PENDING DEPLOYMENT** is that a way where I can define in the json file using a similar logic so I can assign the value to the **DevOps** **system.state** field according to the value of its **JIRA**'s Type:

If JIRA type = **SIT BUG** then
  If Source= **PENDING DEPLOYMENT** then
      Target = **SIT - Doing**
  End if
End if

If JIRA type = **UAT BUG** then
  If Source = **PENDING DEPLOYMENT** then
      Target = **UAT - Doing**
  End if
End if

Thank you for your assistance.</div>

**Comment by Alexander-Hjelm** [comment]
That is doable with the default state mapper. Have a look in the example configurations and see how state mapping is done there, then adapt the state mapping to your own workflow.

**Comment by johnwanng** [comment]
Hi Alexnder,

Thank you for your prompt reply but can you provide the relevant URL or some examples as I am not sure how and where to look for as I am very inexperienced with the migration tool and am still learning about the basics of the syntax used in **json** file, thank you for your assistance.

**Comment by Alexander-Hjelm** [comment]
You can add any of your Azure DevOps work item type under the `for` property, e.g. `SIT Bug` and `UAT Bug`

**Comment by johnwanng** [comment]
But the **SIT Bug** and **UAT Bug** are **JIRA** types and not **DevOps** work item types.

**Comment by johnwanng** [comment]
Hi Alex,

Can you advise whether it is still doable (_perhaps is it possible to specify the **Jira Type** under the **for** property as you have suggested?)? Otherwise, I need to use another approach, e.g. execute 2 separate migration runs - first one just for **SIT Bug** and the second one just for **UAT Bug**, thanks.

**Comment by Alexander-Hjelm** [comment]
I see. Don't think this feature is in place yet, but there are some manual workarounds:

- Export the issues to different Work Item Types, then bulk modify the imported work items in Azure DevOps and change their issue types to Bug. You can temporarily create a new Work Item Type for this.
- Export the issues to different Work Item Types, then prior to importing, you can manually search-replace any occurrences of "UAT Bug" and "SIT Bug" with just "Bug" in the retrieved json documents.

**Comment by rfennell** [comment]
I had the same issue on a migration where I wanted all Jira issues to map to the same same AZDO WIT, but also record the original Jira type

## Migration Configuration
In the migration type mapping I append the Jira type to the end of the AZDO Type e.g.

```json
    "type-map": {
        "type": [
            {
                "source": "Issue",
                "target": "Support Issue - Issue"
            },
            {
                "source": "Epic",
                "target": "Support Issue - Epic"
            },
            {
                "source": "Business Requirement - Business Requirement",
                "target": "Support Issue"
             }
    ]
}
````

## Post export, pre import processing
After the export completed I ran the follow script to split the target WIT to the 'real part' and the  'Jira part', using the latter to added a new  field entry to JSON file.

```powershell
param (
    # [Parameter(Mandatory = $true)]
    $folder = "C:\JiraExport\"
)

$files = Get-ChildItem -Path $folder -Filter *.json

# Initialize the progress bar
$totalFiles = $files.Count
$progress = 0
$files | ForEach-Object {

    # Update the progress bar
    $progress++
    $percentComplete = ($progress / $totalFiles) * 100
    Write-Progress -Activity "Processing JSON files" -Status "Progress: $percentComplete%" -PercentComplete 
    $percentComplete
   
    write-host "Processing $($_.FullName)"
       
    # Read the JSON file
    $content = Get-Content -Path $_.FullName | ConvertFrom-Json

    # Split the merged type property
    $split = ($content.Type).Split("-")

    if ($split.Count -ne 2) {
        write-host " - issue type is not in the expected format"
        continue
    }

    write-host " - setting issue type as '$($split[1].trim())'"

    $content.Type = $split[0].Trim()
    $content.Revisions[0].Fields += @{
        ReferenceName = "Custom.JiraType"
        Value = $split[1].Trim()
    }
    # Convert the JSON object back to a string and save it to the file
   $content | ConvertTo-Json -Depth 100 | Set-Content $_.FullName
}
``` 

I then ran the import as normal
