### ISSUE TITLE
migrate parent ticket with no child present in azure devops then it shows error

### ISSUE THREAD

**Issue by Thadukaajay** [solidify/jira-azuredevops-migrator#826]
**Describe the problem**
A clear and concise description of what the problem/bug is.

**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Closing due to missing information
