### ISSUE TITLE
No target type 'Initiative' is set, field status cannot be mapped.

### ISSUE THREAD

**Issue by NathanDotTo** [solidify/jira-azuredevops-migrator#829]
**Describe the problem**
I have the W message: No target type 'Initiative' is set, field status cannot be mapped.

I see this when exporting from Jira.

I am not sure what that means. In my case "Initiative" is an issue type in the source Jira. I have a type-map from "Initiative" to "Feature".

What might I be missing here please?

**To Reproduce**
Export from Jira.

**Tool version**
Latest as of August 18.

**Attachments**

Please attach the following files:

- config.json

This log contains identity data, so I can't attach it.
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by NathanDotTo** [comment]
{
  "source-project": "xx",
  "target-project": "xxx",
  "query": "project=xx",
  "using-jira-cloud": false,
  "workspace": "x",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "",
  "base-area-path": "x",
  "base-iteration-path": "",
  "ignore-failed-links": true,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Child",
        "target": "System.LinkTypes.Hierarchy-Forward"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Initiative",
        "target": "Feature"
      },
      {
        "source": "Theme",
        "target": "Feature"
      },
      {
        "source": "Request",
        "target": "Feature"
      },
      {
        "source": "Story",
        "target": "Feature"
      },
      {
        "source": "Requirement",
        "target": "Feature"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "User Story"
      },
      {
        "source": "Test",
        "target": "User Story"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },
      {
        "source": "Improvement",
        "target": "User Story"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "components",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Initiative,Feature,Epic,User Story,Bug,Issue,Task,Sub-task,Requirement",
        "mapping": {
          "values": [
            {
              "source": "Open",
              "target": "New"
            },
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "In Progress",
              "target": "Active"
            },
            {
              "source": "Review",
              "target": "In Review"
            },
            {
              "source": "Cancelled",
              "target": "Removed"
            },
            {
              "source": "Resolved",
              "target": "Closed"
            },
            {
              "source": "Closed",
              "target": "Closed"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Implemented",
              "target": "Closed"
            },
            {
              "source": "Obsolete",
              "target": "Closed"
            },
            {
              "source": "In Testing",
              "target": "In Testing"
            },
            {
              "source": "In Code Review",
              "target": "In Code Review"
            },
            {
              "source": "On Hold",
              "target": "On Hold"
            },
            {
              "source": "Backlog",
              "target": "Backlog"
            },
            {
              "source": "Prioritised",
              "target": "Prioritised"
            },
            {
              "source": "Ready for Testing",
              "target": "Ready for Testing"
            },
            {
              "source": "In Analysis",
              "target": "In Analysis"
            },
            {
              "source": "Pre-Analysis",
              "target": "Pre-Analysis"
            },
            {
              "source": "Accepted",
              "target": "Accepted"
            },
            {
              "source": "Rejected",
              "target": "Rejected"
            },
            {
              "source": "Completed",
              "target": "Completed"
            },
            {
              "source": "Approved",
              "target": "Approved"
            },
            {
              "source": "Reopened",
              "target": "Reopened"
            },
            {
              "source": "Submitted",
              "target": "Submitted"
            },
            {
              "source": "Enhance",
              "target": "Enhance"
            },
            {
              "source": "Approved (In Backlog for Prioritization)",
              "target": "Approved"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Story Points",
        "not-for": "Epic"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}

**Comment by Alexander-Hjelm** [comment]
Not a big issue per se. I believe the "for" property of the field map should contain the ADO Work Item type and not the Jira Issue type :)

**Comment by NathanDotTo** [comment]
Thank you. In this case the for field has:

```
        "for": "Initiative,Feature,Epic,User Story,Bug,Issue,Task,Sub-task,Requirement",
```

Either way, it has both "Initiative" and "Feature".

**Comment by Alexander-Hjelm** [comment]
The field should be properly mapped then. You can safely ignore the warning

**Comment by NathanDotTo** [comment]
OK, this implies that there is a defect here then. Why get a warning that I can ignore?

**Comment by Alexander-Hjelm** [comment]
It's a hint that you have specified an invalid mapping (e.g. for a issue type that does not exist in Jira). The tool will skip any such invalid field mappings and still comply, but in some cases this error could indicate that something funny is going on or that you have done something unintended, depending on your setup.

**Comment by NathanDotTo** [comment]
Thank you :-) I am still puzzled, as I don't fully understand what might be missing.

**Comment by Alexander-Hjelm** [comment]
Remove "Initiative" from the `for` property, as this is not an Azure DevOps Workitem type
