### ISSUE TITLE
Resolved date migration from JIRA to ADO

### ISSUE THREAD

**Issue by surendra-github** [solidify/jira-azuredevops-migrator#834]
Hi Team,

From JIRA 2 ADO migration we tried to migrate resolved date but we are facing issues while migrating into any system field or any  custom field.

 

Please let us know how can we do it

**Comment by Alexander-Hjelm** [comment]
@surendra-github please share your field mapping.

Does the resolved date appear in the .json files that the tool creates? Or is the problem on the ADO import side?

**Comment by Alexander-Hjelm** [comment]
On closer inspection, I think that the Microsoft.VSTS.Common date fields should be set automatically as soon as your work item enters the "Resolved" state, right? So Maybe you have omitted Resolved from your state mapping? Is that why Microsoft.VSTS.Common.ResolvedDate is never set? Because I'm pretty sure it's supposed to be set under the hood.

**Comment by surendra-github** [comment]
Hi Alexander,

For all existing work items in ADO resolved date is visible, but when we import issues from JIRA it is not capturing resolved date even we are not mapping resolved date in config file.

can you please explain little more , how can we do it ?

Thanks,

**Comment by Alexander-Hjelm** [comment]
The resolved date is simply the datetime when your issue was moved to the Resolved state. Perhaps the issue was never Resolved?

**Comment by surendra-github** [comment]
Resolved date for issue in jira is present there in jira. 
But we can't migrate it using mapping can you try it from you end? Or do we need to change configuration file? 
Can you suggest some changes in it?

**Comment by Alexander-Hjelm** [comment]
I have managed to make the tool generate the following exception:

```txt
[E][08:53:21] Error mapping field 'Microsoft.VSTS.Common.ResolvedDate' on item 'AGILEDEMO-14'.
[System.InvalidCastException] System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.String'.
   at JiraExport.JiraMapper.<>c__DisplayClass14_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r):
   at JiraExport.JiraMapper.<>c__DisplayClass14_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)
```

Does that look familliar to you @surendra-github ?

I will try to create a fix as soon as I can :)

**Comment by Alexander-Hjelm** [comment]
I was able to succesfully migrate the ResolvedDate field using the following configuration:

```json
  {
      "source": "resolutiondate",
      "type": "datetime",
      "target": "Microsoft.VSTS.Common.ResolvedDate"
  },
```

This successfully creates the target field in ADO:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/cbdee795-65c0-41c6-8ff6-4b1cba26e3ae)

```json
        {
          "ReferenceName": "Microsoft.VSTS.Common.ResolvedDate",
          "Value": "2019-12-10 13:54:24"
        },
```
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/3932eb46-9234-4fe7-ac97-d8278e890202)

I am demoting this issue to a support ticket. Feel free to mention me again if the issue persists!

**Comment by Alexander-Hjelm** [comment]
Documenting solution in docs/faq.md

**Comment by surendra-github** [comment]
Thank you so much .
