### ISSUE TITLE
Extra Labels are added in .json file while exporting and importing into ADO 

### ISSUE THREAD

**Issue by yashsaurabh** [solidify/jira-azuredevops-migrator#837]
When we tried to export issues with no tags into workspace extra tags getting added into .json file similarly when we tried to import we can see extra labels over ADO. 
above tags behavior is not limited to one project . we are facing this problem for many projects

**Comment by Alexander-Hjelm** [comment]
Please describe in more detail. Provide examples of what extra tags are added. If possible, include your config file and an example issue

**Comment by yashsaurabh** [comment]
Thanks for reaching out , here are the extra labels that got added at the time of export in .json file 

IRA Labels : CERT PROD DEV
ADO Tags: CERT PROD DEV STAGE UAT

Config file mapping 
 {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },

**Comment by Alexander-Hjelm** [comment]
@yashsaurabh , have these labels ever been on the issue historically? Maybe the issue is that they aren't properly selected from the correct revisions.

Are you using the latest version of the migrator?

**Comment by yashsaurabh** [comment]
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/49436346/02a986f5-d4ed-4ad1-a703-05db9b82abc1)

**Comment by yashsaurabh** [comment]
Hi thanks for response 
so above is the issue we are getting with latest version of migrator also

**Comment by Alexander-Hjelm** [comment]
That's strange. Looks like Jira Rest API has returned an issue where the `labels` field is null. Any idea what you did to trigger that behavior? Currently lacking sufficient repro steps so cannot commence working on a bug fix at the moment.
