### ISSUE TITLE
Cannot log in to JIRA cloud via API key

### ISSUE THREAD

**Issue by ValekMal** [solidify/jira-azuredevops-migrator#84]
How do you authenticate via JIRA API KEY?

I have two-factor authentication in my JIRA account in the cloud.
In the jira-export.exe I used 
-u username@domain.com:APIKEY
and did not use -p switch.

The application logs in but cannot see any projects.
I get this

"The value 'PROJECTNAME' does not exist for the field 'project'."

Which suggests that there is no visibility of the project,

**Comment by MOlausson** [comment]
Check out https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md#jira-requirements for more ways to authenticate. You should use both the -u and -p parameters.
