### ISSUE TITLE
JsonReaderException when reading item from JIRA

### ISSUE THREAD

**Issue by tilmann-brenk** [solidify/jira-azuredevops-migrator#842]
**Describe the problem**
I am trying to export items from JIRA, but the export stops on the first entry

**To Reproduce**
1. I am running the export from JIRA
jira-export.exe -u ***-p *** --url http://xxx --config config-basic.json
3. The export stops on the first entry
[E][16:56:18] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 29.04.15 - 14:29. Path '[0].created', line 32, position 33.
at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)

**Tool version**
 - I am using jira-azuredevops-migrator-3.0.139.

**Attachments**
[jira-export-log-230824-113315.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12443966/jira-export-log-230824-113315.txt)

**Comment by Alexander-Hjelm** [comment]
Probably an issue with mapping a datetime field. I'd advise to dig around in the old issues to find examples of how to map the fields you are trying to migrate. If that fails, post the configuration file here.
