### ISSUE TITLE
Warning: IncludeCommits was 'true', but no RepositoryMap was specified in the config

### ISSUE THREAD

**Issue by alfreddevries** [solidify/jira-azuredevops-migrator#845]
**Describe the problem**
Receiving warning for every Jira Issue exported when using jira-export

**To Reproduce**
1. Download and Install version 3.0.178
2. Restart export

**Tool version**
 - Version 3.0.178

**Attachments**

Please attach the following files:

- config.json YES in ZIP
- jira-export-log.txt YES
- wi-import-log.txt N/A

**Screenshots**
[jira-export-log-230830-160529.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12476510/jira-export-log-230830-160529.txt)
[OLPFP_configuration.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12476519/OLPFP_configuration.zip)

**Comment by Alexander-Hjelm** [comment]
In order to use the functionality of the IncludeCommits flag, you will need to add a `repository-map` property in your config.

It should look something like:

```json
repository-map: {
    "repository": [
      {
        "source": "Source repository name",
        "target": "Target repository name"
      },
}
```

@NWaterbury, could you please share an example configuration so I can document? :)

**Comment by Alexander-Hjelm** [comment]
Updated docs: https://github.com/solidify/jira-azuredevops-migrator/pull/846

**Comment by Alexander-Hjelm** [comment]
I can report that I am also experiencing similar warning messages without having set the IncludeCommits flag. I will work on a fix asap

```
[W][11:16:19] IncludeCommits was 'true' in the config, but no RepositoryMap was specified in the config. Please add a RepositoryMap in order to migrate git artifact links. Git artifacts will be skipped for now...
```
