### ISSUE TITLE
Importing values other than mapped ones

### ISSUE THREAD

**Issue by harshitjain5june** [solidify/jira-azuredevops-migrator#848]
I have mapped my Jira items with ADO, but I want to add project name to all the items I am importing , I want to set a default value of project for all workitems, is it possible to do so? 
<img width="291" alt="image" src="https://github.com/solidify/jira-azuredevops-migrator/assets/68435639/71fca86a-93c2-4d2d-9b06-b301ad605501">

**Comment by Alexander-Hjelm** [comment]
It should in theory be doable by adding a field map for the `project` field.

Here is a sample of the `project` field from the Jira rest API:

```json
        "project": {
          "self": "https://solidifydemo.atlassian.net/rest/api/2/project/10005",
          "id": "10005",
          "key": "AGILEDEMO",
          "name": "Agile-Demo",
          "projectTypeKey": "software",
          "simplified": false,
          "avatarUrls": {
            "48x48": "https://solidifydemo.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414",
            "24x24": "https://solidifydemo.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414?size=small",
            "16x16": "https://solidifydemo.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414?size=xsmall",
            "32x32": "https://solidifydemo.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10414?size=medium"
          }
```

**Comment by harshitjain5june** [comment]
Using Jira Rest API, not using config-agile.json right?

**Comment by Alexander-Hjelm** [comment]
I mean specify a field mapping in your config file. Check to the documentation if you are unsure where to get started: 
https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md
https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#field-properties

**Comment by harshitjain5june** [comment]
for example here is my fields-map:
"field-map": {
    "field": [
      {
        "source": "",
        "target": "System.Tags",
        "mapping": {
          "values": [
            { "source": "*",
              "target": "migrated"
            }
          ]
        }
      },
      
      
      here i am trying that each workitem I migrate gets a migrated tag associated with, here I am not sure what to mention in source because i am not mapping it with Jira, I want to just provide a default value "migrated" to tag of each item.

**Comment by Alexander-Hjelm** [comment]
I advise you to read through the docs and look at the configuration samples to understand how field mapping works with our tool :)

**Comment by harshitjain5june** [comment]
I have read the documentation thoroughly, just wanted to know one thing now , i am mapping values of the labels to be "migrated" :
 {
        "source": "labels",
        "target": "System.Tags",
        "mapping": {
          "values": [
            { 
              "source": "*",
              "target": "migrated"
            },
            {
              "source": null,
              "target": "migrated"
            }
          ]
        }
      }
      
      what I want is any label present in Jira to be mapped with "migrated" tag in ADO, also if no label is present that also should get a tag   "migrated" in ADO. But the above logic is not working, I tried using * and null.

**Comment by Alexander-Hjelm** [comment]
I can confirm that we we not presently support the use of wildcards or null in the value mapper. Instead you must use a direct key-value translation without wildcards.

https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/RevisionUtils/FieldMapperUtils.cs#L82C25-L82C25

Let me know if you are interested, and I can create a feature request for custom patterns and wildcards on your behalf :)
