### ISSUE TITLE
Option to exclude revisions to work items where nothing changes

### ISSUE THREAD

**Issue by nickn00** [solidify/jira-azuredevops-migrator#852]
**Is your feature request related to a problem? Please describe.**
There are a large number of transactions with ADO to add "revisions" to a work item where nothing changes.  This slows down the import into ADO and triggers a resource consumption limit on the ADO server.

**Describe the solution you'd like**
Don't import revisions where no change occurs

**Describe alternatives you've considered**
A script to parse the json files and remove superfluous revisions

**Comment by nickn00** [comment]
I've done some more checking and found that the revisions where nothing changes are due to incorrect field mapping on my side, but it would be useful to have the option to exclude certain changes, such as changes to time spent, time remaining, etc.

These changes cause thousands of extra updates during the import in my case, which slows the import down and could be excluded, if others have the same problem?

**Comment by Alexander-Hjelm** [comment]
Agreed. I will work on implementing this feature soonish. At the moment there are more pressing bugs that need my attention though :)

If you want to have a crack at it yourself, you should edit here and add a check that verifies that the revision actually contains some fields, links or attachments: https://github.com/solidify/jira-azuredevops-migrator/blob/c8127881271424b428ff2d13547ebbe91bb6dea7/src/WorkItemMigrator/WorkItemImport/ExecutionPlanBuilder.cs#L40C38-L40C38

**Comment by Alexander-Hjelm** [comment]
@nickn00 See PR https://github.com/solidify/jira-azuredevops-migrator/pull/876. Please give it a review if you are able!

**Comment by Alexander-Hjelm** [comment]
Merged #876 . Open a new issue if there are any problems with the new feature
