### ISSUE TITLE
Zephyr test cases migration from Jira to Azure test plans

### ISSUE THREAD

**Issue by harshitjain5june** [solidify/jira-azuredevops-migrator#853]
Hi, I wanted to know is it possible to migrate Zephyr test cases to Azure devops using this tool?

**Comment by Alexander-Hjelm** [comment]
Hello Harshit :)

Migration of Zephyr test data is part of our Jira Migrator PRO offering, which is currently in a discounted early adopter phase. You can read more here: https://github.com/solidify/jira-azuredevops-migrator#jira-azure-devops-migrator-pro, and send us an  email at support.jira-migrator@solidify.dev if you are interested in booking a demo!
