### ISSUE TITLE
How to map child subtask of JIRA in ADO

### ISSUE THREAD

**Issue by sabhinandan** [solidify/jira-azuredevops-migrator#857]
Hello,

I have task with Sub-Task in JIRA, I want same relationship to be continued in ADO. Attached is the image for the same.

Added below configuration in config-basic.json under type-map
	  {
        "source": "Sub-task",
        "target": "Task"
      }
Please suggest, What needs to be added in link-map to make this work as currently sub-task is created as task in ADO but no relationship is created. 
"link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/2655352/7201bdd8-ac8b-4ef7-94c7-fbc51d83e870)

**Comment by Alexander-Hjelm** [comment]
You possibly need to add a mapping for the Child link type, but not 100% sure here. Since you have already mapped the parent link type, this scenario should already be taken care of.

```
{
"source": "Child",
"target": "System.LinkTypes.Hierarchy-Forward"
},
```

Potentially related to https://github.com/solidify/jira-azuredevops-migrator/issues/495

**Comment by sabhinandan** [comment]
Thanks, I already added this but outcome JSON is not the correct one, I mean generating that relationship in ADO.
I did some changes after generating outcome JSON and found some manual fix, will test it with more cases and share updated JSON with you, so that you can fix the code and that manual work is not needed
