### ISSUE TITLE
default CustomField mapping silently failing?

### ISSUE THREAD

**Issue by AnthonyRobinson** [solidify/jira-azuredevops-migrator#868]
I am mapping customFields in Jira to custom fields in ADO and attempting to use the "default" mapper.

My Jira issue's customFields are as follows:

```
{
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    "id": "99529",
    "self": "https://jira.yourorghere.com/rest/api/2/issue/99529",
    "key": "IOB-1717",
    "fields": {
        "customfield_10478": null,
        "customfield_10470": "user@yourorghere.com",
        "customfield_10472": "XPLOR Inc",
        "customfield_10473": "159158",
        "customfield_10870": "user@yourorghere.com"
    }
}
```

My config file settings are as follows:

```
"field-map": {
    "field": [
        {
            "source": "customfield_10472",
            "target": "Custom.AccountName"
        },
        {
            "source": "customfield_10473",
            "target": "Custom.CustomerNumber"
        },
        {
            "source": "customfield_10478",
            "target": "Custom.IntRequestType"
        },
        {
            "source": "customfield_10470",
            "target": "Custom.TechnicalContactEmail"
        },
        {
            "source": "customfield_10870",
            "target": "Custom.TechnicalContact"
        }
    ]
}
```

During the Jira export phase, the custom fields don't show up in the exported Jira item's json file in the workspace, and consequently, not in the imported ADO item either.

As a test, I tried an export/import run using "MapRendered."  This pulls the custom fields out as expected, but fails on import (as expected) as the target ADO field is too small for the generated HTML.

**Tool version**
 - v3.0.186

**Attached files**

[config_IOB.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12784818/config_IOB.json.txt)
[jira-export-log.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12786903/jira-export-log.txt)

[edit] typos and add attachments

**Comment by Alexander-Hjelm** [comment]
I have played around and discovered that it seems like the tool is expecting us to refer to custom fields by name and not by ID. Simply include the **source-type** property in your field mapping and set it to **name**. The **source** should then be the same field name as you see in the Jira interface. Not sure if the experience will be different, but you could try something like:
```json
      {
        "source": "Account Name",
        "source-type": "name",
        "target": "Custom.AccountName"
      },
```

Let me know if that works better!

**Comment by nickn00** [comment]
@Alexander-Hjelm, I had the same issue and your suggestion fixed it.

Thank you :)

**Comment by Alexander-Hjelm** [comment]
Perfect. I documented the above case here:

https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

CLosed the issue. Reopen if the problem persists :)
