### ISSUE TITLE
Time in increments

### ISSUE THREAD

**Issue by nickn00** [solidify/jira-azuredevops-migrator#869]
**Is your feature request related to a problem? Please describe.**
Task effort is recorded in seconds in Jira and when you import the task into Devops it converts to hours with high precision values such as 8.08333333333333

**Describe the solution you'd like**
Convert to hours in suitable increments (15mins or 30mins, etc).  I've already altered the code in my situation to increment in 15mins (0.25 hours), but could do a pull request and add an increment value to the configuration files for the user to set their own increments, if others have the same problem?

**Describe alternatives you've considered**
No alternative

**Additional context**
Example from ADO:
![Hours to high decimal places](https://github.com/solidify/jira-azuredevops-migrator/assets/85354682/8f94aed1-8871-4b89-a680-d536d0c98915)

**Comment by Alexander-Hjelm** [comment]
See https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md#mappers

The `MapRemainingWork` mapper should do exactly what is requested here!
