### ISSUE TITLE
Email for user 'xxxxx' not found in Jira, using username 'xxxxx' for mapping error

### ISSUE THREAD

**Issue by sanjeev40084** [solidify/jira-azuredevops-migrator#87]
I have couple of users who are no longer in Jira however there are tasks which were assigned to them in previous sprints. Not sure if that is why but i am getting following error while running the migration tool.

Email for user 'OldUserFirstname.OldUserLastname' not found in JIRA, using username 'OldUserFirstname.OldUserLastname' for mapping.
Could fnot find user 'OldUserFirstname.OldUserLastname' identity in user map. Using original identity 'OldUserFirstname.OldUserLastname'

where 'OldUserFirstname.OldUserLastname' is username of old user.

I tried updating 'users.txt' file something like this, but it didn't work
OldUserFirstname.OldUserLastname= validuser@gmail.com 

Any suggestion to fix this issue?

Thanks
Sanjeev

**Comment by sanjeev40084** [comment]
@MOlausson not sure if this is why, but i believe in current implementation, user info is retrieved by passing username, looking at this api it looks like username is deprecated and prefer using accountid: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-user-get 
Also looks like getting user's email address is whole different process too: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-user-email-get

**Comment by MOlausson** [comment]
@sanjeev40084 interesting findings. I'll explore the apis and see if we need to change the implementation.

**Comment by MOlausson** [comment]
@sanjeev40084 I've looked at this now. It's clear that emails are not returned as we expect anymore so will need to look into that. However, you should be able to map usernames in the users.txt file like you reported. When you say it didn't work, what does that mean?

**Comment by MOlausson** [comment]
I'll create a story to address the changes in the user profile apis. I've verified that the user mapping works so let us know if you still are having problems.

**Comment by sanjeev40084** [comment]
@MOlausson as i mentioned in my previous comments, i was having trouble getting the email address of the user and it was only able to get the username of the work item. in my users.txt mapping file i added mapping against those username something like this firstname.lastname=firstname.lastname@email.com
firstname2.lastname2=firstname2.lastname2@email.com
 but in the Azure DevOps side, i still got username on the work items i.e. (firstname.lastname) for the 'Assigned To' field. Not sure if i am looking at right place, the user mapping stuff, where does that get used in Azure DevOps side??

**Comment by MOlausson** [comment]
@sanjeev40084 got it. Because of the change in Atlassian's GRPR policies. So right now the best option is to map the jira name to the azure devops email in the mapping file.

**Comment by rakeshagrahari** [comment]
Hi @MOlausson ,
I am facing same issue.
In the Azure DevOps side, i got username on the work items i.e. (firstname.lastname) for the 'Assigned To.
But in Azure DevOps we use email address of user for Assigned to.
In users.txt I have mapped user id with email address like 
 firstname.lastname=firstname.lastname@gmail.com
But getting first.last name in Azure devops boards in Assigned To.
Can you please guide me how I can assigned email address for Assigned To in Azure DevOps ?
