### ISSUE TITLE
can we migrate Jira project with large number of issues in chunks ?

### ISSUE THREAD

**Issue by yashsaurabh** [solidify/jira-azuredevops-migrator#870]
i am facing Azure DevOps throughput units (TSTUs) consumption issue while migrating large number of jira issues to azuredevops 
can we migrate tickets in chunks ?
Do we have any solution on that ?

**Comment by Jbekker** [comment]
Quite recently a feature was added to allow waiting between revision imports, that should prevent excessive throttling. Take a look at https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md

<html>
<body>


sleep-time-between-revision-import-milliseconds | False | integer | How many milliseconds to sleep between each revision import. Use this if throttling is an issue for ADO Services. Default = 0 (no sleep).
-- | -- | -- | --



</body>
</html>

**Comment by yashsaurabh** [comment]
Thank you  for you help :) @Jbekker
