### ISSUE TITLE
batch size limit?

### ISSUE THREAD

**Issue by sgullluu** [solidify/jira-azuredevops-migrator#88]
what is the limit of the batch size? can we export 40k work item in one single export.

**Comment by MOlausson** [comment]
It's used to controll how many items are fetched at a time from Jira so no need to change that I would say. You can export many items but the services (Jira and Azure DevOps) have throttling so you may get degraded performance. I usually recommend migrating items in batches to be in control, one thing to be aware of then is to bucket all related items so you don't get into problems with missing links.

Good luck migrating!

**Comment by MOlausson** [comment]
@sgullluu The batch size is only used against the service apis to avoid fetchin data too eagerly. You have a good idea, I'll add it for the team to review. You can try to bucket exports using the JQL filter, for instance something like this matches items in a certain range: 
`project = scrum and id >SCRUM-10 and id <= SCRUM-20 order by id ASC`
