### ISSUE TITLE
Field 'Activated Date' cannot be empty, even after passing ActivatedDate value in Json

### ISSUE THREAD

**Issue by KatteriSharath** [solidify/jira-azuredevops-migrator#884]
**Describe the problem**
Hi Team,
For few Jira Items, even though the ActivatedDate Field is present in the generated JSON, while and after importing to Azure it is giving the error: Invalid field status 'InvalidType' for field 'Microsoft.VSTS.Common.ActivatedDate'.

below is the Json generated after Exporting from Jira

        {
          "ReferenceName": "System.Title",
          "Value": "Title_Issue "
        },
        {
          "ReferenceName": "System.AssignedTo",
          "Value": "Masked"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": "3"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.ActivatedBy",
          "Value": "Masked"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Scheduling.OriginalEstimate",
          "Value": "80"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.ActivatedDate",
          "Value": "14/06/2023 10:06:29"
        },
        {
          "ReferenceName": "System.State",
          "Value": "Active"
        }
below is the error while importing
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147804309/f32d6f77-0102-460d-a335-9643ec4b7399)

below is the error displaying in Azure board
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147804309/fe44c109-85b1-4f0c-9e33-c77236f7b28e)

**Comment by Alexander-Hjelm** [comment]
[Debug.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12900298/Debug.zip)

@KatteriSharath, give this build of the WorkItem Importer a try and let me know the resuults!

**Comment by KatteriSharath** [comment]
Hi @Alexander-Hjelm , Thanks for the response.
Since i do not have permission to download zip file i could not able to try the debug.
but j have referred https://github.com/solidify/jira-azuredevops-migrator/pull/885/files PR and made changes manually and tried, i am still getting the same issue.

**Comment by Alexander-Hjelm** [comment]
@KatteriSharath Ok!

It looks like ActivatedDate field on your exported work item is on the wrong format. The value is `14/06/2023 10:06:29` when it should be on a format like `2023-06-14T10:06:29.635+00:00`.

Could you try and edit the value for `Microsoft.VSTS.Common.ActivatedDate` in your exported config, just to see if that fixes the error or not? Get back to me with the results.

If so, let me have a look and see if maybe the tool is missing a conversion somewhere.

**Comment by Alexander-Hjelm** [comment]
@KatteriSharath Furthermore, which time zone are you in?

**Comment by KatteriSharath** [comment]
@Alexander-Hjelm i am in BST time zone (UK)

**Comment by KatteriSharath** [comment]
Additionally, I conducted testing on approximately 300 work items, with only 5 of them exhibiting this error. Moreover, I have just attempted this for another work item, and the activation date is as follows:

"ReferenceName": "Microsoft.VSTS.Common.ActivatedDate",
"Value": "11/09/2023 10:55:37"

This item was successfully imported into Azure without encountering any errors.

**Comment by wallymathieu** [comment]
When using a process that uses "Resolved" there is also "Resolved Date" not being set for resolved issues.
