### ISSUE TITLE
Images in ADO comments are linked to JIRA server 

### ISSUE THREAD

**Issue by yashsaurabh** [solidify/jira-azuredevops-migrator#887]
I am trying to migrate some tickets having Images in History in jira . But when it appeared on ADO some images are broken with image icon only in comment section .
when i double click on that icon it will redirect me to JIRA portal  .
so how can we remove those Hyperlink of JIRA?
can you please help me on that ?

**Comment by Alexander-Hjelm** [comment]
Potentially related to https://github.com/solidify/jira-azuredevops-migrator/issues/851?
