### ISSUE TITLE
AcceptanceCriteria field breaks images 

### ISSUE THREAD

**Issue by diegoq** [solidify/jira-azuredevops-migrator#888]
When I migrate field description in jira and map  the target field Microsoft.Common.AcceptanceCriteria.

The images does not show correctly. For example.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/3793947/0f734b5b-88ed-4171-8ff6-a8725f809dc0)

This is how jira shows it.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/3793947/357ffef0-ecd2-4c8f-8182-d94da5651fca)

**Comment by Alexander-Hjelm** [comment]
FYI the reference name for the field is "Microsoft.VSTS.Common.AcceptanceCriteria".

Can you share your `config.json` file?

**Comment by Alexander-Hjelm** [comment]
Potentially related to https://github.com/solidify/jira-azuredevops-migrator/issues/851?

**Comment by diegoq** [comment]
Sure,

That's my config file.
{
  "source-project": "COE SOFTWARE",
  "target-project": "AMS SES",
  "query": "\"Epic Link\"=SW-57991 and issue in(SW-59066, SW-58880) ORDER BY rank",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Iteracion",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Debug",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "AMS SES",
  "base-iteration-path": "AMS SES",
  "ignore-failed-links": true,
  "include-link-comments": false,
  "include-jira-css-styles":false,
  "process-template": "Custom-agile",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      }
    ]
  },
  "type-map":{
    "type": [
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "User Story"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "Task"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.Common.AcceptanceCriteria",
        "mapper":"MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper":"MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "To Do"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "User Story, Epic",
        "mapping": {
          "values": [
            {
              "source": "Parking Lot",
              "target": "Backlog"
            },
            {
              "source": "New",
              "target": "Backlog"
            },
            {
              "source": "Pending Grooming",
              "target": "Requeriment"
            },
            {
              "source": "Ready",
              "target": "Requeriment"
            },
            {
              "source": "Ready for DEV",
              "target": "Requeriment"
            },
            {
              "source": "Development",
              "target": "Active"
            },
			{
              "source": "Build Installed",
              "target": "Active"
            },
			{
              "source": "Certification",
              "target": "Active"
            },
            {
              "source": "Done",
              "target": "Done"
            },
			{
              "source": "Approved",
              "target": "Done"
            },
			{
              "source": "Closed",
              "target": "Closed"
            },
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Feature",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "not-for": "Task"
      },
      {
        "source": "remainingEstimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}

**Comment by diegoq** [comment]
In addition if I use the description field the images don't break.

**Comment by Alexander-Hjelm** [comment]
Looks like the attachment path correction is only implemented for Description, Repro Steps and Comments as of today. Let me create a fix and upload a build for you to try out @diegoq. I will get back to you with a build soon!

**Comment by Alexander-Hjelm** [comment]
[Debug.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12924333/Debug.zip)
@diegoq Try this build and let me know the results!

**Comment by Alexander-Hjelm** [comment]
[Debug.zip](https://github.com/solidify/jira-azuredevops-migrator/files/12954805/Debug.zip)

You are correct, use this one

**Comment by diegoq** [comment]
Hi @Alexander-Hjelm, now the jira-export is missing.

**Comment by diegoq** [comment]
Ok Let me do it

**Comment by Alexander-Hjelm** [comment]
Perfect! :)

The bundles I sent you are based on the main line, so you already have the latest version of the tool. Continue using that until we have released the next version with these changes incorporated.

Merging the PR will close the issue. Feel free to reopen it and tag me if the problem persists!
