### ISSUE TITLE
Migrating Checklists

### ISSUE THREAD

**Issue by skynet2024** [solidify/jira-azuredevops-migrator#891]
How would you migrate Checklists?

Tried this: 
{
  "source": "Checklist",
  "target": "Microsoft.VSTS.TCM.Steps",
  "mapper": "MapArray"
}

All help is appreciated.

**Comment by Alexander-Hjelm** [comment]
Good question. I don't think we have ever documented this situation.

Could you make a REST API call to the /Iissue endpoint and get the details of your checklist field? How does it look in the api response?

Example: `https://<organization>.atlassian.net/rest/api/2/issue/ISSUEKEY-XXX/`

**Comment by skynet2024** [comment]
Hi. Thank you for your reply. I made the REST API call:

"customfield_number": "items:\n  - text: ChecklistItem1\n    checked: true\n  - text: ChecklistItem2\n",        
"customfield_number": "# Default checklist\n* [x] ChecklistItem1\n* [x] ChecklistItem2\n* "

**Comment by Alexander-Hjelm** [comment]
The field data is a simple text string, but it has a pretty weird structure.

It is possible to migrate the whole value as-is, or use MapArray to migrate mulitple values as an array. See https://github.com/solidify/jira-azuredevops-migrator/issues/374

Furthermore, it is possible to write a custom mapper for the purpose of extracting the substring we are interested in.
