### ISSUE TITLE
Problems with linked bugs

### ISSUE THREAD

**Issue by diegoq** [solidify/jira-azuredevops-migrator#894]
I have a problem trying to migrating bugs.

In jira the bugs are linked
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/3793947/f9f15fb8-7285-4001-af19-a7d70d3914cb)

I get this message in the command prompt 
Link with description 'This issue is blocked by SW-59782' is either not found or this issue (SW-58459) is not inward issue.

This is my json config.

{
  "source-project": "COE SOFTWARE",
  "target-project": "AMS SES",
  "query": "\"Epic Link\"=SW-57991 and issue in(SW-58459, SW-59782, SW-59773) ORDER BY rank",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Iteracion",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Debug",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "AMS SES",
  "base-iteration-path": "AMS SES",
  "ignore-failed-links": true,
    "include-link-comments": false,
  "include-jira-css-styles":false,
  "process-template": "Custom-agile",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Parent",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "Relates",
        "target": "System.LinkTypes.Related"
      },
      {
        "source": "Duplicate",
        "target": "System.LinkTypes.Duplicate-Forward"
      },
      {
        "source": "Blocks",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      },
      {
        "source": "is blocked by",
        "target": "System.LinkTypes.Hierarchy-Forward"
      }
    ]
  },
  "type-map":{
    "type": [
      {
        "source": "Feature",
        "target": "Feature"
      },
      {
        "source": "Epic",
        "target": "Epic"
      },
      {
        "source": "Story",
        "target": "User Story"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task",
        "target": "Task"
      },
      {
        "source": "Sub-task",
        "target": "Task"
      },
      {
        "source": "Subtask SQA",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.Common.AcceptanceCriteria",
        "mapper":"MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "Blocker",
              "target": "1"
            },
            {
              "source": "Critical",
              "target": "1"
            },
            {
              "source": "Highest",
              "target": "1"
            },
            {
              "source": "Major",
              "target": "2"
            },
            {
              "source": "High",
              "target": "2"
            },
            {
              "source": "Medium",
              "target": "3"
            },
            {
              "source": "Low",
              "target": "3"
            },
            {
              "source": "Lowest",
              "target": "4"
            },
            {
              "source": "Minor",
              "target": "4"
            },
            {
              "source": "Trivial",
              "target": "4"
            }
          ]
        }
      },
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      {
        "source": "comment",
        "target": "System.History",
        "mapper":"MapRendered"
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Task",
        "mapping": {
          "values": [
            {
              "source": "Parking Lot",
              "target": "To Do"
            },
			{
              "source": "Ready",
              "target": "To Do"
            },
			{
              "source": "Ready for DEV",
              "target": "To Do"
            },
            {
              "source": "Development",
              "target": "In Progress"
            },
            {
              "source": "Done",
              "target": "Closed"
            },
            {
              "source": "Closed",
              "target": "Closed"
            }
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "User Story, Epic",
        "mapping": {
          "values": [
            {
              "source": "Parking Lot",
              "target": "Backlog"
            },
            {
              "source": "New",
              "target": "Backlog"
            },
            {
              "source": "Pending Grooming",
              "target": "Requirement"
            },
            {
              "source": "Ready",
              "target": "Requirement"
            },
            {
              "source": "Ready for DEV",
              "target": "Requirement"
            },
            {
              "source": "Development",
              "target": "Active"
            },
			{
              "source": "Build Installed",
              "target": "Active"
            },
			{
              "source": "Certification",
              "target": "Active"
            },
            {
              "source": "Done",
              "target": "Done"
            },
			{
              "source": "Approved",
              "target": "Done"
            },
			{
              "source": "Closed",
              "target": "Closed"
            },
          ]
        }
      },
      {
        "source": "status",
        "target": "System.State",
        "for": "Feature",
        "mapping": {
          "values": [
            {
              "source": "To Do",
              "target": "New"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            }
          ]
        }
      },
      {
        "source": "Story Points",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort",
        "not-for": "Task"
      },
      {
        "source": "remainingEstimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "for": "Bug,Task"
      },
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      }
    ]
  }
}

**Comment by Alexander-Hjelm** [comment]
Probably mapping your "Blocks" link type like this will give you issues, as an issue can only have one parent in Azure DevOps:

```json
{
"source": "Blocks",
"target": "System.LinkTypes.Hierarchy-Reverse"
},
```

**Comment by Alexander-Hjelm** [comment]
Potentially fixed by https://github.com/solidify/jira-azuredevops-migrator/pull/1072
