### ISSUE TITLE
TF51535: Cannot find field Custom.FieldName

### ISSUE THREAD

**Issue by skynet2024** [solidify/jira-azuredevops-migrator#895]
Custom fields are being exported, both not mapped when migrating them to ADO.

Followed this guide:
https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field-by-name

Nevertheless, get this error when migrating:
TF51535: Cannot find field Custom.FieldName
Work Item failed to save.

config.json:

{
    "source": "customfield_number",
    "source-type": "value",
     "target": "Custom.TypeOfFailure",
    "mapper": "MapTags"
}
--> multiple values can be selected here
	  
{
    "source": "customfield_number",
    "target": "Custom.Complexity",
    "mapper": "MapArray"
}
--> one value from a dropdrown lit can be selected

All help is appreciated.

**Comment by Alexander-Hjelm** [comment]
Try both of the methods metioned in the FAQ? https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

Incluing mapping by the field name (not the field key)

**Comment by timakamystery** [comment]
not sure if put this into a correct issue. but using ver. 250 custom fields don't get into the json files, whereas sticking to v.139 - works ok.
e.g.:
```
      {
        "source": "customfield_14128",
        "target": "Custom.CustomString1"
      },
      {
        "source": "customfield_12359",
        "target": "Microsoft.VSTS.Build.IntegrationBuild"
      },
```

Also on import new ver. has:
```
[E][10:16:23] TF51535: Cannot find field Custom.TimeSpentSecondsRendered.
```
```
      {
        "source": "timespent$Rendered",
        "target": "Custom.TimeSpentSecondsRendered"
      },
```
while the other ver. throws no such..

**Comment by Alexander-Hjelm** [comment]
@timakamystery Please do not hijack other people's support issues. Create a new issue instead.

**Comment by timakamystery** [comment]
> @timakamystery Please do not hijack other people's support issues. Create a new issue instead.

https://github.com/solidify/jira-azuredevops-migrator/issues/912
