### ISSUE TITLE
Set field with default value in ADO without source field

### ISSUE THREAD

**Issue by Love-Ry1** [solidify/jira-azuredevops-migrator#896]
Hello! I have a field "Enviroment" for my bug work items in my ADO. I do not have a corresponding field for my Jira work items. I wonder if it is possible to set a default value for that field when importing items, without having a source field from Jira?

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/83970045/67d26fce-0238-4017-800a-cda534a78341)

**Comment by Alexander-Hjelm** [comment]
Should be doable by creating a Work Item Rule in Azure DevOps. Otherwise simply bulk edit the work items in ADO WIT Queries and set the value of the items there.

Here is how I have mapped the `Environments` field previously:

```json
      {
        "source": "environment",
        "source-type": "name",
        "target": "Microsoft.VSTS.TCM.SystemInfo",
        "for": "Bug,Epic"
      }
```

**Comment by Love-Ry1** [comment]
Hi, thanks for the reply! That sounds like a good idea. But I will also post the work-around I did, in case it can help anyone in the future: I used the jira api to find a common field which was static for all work items I wanted to target.  In my case I used "issueType" as source.
My field-map entry then looked like this:
```
{
	"source": "issueType",
	"source-type": "name",
        "target": "Custom.Environment",
	"for": "Bug",
	"mapping": {
         "values": [
           {
           "source": "Bug",
           "target": "Production"
           }
           ]
        }
},
```
This worked in my case without any issues.
