### ISSUE TITLE
Linked child issues are not showing up on Epics

### ISSUE THREAD

**Issue by cmwivanti** [solidify/jira-azuredevops-migrator#897]
**Describe the problem**
Linked child issues are not showing up on Epics with on prem Jira server  (v8.9.1#809001)
I'd like to map Epics to ADO features. However even if I keep Epics mapped to ADO Epics the linked child items do not show.
Export logs show no links, but Jira shows 6 linked child issues.
This problem only exists on Epics.   Stories with Child links work. 

**Tool version**
jira-azuredevops-migrator-3.0.229
[jira-export-log.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13191113/jira-export-log.txt)
[wi-import-log.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13191114/wi-import-log.txt)
[HER-Config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13191115/HER-Config.txt)

**Comment by Alexander-Hjelm** [comment]
@cmwivanti Is this related to https://github.com/solidify/jira-azuredevops-migrator/issues/862?

**Comment by cmwivanti** [comment]
Yes, this is completed.  I was able to verify pulling and building master.  I just didn't see it it the last release.

Thank you!

**Comment by aakash-pinc** [comment]
@Alexander-Hjelm : Would you please release a newer version for this?

@cmwivanti : Would you please attach the zip file if you able to build master branch?

**Comment by Alexander-Hjelm** [comment]
@aakash-pinc New release here: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.250
