### ISSUE TITLE
JQL and 0 exported issues

### ISSUE THREAD

**Issue by lingbin23** [solidify/jira-azuredevops-migrator#903]
**Describe the problem**
I was trying to migrate a Jira project “Eunomia” to Azure DevOps by following the instruction here: https://solidify.dev/blog/jira-azure-devops-migration
 
I download the latest version 3.0.229, and configured the config-scrum.json file and added the users.txt file in the root.
 
I got the following error when I set “query": "project = Eunomia ORDER BY Rank ASC",   

Then I emptied the query, it’s processed but no any record was exported, could you help and tell what’s wrong with config or process? 

**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]
[jira-export-log-231109-221003.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13318332/jira-export-log-231109-221003.txt)
[jira-export-log-231109-171933.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13318333/jira-export-log-231109-171933.txt)
[jira-export-log-231109-171811.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13318334/jira-export-log-231109-171811.txt)

Please attach the following files:

[config-scrum.json](https://github.com/solidify/jira-azuredevops-migrator/files/13318337/config-scrum.json)
[users.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13318338/users.txt)

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147597563/0cf8eaad-0451-429a-acc7-4d355cfdbb7c)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147597563/3919b277-9241-42c0-a6eb-5fdf942dab23)

**Comment by Alexander-Hjelm** [comment]
Hi @lingbin23 

It seems that no issues were exported. I would advise testing your JQL query in Jira and verifying that it actually matches some items first.

**Comment by lingbin23** [comment]
Thanks, while my JQL is working in our JIRA, and returning the expected items/records.   Please see the screenshot below:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147597563/507225d5-ab28-48a1-bd4a-eb7f0b7b5833)

Also it's still not working even the query is empty as shown in my last message.

**Comment by Alexander-Hjelm** [comment]
Try using the project key instead of the project name in the query?

**Comment by lingbin23** [comment]
Tried that already, still the same.

**Comment by Alexander-Hjelm** [comment]
Try with project key and quotation marks? This query works for me, for example:

```
    "query": "project = \"AGILEDEMO\" ORDER BY created DESC",
```

where `AGILEDEMO` is the project key.

**Comment by lingbin23** [comment]
I tried that as well, still not working, EUN is the project Key:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147597563/f8204309-42f5-4c12-a311-88220755e14d)

this is the config:
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/147597563/fd748ad1-faa3-4c31-bd4c-2acf18363ab2)

**Comment by Alexander-Hjelm** [comment]
Not sure what the problem could be then. The error essentially says that you do not have access to a project named EUN.

The issue could be either of the following:
- There is no project with that name on the specified jira instance
- The query is malformed
- Your user is lacking access to view the project

**Comment by eb-creator** [comment]
Has a solution been found for this? My team is getting the same issue and have tried all the strategies mentioned here.

**Comment by lingbin23** [comment]
No, we still have not found any solution to resolve it yet.

**Comment by eb-creator** [comment]
@Alexander-Hjelm My organization has tried using different users with different access levels, changed the queries to numerous other filters, and have verified that our project name is present. Do you have any other suggestions for how to solve this?

**Comment by Alexander-Hjelm** [comment]
What version of Jira are you running? @eb-creator

**Comment by eb-creator** [comment]
We are a company-managed project and we use JIRA Cloud so I don't believe there's a specific version number 

<meta name="application-name" content="JIRA" data-name="jira" data-version="1001.0.0-SNAPSHOT"><
This is the string I get when looking at the source code

**Comment by Alexander-Hjelm** [comment]
Aha ok, if you are running in Jira Cloud, that makes it even more weirder. I'm regularly doing integration tests against our jira cloud organization and there everything is running now without hiccups.

Are you able to reach the issue search rest API endpoint? Try to see if you can set up a query in postman or similar, with the same JQL query as you are trying in your config.json-file, with the same user + API token/password and let me know the result of that.

Here is an example:

```
curl -D- 
  -u johnie:johnie 
  -X POST 
  -H "Content-Type: application/json" 
  --data '{"jql":"project = QA","startAt":0,"maxResults":2,"fields":["id","key"]}' 

 "http://johnie:8081/rest/api/2/search"
```

More information: https://hevodata.com/learn/jira-api-get-issue/

**Comment by el-genius** [comment]
I faced the same and I'm using Jira cloud, I upload config file, you can take a look

Also, I tried many other projects I faced the same issue

[config-scrum.json](https://github.com/solidify/jira-azuredevops-migrator/files/13670275/config-scrum.json)


![image](https://github.com/solidify/jira-azuredevops-migrator/assets/18281778/f1851963-d45b-4fc4-9931-056745ec10bd)

**Comment by Alexander-Hjelm** [comment]
@el-genius Try the issue search endpoint in Postman or similar as I wrote above, and see if you get the same output or not. It could be that you are specifying the project name/project key incorrectly in the query

**Comment by LivSarah** [comment]
I have been struggling with just the same issue for two day now and just had a breakthrough! Using the API-token from Jira insted of my password finally got me past that pesky error! Anyone else wanna give that a try?

**Comment by Alexander-Hjelm** [comment]
@LivSarah That's strange. We should probably add a more helpful warning in that case.

For anyone else still encountering this issue, you can check common authentication problems + ccredentials to try in the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#2-why-i-am-getting-unauthorized-exception-when-running-the-export

**Comment by LivSarah** [comment]
As far as I can tell from the previous screenshots here, they have alsobeen using their passwords when running the command (as expected). So I'm curious if it will work for the other to use API token instead. 
@lingbin23 @eb-creator @el-genius ?

**Comment by akshayptrm** [comment]
We are also facing the same issue , We  have tried with token ,  profile id etc , tried different combinations But it didn't work , We also tried keys in the query and source project name . For previous similar tickets the solutions where all so random , some didn't made any change , and for some it was changing source name or so . Having tried all these , wonder what may be the real issue,

**Comment by Alexander-Hjelm** [comment]
@akshayptrm Have you tried the troubleshooting steps I posted here? https://github.com/solidify/jira-azuredevops-migrator/issues/903#issuecomment-1833259999

**Comment by akshayptrm** [comment]
@Alexander-Hjelm ,HI, yes I had tried those troubleshooting steps, Actually I was just writing a comment as an add-on to my previous one , I  was finally able to run the export , there seems to be an issue while using the query 'Project ='project-name' or key, It worked for me by using Project ='project id' as query , and also I had added a new api token as password , and used  email address as username, Any one facing the issue try these steps ,It might work, I tried the query in postman and there was the same issue while using key or project name ,using project id it works.

**Comment by Alexander-Hjelm** [comment]
@akshayptrm Glad it helped!

It seems like there are a lot of possible solutions to this problem, so I might collect all the various solutions that everybody have tried in an FAQ post.

**Comment by akshayptrm** [comment]
> @akshayptrm Glad it worked!
> 
> It seems like there are a lot of possible solutions to this problem, so I might collect all the various solutions that everybody have tried in an FAQ post.

Yeah, Don't know why all the solutions are all so different ,lol, and The response from the api ,even if the authentication failed the response shows 'The value is not found in project' error message adds to the confusion.

**Comment by Alexander-Hjelm** [comment]
I have documented some possible solutions here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#12-i-get-https-response-code-400-and-a-systemaggregate-exception-with-the-warning-failed-to-get-item-count-using-query--and-no-items-are-exported

Feel free to continue using this issue to discuss if the problem should persist.
