### ISSUE TITLE
Imported work items don't appear in the project Board

### ISSUE THREAD

**Issue by aarontll** [solidify/jira-azuredevops-migrator#910]
I have migrated a test agile project successfully, mapping to custom states in ADO that better align with what was in use in Jira. The work items seem to migrate successfully, but none are appearing in the project board, which remains empty. I adjusted the board settings before importing so that the columns align with the custom states I've defined for each item type (user story, etc). The iteration is specified in the config file to match the iteration in the project. The imported work items are also not visible in the backlog.

If I manually create a new work item in the project, that does appear in the board automatically. If I change the state on migrated items and save them, regardless of state chosen, they still do not appear on the board.

**Comment by Alexander-Hjelm** [comment]
You will need to configure the ADO board to capture the desired work items before you can actually see them on the board. This is a separate step apart from running our migrator.
