### ISSUE TITLE
inline images in repro steps from Jira not coming after migration in azure devops

### ISSUE THREAD

**Issue by shweta22992** [solidify/jira-azuredevops-migrator#911]
**Describe the problem**
Inline images in repro steps (in Item Info) from Jira not coming after migration in azure devops (checking in repro steps).
Instead of the image getting this -  *!image-2023-11-17-12-09-02-249.png|width=799,height=421!* 
Very similar to this github issue - https://github.com/solidify/jira-azuredevops-migrator/issues/114
just that I am getting in repro steps the problem
Also tried to use the mapper - MapRendered in the mapping but after that the repro steps got blank in azure

**To Reproduce**
1. Try importing a bug with repro steps having images in it

**Tool version**
 - Version of the jira-azuredevops-migrator tool - 3.0.115 (also tried on 3.0.250 but same behaviour)
**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt
- 
[config-agile.json](https://github.com/solidify/jira-azuredevops-migrator/files/13425630/config-agile.json)
[jira-export-log-231121-161953.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13425632/jira-export-log-231121-161953.txt)
[wi-import-log-231121-164942.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13425633/wi-import-log-231121-164942.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Usually you will want to migrate the description to ReproSteps, like this:

```json
      {
        "source": "description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug",
        "mapper": "MapRendered"
      },
```

Or is Repro Steps a custom field in your case? In that case, possibly related to https://github.com/solidify/jira-azuredevops-migrator/issues/602

**Comment by shweta22992** [comment]
Yes Repro Steps is a custom field that we are using in which all the screenshots etc we put, in description generally just plain text we put in our case. Is there any way you can suggest to work out images in Repro Steps.
In issue  - https://github.com/solidify/jira-azuredevops-migrator/issues/602 it mentions first revision is migrated but in my case after using MapRendered I am getting completely blank in Repro Steps in ADO.

**Comment by Alexander-Hjelm** [comment]
Gotcha. Most likely it is because the tool is trying to append the string "$Rendered" to the field id, as this is how description and other HTML fields work in Jira. Custom fields do not work this way however, so a fix is required on our part.

I am marking this issue as a bug report.

**Comment by Alexander-Hjelm** [comment]
@shweta22992, can you run the exporter with the setting "log-level": "Debug" in your configuration, and let me know what the output becomes for your ReproSteps field in the log? It should say something about which field it is trying to export and what the transformed value becomes.

**Comment by shweta22992** [comment]
@Alexander-Hjelm attaching the export log file. 
[jira-export-log-231123-103627.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13446657/jira-export-log-231123-103627.txt)
' to field 'Microsoft.VSTS.TCM.ReproSteps' is what I could see in the log.
Also if possible can you pls let me know in how much time can we expect a fix for the bug.

**Comment by Alexander-Hjelm** [comment]
I see a lot of these for example:

```txt
[D][10:36:50]    Mapped value '*Server: PSP*
*tFDB:  thinkfolio_222nathann*

*User: rfurbear*
*Portfolio(s)/Group(s):  Any* 
 * Make sure that this Admin option is set like this 

!image-2023-11-17-11-39-01-307.png|width=579,height=389!
 * Set up a CDS trades - click on Open OTC position and select CDS 

!image-2023-11-17-12-07-41-345.png|width=538,height=248!

 
 - make sure to set the deal date a day back . This a key point here . 

*!image-2023-11-17-12-09-02-249.png|width=799,height=421!*

 

*!image-2023-11-17-12-09-29-084.png|width=753,height=392!*
 * Save the trade at Working  and as you can see here the accrued  is positive and this is what the trademarketside will look like at this point. 

*!image-2023-11-17-12-11-15-937.png|width=628,height=259!*
 * Run a tE15 – with a specific load source with no data.- run te15 with sloadsource 'nope' 

!image-2023-11-17-11-16-25-901.png|width=549,height=283!

 

*Expected Result: Accrued doesn't change and there is no error* 
*Actual Result:* Accrued has become negative change and there is an error in the logs 

{*}!image-2023-11-17-12-19-44-651.png|width=649,height=245!{*}{*}{*}{*}{*}

 

*!image-2023-11-17-12-27-39-073.png|width=1234,height=724!*

{*}Screenshot(s){*}:' to field 'Microsoft.VSTS.TCM.ReproSteps'.
```

Which should indicate that the value got mapped correctly.

Unfortunately it is hard to give an estimate at the moment, since I'm the only resource from our side who is actively working on this project, and at the moment there are other pressing needs. We always welcome community contributions though. And if you need prority support, contact us at support.jira-migrator@solidify.dev to inquire about consulting services.

**Comment by shweta22992** [comment]
One point I missed to mention the above log comes when not using MapRendered and when I add this mapper then ReproSteps get miss from the log file. Attaching the log file after MapRendered.
[jira-export-log-231124-124033.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13456133/jira-export-log-231124-124033.txt)
Will discuss with my team regarding the priority

**Comment by Alexander-Hjelm** [comment]
@shweta22992 what field type is your **Repro Steps** field in Jira? I tried to reproduce the issue for Jira Cloud, but when creating a new field I cannot seem to find any field type that resembles anything like "Html tect field" or similar.  The closest field type I can find is **Text Field (multi-line)**, but that one does not have support for inline images, etc...

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/88f6ef41-aed0-466c-8ff7-e7638968ad40)

**Comment by shweta22992** [comment]
@Alexander-Hjelm it is just like the description field that we have for a bug in JIRA, it has type Wiki Style Renderer.

**Comment by Alexander-Hjelm** [comment]
Ok! It looks like only Custom fields of type "Free Text Field (unlimited text)" or "Text Field" supports the **Wiki Style Renderer**.
 I will try and reproduce this problem as soon as I can,

**Comment by Alexander-Hjelm** [comment]
Issue closed with merge of PR https://github.com/solidify/jira-azuredevops-migrator/pull/918, please reopen the issue and tag me if the problem persists.

**Comment by shweta22992** [comment]
@Alexander-Hjelm I tried the latest release but the issue is still there for me. Image doesnt come and if I use MapRendered then it becomes blank.
[jira-export-log-231129-110224.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13496510/jira-export-log-231129-110224.txt)
[wi-import-log-231129-110256.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13496511/wi-import-log-231129-110256.txt)

**Comment by shweta22992** [comment]
Also not getting the option to reopen, if you can pls reopen at your end . @Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
Demoting to support issue.

As I stated in #919, please make sure you have read through the FAQ on mapping and troubleshooting custom fields, I suspect you will find your answer there: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

I suspect that you have tried to enter the jira field name without using `"source-type`: "name"` in the configuration :)

**Comment by shweta22992** [comment]
Thanks, working now after adding the "source-type: "name" in config. Closing the issue.

**Comment by Alexander-Hjelm** [comment]
Perfect! :)
