### ISSUE TITLE
Can not export custom fields anymore using the latest ver. Also: TF51535: Cannot find field Custom.TimeSpentSecondsRendered.

### ISSUE THREAD

**Issue by timakamystery** [solidify/jira-azuredevops-migrator#912]
using ver. 250 custom fields don't get into the json files, whereas sticking to v.139 - works ok.
e.g.:
```
      {
        "source": "customfield_14128",
        "target": "Custom.CustomString1"
      },
      {
        "source": "customfield_12359",
        "target": "Microsoft.VSTS.Build.IntegrationBuild"
      },
```

Also on import new ver. has:
```
[E][10:16:23] TF51535: Cannot find field Custom.TimeSpentSecondsRendered.
```
```
      {
        "source": "timespent$Rendered",
        "target": "Custom.TimeSpentSecondsRendered"
      },
```
while the other ver. throws no such..

[wi-import-log-231115-101603.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13428425/wi-import-log-231115-101603.txt)
[jira-export-log-231115-101221.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13428427/jira-export-log-231115-101221.txt)
[config-evbs.json](https://github.com/solidify/jira-azuredevops-migrator/files/13428428/config-evbs.json)

**Comment by Alexander-Hjelm** [comment]
Regarding the first issue, have you tried the solution under: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

Regarding the second issue, it seems that your field is not present in the ADO work item tracking Process Template. You need to actually create the field first.

**Comment by timakamystery** [comment]
>> Regarding the second issue, it seems that your field is not present in the ADO work item tracking Process Template. You need to actually create the field first.
same config works ok w/the old ver. as mentioned.

**Comment by Alexander-Hjelm** [comment]
Not sure what the problem could be otherwise. The log is saying that the following field is required in your ADO process, but it could not be found: `Custom.TimeSpentSecondsRendered`

**Comment by timakamystery** [comment]
regarding #2
when try unrendered like, get nothing present in the json
```
      {
        "source": "timespent",
        "target": "Microsoft.VSTS.Scheduling.CompletedWork"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork"
      },
```

**Comment by timakamystery** [comment]
ver. 284
config:
```
      {
        "source": "resolutiondate",
        "type": "datetime",
        "target": "Microsoft.VSTS.Common.ResolvedDate"
      },
```
```
[E][10:07:14] Error mapping field 'Microsoft.VSTS.Common.ResolvedDate' on item 'ESSUITE-9134'.
[System.InvalidCastException] System.InvalidCastException: Specified cast is not valid.
   at JiraExport.JiraMapper.<>c__DisplayClass14_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r): 
   at JiraExport.JiraMapper.<>c__DisplayClass14_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)
```
didn't face such an issue before

**Comment by Alexander-Hjelm** [comment]
@timakamystery

I assumed you have checked https://github.com/solidify/jira-azuredevops-migrator/issues/834?

What version of Jira cloud/server are you running?

**Comment by timakamystery** [comment]
hi Alex
Jira DC v9.11.2
what to check @ #834  ?

**Comment by Alexander-Hjelm** [comment]
Ok!

Is it possible for you to build the source code and run the tool in an IDE? If so, can you set a breakpoint at this line (https://github.com/solidify/jira-azuredevops-migrator/blob/771e3a9d4af57160377a3acb51d95aa217ea3629/src/WorkItemMigrator/JiraExport/JiraItem.cs#L504C31-L504C31)?

And report back to me with a screenshot showing the value of `prop.Value`?

**Comment by timakamystery** [comment]
I have VSC. Never worked w/.NET but me being a devops the task above looks like a nice exercise. Will let u know, thx

**Comment by Alexander-Hjelm** [comment]
@timakamystery Of course, let me know if you need any help building the project. Setting up VS should be pretty straightforward, although it can be pretty memory heavy.

**Comment by timakamystery** [comment]
Rechecked my export log files. Last time it repro-d on 20/12 on ver. 284. On yesterday's export using ver. 329 - it didn't. Fixed ? :)

**Comment by Alexander-Hjelm** [comment]
It could very well be. We have fixed some issues related to various specific custom field types since 3.0.284.

But am I correct in my understanding that from 3.0.329 and onwards, the problem no longer appears for you? Or?

**Comment by timakamystery** [comment]
I've just did 1 migration yesterday using the latest at that point 329 and yes, it didn't repro. Will let u know if it changes. Thx

**Comment by Alexander-Hjelm** [comment]
Ok! Good to know, but would be nice to get to the bottom of it.

Let's keep this issue open, and feel free to tag me if the issue ever arises again.

The bot should close the issue in 30 days if no more activity is logged.

If I don't hear anything else, I will assume that everything is fine :D

**Comment by timakamystery** [comment]
repro-d again on latest 356
```
[E][17:43:11] Error mapping field 'Microsoft.VSTS.Common.ResolvedDate' on item 'ESSUITE-8024'.
[System.InvalidCastException] System.InvalidCastException: Specified cast is not valid.
   at JiraExport.JiraMapper.<>c__DisplayClass15_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r): 
   at JiraExport.JiraMapper.<>c__DisplayClass15_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)
```
will try in debug (not sure when yet)

**Comment by timakamystery** [comment]
@Alexander-Hjelm  and 1 more q. when a sprint is completed, all open issues get moved to the next sprint, which makes the field to hold multiple values, e.g. Sprint: IVR-2402, CC-Sprint-67. Hence json files don't have an Iteration Path. Expected: Iteration Path is filled with the latest value (usually the currently running sprint). Any suggestions pls ?
