### ISSUE TITLE
Unable to import the issues under Epic

### ISSUE THREAD

**Issue by pranaykh16** [solidify/jira-azuredevops-migrator#915]
**We are able to export only Epic not the issues under it.

Is solidify support to export issues under Epic for Jira Datacenter version.**

Source - **Jira Datacenter version**

**Comment by Alexander-Hjelm** [comment]
Insufficient desrciption of the issue. Please describe the issue in more detail and include any relevant configuration files and log files.

**Comment by pranaykh16** [comment]
Hi Team,

Scenario - We need to migrate the one Epic and issues which under it from ### **Jira (Datacenter Version)** to **Azure DevOps.**

Issue - We execute the tool and export and import the details to Azure DevOps, everything looks good but **### when we check at the Azure DevOps portal we only see Epic not the issues which are linked with it in Jira**.

**### So any idea why issues that were linked to Epic didn't migrated ???**

**Comment by Alexander-Hjelm** [comment]
So far the problem remains very vague, but here are some general guidelines:

- Make sure that all of your desired items are caught by the query in your config.json (You can test the JQL query manually in Jira.
- Make sure that there are no errors or related warnings in any of the log files.
- Maybe the linked issues are in another project.
- Maybe the link type is not set up in your link mapping

**Comment by pranaykh16** [comment]
Thank you for sharing the Guidelines, Now it is working fine after updating the JQL query.
