### ISSUE TITLE
Custom Field not getting mapped from Jira to ADO

### ISSUE THREAD

**Issue by shweta22992** [solidify/jira-azuredevops-migrator#916]
**Describe the problem**
I have a Jira field Component/s (in Details) and want to map into custom field tF Components into ADO but is not getting mapped.

**Tool version**
 - 3.0.115

**Attachments**

Please attach the following files:
[config-agile.json](https://github.com/solidify/jira-azuredevops-migrator/files/13459699/config-agile.json)
[jira-export-log-231124-191934.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13459746/jira-export-log-231124-191934.txt)
[wi-import-log-231124-191955.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13459747/wi-import-log-231124-191955.txt)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
The entry in your config looks weird: `"source": "Component/s"`

Confirm that this is the correct name of the field? You might need to do a Rest API query to find the correct key of the issue field.

**Comment by shweta22992** [comment]
Hi @Alexander-Hjelm I checked in the rest response and I could see different name like below -
"components": [
      {
        "self": "https://xxxxrest/api/2/component/xxx",
        "id": "16163",
        "name": "comp"
      }
    ]
but after changing the name in config still it didnt get map 
{
        "source": "components",
        "target": "tF Components",
	"mapper": "MapArray",
	"for":"Epic,Feature,Task,User Story,Bug"
}
Is there something I am missing here

**Comment by Alexander-Hjelm** [comment]
Are you sure that the **reference name** of the field in ADO is actually "tF Components"? This looks strange. Are you maybe using the **field name** instead? Usually spaces are not allowed in the reference name.

**Comment by Alexander-Hjelm** [comment]
Field consolidation is a PRO feature only. You can read more about the PRO version, which is currently in an early adopter evaluation phase, here: https://github.com/solidify/jira-azuredevops-migrator#jira-azure-devops-migrator-pro

You can also use the contact information there to inquire about purchasing the PRO version :)

**Comment by shweta22992** [comment]
Got it, thanks.
