### ISSUE TITLE
Some fields while mapping from JIRA to ADO are showing old revision data 

### ISSUE THREAD

**Issue by shweta22992** [solidify/jira-azuredevops-migrator#919]
**Describe the problem**

While mapping the fields, some fields in ADO are showing the old revision (mostly first that I could see) data instead of the latest one
**To Reproduce**

1. Try mapping the fields like Target Release, Requesting Company (3.0.266 was fine in 3.0.115) having multiple revisions
2. In ADO the target fields shows old data

**Tool version**
 -  3.0.115, 3.0.266

**Attachments**

Please attach the following files:

[jira-export-log-231129-110224.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13496893/jira-export-log-231129-110224.txt)

[wi-import-log-231129-110256.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13496895/wi-import-log-231129-110256.txt)
[config-agile.json](https://github.com/solidify/jira-azuredevops-migrator/files/13496900/config-agile.json)

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/16130062/8d3bbc5d-cf07-4087-9bde-cbb934d0ffee)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/16130062/c1e53b5b-ea00-427d-b10b-1982b5a206af)

**Comment by Alexander-Hjelm** [comment]
Please make sure you have read through the FAQ on mapping and troubleshooting custom fields, I suspect you will find your answer there: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

**Comment by shweta22992** [comment]
Thanks I got them correct now by changing in the custom field mapping.
