### ISSUE TITLE
Unable to Map the Resolution Field Data

### ISSUE THREAD

**Issue by pranaykh16** [solidify/jira-azuredevops-migrator#920]
Scenario - We need to map the Jira resolution field data to ADO Custom created Field.

Configuration 

{
        "source": "resolution",
        "target": "Custom.Resolutions",
        "mapping": {
          "values": [
            {
              "source": "None",
              "target": "None"
            },
            {
              "source": "Resolved",
              "target": "Resolved"
            },
            {
              "source": "Unresolved",
              "target": "Unresolved"
            },
            {
              "source": "Done",
              "target": "Done"
            }        
          ]
        }
      },

Current Situation - Resolution Field Data is not mapping on the ADO Field.

So could you please provide assistance on the above issue.

**Comment by Alexander-Hjelm** [comment]
Please see the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by pranaykh16** [comment]
Hi Team,

So **### We are facing mapping issues with ADO Epic work item resolution field**, But for User Story & Task resolution data is mapping correctly.

**Comment by Alexander-Hjelm** [comment]
@pranaykh16 

It is my understanding that this is a different issue than originally?

Consider contacting us for a paid support plan or other consulting services: https://github.com/solidify/jira-azuredevops-migrator#jira-azure-devops-migrator-pro
