### ISSUE TITLE
Unable to Map the Jira Time tracking Fields

### ISSUE THREAD

**Issue by pranaykh16** [solidify/jira-azuredevops-migrator#921]
Scenario - We need to map the Jira time tracking fields to ADO Efforts Fields.

Configuration - 

{
        "source": "Estimated",
        "target": "Microsoft.VSTS.Scheduling.OriginalEstimate",
        "for": "Bug,Task"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork",
        "for": "Feature,Epic,User Story,Bug,Task"
      },
      {
        "source": "Logged",
        "target": "Microsoft.VSTS.Scheduling.CompletedWork",
        "for": "Bug,Task"
      },

Current Situation - We have tried multiple configuration mappings and it is not working.

**Comment by Alexander-Hjelm** [comment]
See FAQ on mapping custom fields: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by aakash-pinc** [comment]
@pranaykh16: Is this working? Are you able to migrate time tracking fields to ADO? If so, how did you do it?
