### ISSUE TITLE
Child items not getting mapped properly in ADO

### ISSUE THREAD

**Issue by shweta22992** [solidify/jira-azuredevops-migrator#922]
**Describe the problem**

While migrating from JIRA to ADO the child tickets are not getting mapped properly (losing the title, description etc). I get the error in import log 
[E][16:43:02] TF51535: Cannot find field Link to parent Feature.
[E][16:43:02] Work Item 359981 failed to save.
Also the area path of the child tickets is becoming different than of parent

**Tool version**
 - 3.0.266

**Attachments**

Please attach the following files:

[config-agile.json](https://github.com/solidify/jira-azuredevops-migrator/files/13526000/config-agile.json)
[jira-export-log-231201-164041.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13526003/jira-export-log-231201-164041.txt)
[wi-import-log-231201-164207.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13526004/wi-import-log-231201-164207.txt)

**Screenshots**
Example of a child ticket coming without data
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/16130062/a78a187a-c90c-4a70-8025-d66aafaf3653)

**Comment by Alexander-Hjelm** [comment]
Please see the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field
