### ISSUE TITLE
For some custom fields if the value was made blank in JIRA then it shows the previous revision in ADO

### ISSUE THREAD

**Issue by shweta22992** [solidify/jira-azuredevops-migrator#927]
**Describe the problem**

For a few custom fields when migrating in ADO its showing the prev value before it was made blank. Also in export logs I can see an null reference exception for some fields.
for eg, for below field this happens
 {
        "source": "Resolution Version(s)",
		"source-type": "name",
        "target": "Custom.tFResolutionVersion",
		"mapper": "MapTags",
		"for":"User Story,Bug"
},

**Tool version**
 - 3.0.266

**Attachments**

Please attach the following files:

[jira-export-log-231206-160727.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13600950/jira-export-log-231206-160727.txt)
[wi-import-log-231206-164312.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13600951/wi-import-log-231206-164312.txt)
[config-agile.json](https://github.com/solidify/jira-azuredevops-migrator/files/13600957/config-agile.json)

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Wondering if this is maybe related to the MapTags mapper. I will try to replicate the scenario where the tags are unset.

What type is the field "Resolution Version(s)"? Is it a built-in or custom field?

**Comment by shweta22992** [comment]
@Alexander-Hjelm it may be taking None as a value, when I check the history I get it like below - 
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/16130062/c9d54954-fc44-4069-89c0-72a055034599)

"Resolution Version(s)" is a custom field we are using.
MapTags I am using as we run some custom code on that field and we want that to be delimited by some proper character that can be checked, initially it was coming space separated, so by MapTags it made it semicolon separated

**Comment by Alexander-Hjelm** [comment]
@shweta22992 Why not just use MapArray instead?

**Comment by shweta22992** [comment]
I was initially using MapArray but that was giving space delimited which we think may not be a robust option to go with for processing later.
Also I tried removing the MapTags mapper and still it was giving me the issue.

**Comment by Alexander-Hjelm** [comment]
That shouldn't be possible. The MapArray mapper will take the value, split by comma and delimit the result by semicolon. You can refer to the source code here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/RevisionUtils/FieldMapperUtils.cs#L149

**Comment by shweta22992** [comment]
@Alexander-Hjelm I will take a look at this and again try to change, but if you can suggest something for the data issue after getting blank, as that is the more problematic thing for us currently

**Comment by shweta22992** [comment]
@Alexander-Hjelm I have raised a PR for this 
https://github.com/shweta22992/fix-nulldatanotmapped/pull/1
do let me know if this looks fine or any suggestions you have

**Comment by Alexander-Hjelm** [comment]
@shweta22992 Ah! That could indeed be an issue. My bad. Thanks for sniffing this one out.

I think a safer way would be to store (value || "") in an interim variable, so that we don't accidentally edit something outside of the current block.

I will create a fix for this asap.

**Comment by Alexander-Hjelm** [comment]
@shweta22992 Nevermind, upon closer inspection I think your PR looks good enough as it is.

It seems like you have raised a PR to the main line of your own fork. I'm not sure if this was on purpose or not?

If you want credit for you fix, please edit the PR so that it merges into the main repo! Let me know otherwise and I'll apply the fix.

**Comment by shweta22992** [comment]
@Alexander-Hjelm no that got by mistake I think. was truing to raise to the main repo. I will check where I have to make change for pointing it to main repo

**Comment by shweta22992** [comment]
https://github.com/solidify/jira-azuredevops-migrator/pull/940
