### ISSUE TITLE
Getting a 400 error when trying to export from JIRA

### ISSUE THREAD

**Issue by jstrasburger17** [solidify/jira-azuredevops-migrator#929]
Getting a 400 error when trying to export from JIRA

[E][14:41:36] Failed to get item count using query: 'project = ICC '
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'ICC' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)

**To Reproduce**

Have tried with every combination possible of username, password and APIToken

jira-export -u "username@email.com" -p "password" --url https://xxxxxx.atlassian.net/ --config config-agile.json --force
jira-export -u "username@email.com" -p "APItoken" --url https://xxxxxx.atlassian.net/ --config config-agile.json --force
jira-export -u "username" -p "API token" --url https://xxxxxx.atlassian.net/ --config config-agile.json --force
jira-export -u "username" -p "password" --url https://xxxxxx.atlassian.net/ --config config-agile.json --force

In addition, have used incorrect username/password and get the same error, trying to get a 401 error
It's as if the export tool is not communicating to Jira

My account has Admin permission in Jira and no issue authenticating via browser

export tool is reading the config file:   config-agile.json
If I change the query the error message changes accordingly

**Tool version**
 - Version of the jira-azuredevops-migrator tool [3..0284]

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/102532667/1212f4ad-bff2-4ed7-8a63-82d9bddab30d)
![jiramigrator_screenshot](https://github.com/solidify/jira-azuredevops-migrator/assets/102532667/e6bb0e64-cbf1-4ed5-9d0f-32beeec087f8)
[jira-export-log-231214-144117.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13677658/jira-export-log-231214-144117.txt)

**Comment by Alexander-Hjelm** [comment]
Likely related to https://github.com/solidify/jira-azuredevops-migrator/issues/903. Try the fixes suggested there and let us know if the problem still persists.

**Comment by jstrasburger17** [comment]
I got this working today with the new version  https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.285
v3.0.285  (did not work with previous version v3.0.284)

used email address and API Token and the query below in config.json file

 "query": "project = \"ICC\" ORDER BY Rank ASC",

If others have the same problem refer to #903
Likely related to https://github.com/solidify/jira-azuredevops-migrator/issues/903

**Comment by Alexander-Hjelm** [comment]
Nice! Closing. See continued discussion in #903. I will document this solution in the FAQ
