### ISSUE TITLE
Rework how user mapping is done

### ISSUE THREAD

**Issue by MOlausson** [solidify/jira-azuredevops-migrator#93]
The api's to look up emails have changed, we should find another way of mapping user.

From #87

@MOlausson not sure if this is why, but i believe in current implementation, user info is retrieved by passing username, looking at this api it looks like username is deprecated and prefer using accountid: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-user-get
Also looks like getting user's email address is whole different process too: https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-user-email-get

**Comment by sanjeev40084** [comment]
@MOlausson looks like email is available in new version of Jira API :)
https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-user-get
