### ISSUE TITLE
Jira export not working for 2 step / 2SV authenticated Jira account

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#931]
Jira export not working for 2 step / 2SV authenticated Jira account

**Comment by Alexander-Hjelm** [comment]
Make sure that you have tried all possible solutions listed in the FAQ: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#2-why-i-am-getting-unauthorized-exception-when-running-the-export

For Jira Servers with MFA enforced, we recommend using an OAuth token for authenticating with the Jira Rest API instead.

**Comment by ankusinha23** [comment]
hi @Alexander-Hjelm  can u help me how to create OAuth token for authenticating with the Jira Server related api

**Comment by Alexander-Hjelm** [comment]
Atlassian should have fairly extensive documentation on this.

If you require an engagement with us for help, feel free to contact us at support.jira-migrator@solidify.dev for expert consulting services.
