### ISSUE TITLE
Importing Git Commit links results in error "Commit link could not be read"

### ISSUE THREAD

**Issue by cobypritchard** [solidify/jira-azuredevops-migrator#932]
**Describe the problem**

For Azure DevOps the vstfs is not in the correct format causing the "Commit link could not be read" error to display in GUI. Looking at the work item through the API the invalid link is:  
"url": "vstfs:///Git/Commit/{projectName}/{repositoryName}/{commitId}".

The correct format should be:
"url": "vstfs:///Git/Commit/{projectId}%2f{repositoryId}%2f{commitId}".

**To Reproduce**

1. Insert into config.json:
```
  "include-commits": true,
  "repository-map": {
    "repository": [
      {
        "source": "SourceA",
        "target": "SourceB"
      },
    ]
  },
```
2. Run the jira-export.exe to export JIRA data.
3. Run the wi-import.exe to import the data.

**Tool version**
3.0.288

**Attachments**

Please attach the following files:

**Screenshots**
<img width="291" alt="commitlink" src="https://github.com/solidify/jira-azuredevops-migrator/assets/1855859/7741407f-e5e3-4f28-a8c1-e7e3e973552d">
<img width="859" alt="apilink" src="https://github.com/solidify/jira-azuredevops-migrator/assets/1855859/e5f014e3-c78d-44bf-af77-2a4487a85158">

**Comment by Alexander-Hjelm** [comment]
@cobypritchard I think this is strange, since other people have reported the commit links working fine.

What version of Azure DevOps are you running? Cloud or Server? Which version of server?

I'm a bit hesitant to merge your PR straight away, in case it could cause compatibility issues for other people on other versions of Azure DevOps.

**Comment by cobypritchard** [comment]
@Alexander-Hjelm 
Cloud
Sprint 231

I don't know if it is different for TFS or On-Prem. I don't have access to those systems.

I used this [Pull Requests - Create](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/create?view=azure-devops-rest-7.1&tabs=HTTP) and this [Artifact Uri Query - Query](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/artifact-uri-query/query?view=azure-devops-rest-7.1&tabs=HTTP) for my changes.

**Comment by Alexander-Hjelm** [comment]
Ok! Upon reviewing the API documentation it seems that your solution is the correct one.

Let me merge into a feature branch on the mother repo so we can run some tests!
