### ISSUE TITLE
Mapping Checkbox field in Jira to a Boolean field in Azure DevOps

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#935]
I have been trying to map a checkbox field in JIra to a Boolean field in ADO without success. I get the following error message:

[E][15:54:47] Error mapping field 'Custom.XXXXOptions' on item 'LIC-99'.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraMapper.<>c__DisplayClass14_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r):
   at JiraExport.JiraMapper.<>c__DisplayClass14_0`1.<IfChanged>b__0(JiraRevision r)
   at JiraExport.JiraMapper.MapFields(JiraRevision r)

I am using the below in my config file:
{
                "source": "XXXX Options",
                "source-type": "name",
                "target": "Custom.XXXXOptions"
            },

I have searched the FAQ but have not found anything that seems to solve my problem. 

Is what I am doing possible?

**Comment by Alexander-Hjelm** [comment]
@C-F-Palmer What version of Jira is this?

I did a test against Jira Cloud with the below field map:

```
      {
        "source": "alexander-testar-custom-checkboxes",
        "source-type": "name",
        "target": "Custom.CustomCheckboxes"
      },
```

Here I have defined a custom field of the standard type "Checkboxes", and set the value only on the first revision:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/c73ef2af-8753-46a8-9072-ce5da72694ee)

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/10683896/a5ac94cb-99b0-45c6-af5c-0c5259392fdd)

As you can see, the resulting work item contains the correct mapped value on the first revision:

```json
    {
      "Author": "alexander.hjelm@solidify.dev",
      "Time": "2023-12-22T19:29:46.337+01:00",
      "Index": 0,
      "Fields": [
        {
          "ReferenceName": "System.Title",
          "Value": "[AGILEDEMO-43] [Jira smoke tests] Task with custom checkboxes"
        },
        {
          "ReferenceName": "Microsoft.VSTS.Common.Priority",
          "Value": "3"
        },
        {
          "ReferenceName": "Custom.Reference",
          "Value": "AGILEDEMO-43"
        },
        {
          "ReferenceName": "Custom.CustomCheckboxes",
          "Value": "Option 1;Option b"
        },
        {
          "ReferenceName": "System.State",
          "Value": "New"
        }
      ],
```

Check if there are any major differences between our cases and let me know if you find anything significant!

**Comment by Jbekker** [comment]
Just a gut feeling: before [v3.0.310](https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.310) and to be precise PR #901, you would get a null reference exception if the mapping contains a custom field that does not exist in Jira. Can you try this again with the latest version?

**Comment by Alexander-Hjelm** [comment]
@Jbekker I trust your gut feeling 😆 

Do you know right now where in the code this null reference exception would arise?

**Comment by Jbekker** [comment]
For sure! please see https://github.com/solidify/jira-azuredevops-migrator/blob/v3.0.308/src/WorkItemMigrator/JiraExport/JiraMapper.cs#L400

Variable _customFieldName_ can be null when the field with the specified name in the configuration can't be found. In that case _customFieldName.toLower()_ would give the null reference exception.

**Comment by C-F-Palmer** [comment]
> Just a gut feeling: before [v3.0.310](https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.310) and to be precise PR #901, you would get a null reference exception if the mapping contains a custom field that does not exist in Jira. Can you try this again with the latest version?

Hi Alexander and Jelle,

Happy New Year to you both!!

Jelle was correct. I upgraded to the latest version (3.0.328) and I no longer get the error message.

However the field is not being mapped. 

Jira Field:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/92213401/08e6e6d0-dd20-4e1f-8fe8-92d66ed25577)

Azure Field:

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/92213401/75eeb663-8158-4339-97e5-0f6e6c7aaee5)

Export Log:

====================================================================
Jira Export Log
====================================================================
Tool version : 3.0.328
Start time   : 03/01/2024 11:35:16
Telemetry    : Enabled
Session id   : 6d02e98a-d3c6-4186-bdde-eb1db77808fa
Tool user    : IKONSCIENCE\cpalmer
Config       : config-scrum.json
Force        : yes
Log level    : Debug
Machine      : xxxxxxxx
System       : Microsoft Windows 10.0.22621
Jira url     : http://xxxxxxxxxx
Jira user    : chris.palmer
Jira version : 7.11.1
Jira type    : Server
====================================================================
[I][11:35:15] Connecting to Jira...
[I][11:35:15] Retrieving Jira fields...
[I][11:35:16] Retrieving Jira link types...
[D][11:35:16]    Get item count using query: 'project = LIC AND key = LIC-52'
[I][11:35:16] Export started. Selecting 1 items.
[W][11:35:16] User mapping file 'C:\Jira Export 3.0.328\users.txt' not found, ignoring mapping user identities.
[I][11:35:16] Initializing Jira field mapping...
[W][11:35:16] Could not find the field id for 'XXX Options', please check the field mapping!
[W][11:35:16] Could not find the field id for 'XX Options', please check the field mapping!
[W][11:35:16] Could not find the field id for 'XXXXXXXXX Options', please check the field mapping!
[W][11:35:16] Could not find the field id for 'XXXXX Options', please check the field mapping!
[W][11:35:16] Could not find the field id for 'Flag Options', please check the field mapping!
[W][11:35:16] Could not find the field id for 'XXXXXXX Options', please check the field mapping!
**[W][11:35:16] Could not find the field id for 'XXXX Options', please check the field mapping!**

I am using this format in my mapping file:

{
                "source": "XXXX Options",
                "source-type": "name",
                "target": "Custom.XXXXOptions"
            },

Not sure what I am doing wrong now?

**Comment by C-F-Palmer** [comment]
Please hold off investigating my above comments. I think I know where I am going wrong. Although the JIra field is a checkbox when you edit/select it, it does however add the name of the checkbox to the field and therefore using a boolean field in ADO will probably not work for this.

**Comment by Alexander-Hjelm** [comment]
Happy new year @C-F-Palmer ! :)

Check the FAQ section for mapping custom fields maybe if you haven't already? There are some recommendations and troubleshooting guides there: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by C-F-Palmer** [comment]
I have this working now. Thanks for your help. I changed the ADO field from a Boolean field type to a text single line field type.

**Comment by Alexander-Hjelm** [comment]
Perfect.

I will address the nullreference exception mentioned here as soon as I have time: https://github.com/solidify/jira-azuredevops-migrator/issues/935#issuecomment-1875166578

**Comment by Alexander-Hjelm** [comment]
Looks like the problematic line was already removed in v3.0.310. I'm closing this issue now, as all works seems to be done. Feel free to reopen the issue if the problem persists or if you have any questions or concerns.
