### ISSUE TITLE
how to restrcit the number of item to be exported during JIRA export

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#944]

**Comment by ankusinha23** [comment]
for example there are 40000 work items so i want to export first 1000 and then next 1000 and so on.. how we can achieve that

**Comment by Alexander-Hjelm** [comment]
@ankusinha23 We have no plans to support pagniation, but you can achieve something similar by limiting export to batches of issues through the `query` property of your `config.json` file. Simply enter a JQL query that filters issues on the `ìd` property, for example:

```
project = "PROJECTKEY" AND id >= 10000 AND id < 11000
project = "PROJECTKEY" AND id >= 11000 AND id < 12000
project = "PROJECTKEY" AND id >= 12000 AND id < 13000
```

And so on.

You can always use the **issues** view in your Jira project to experiment with different JQL queries.
