### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.SourceControl.WebApi

### ISSUE THREAD

**Issue by keeperlou** [solidify/jira-azuredevops-migrator#946]
Hello, 

I am facing an error while importing to azure devops cloud.

The error is:  Unexpected migration error.
[System.IO.FileNotFoundException] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.SourceControl.WebApi, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

[wi-import-log-231227-113732.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13777881/wi-import-log-231227-113732.txt)

[config-agileV2.json](https://github.com/solidify/jira-azuredevops-migrator/files/13777885/config-agileV2.json)

[jira-export-log-231227-101038.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13777888/jira-export-log-231227-101038.txt)

command in CLI: wi-import --token xxxxxxxx --url https://dev.azure.com/ITNR-DLWR/ --config config-agileV2.json --force

Version: 3.0.303 

I really don't know how to fix this. Could it be due to permission on the devops?

**Comment by Alexander-Hjelm** [comment]
@keeperlou Try the latest versino (3.0.308)!

What OS/Platform are you running on?

**Comment by keeperlou** [comment]
@Alexander-Hjelm   this on windos 11

**Comment by keeperlou** [comment]
@Alexander-Hjelm I re-tried it with latest version but still the same error:

[wi-import-log-231228-120635.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13785915/wi-import-log-231228-120635.txt)

Could this be an error due to not enough permissions on devops?
thank you

**Comment by Alexander-Hjelm** [comment]
Verify that the path to the workspace and the config file are correct, first of all.

You can check the necessary ADO permissions here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md#azure-devopstfs-requirements

**Comment by keeperlou** [comment]
@Alexander-Hjelm 
I re-tried it with the latest version. All permissions are ok. Path of workspace is ok. The config file is between the extracted files

Could the error due to windows 11?

I have no clue on what I can try next

Thank you very much for your help

**Comment by whambo666** [comment]
Getting _exactly_ the same error here also. 

v.3.0.310 - Win10 - ADO permissions, workspace & config file links all correct.
