### ISSUE TITLE
AssignedTo is generated with the null at the export. Import fails with [System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ValekMal** [solidify/jira-azuredevops-migrator#95]
I have a user mapping file, which has the *=john@blablabla.ddd clause in the end of the file. 
When exporting, the files are generated properly and look okay, no errors.
When importing, the wi-import gives 

[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.

The section of the JIRA file is below:

"Index":6,"Fields":[{"ReferenceName":"System.AssignedTo","Value":null}],"Links":[],"Attachments":[],"AttachmentReferences":false},{"Author":"john@blablabla.ddd","Time":"2019-03-27T12:09:03.42+11:00",

Note the "Value":null in there.
The change number 7 in JIRA was that the assigned user was changed from a real user to Unassigned.

**Comment by MOlausson** [comment]
Fixed from v2.2.88.
