### ISSUE TITLE
Attachments not exporting in version 3.0.328 (latest version)

### ISSUE THREAD

**Issue by C-F-Palmer** [solidify/jira-azuredevops-migrator#952]
Hi Alexander,

I have noticed that the attachments are not exporting in the latest version. I am getting the same error message as was raised in issue #851.

**[D][13:45:49]    No attachment to undo for 'Added 18368/Hess PO for MSrenewal 2018-19.pdf'.
[D][13:45:49]    Attachment Hess PO for MSrenewal 2018-19.pdf cannot be migrated because it was deleted.**

**Comment by Alexander-Hjelm** [comment]
@C-F-Palmer Could this possibly be related to https://github.com/solidify/jira-azuredevops-migrator/issues/851?

**Comment by C-F-Palmer** [comment]
> @C-F-Palmer Could this possibly be related to #851?

Hi Alexander, I believe it is the same issue as reported in #851.

**Comment by Alexander-Hjelm** [comment]
OK!

Let's close this issue and continue discussion in #851
