### ISSUE TITLE
Unexpected migration error

### ISSUE THREAD

**Issue by denissatoru** [solidify/jira-azuredevops-migrator#954]
Hello, guys.

I'm facing this problem when I try to import in Azure.

[E][17:47:26] Unexpected migration error.
[Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: The resource cannot be found.

![image](https://github.com/solidify/jira-azuredevops-migrator/assets/155082091/ab95ec4a-187e-4c54-93ef-2ade6bcbff15)

And later, many and many lines of errors...

Perhaps I have to install the Visual Studio?

Could you help me?

Tks!

**Comment by Alexander-Hjelm** [comment]
I'm taking a guess here, but I think that the most likely culprit is the Azure DevOps connectivity. Make sure that you are using the correct credentials, your token has the proper scopes and is not expired, no issues  with proxy or firewall, etc...

Check that the ADO URL is written correctly in the command and that the project name is correct in the config.
