### ISSUE TITLE
Mapping source and target for item types

### ISSUE THREAD

**Issue by reminvestor** [solidify/jira-azuredevops-migrator#955]
I am trying to migrate these ready to work items for each item type. I have ready to work items for Improvement, Epic and Bugs. I don't see a way to configure my migration config to do this. JIRA was setup with these sub statuses for each type. Can this be configured to map correctly?

[I][12:34:16] Processing 13/1490 - 'NMAP-1941'.
[W][12:34:17] Missing mapping value 'READY FOR WORK' for field 'status' for item type 'Improvement'.
[I][12:34:17] Processing 14/1490 - 'NMAP-1940'.
[W][12:34:18] Missing mapping value 'READY FOR WORK' for field 'status' for item type 'Improvement'.
[I][12:34:18] Processing epic parent 'NMAP-1626'.
[W][12:34:19] Missing mapping value 'READY FOR WORK' for field 'status' for item type 'Epic'.
[I][12:34:19] Processing 15/1490 - 'NMAP-1939'.
[W][12:34:19] Missing mapping value 'READY FOR WORK' for field 'status' for item type 'Improvement'.
[I][12:34:19] Processing 16/1490 - 'NMAP-1938'.
[W][12:34:22] Missing mapping value 'READY FOR WORK' for field 'status' for item type 'Bug'.

**Comment by Alexander-Hjelm** [comment]
In your field-map, the status **READY FOR WORK** is missing for all of the above work items types. You will need to add a status mapping in your config for that value.

**Comment by reminvestor** [comment]
{
        "source": "status",
        "target": "System.State",
        "for": "New Feature,Epic,User Story,Bug, Improvement",
        "mapping": {
          "values": [
            {
              "source": "Development In Progress",
              "target": "Development"
            },
            {
              "source": "Ready for QA",
              "target": "Ready for QA"
            },
            {
              "source": "Deployed to QA",
              "target": "Deployed to QA"
            },
            {
              "source": "Ready to Deploy: UAT",
              "target": "Ready for UAT"
            },
            {
              "source": "Deployed to UAT",
              "target": "Deployed for UAT"
            },
            {
              "source": "READY FOR WORK",
              "target": "READY FOR WORK"
            },
          ]
        }
        
        Under field-map source field status I have this which does't seem to be it.

**Comment by Alexander-Hjelm** [comment]
Seems like there is a space too much here?

```
"for": "New Feature,Epic,User Story,Bug, Improvement"
```
