### ISSUE TITLE
Migrate JIra afeect version to found in BUild field in Azure devops

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#958]
I need to migrate **Afeect version** of JIRA field which is text box to **Found in Build** in Azure devops which is dropdown where we can enter text as well .. what chnages i need to do in config file
![JIRA](https://github.com/solidify/jira-azuredevops-migrator/assets/154508737/0acec93b-4a8a-4eff-bc33-87187b3cfcc9)
![Azure Devops](https://github.com/solidify/jira-azuredevops-migrator/assets/154508737/4a0baea2-668d-440e-9480-9058213c76b7)

What chnages in config i need to make for the same including the mapper type.
this is config file
[config.json](https://github.com/solidify/jira-azuredevops-migrator/files/13869448/config.json)

**Comment by Alexander-Hjelm** [comment]
The field mapping would look something like this, I think:

```md
      {
        "source": "versions",
        "target": "Custom.MyAdoFieldReference"
      },
```

Maybe consider using the Array mapper:

```md
      {
        "source": "versions",
        "target": "Custom.MyAdoFieldReference",
        "mapper": "MapArray"
      },
```

Where `Custom.MyAdoFieldReference` is the Work Item Field References in your Azure DevOps instance.
