### ISSUE TITLE
Work Item status is coming wrong from JIRA during JIRA export

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#962]
this is the config .. i am configuring mapping for all the status in the config .json
[config.json](https://github.com/solidify/jira-azuredevops-migrator/files/13898080/config.json)
 but during export among all the status only for status Backlog and Unestimated from JIRA is getting properly mapped with azure devops state and migrated properly in azure devops . but for JIRA Status Open,In Progress and Reopened its not working .. during JIRA export itself wrong value od JIRA Stauus which is always **Backlog** is coming in JIRAVersion object while debugging the code
 
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/154508737/3d3853d5-17d7-44c7-9046-1fe611fa6c26)
 this is the workflow
 
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/154508737/87ebfd3c-7ff7-45c7-8073-884f4f8bd97f)
and this is the azure devops workitem state
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/154508737/3f8741e4-6126-421b-8238-e98fb46c0af7)

**Comment by Alexander-Hjelm** [comment]
@ankusinha23 Hard to say straight away. Your config looks correct. Could be the spelling/casing of the status names?

Please attach the export log as well if possible.

**Comment by ankusinha23** [comment]
@Alexander-Hjelm  here the log file
[Uploading jira-export-log-240111-140600.txt…]()

**Comment by Alexander-Hjelm** [comment]
Seems like the link got broken. Try uploading again?

**Comment by Alexander-Hjelm** [comment]
Same issue with the link, but from the snippet I can tell that you have a lot of unmapped statuses for the Epic issue type.

**Comment by ankusinha23** [comment]
@Alexander-Hjelm  yes . but currently i m focusing on bug one .. epic still need to work upon and this isusue is coming while bug migration

**Comment by ankusinha23** [comment]
@Alexander-Hjelm  also wanted to check if its possible to have 2or more JIRA field migrated to one field for example some text fieldin azure devops?

**Comment by Alexander-Hjelm** [comment]
> @Alexander-Hjelm also wanted to check if its possible to have 2or more JIRA field migrated to one field for example some text fieldin azure devops?

Yes, that's a PRO feature. You can read more about our pro offering here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-azure-devops-migrator-pro
