### ISSUE TITLE
causes link type not getting mapped in ADO

### ISSUE THREAD

**Issue by anurao98** [solidify/jira-azuredevops-migrator#963]
How should we map causes and is caused by link types in tool v3.0.328 ?

tried mapping:
{
"source": "causes",
"target": "System.LinkTypes.Related"
},
{
"source": "is caused by",
"target": "System.LinkTypes.Related"
}
but not getting mapped as Related in ADO. No links are established in ADO with the above mapping. @Alexander-Hjelm please give a check.

**Comment by Alexander-Hjelm** [comment]
You can find link type references for Azure DevOps here: https://learn.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops

Causes/Is Caused By seem to be custom link types? In that case you need to specify the Link type Name. Check the spelling/casing maybe.
