### ISSUE TITLE
Migrate Field name along with value in azure devops

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#966]
how can we include the field name along with value in a text .for eg supposose a field named Affect Versions in JIra is migrated to some text field  in azure devops so how can miggrated as **affect version - value** in the text field of azure devops

**Comment by Alexander-Hjelm** [comment]
That's a feature in Jira Migrator PRO. You can read more here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-azure-devops-migrator-pro

Reach out to us at support.jira-migrator@solidify.dev to inquire about the product and get a quote.
