### ISSUE TITLE
I am trying to export WITs from Jira and Confluence and Import them to Azure Devops. It doesnt bring the links from Confluence

### ISSUE THREAD

**Issue by Yoda-Man** [solidify/jira-azuredevops-migrator#969]
I am trying to export WITs from Jira and Confluence and Import them to Azure Devops. It doesnt bring the links from Confluence

**Comment by Alexander-Hjelm** [comment]
Migrating Confluence to Azure DevOps Wikis + preserving issue links inside Confluence pages is a feature of our Jira Azure DevOps Migrator PRO offering. Read more here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-azure-devops-migrator-pro

Feel free to email us at [support.jira-migrator@solidify.dev](mailto:support.jira-migrator@solidify.dev) to inquire and receive a quote.
