### ISSUE TITLE
Error while JIRA exporT

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#971]
[config.json](https://github.com/solidify/jira-azuredevops-migrator/files/14038025/config.json)
[jira-export-log-240124-165704.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14038028/jira-export-log-240124-165704.txt)

NOT SURE WHY i m getting these errors
[W][16:57:06] No target type 'Epic' is set, field status cannot be mapped.
[W][16:57:06] No target type '' is set, field status cannot be mapped.
[W][16:57:06] No target type 'Customizing ' is set, field status cannot be mapped.
[W][16:57:06] No target type 'Customizing Sub-task' is set, field status cannot be mapped.
[W][16:57:06] No target type 'Sub-task' is set, field status cannot be mapped.
[W][16:57:06] No target type 'Epic' is set, field status cannot be mapped.
[W][16:57:06] No target type '' is set, field status cannot be mapped.
[W][16:57:06] No target type 'Customizing ' is set, field status cannot be mapped.
[W][16:57:06] No target type 'Customizing Sub-task' is set, field status cannot be mapped.
[W][16:57:06] Ignoring target mapping with key: 'System.State', because it is already configured.
[W][16:57:06] No target type 'Sub-task' is set, field status cannot be mapped.
[I][16:57:06] Processing 1/11 - 'WECLAPP-42954'.

**Comment by eplnde** [comment]
You are mapping Epics to Features:
        "source": "Epic",
        "target": "Feature"

So later definitions shall filter on "Feature" (the AzDo item), not Epic
    "source": "status",
     "target": "System.State",
     "for": "**Epic**",
