### ISSUE TITLE
Possible to map "type" to a field in AzDo for JIRA AzDo migrator

### ISSUE THREAD

**Issue by wallymathieu** [solidify/jira-azuredevops-migrator#976]
**While migrating issues from JIRA to AzDo**
In a JIRA configuration with many custom issue types we would like for the issue type information to be available after a migration (even though we might not use the same issue types in AzDo).

**Description of the solution we would like**
We would like for it to be possible to specify a field mapping from source type to your own field that you can configure in AzDo.

**An alternative solution we have considered**
Exporting all of the JIRA issues in the format that JIRA responds with in order to write a separate script to update the mapped json-data.

**Comment by Alexander-Hjelm** [comment]
Hello @wallymathieu !

The Jira Migrator PRO and Atlassian Migration Suite offerings from Jira both contain a helpful utility that retrieves the issue metadata and all available states and fields per issue type, as well as the expected schema for each field. Reach out to us at <support.jira-migrator@solidify.dev> to make an inquiry! See this section for more insformation: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-azure-devops-migrator-pro
