### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by marek-dziechciarz** [solidify/jira-azuredevops-migrator#981]
jira-export -u myUser -p myPassword --url https://myorganization.atlassian.net --config config.json --force
run in Windows CMD
off course myUser, myPassword and myorganization changed to my data
returns Permission denied.

**Comment by Alexander-Hjelm** [comment]
Unless you have somehow bound "jira-export" as an environment variable, you need to specify the path to the .exe

**Comment by marek-dziechciarz** [comment]
also run like .\jira-export.exe .... returned same Permission denied

**Comment by Alexander-Hjelm** [comment]
You probably need to configure you terminal/system or run with elevated access

**Comment by marek-dziechciarz** [comment]
I run teminal as administrator so it shouldn't be higher perms

**Comment by marek-dziechciarz** [comment]
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/56233997/fd8c375d-a94a-471d-b01c-4cbdf583407c)

**Comment by marek-dziechciarz** [comment]
to be clear, I try to run this app on MS Windows 11

**Comment by marek-dziechciarz** [comment]
yup, i've run this, there was -? parameter just after filename so it caused problems
