### ISSUE TITLE
Getting error while migrating a work item of Project A containing references to work items of Project B.

### ISSUE THREAD

**Issue by dhananjaykumar-pathak** [solidify/jira-azuredevops-migrator#984]
While migrating from Jira to Azure DevOps, getting error while migrating a work item of Project A containing references to work items of Project B. The work items for Project B have yet not been created in the Azure cloud. When i try to migrate, it gives below error as well during the Azure import,

Error when creating new Work item: One or more errors occurred. - TF401322: You don't have bypass rules permission. Please contact your collection administrator to grant this permission for enabling this action.

Please help asap. Attached is the config file for it.
[Uploading config.json…]()

**Comment by Alexander-Hjelm** [comment]
You need elevated permissions in the ADO project, Specifically the Bypass Rules on WorkItem Updates permission.
