### ISSUE TITLE
Parent - child relation impropoer migrate

### ISSUE THREAD

**Issue by marek-dziechciarz** [solidify/jira-azuredevops-migrator#985]
I have few Jira objects:
Epic that contains child Story
And that Story contains child Bug and Task
Task that contains chold Subtask
That task has duplicate Task and is tested by Test Case

Anf after migration to DevOps i have:
Epic with no child (but should have child Story)
Story witch is child of Bug (but chould be child of Epic)
Task tested by Test case and duplicated by ANother task and Child Subtask itch is correct but has no parent but chould has Story
Bug with child of Story but should be parent Story
My configuration of link-map below
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/56233997/2dcc8fce-f7f1-49d1-bc14-8ace2a1861ab)

In my opinion application ignores witch type parent-child relation is witch task is parent and witch is child because it gathers information only form Name, and ignores Outward and Inward description in Jira
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/56233997/eef2b3e1-f6ed-4ce3-ab95-d43d1895163c)
So if the Task has also parent and child task so exporter get both them and maps to ine of the type which is not good.

I think it could use only parent value, because enven if there are also child tasks, so it will be linked via those tasks in the fiture steps

**Comment by Alexander-Hjelm** [comment]
I would advise checking the export and import logs. This is not enough information to reproduce your issue!

**Comment by marek-dziechciarz** [comment]
Here are my export files, i belive that logs shoud be enough but i've added also the rest of migrate files
[ICQ-124.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309673/ICQ-124.json)
[ICQ-125.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309674/ICQ-125.json)
[ICQ-127.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309675/ICQ-127.json)
[ICQ-128.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309676/ICQ-128.json)
[ICQ-129.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309677/ICQ-129.json)
[ICQ-130.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309678/ICQ-130.json)
[ICQ-131.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309679/ICQ-131.json)
[itemsJournal.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14309680/itemsJournal.txt)
[jira-export-log-240216-112115.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14309681/jira-export-log-240216-112115.txt)
[wi-import-log-240216-112137.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14309682/wi-import-log-240216-112137.txt)

As i see there are a problem with link between ICQ-125 and ICQ-127, because there are situation like this in Jira:
ICQ-124 - Epic
ICQ-125 - Story (child 124)
      ICQ-130 (child 125) - Bug
      ICQ-127 (child 125) - Task
           ICQ-129 (child 127) - Subtask
Because of system sees that 129 is parent of 127 which is wrong because it is 127 is parent of 127, so it can't add parent link to 127 because it has wrong parent 129


[config-icq.json](https://github.com/solidify/jira-azuredevops-migrator/files/14309702/config-icq.json)

**Comment by marek-dziechciarz** [comment]
Any ideas?
