### ISSUE TITLE
Attachments extracted from JIRA are corrupted

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [solidify/jira-azuredevops-migrator#986]
First of all, thank you so much for building this tool to support the community around this migration. This works really well. 

During my migration, I have encountered an issue where in images/attachments downloaded from JIRA are corrupted. Surprisingly all the image size are same. I think there is something going wrong with extracting attachment. 

When I open the image file in notepad, all i see is the HTML CODE. No idea what it is.

**Comment by Alexander-Hjelm** [comment]
Does the HMLT response in the image file give any hints as to what the problem could be?

For instance if you are unauthenticated, the REST API can sometimes return a login page.

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm  yeah. As you suspected, there is some information around Authentication in the file. I do have an active session while I'm doing an export from JIRA. User stories are getting exported successfully though.  Am I missing something here? 

Snippet from Image HTML Content **<title>Validate Two Factor(2FA) :- Methods List -- JIRA</title>**

**Comment by Alexander-Hjelm** [comment]
That looks very strange to me. Could it be that there is an issue or a historical attachment which has been deleted? Or otherwise which your users does not have access to read?

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm - Image does exist in JIRA. I suspect its something to do with 2FA as the HTML shows some hint on that. Can you please help out ? thanks in advance. 

`<div class="mo-aui-page-panel">
        <div class="aui-page-panel-inner">
            <section class="aui-page-panel-content">
                <header class="aui-page-header">
                    <div class="aui-page-header-inner">
                        <div class="aui-page-header-main">
                            <h1>Validate Two Factor</h1>
                        </div>
                    </div>
                </header>
                <hr/>
                                <form class="aui">
                    <p id="Yuvaraj Palani" class="hideElement" onclick="openCloseElemenet('Yuvaraj Palani')">Hello Yuvaraj Palani,</p>
                    <p>Select the 2FA method for additional validation.</p>
                </form>

                <form action="" class="mo-aui" id="mo-2fa-validate-form" method="post">
                    <input type="hidden" name="atl_token" value="$atl_token"/>
                    
                                            <div>
                            <input type="radio" class="radio" id="configureGoogleAuthenticator"
                                   name="configureTwoFactor" value="GoogleAuthenticator">
                            <label for="configureGoogleAuthenticator">Mobile Authenticator</label>
                        </div>
                    
                    
                    
                                            <div>
                            <input type="radio" class="radio" id="configureOtpOverEmail"
                                   name="configureTwoFactor" value="OtpOverEmail">
                            <label for="configureOtpOverEmail">OTP Over Email</label>
                        </div>
                    
                    
                    
                    
                    
                    <div style="margin-top: 10px;">
                        <input class="aui-button aui-button-primary" id="otp-validate-form-submit" name="Submit"
                            type="submit" value="Next"/>&nbsp;&nbsp;&nbsp;
                        <a href="https://jira.techmahindra.com/plugins/servlet/twofactor/userlogout">Abort and Logout</a>
                    </div>
                </form>
            </section>
        </div>
    </div>`

**Comment by Alexander-Hjelm** [comment]
Are you using a Jira API token instead of your user password when running the exporter? That should in theory bypass any 2FA setup.

**Comment by Alexander-Hjelm** [comment]
Great! :D

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm  - Sorry to bother you again on this issue. Still I'm running in to the same issue where attachments are not getting exported properly where stories are getting extracted successfully.. 
jira-export -u {username} -p {password} -t {token}  --url {url} --config config-agile.json --force

![Uploading Screenshot (293).png…]()

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm  - Can you please assist ASAP ? Thanks in advance

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm - Did you get a chance to check on this ?

**Comment by Alexander-Hjelm** [comment]
I can suggest a few action points to try and troubleshoot the issue :)

1. Try all possible permutations of the user credentials. See: <https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#2-why-i-am-getting-unauthorized-exception-when-running-the-export>
1. Verify your user permissions in Jira. If possible, try to run the tool with the most permissive role (project administrator if possible)
1. Verify that you can retrieve the attachment manually with Postman, cURL or a similar tool.

**Comment by Yuvarajsfcloud** [comment]
Hi @Alexander-Hjelm, 

Thanks for your response. I found something weird about the Api version used to access JIRA server (Jira v9.12.1). 
Below is my observation.

1. /rest/api/3 (doesn't work)
2. /rest/api/2 (works, able to receive JIRA stories through postman)

Do we have to change anything in solidify code based on the version we are accessing ?

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm  - Hope you are doing well. Did you get a chance to check on the above issue ? 
Thanks in advance

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm - Do you think while hitting the image URL from the tool, there is some problem with maintaining the session which results in directing to the login page ?

**Comment by Alexander-Hjelm** [comment]
Here is how to get the attachment contents:

- GET request to /rest/api/3/attachment/{attachmentId}
  - obtain attachmentFilename from the response
- GET request to {Jira_Base_URL}/secure/attachment/{attachmentId}/{attachmentFilename}

That should work simply by forging and pasting the above URLs into a web browser window where you are already authenticated in Jira.

What happens if you try the above? Are you able to get the attachment contents?

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm - PFB the results 

- GET request to /rest/api/3/attachment/{attachmentId} (Works)

- GET request to {Jira_Base_URL}/secure/attachment/{attachmentId}/{attachmentFilename} (Getting 2FA content in response)

I'm using Bearer Token to authenticate from postman. 

If I try the same in the browser, able to see the image (I'm already authenticated).

**Comment by Alexander-Hjelm** [comment]
What about simply right clicking the image on the issue description/discussion and choosing Open in New Tab? Shouldn't that produce the same result?

In theory the attachment should not even render on the issue screen. Super weird.

Here are some issues and community posts from Atlassian which I dug up. Maybe could be relevant:

- https://jira.atlassian.com/browse/JRACLOUD-67281
- https://community.atlassian.com/t5/Jira-Software-questions/Get-attachments-from-API-using-NODE-and-getting-error-401/qaq-p/2333108

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm - Does it has anything to do with type of token being used for authentication? 
I currently Personal Access Token which I generate from my profile.

**Comment by Alexander-Hjelm** [comment]
Nah that should not be an issue, If you already tried all possible combinations of your credentials in our FAQ and only Personal Access Token worked then you should go with that: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#2-why-i-am-getting-unauthorized-exception-when-running-the-export

What if you were to obtain an API token from another user with at least Project Administrator access, or the same access level as yourself, and run the tool with that? Does that produce a different result?

**Comment by Alexander-Hjelm** [comment]
No workaround yet as far as we know, other than maybe downloading the missing attachments manually and placing them in the correct path inside the Attachments folder in your migration Workspace, which could be more or less feasible depending on how many missing attachments you are dealing with.

We continue to look into it for now, but we have been unsuccessful in reproducing the erroneous response so far.

**Comment by masteragi** [comment]
I am sure it could also be caused by the (outdated) Jira Server version we are running (9.12.2). I would be happy to offer my setup for debugging purposes (to at least reproduce the issue) and possibly expedite fixing the issue. I can also offer to implement the fix if you give me some pointers.

**Comment by masteragi** [comment]
I have found a way to download all attachments at once using following Jira Plugin: https://marketplace.atlassian.com/apps/1211093/download-attachments?tab=support&hosting=datacenter

However the Plugin create a folder for each Jira work item (named by Jira Issue-Key) and Solidify Migrator expects the attachments in folders named by Jira Attachment-ID. Do you see an easy way to transform the folder structure from Issue-Key to Attachment-ID? My second idea would be to create a script to go through all the files created by Solidify Migrator and replace them with files downloaded by the Jira Plugin (that might be the easiest way as no other changes in the exported files would be required). What do you think?

**Comment by Alexander-Hjelm** [comment]
You can retrieve the attachments of a single issue with the below endpoint:

api/2/issue/{issueIdOrKey}/attachments

In the response you should be able to get the file name and attachment ID!

There is also an endpoint for listing all issues.

**Comment by masteragi** [comment]
I have decided to go with the simpler solution and have written the following PowerShell script to replace the files from the Solidify export with the files from the Jira Plugin Attachment export:

```powershell
# Define the directories
$solidify_export_dir = ".\Solidify-Export\Attachments"
$plugin_export_dir = ".\Jira-Plugin-Export"

# Get all subdirectories of Solidify-Export
$solidify_subdirs = Get-ChildItem -Path $solidify_export_dir -Directory

# Loop over all subdirectories of Solidify-Export
foreach ($solidify_subdir in $solidify_subdirs) {
    # Get all files in the subdirectory
    $files = Get-ChildItem -Path $solidify_subdir.FullName -File
    # Loop over all files in the subdirectory
    foreach ($file in $files) {
        # Try to find the same file in Plugin-Export
        $plugin_files = Get-ChildItem -Path $plugin_export_dir -Recurse -File | Where-Object { $_.Name -eq $file.Name }
        # If found, copy it to the original location, overwriting the original file
        foreach ($plugin_file in $plugin_files) {
            Copy-Item -Path $plugin_file.FullName -Destination $solidify_subdir.FullName -Force
            Write-Host ("Copied file", $plugin_file.FullName, "to",  $solidify_subdir.FullName) -Separator " "
        }
    }
}
```
