### ISSUE TITLE
Jira Export step is generating messages "Rendered field customfield_11111 contains unparsable type Null, using text"

### ISSUE THREAD

**Issue by steverwyllie** [solidify/jira-azuredevops-migrator#989]
I'm trying to migrate Custom Jira fields to Custom ADO fields using the Community tool. Having switched Debug on, I've noticed that the Jira export step produces the message "Mapped value 'Jira-field-content' to field 'ADO-field-name' " when everything's OK.

However, for most (all?) of the Custom Jira fields I'm trying to migrate to ADO, I'm seeing the message "Rendered field customfield_11111 contains unparsable type Null, using text". When that message is generated
* the positive 'Mapped value...' message doesn't appear, and
* those fields aren't migrated to ADO

Can anyone provide some guidance on anything we need to do in Jira, to address whatever problem is generating the messages "Rendered field .... contains unparsable type Null, using text" ?

**Tool version**
 - Jira Exporter v3.0.356

**Attachments**
[jira-export-log-240220-111416.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14349279/jira-export-log-240220-111416.txt)
[wi-import-log-240220-113011.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14349280/wi-import-log-240220-113011.txt)
[config-scrum(COPY).json](https://github.com/solidify/jira-azuredevops-migrator/files/14349288/config-scrum.COPY.json)

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Comment by Alexander-Hjelm** [comment]
I see in your config that you have mapped a lot of custom data by name, without specifying `"source-type": "name"` in the field map. Could that be the issue maybe?

See https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field

**Comment by steverwyllie** [comment]
Hi Alexander. I'd like to express my sincere thanks for responding so quickly - and identifying the actual problem!
