### ISSUE TITLE
Multiple fields found for assignee. Selecting customfield_24863.

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [solidify/jira-azuredevops-migrator#994]
I'm running in to below warning during my migration.

"Multiple fields found for assignee. Selecting customfield_24863."

I understand we have multiple fields present for Assignee Field & we use Standard assignee field & not custom one. But the tool is defaulting to custom one. Is there any way we can default it to Standard assignee field .

**Comment by Alexander-Hjelm** [comment]
Hello! :)

Assuming that this is related to the JiraExporter, you can get around this issue by refering to the source field via ID instead of name, like this:

```json
      {
        "source": "customfield_10072",
        "target": "Custom.CustomDatePicker",
        "source-type": "id",
      },
```

See the FAQ section for mapping custom fields: <https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#3-how-to-map-custom-field>

**Comment by Yuvarajsfcloud** [comment]
Hello ,
thanks for your quick response.
we wanted to use standard Assignee field and not the custom one , but the tool always selects the custom one .

can you please help?

regards
Yuvaraj

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Alexander-Hjelm** [comment]
Maybe like this?

```json
      {
        "source": "assignee",
        "target": "Custom.CustomDatePicker",
        "source-type": "id",
      },
```

**Comment by Yuvarajsfcloud** [comment]
Though it gives a warning on the CMD, its taking the value from Standard assignee field. Not sure if I have to worry about that. 

But facing similar issue for Story point Estimate as well. How do we select a specific field in that case ?

**Comment by Alexander-Hjelm** [comment]
What's the warning message?

In general, I would advise to get the Issue using the Api endpoint: GET /rest/api/3/issue/{issueIdOrKey}

Then in the response you can find the FieldId which you can use for mapping the field uniquely! Use id as the field name can be ambiguous,

**Comment by Yuvarajsfcloud** [comment]
@Alexander-Hjelm - Thank you. this worked :). I'm closing this issue.
