### ISSUE TITLE
Migrating test details(design steps, test runs, test plans and so on) from Cloud JIRA with X-Ray to Azure

### ISSUE THREAD

**Issue by KRVijayalakshmi** [solidify/jira-azuredevops-migrator#996]
# Read this before submitting your support ticket/bug report

- [ ] Make sure that you have searched for your problem in the **FAQ**: <https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md>
- [ ] Make sure that you have searched for your problem in the **issue board** (you can search for keywords in the **filters** search bar): <https://github.com/solidify/jira-azuredevops-migrator/issues?q=is%3Aissue+>
- [ ] Fill in the issue template below (starting with **Describe the problem**)
- [ ] Delete this section but keep the issue template
---

**Describe the problem**

We need to understand if the **jira-azuredevops-migrator** will be able to migrate the testing related artifacts example- Test details with design steps, test runs, test plans and linked issues form Cloud Jira with X-ray to ADO.
**To Reproduce**

**Tool version**
 - Version of the jira-azuredevops-migrator tool [e.g. 2.3.117]

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**

**Comment by Alexander-Hjelm** [comment]
Hello @KRVijayalakshmi :)

> We need to understand if the jira-azuredevops-migrator will be able to migrate the testing related artifacts example- Test details with design steps, test runs, test plans and linked issues form Cloud Jira with X-ray to ADO.

X-Ray test artifacts are supported by our premium offering, in the form of a separate program called the **Jira Test Management Migrator** which runs on top of the Jira Azure DevOps Migrator.

You can read more here: https://github.com/solidify/jira-azuredevops-migrator?tab=readme-ov-file#jira-test-management-migrator, or visit the product page at our website: https://solidify.dev/products/atlassian-migration-suite

Feel free to reach out to us at [support.jira-migrator@solidify.dev](mailto:support.jira-migrator@solidify.dev)

**Comment by KRVijayalakshmi** [comment]
Thanks for the updates team.

I would like to know more details on premium offering (license details etc.) and any pre-requisites to have the migration successful.

**Comment by Alexander-Hjelm** [comment]
You can purchase the Atlassian Migration Tool directly from us or via Azure SAAS offerings.

See our website for details + price: https://solidify.dev/products/atlassian-migration-suite.

Here is a pdf (https://github.com/solidify/atlassian-migration-suite-docs/blob/main/migration-jira-test-mgmnt.pdf) which contains among other things:

- Technical documentation
- How tos
- Permission requirements
- Supported/unsupported data for each Jira Test framework

The tool needs a Windows-based system or VDI to work.

**Comment by KRVijayalakshmi** [comment]
Thanks for the reference documents.

We have booked the slot for the demo session on 19th Mar 4:20 IST to have more insight before we get into further discussion.

**Comment by KRVijayalakshmi** [comment]
Post the discussion with the support team in our Demo, we understand that the test runs , pre-conditions, test sets, attachments at the test design step level is still not incorporated in the JIRA Test Management Migrator tool. We may not be able to proceed further as this is the major junk of data that needs to be migrated to Azure.
 Also, the history will hold the latest change and not all the previous history details which is again a concern area.

However, the support team confirmed to revert with the latest date we may have this feature released which would help us to take it further from that point.

**Comment by Alexander-Hjelm** [comment]
> Post the discussion with the support team in our Demo, we understand that the test runs , pre-conditions, test sets, attachments at the test design step level is still not incorporated in the JIRA Test Management Migrator tool. We may not be able to proceed further as this is the major junk of data that needs to be migrated to Azure. Also, the history will hold the latest change and not all the previous history details which is again a concern area.
> 
> However, the support team confirmed to revert with the latest date we may have this feature released which would help us to take it further from that point.

I will check with the Test Management Migrator Team what the status is on Historical test data for the XRay adapter. I will let you know as soon as I know more.

I know that we are in the process of adding this feature for some of the test frameworks, so it could very well be that we could support it shortly.

**Comment by Payel-roy228** [comment]
Hi, 
We need clarification on the below 2 points:
1. Do we have any in-built importing options for importing the test execution details on ADO side in case we are trying to import the test cases from Excel.
2. Also do you have any documentation available to access the API details in the test execution level in ADO side.

Thanks in advance!

**Comment by Alexander-Hjelm** [comment]
@Payel-roy228 The Jira Test Management Migrator is an end-to-end solution and does not integrate with the Excel testdata export. As such, the tool will need live connectivity to both ADO and Jira.

Here is all the documentation which we have available: https://github.com/solidify/atlassian-migration-suite-docs/blob/main/migration-jira-test-mgmnt.pdf

**Comment by Payel-roy228** [comment]
@Alexander-Hjelm Hi, we want a clear understanding on the import feature of ADO for test execution/test suite, for ex: do we have an option to import the test execution details which is residing in an Excel sheet. Can you please confirm and elaborate on that. 
Also, could you please share the API documentation available for ADO to work with test suite level. Thanks!

**Comment by Alexander-Hjelm** [comment]
@Payel-roy228 In the case of XRay, only test executions inside your Jira instance will be migrated.

You can find the API documentation for Azure Test Plans over at microsoft.com

**Comment by Alexander-Hjelm** [comment]
I am not sure what you mean by migrating test execution details from an Excel sheet to ADO :)

We only support live migrations directly between your Jira instance and your ADO instance.

As such, you will require a machine with connectivity to both servers/organizations.

**Comment by Payel-roy228** [comment]
@Alexander-Hjelm Hi, referring to your below tagged comment that was posted by you after our demo call stating all the limitations. Since we have the mentioned limitations hence, we are trying to refer to the import and export functionalities in ADO on Test suite level. Also, addition to that we don't see the import/export option for the "Execute" tab like we see for "Define" tab.
Adding a screenshot for reference.

Also can you please provide us with a template for the exact field level names that can be used to import test cases between JIRA and ADO. 

On ADO side, when we are trying to export only the 5-6 columns (like ID, Work Item Type, Title, Test Step, Step Action etc.) are getting extracted though we are adding more columns from the "Column options". Can you please let us know how to export more that these 5-6 fields through export option in excel from ADO. 

[ADO Test Suite level screens.docx](https://github.com/solidify/jira-azuredevops-migrator/files/14918498/ADO.Test.Suite.level.screens.docx)


> > Post the discussion with the support team in our Demo, we understand that the test runs , pre-conditions, test sets, attachments at the test design step level is still not incorporated in the JIRA Test Management Migrator tool. We may not be able to proceed further as this is the major junk of data that needs to be migrated to Azure. Also, the history will hold the latest change and not all the previous history details which is again a concern area.
> > However, the support team confirmed to revert with the latest date we may have this feature released which would help us to take it further from that point.
> 
> I will check with the Test Management Migrator Team what the status is on Historical test data for the XRay adapter. I will let you know as soon as I know more.
> 
> I know that we are in the process of adding this feature for some of the test frameworks, so it could very well be that we could support it shortly.
